### ISSUE TITLE
The gallery thumbnails are too small

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1038]
**Description of the problem**

Here is a comparison between the [PyGMT gallery](https://www.pygmt.org/dev/gallery/index.html) and the [matplotlib gallery](https://matplotlib.org/stable/gallery/index.html)

|PyGMT | Matplotlib |
|---|---|
| ![image](https://user-images.githubusercontent.com/3974108/110960089-63b41000-831c-11eb-86ab-6bc074602ed6.png) | ![image](https://user-images.githubusercontent.com/3974108/110959565-d07ada80-831b-11eb-8458-24ccde71da47.png) |

You may notice that the PyGMT gallery thumbnails are always smaller than the ones in matplotlib and [sphinx-gallery](https://sphinx-gallery.github.io/stable/auto_examples/index.html). The reason is that we limit the max width of images to 80% in the CSS:

https://github.com/GenericMappingTools/pygmt/blob/aff5db7f0f3d13e75313648528a50edcd2500b80/doc/_static/style.css#L41-L43

We made the change in #420 to avoid too large badges in the changelog file (https://github.com/GenericMappingTools/pygmt/pull/420#issuecomment-622162738). Apparently, the 80% CSS style is not ideal, and it affects all images. 

The simplest solution is changing `max-width` to 100%. Here is a comparison if we change the max-width to 100%. The gallery thumbnails look larger and better.

| max-width=80% | max-width=100% |
|---|---|
| ![image](https://user-images.githubusercontent.com/3974108/110960089-63b41000-831c-11eb-86ab-6bc074602ed6.png) | ![image](https://user-images.githubusercontent.com/3974108/110960921-403d9500-831d-11eb-966d-7534a44b158a.png) |

However, it also increases the size of other images to 100%. For example,

| max-width=80% | max-width=100% |
|---|---|
| ![image](https://user-images.githubusercontent.com/3974108/110961271-9ad6f100-831d-11eb-85cc-fbb0de6f2337.png) | ![image](https://user-images.githubusercontent.com/3974108/110961300-a32f2c00-831d-11eb-92bc-1095bcbd6231.png) |
| ![image](https://user-images.githubusercontent.com/3974108/110961963-60ba1f00-831e-11eb-827d-e9838bf4ce16.png) | ![image](https://user-images.githubusercontent.com/3974108/110962004-6f083b00-831e-11eb-981b-a113b7988ba5.png) |

To me, 80% max-width looks better for these individual large images, but 100% max-width looks better for gallery thumbnails.

We should find a way to control the different settings of the two groups of images.

BTW, looking at the matplotlib gallery, I think we can also:

- add a box to each thumbnail
- centering the titles of the gallery examples

**Comment by meghanrjones** [comment]
I agree that 100% max-width looks better for the thumbnails. For the ROSES tutorial (and generally files in the .rst files), we can just set the width to 80% in the figure directive rather than relying on max-width. For any fig.show() output, I think it could be better to not scale the images at all given that it obscures the purpose of the *width* or *height* in **-J**.

**Comment by willschlitzer** [comment]
I agree that bigger thumbnails look better.
