### ISSUE TITLE
Rename files in the tutorials using underscores

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1039]
Following #1034, we should use underscores for all Python files. We did the renaming in recent PRs, but there are still a few files in the [`examples/tutorials`](https://github.com/GenericMappingTools/pygmt/tree/master/examples/tutorials) directory that should be changed.

**Comment by meghanrjones** [comment]
I can address this issue

**Comment by seisman** [comment]
Closed by #1041.
