### ISSUE TITLE
Curate a list of PyGMT community contributions

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#1059]
**Description of the desired feature**

Team, what do people think about adding a "User Contributions" section on the sidebar (similar to https://docs.generic-mapping-tools.org/6.1/users-contrib-scripts.html). I think there's a lot of good examples (from workshops/papers/posters/etc) floating out there in the wild and it would be good to have a place to link to some of them

Some examples that I know of (feel free to edit and add to the list):

- https://github.com/liamtoney/gi-pygmt-2021
- https://www.iris.edu/hq/inclass/lesson/728
- https://github.com/michaelgrund/GMT-plotting
- https://github.com/MIGG-NTU/PyGMT2021
- https://github.com/GenericMappingTools/foss4g2019oceania
- https://github.com/mrsiegfried/Venturelli2020-GRL
- https://github.com/weiji14/nzasc2021

Alternatively, we could setup an 'awesome-pygmt' page (see https://github.com/sindresorhus/awesome) if we think there will be a lot of these, and just have a link to it on the sidebar.

**Are you willing to help implement and maintain this feature?** Need some input from people :)

**Comment by seisman** [comment]
I think a list of links in the PyGMT documentation is enough. A separate awesome-pygmt repository and site mean more maintenance burden on us.

**Comment by willschlitzer** [comment]
Are you envisioning this as just PyGMT-focused tutorial/posters/papers, or including geoscience (and other -science) work that uses PyGMT in it?

**Comment by michaelgrund** [comment]
> 
> 
> I think a list of links in the PyGMT documentation is enough. A separate awesome-pygmt repository and site mean more maintenance burden on us.

Agree with @seisman. I think a list of links is sufficient.

**Comment by seisman** [comment]
Do we need to ask for permissions if we want to add any repositories/websites to the list?

**Comment by michaelgrund** [comment]
> 
> 
> Do we need to ask for permissions if we want to add any repositories/websites to the list?

Not sure, e.g. ObsPy lists several extensions to the main package etc. on their GitHub page. Maybe we do it in a similar way or ask them how they handle it.

**Comment by seisman** [comment]
At least most of the tutorials/examples are owned by our project maintainers/contributors. So at least we can list these sites and ask users to contribute more to the list:

> * [liamtoney/gi-pygmt-2021](https://github.com/liamtoney/gi-pygmt-2021)
> * [iris.edu/hq/inclass/lesson/728](https://www.iris.edu/hq/inclass/lesson/728)
> * [michaelgrund/GMT-plotting](https://github.com/michaelgrund/GMT-plotting)
> * [MIGG-NTU/PyGMT2021](https://github.com/MIGG-NTU/PyGMT2021)
> * [GenericMappingTools/foss4g2019oceania](https://github.com/GenericMappingTools/foss4g2019oceania)
> * [mrsiegfried/Venturelli2020-GRL](https://github.com/mrsiegfried/Venturelli2020-GRL)
> * [weiji14/nzasc2021](https://github.com/weiji14/nzasc2021)

**Comment by seisman** [comment]
@GenericMappingTools/pygmt-contributors I just added these resources in PR #1210. Please leave your comments there.
