### ISSUE TITLE
Fail to open images in external viewer programs if running PyGMT in a Python script

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1061]
**Description of the problem**

Here is a simple Python script to reproduce the issue. 
```python
import pygmt

fig = pygmt.Figure()
fig.basemap(region=[0, 10, 0, 10], projection="X10c/10c", frame="+tFigure1")
print("Openning Figure1")
fig.show(method="external")
```
When I run the codes in a Python/IPython interpreter, it works well and can open the preview image. However, if I save it in a Python script and run it using `python test.py`, sometimes it can open the image but sometimes it fails and gives an error like (I'm using macOS):

![image](https://user-images.githubusercontent.com/3974108/111100070-4bf7aa00-851d-11eb-808d-0a341e1a0a19.png)

The reason is simple, on macOS, we call the `open` program to open the image. Because we can't detect the status of the external viewer, the Python script continues to execute the code and exit. When the script exits, Python will call the destructor of the Figure class (i.e., `Figure.__del__` method), which deletes the preview directory and also the preview image.

So, the preview image will show if the `open` program opens the image before Python deletes it, and will fail to open the image if it's already deleted.

---

The following script is similar to the above one, but instead, it plots and opens two images.
```
import pygmt

fig = pygmt.Figure()
fig.basemap(region=[0, 10, 0, 10], projection="X10c/10c", frame="+tFigure1")
print("Openning Figure1")
fig.show(method="external")

fig = pygmt.Figure()
fig.basemap(region=[0, 10, 0, 10], projection="X10c/10c", frame="+tFigure2")
print("Openning Figure2")
fig.show(method="external")
``` 

Again, the script works well in a Python/IPython interpreter, but usually can open Figure1 and can't open Figure2 when running a script. Figure1 can be successfully opened because plotting the second figure take some time, so the first `Figure.show()` call can open Figure1 before the program exits.

---

The only solution I can figure out is adding a short pause after calling the external viewer, i.e., 
adding `time.sleep(0.5)` at the end of the `launch_external_viewer(fname)` function.

https://github.com/GenericMappingTools/pygmt/blob/1fb9e2e4e523baaf3aaedb90d71872ede6d03bb7/pygmt/helpers/utils.py#L195

It works well for me, and should also work for Linux, but I'm not sure about Windows. The 0.5 second pause time is empirical, and may not work for slow computers.

I opened the PR #1062 with the above solution, so that anyone can test it with/without the pause.

**Comment by core-man** [comment]
I use CentOS 7.5 to test. Both two examples work in JupyterLab no matter if `time.sleep(0.5)` is added.

However, it shows the same bug as @seisman when running a script (I tried three times for each cases).
- The first example (only Figure 1) does not work and shows the same bug, but it works if `time.sleep(0.5)` is added.
- The second example (two figures) can display Figure 1 but cannot open Figure 2, but it works if `time.sleep(0.5)` is added .

**Comment by seisman** [comment]
The issue is partially fixed by #529, but I'll leave the issue open for a longer time.

**Comment by weiji14** [comment]
Do we want to keep this issue open @seisman? Or can we close it since `time.sleep(0.5)` seems to be good enough for most cases.

**Comment by seisman** [comment]
> Or can we close it since `time.sleep(0.5)` seems to be good enough for most cases.

At least one user reported to me that `time.sleep(0.5)` still doesn't work for him, possibly because his computer is old and slow. He has to change it to something like `time.sleep(1.0)` to make it work.

Perhaps we should add a parameter like `sleep=0.5` to the `Figure.show()` function (and `launch_external_viewer`) so that users can customize the waiting time.

**Comment by weiji14** [comment]
> Perhaps we should add a parameter like `sleep=0.5` to the `Figure.show()` function (and `launch_external_viewer`) so that users can customize the waiting time.

Yep, that sounds like a good option. Will need to modify these parts:

https://github.com/GenericMappingTools/pygmt/blob/bafb8ab906aa87eb1dab3ce286b9baa91e145099/pygmt/helpers/utils.py#L256
https://github.com/GenericMappingTools/pygmt/blob/bafb8ab906aa87eb1dab3ce286b9baa91e145099/pygmt/figure.py#L332
https://github.com/GenericMappingTools/pygmt/blob/bafb8ab906aa87eb1dab3ce286b9baa91e145099/pygmt/figure.py#L265
