### ISSUE TITLE
Add an example for Oblique Mercator projection

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1073]
**Description of the desired feature**

Add an example to the [projections section](https://www.pygmt.org/dev/projections/index.html#) of the PyGMT user guide showing in the three ways to define the Oblique Mercator projection.

References:

As always, the contributing guide: https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md
GMT documentation for the Oblique Mercator projection: https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html#jo
The other PyGMT projection examples (located in `examples/projections/`).

**Are you willing to help implement and maintain this feature?** I would welcome help, but can add this for v0.4.0 if no one else wants to.

**Comment by eemcmullan** [comment]
Hello! I am interested in contributing to this project, and would be happy to work on this issue.

**Comment by meghanrjones** [comment]
Thanks, @eemcmullan! Feel free to open a PR and reach out if you have any questions!
