### ISSUE TITLE
The color parameter of plot and plot3d methods can be 1d array

### ISSUE THREAD

**Issue by core-man** [GenericMappingTools/pygmt#1075]
**Description of the problem**

We need to update the documentation for the `color` parameter in [plot](https://www.pygmt.org/dev/api/generated/pygmt.Figure.plot.html#pygmt.Figure.plot) and [plot3d](https://www.pygmt.org/dev/api/generated/pygmt.Figure.plot3d.html#pygmt.Figure.plot3d) because `color` can also be `1d array` (originally posted in https://github.com/GenericMappingTools/pygmt/pull/1065#issuecomment-801212175).

---

See the description  of the `color` parameter of [plot](https://www.pygmt.org/dev/api/generated/pygmt.Figure.plot.html#pygmt.Figure.plot):
> **color** (str) – Select color or pattern for filling of symbols or polygons. Default is no fill.

See the description of the `color` parameter of [plot3d](https://www.pygmt.org/dev/api/generated/pygmt.Figure.plot3d.html#pygmt.Figure.plot3d):
> **color** (str) – Select color or pattern for filling of symbols or polygons. Default is no fill.

---

However, `color` can also be a **1d array** just like the `sizes` parameter when we use `x`/`y` parameters for in the `plot` and `plot3d` methods. See the last example in [Plotting data points](https://www.pygmt.org/latest/tutorials/plot.html). We can set `color=data.depth_km` and `data.depth_km` is a 1d array.
```
import pygmt
data = pygmt.datasets.load_japan_quakes()
region = [
    data.longitude.min() - 1,
    data.longitude.max() + 1,
    data.latitude.min() - 1,
    data.latitude.max() + 1,
]
print(region)
print(data.head())

fig = pygmt.Figure()
fig.basemap(region=region, projection="M15c", frame=True)
fig.coast(land="black", water="skyblue")
pygmt.makecpt(cmap="viridis", series=[data.depth_km.min(), data.depth_km.max()])
fig.plot(
    x=data.longitude,
    y=data.latitude,
    sizes=0.02 * 2 ** data.magnitude,
    color=data.depth_km,
    cmap=True,
    style="cc",
    pen="black",
)
fig.colorbar(frame='af+l"Depth (km)"')
fig.show()
```

**Comment by seisman** [comment]
If I understand it correctly, we only need to update the docstrings to mention that `color` can be a string or a 1darray?

**Comment by core-man** [comment]
> If I understand it correctly, we only need to update the docstrings to mention that `color` can be a string or a 1darray?

I think so. May better to add a note like the `size` parameter for the [`plot`](https://www.pygmt.org/dev/api/generated/pygmt.Figure.plot.html#pygmt.Figure.plot) method.

> **sizes** (*1d array*) – The sizes of the data points in units specified using `style`. Only valid if using `x`/`y`.

Because we raise `GMTInvalidInput` when `color` is used with the `data` parameter just like the `sizes` parameter.

https://github.com/GenericMappingTools/pygmt/blob/1a2289a20519a4dbf1c78543acd4a654b981811e/pygmt/src/plot.py#L207-L211

https://github.com/GenericMappingTools/pygmt/blob/1a2289a20519a4dbf1c78543acd4a654b981811e/pygmt/src/plot.py#L214-L218

**Comment by seisman** [comment]
Sounds good. Maybe also need to mention that `cmap` is required if `color` is a 1darray (I don't check if it's true).

**Comment by core-man** [comment]
> Sounds good. Maybe also need to mention that `cmap` is required if `color` is a 1darray (I don't check if it's true).

I think so. See GMT [plot](https://docs.generic-mapping-tools.org/latest/plot.html#S):

> where the optional z is required when -C is used

**Comment by seisman** [comment]
@core-man This issue looks easy to fix. Do you want to work on it?

**Comment by core-man** [comment]
> @core-man This issue looks easy to fix. Do you want to work on it?

So we don't want to leave it to new contributors?

**Comment by seisman** [comment]
> So we don't want to leave it to new contributors?

The description of the issue is so long that people may be lost about what they should do. 

You may either submit a quick fix or give more details about the expected changes.
