### ISSUE TITLE
Exclude dvc related files from source distribution

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1086]
The new workflow in #1036 adds more files into the git repository and some files are included in the source distribution by default.

Run `make package` and check the files in the tarball `dist/pygmt-X.Y.Z.tar.gz`.

I see some new files in the source distribution:

- `.dvc`
- `.dvcignore`
- `pygmt/tests/baseline/*.dvc`

Some DVC images (e.g., `pygmt/tests/baseline/test_logo.png`) are also included in the tarball although they **should** be ignored by git and excluded from the source distribution by default.

A related question is: do we want to include the baseline images in the source distribution?

**Comment by weiji14** [comment]
> A related question is: do we want to include the baseline images in the source distribution?

As you mentioned in https://github.com/GenericMappingTools/pygmt/issues/999#issuecomment-791093992_:

> FYI, the tarball size can be reduced from 6.2 MB to 600 K if we can remove all baseline images. 😄

I think we should move towards trimming the size of the PyPI sdist (.tar.gz) and bdist (.whl) down to less than 1MB. This would mean that `pygmt.test()` at https://www.pygmt.org/v0.3.1/install.html#full-test-optional won't work out of the box. But really, what other Python package ships with a full test suite **and** tells users to run those tests anyway?

> I see some new files in the source distribution:
> 
>     * `.dvc`
> 
>     * `.dvcignore`
> 
>     * `pygmt/tests/baseline/*.dvc`
> 
> 
> Some DVC images (e.g., `pygmt/tests/baseline/test_logo.png`) are also included in the tarball although they **should** be ignored by git and excluded from the source distribution by default.

Yep, we should update the MANIFEST.in file to exclude these `*.dvc* ` files, and also the PNG files. If we really want to have those PNG baseline images somewhere, we can think about storing them on the Zenodo DOI for archival purposes (though might need a bit of work).

**Comment by seisman** [comment]
> what other Python package ships with a full test suite **and** tells users to run those tests anyway?
> 
> >

Matplotlib includes all baseline images in their source tarballs (~40 MB) (https://pypi.org/project/matplotlib/#files), but not in wheels (~10 MB). They recommend users to download the source tarball and extract the test codes and baseline images before doing tests (https://matplotlib.org/stable/users/installing.html#test-data).

> If we really want to have those PNG baseline images somewhere, we can think about storing them on the Zenodo DOI for archival purposes (though might need a bit of work).

Perhaps it's simpler to just upload the baseline images as GitHub release assets.

**Comment by seisman** [comment]
> Some DVC images (e.g., `pygmt/tests/baseline/test_logo.png`) are also included in the tarball although they **should** be ignored by git and excluded from the source distribution by default.

These images are included in the source distribution because the following line:

https://github.com/GenericMappingTools/pygmt/blob/74c93662a5a046ecd0f1d1710eb5118204a35ecb/setup.py#L21

**Comment by seisman** [comment]
Here are the rules about which files are included in the source distributions:

- All files tracked by git are included
- Any files in the _baseline_ directory are included (no matter the files are tracked by git or not)
- Any files listed in the `MANEFEST.in` files are excluded.

In the "Publish to PyPI" workflow, we don't run the `dvc pull` command, so the dvc-tracked baseline images are not in the _baseline_ directory, and are not included in the source distributions. If you download the tarball from TestPyPI (https://test.pypi.org/project/pygmt/0.3.2.dev38/#files), you will see that dvc-tracked images (e.g., `test_logo.png`) are not included.

In the "Tests" workflow, we run the `dvc pull` command, so the dvc-tracked images are download from the remote repository. When we build the source distribution, the dvc-tracked images are also included and installed. So we can still run the tests.

---

So, the only thing we need to do is adding `.dvc` and `.dvcignore` into the `MANIFEST.in` file. See the PR #1095.

After we finish the migration of all baseline images, the source distribution will only contain the '.dvc' files, but not the '.png' files.
