### ISSUE TITLE
Wrap blockmean and blockmode

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1091]
**Description of the desired feature**

Wrap [blockmean](https://docs.generic-mapping-tools.org/dev/blockmean.html) and [blockmode](https://docs.generic-mapping-tools.org/dev/blockmode.html). As @weiji14 mentioned previously, much of blockmedian can be moved to a generic _blockm* function which can be used for all three block average estimation methods.

**Are you willing to help implement and maintain this feature?** Yes- will submit a PR with blockmean for discussion.

**Comment by meghanrjones** [comment]
Assigning this issue to @arleaman in the ESWN/PyGMT workshop

**Comment by seisman** [comment]
The two modules have been wrapped in #1456 and #1092. Closing the issue.
