### ISSUE TITLE
Incorrect parameter in Figure.meca()

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1094]
**Description of the problem**

[Figure.meca](https://www.pygmt.org/dev/api/generated/pygmt.Figure.meca.html#pygmt.Figure.meca) defines an alias as ``C = offset``. Based on the description of the ``offset`` parameter, I think this alias should be for the **-A** option in GMT's meca (https://docs.generic-mapping-tools.org/dev/supplements/seis/meca.html#a); **-C** is for giving a cmap for the compressive part of the beachball. 

This is both a code and documentation issue, since there are these two checks for **-C** in kwargs (which should not be required for meca):

```
            # Add in plotting options, if given, otherwise add 0s
            for arg in plot_longitude, plot_latitude:
                if arg is None:
                    spec.append(0)
                else:
                    if "C" not in kwargs:
                        kwargs["C"] = True
                    spec.append(arg)
```

Relates to the proposed refactoring in https://github.com/GenericMappingTools/pygmt/pull/1002

**Comment by seisman** [comment]
GMT made some changes to the **-C** option recently (https://github.com/GenericMappingTools/gmt/pull/4873), although it's still backward-compatible.

We should upgrade the `Figure.meca()` syntax to match the GMT 6.2.0 syntax.

**Comment by meghanrjones** [comment]
> GMT made some changes to the **-C** option recently ([GenericMappingTools/gmt#4873](https://github.com/GenericMappingTools/gmt/pull/4873)), although it's still backward-compatible.
> 
> We should upgrade the `Figure.meca()` syntax to match the GMT 6.2.0 syntax.

Thanks for pointing this out - lesson learned to check the 'latest' documentation in addition to the 'dev' documentation before posting.
