### ISSUE TITLE
Add instructions to clean up files tracked by DVC

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1112]
Running `dvc pull` can download the PNG images tracked by dvc, but how can I remove these images?

I want to remove these dvc-tracked PNG images, so that:

1. it's easier to know which images are still tracked by git
2. I can have a refreshing download of all dvc-tracked images when I feel that something is wrong.

I had a quick look at the dvc command reference but did't find the command.

The command should be added to the CONTRIBUTING.md file.

**Comment by meghanrjones** [comment]
Not sure the answer to your actual question, but I suspect that viewing here might be the easiest way to see what's still tracked by git (https://dagshub.com/GenericMappingTools/pygmt/src/master/pygmt/tests/baseline) if my interpretation is correct that the files with the different symbol and blue highlighting are on DAGsHub.

**Comment by weiji14** [comment]
How about removing the `.dvc/cache/` folder? Technically all the PNG images are just reflinks (assuming you are using a modern-ish folesystem), see https://dvc.org/doc/user-guide/large-dataset-optimization#file-link-types-for-the-dvc-cache.

I did think about adding `rm -rf .dvc/cache/` to the Makefile, but not sure if that's what you mean.

**Comment by willschlitzer** [comment]
Just unsuccessfully tried to do this. `dvc` does have a `remove` command, but that didn't accomplish what I was hoping to do (delete unused `solar` test images from `dvc`)

**Comment by seisman** [comment]
I still don't find a `dvc` command for this, but I'm closing the issue, because we won't need it after finishing the migration of baseline images.

Currently, I simply do:
```
cd pygmt/tests/baseline
rm *.png
git restore .
```

**Comment by meghanrjones** [comment]
For me, `dvc gc -aT` was useful for removing images not used in the workspace, all branches, and tags (just reduced cache size by ~40%). One just needs to be careful to make sure the clean-up is only for the local repository and not the remote.

Here is the link to the `dvc gc` docs: https://dvc.org/doc/command-reference/gc#gc
