### ISSUE TITLE
Change non-ASCII quotes “ to ASCII quotes "

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1130]
The following files use non-ASCII double quotes `“”`, but ideally we should use ASCII double quotes `""`:
```
examples/gallery/lines/linestyles.py:Giving “dotted” or “.” yields a dotted line, whereas a dashed pen is requested
examples/gallery/lines/linestyles.py:with “dashed” or “-”. Also combinations of dots and dashes, like “.-” for a
examples/projections/misc/misc_robinson.py:the world map “look” right 22. The scale is true along latitudes 38. The projection was
examples/projections/misc/misc_sinusoidal.py:“Equal-area Mercator” projection. The central meridian is a straight line; all other
examples/projections/misc/misc_winkel_tripel.py:German word “tripel” refers to this junction of where each of these elements are least
examples/projections/misc/misc_winkel_tripel.py:and Son started to use it in its world-renowned “The Times Atlas of the World” in the
pygmt/src/coast.py:        Select filling or clipping of “dry” areas.
pygmt/src/coast.py:        Select filling or clipping of “wet” areas.
pygmt/src/grdtrack.py:    ``interpolation``; Default uses “natural” conditions (second partial
```

**Comment by shahid-0** [comment]
i will ready to  take this issue

**Comment by seisman** [comment]
@shahid-0 Thanks for your help! Let us know if you need help.

**Comment by adii095** [comment]
Can we create a new python file that goes through all the above files in the directory and then replaces occurrences of non-ASCII double quotes to ASCII as requested? Is that the way to do it?

**Comment by seisman** [comment]
The easiest way is to edit the above files manually. Of course, you can write a simple Python or Shell script to do the job automatically.

**Comment by shahid-0** [comment]
Hi I create the python file and change the code but when I push the file to the repository this will me this issue "error: failed to push some refs" so as a beginner I don't know how to resolve this issue

**Comment by core-man** [comment]
> Hi I create the python file and change the code but when I push the file to the repository this will me this issue "error: failed to push some refs" so as a beginner I don't know how to resolve this issue
> can you please help me what is the issue

Could you present the git commands you use? Or you could refer to Aaron Meurer's [tutorial on the git workflow](https://www.asmeurer.com/git-workflow/).
