### ISSUE TITLE
Change the title of the "Set the region" and "Plot lines" tutorials

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1134]
The PyGMT documentation has several tutorials (see the User Guide in the sidebar on https://www.pygmt.org/dev/). Most of the tutorials have titles like "Plotting XXX", "Adding XXX", or "Creating XXX", except for two tutorials.

- The title of the [lines.py](https://github.com/GenericMappingTools/pygmt/blob/master/examples/tutorials/lines.py) tutorial is "Plot lines", and should be changed to "Plotting lines".
- The title of the [regions.py](https://github.com/GenericMappingTools/pygmt/blob/master/examples/tutorials/regions.py) tutorial is "Set the region", and should be change to "Setting the region".

**Comment by iamayushdas** [comment]
Assign this to me
