### ISSUE TITLE
Update CSS for sphinx_rtd_theme 0.5.1

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1151]
**Description of the problem**

#1150 updated sphinx_rtd_theme to 0.5.1, which fixed the search problem but added unnecessary whitespace to the parameters section (see https://github.com/GenericMappingTools/pygmt/pull/629 for context). The custom CSS in `doc/_static/style.css` should be updated for improved appearance with the latest sphinx_rtd_theme release.

**Comment by meghanrjones** [comment]
I can update the custom CSS, but probably will not have time to do so right away. Anyone is welcome to comment or self-assign if they are interested in addressing this issue instead.

**Comment by weiji14** [comment]
Just mentioning that #1174 (see https://github.com/GenericMappingTools/pygmt/pull/1174#discussion_r606914578) may need to be backported to the gh-pages too, and can be done alongside the backport of #1150 (see https://github.com/GenericMappingTools/pygmt/pull/1150#issuecomment-811053780). But no rush on this, GMT 6.2.0 comes first :slightly_smiling_face:
