### ISSUE TITLE
Remove the extra period from the copyright information in the footer

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1152]
If you visit the PyGMT dev documentation (https://www.pygmt.org/dev/) and scroll down to the bottom, you will see there are two periods after "The PyGMT Developers" in the copyright (see the screenshot below):

![image](https://user-images.githubusercontent.com/3974108/113226810-14983580-925f-11eb-81ed-04269345fdbd.png)

One period is hard-coded in the sphinx_rtd_theme template (v0.5.1) and another one is from the `copyright` variable in the `conf.py` file.

We need to remove the extra period. The fix is very simple, just need to modify the [`conf.py`](https://github.com/GenericMappingTools/pygmt/blob/master/doc/conf.py) file and remove the trailing period from the following line: 

https://github.com/GenericMappingTools/pygmt/blob/0e64122f256337f253ed36595b84fe143e1935a9/doc/conf.py#L120

**Comment by itsabhianant** [comment]
Hi @seisman,

I have read the issue and also got how to fix it. I really want to fix this issue. Could you please assign this to me?

Best, 
Abhishek

**Comment by seisman** [comment]
@itsabhianant Great. Assigned to you.
