### ISSUE TITLE
Create new gallery category "Histogram"

### ISSUE THREAD

**Issue by michaelgrund** [GenericMappingTools/pygmt#1156]
**Description of the desired feature**

As discussed in #876 and mentioned in #794 (rose wrapper) we should add a new category "Histogram" to the gallery in which we store e.g. the rose and histogram (#1072) examples.

**Are you willing to help implement and maintain this feature?** Yes, but volunteers are welcome.

**Comment by seisman** [comment]
To create the new "histogram" gallery category, you need to:

- create a directory `examples/gallery/histograms`
- Add a `README.txt` in the directory `examples/gallery/histograms`
- Add the path to the [`conf.py`](https://github.com/GenericMappingTools/pygmt/blob/e131d26f9666bb28aa11d938f232f30036791976/doc/conf.py#L72) file
- Move the example [`rose.py`](https://github.com/GenericMappingTools/pygmt/blob/master/examples/gallery/embellishments/rose.py) to the directory `examples/gallery/histograms`

See https://github.com/GenericMappingTools/pygmt/pull/1019 for an example PR.
