### ISSUE TITLE
Fix a "Title underline too short" warning in building the documentation

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1175]
**Description of the problem**

Building the documentation gives an warning:

```
doc/tutorials/vectors.rst:459: WARNING: Title underline too short.

Plot Circular Vectors
----------
```

As the warning says, the title underline is shorter than the title "Plot Circular Vectors".

The fix is simple.

- Go to file [doc/tutorials/vectors.rst](https://github.com/GenericMappingTools/pygmt/blob/master/examples/tutorials/vectors.py)
- Scroll down to line 254
- Add more underlines so that the underlines is the same length as the title.

**Comment by xdshivani** [comment]
I would like to work on this.

**Comment by seisman** [comment]
@xdshivani Great! Let me know if you need any help. 

Just a tip before you start your first contribution: when submit your pull request, it would be better to create a new branch for your changes, instead of committing the changes directly to your own master branch.
