### ISSUE TITLE
Wrong style of toctree caption due to breaking changes in docutils 0.17

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1176]
**Description of the problem**

Go to https://www.pygmt.org/dev/, you will see:

![image](https://user-images.githubusercontent.com/3974108/113537087-b09aa780-95a5-11eb-84f5-89348e1fdd88.png)

The toctree captions don't show correctly, dut to breaking changes in docutils 0.17.

See related bug reports and possible fixes:

- https://github.com/readthedocs/sphinx_rtd_theme/issues/1112
- https://github.com/readthedocs/sphinx_rtd_theme/issues/1111
- https://github.com/sphinx-doc/sphinx/issues/9001
- https://github.com/sphinx-doc/sphinx/pull/9059

I think we need to pin docutils to 0.16 as a workaround, and wait for upstream fixes. Agree?

**Comment by weiji14** [comment]
> I think we need to pin docutils to 0.16 as a workaround, and wait for upstream fixes. Agree?

Since this only affects the `dev` doc page, I would wait for 24-48 hours to see if `docutils` does a bugfix release that would resolve things automatically.

**Comment by seisman** [comment]
More problems due to docutils 0.17:

![image](https://user-images.githubusercontent.com/3974108/113599428-9942d500-960c-11eb-8d4b-03c66e1c6634.png)

![image](https://user-images.githubusercontent.com/3974108/113599457-a52e9700-960c-11eb-80b1-0cf0c7302429.png)

**Comment by meghanrjones** [comment]
All the lists are messed up as well: https://www.pygmt.org/dev/changes.html. Since there are so many problems, I think pinning to a prior version is appropriate rather than waiting.

**Comment by seisman** [comment]
Yes to me.

**Comment by meghanrjones** [comment]
I think we can close this now, correct?
