### ISSUE TITLE
Remove "Full test" section from the installation guide

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1200]
The [installation guide](https://www.pygmt.org/v0.3.1/install.html#full-test-optional) provides commands to run the PyGMT full test:
```
import pygmt
pygmt.show_versions()
pygmt.test()
```

The commands no longer work since we just migrated all baseline images to DVC (#1036, #1131), and the source and binary distributions no longer contain the baseline images (#1086).

Users who install PyGMT using conda or pip won't have baseline images in their PyGMT installation directory, and there is no easy to download these baseline images automatically without negative effects (https://github.com/GenericMappingTools/pygmt/issues/1111#issuecomment-817077710). So it means users won't be able to run full tests anymore.

On the other hand, running full tests is unnecessary for most users:

- PyGMT should work correctly if the [quick check](https://www.pygmt.org/v0.3.1/install.html#quick-check) passes
- Users may use different GMT versions, thus some tests may break. The failing tests may cause more confusion 

I think we should remove the "Full test" section from the installation instructions. 

Comments?

**Comment by core-man** [comment]
Sounds good. I never ran the full test for the software used in my studies.

**Comment by meghanrjones** [comment]
Agreed, sounds good.
