### ISSUE TITLE
Installation using Miniconda needs additional required package "tbb"

### ISSUE THREAD

**Issue by leonfoks** [GenericMappingTools/pygmt#1294]
**Description of the problem**

Install issues on Mac OSX using Miniconda (not anaconda) distribution.
I followed the conda install instructions, added $HOME/miniconda3/lib to GMT_LIBRARY_PATH and still had issues. 
tbb comes automatically with the Anaconda distribution but not the Miniconda distribution, therefore libtbb could not be found from libtiledb.

The solution was to add "tbb" to the list of packages before installing gmt, and then pygmt.
i.e. numpy pandas xarray netcdf4 packaging tbb gmt

It's pretty minor, but it might be worth adding tbb to the install instructions.
Cheers!

**Full code that generated the error**

```python
import pygmt
```

**Full error message**

```
dyld: Library not loaded: @rpath/libtbb.dylib
  Referenced from: /Users/nfoks/miniconda3/lib/libtiledb.dylib
  Reason: image not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nfoks/miniconda3/lib/python3.8/site-packages/pygmt/__init__.py", line 51, in <module>
    _begin()
  File "/Users/nfoks/miniconda3/lib/python3.8/site-packages/pygmt/session_management.py", line 16, in begin
    with Session() as lib:
  File "/Users/nfoks/miniconda3/lib/python3.8/site-packages/pygmt/clib/session.py", line 184, in __enter__
    self.create("pygmt-session")
  File "/Users/nfoks/miniconda3/lib/python3.8/site-packages/pygmt/clib/session.py", line 331, in create
    c_create_session = self.get_libgmt_func(
  File "/Users/nfoks/miniconda3/lib/python3.8/site-packages/pygmt/clib/session.py", line 283, in get_libgmt_func
    self._libgmt = load_libgmt()
  File "/Users/nfoks/miniconda3/lib/python3.8/site-packages/pygmt/clib/loading.py", line 59, in load_libgmt
    raise GMTCLibNotFoundError("\n".join(error_msg))
pygmt.exceptions.GMTCLibNotFoundError: Error loading GMT shared library at 'libgmt.dylib'.
dlopen(libgmt.dylib, 6): Library not loaded: @rpath/libtbb.dylib
  Referenced from: /Users/nfoks/miniconda3/lib/libtiledb.dylib
  Reason: image not found
```

**System information**

Please paste the output of `python -c "import pygmt; pygmt.show_versions()"`:

```
PyGMT information:
  version: v0.3.1
System information:
  python: 3.8.5 (default, Sep  4 2020, 02:22:02)  [Clang 10.0.0 ]
  executable: /Users/nfoks/miniconda3/bin/python
  machine: macOS-10.14.6-x86_64-i386-64bit
Dependency information:
  numpy: 1.20.3
  pandas: 1.0.5
  xarray: 0.18.2
  netCDF4: 1.5.6
  packaging: 20.9
  ghostscript: 9.54.0
  gmt: 6.1.1
GMT library information:
  binary dir: /Users/nfoks/miniconda3/bin
  cores: 8
  grid layout: rows
  library path: /Users/nfoks/miniconda3/lib/libgmt.dylib
  padding: 2
  plugin dir: /Users/nfoks/miniconda3/lib/gmt/plugins
  share dir: /Users/nfoks/miniconda3/share/gmt
  version: 6.1.1
```

**Comment by weiji14** [comment]
HI @leonfoks, could you provide the full output from running `conda list`? I'm wondering if there's another dependency interfering with the install on miniconda. Two possible issues I spotted were:

1. The installed `pandas` version (1.0.5) is about a year old, the most recent one is 1.2.4 (which is why I suspect there could be a package conflict somewhere).
2. Adding `$HOME/miniconda3/lib` to `GMT_LIBRARY_PATH` shouldn't be needed if you did `conda activate pygmt`.

We'll check if other macOS users can reproduce this too. Cc @seisman if you have time.

**Comment by leonfoks** [comment]
Aha! that worked. I think my folly was forgetting to activate the environment. Using the pygmt env installed Pandas 1.2.4 and it worked fine! Sorry about that and thanks for getting back so quickly.

**Comment by weiji14** [comment]
Glad to help out, and thanks for trying out PyGMT :grin:
