### ISSUE TITLE
Some rose tests are wrong

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1315]
**Description of the problem**

_The issue was first reported in https://github.com/GenericMappingTools/gmt/pull/5289#issuecomment-852667972._

The GMT `rose` module expects *length* and *azimuth*. 

The sample data `@fractures_06.txt` contains *azimuth*,*length*. When writing the `load_fractures_compilation` function, we decided to return *length*,*azimuth*, rather than *azimuth*,*length*, so that the rose tests don't need to swap the columns. However, when writing the tests, we incorrectly used `incols=[1, 0]`, which swaps the columns to *azimuth*,*length* again. 

The baseline images are correct because the **-i** option doesn't work as expected due to an upstream bug (fixed in https://github.com/GenericMappingTools/gmt/pull/5289). Thus, after the fix, the `incols=[1, 0]` parameter is no longer needed.

We need to fix these rose tests after bumping to GMT 6.2.0.

**Comment by michaelgrund** [comment]
> 
> 
> **Description of the problem**
> 
> _The issue was first reported in [GenericMappingTools/gmt#5289 (comment)](https://github.com/GenericMappingTools/gmt/pull/5289#issuecomment-852667972)._
> 
> The GMT `rose` module expects _length_ and _azimuth_.
> 
> The sample data `@fractures_06.txt` contains _azimuth_,_length_. When writing the `load_fractures_compilation` function, we decided to return _length_,_azimuth_, rather than _azimuth_,_length_, so that the rose tests don't need to swap the columns. However, when writing the tests, we incorrectly used `incols=[1, 0]`, which swaps the columns to _azimuth_,_length_ again.
> 
> The baseline images are correct because the **-i** option doesn't work as expected due to an upstream bug (fixed in [GenericMappingTools/gmt#5289](https://github.com/GenericMappingTools/gmt/pull/5289)). Thus, after the fix, the `incols=[1, 0]` parameter is no longer needed.
> 
> We need to fix these rose tests after bumping to GMT 6.2.0.

Good catch @seisman.

**Comment by seisman** [comment]
> If it's ok, I would self-assign this issue to myself and fix it after bumping to GMT 6.2.0.

Yes, assign it to @michaelgrund.
