### ISSUE TITLE
No module issue when importing pygmt

### ISSUE THREAD

**Issue by BRseis** [GenericMappingTools/pygmt#1326]
Hi, 
I'm new to gmt and pygmt.
I tried installing it according the scripts for anaconda but when i try to test it it doesn't recognize pygmt as a module.
Removed and reinstalled anaconda and its packages and then reinstalled pygmt.
Now i got pygmt as a kernel but yet i get the same result when i try to import pygmt .
I am using windows 10.
![image](https://user-images.githubusercontent.com/85621008/121348035-24e82300-c928-11eb-93c6-6e2a9a12e3ac.png)
I would appreciate any help

**Comment by core-man** [comment]
Did you activate the environment within which you install pygmt, e.g., run `conda activate pygmt`

**Comment by BRseis** [comment]
yes I did.
checked to make sure...
![image](https://user-images.githubusercontent.com/85621008/121358050-95943d00-c932-11eb-9520-e991ba06b7b5.png)

**Comment by core-man** [comment]
How about running `import PyGMT` under pygmt environment using PowerShell directly.

**Comment by meghanrjones** [comment]
It could be a path error. If you type `which python` after activating the conda environment, the path should show python inside the conda env, rather than a different python installation.

p.s. Welcome to the community! For future questions, please post in the PyGMT Q&A section of the [user forum](https://forum.generic-mapping-tools.org/c/questions/pygmt-q-a/11). You are welcome to post bug reports/feature requests here on GitHub.

**Comment by BRseis** [comment]
> It could be a path error. If you type `which python` after activating the conda environment, the path should show python inside the conda env, rather than a different python installation. (edit: this might be `where python` for Windows).
> 
> p.s. Welcome to the community! For future questions, please post in the PyGMT Q&A section of the [user forum](https://forum.generic-mapping-tools.org/c/questions/pygmt-q-a/11). You are welcome to post bug reports/feature requests here on GitHub.

thank you.
I will try their forum too.

P.S. i tried, nothing changed...
![image](https://user-images.githubusercontent.com/85621008/121362425-5ec02600-c936-11eb-8302-f20a10eea056.png)

**Comment by seisman** [comment]
The same issue was posted on the forum (https://forum.generic-mapping-tools.org/t/no-module-issue-when-importing-pygmt/1769). 

I'm closing the issue.

**Comment by BRseis** [comment]
I opened the issue there since you guys instructed me to address there...

**Comment by meghanrjones** [comment]
> I opened the issue there since you guys instructed me to address there...

Yes, thank you for opening the issue on the forum. We'll continue the conversation over there.
