### ISSUE TITLE
Release PyGMT v0.4.0

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1333]
**Release**: [v0.4.0](https://github.com/GenericMappingTools/pygmt/milestones/6)
**Scheduled Date**: 2021/06/20
**Pull request due date**: 2021/06/18

**Priority PRs/issues to complete prior to release**
- [x] Reinstall optional geopandas dependency on CI tests (https://github.com/GenericMappingTools/pygmt/pull/1331)
- [x] Specify rectangle's width and height via style parameter in multi-parameter symbols example (https://github.com/GenericMappingTools/pygmt/pull/1325)
- [x] Allow x/y/z input for blockmedian and blockmean (https://github.com/GenericMappingTools/pygmt/pull/1319)
- [x] Raise a warning for the use of short-form parameters when long-forms are available (https://github.com/GenericMappingTools/pygmt/pull/1316)
- [x] Update grdfill parameters (https://github.com/GenericMappingTools/pygmt/pull/1283)
- [x] Support tab completion by inserting aliases into the method signature (https://github.com/GenericMappingTools/pygmt/pull/1282)
- [x] Figure.plot3d: Deprecate parameter "columns" to "incols" (remove in v0.6.0) (https://github.com/GenericMappingTools/pygmt/pull/1040)

**Before release**:
- [x] Reserve a DOI on [Zenodo](https://zenodo.org) by clicking on "New Version" @weiji14
- [x] Finish up 'Changelog entry for v0.x.x' Pull Request: @meghanrjones
  - [x] Add a new entry in `doc/_static/version_switch.js` for documentation switcher
  - [x] Update citation information https://github.com/GenericMappingTools/pygmt#citing-pygmt
  - [x] Add the documentation link https://github.com/GenericMappingTools/pygmt#documentation-for-other-versions
  - [x] Add compatibility information https://github.com/GenericMappingTools/pygmt#compatibility-with-python-and-gmt-versions
  - [x] Copy draft changelog from Release Drafter and edit it to look nice

**Release**:
- [x] At the [PyGMT release page on GitHub](https://github.com/GenericMappingTools/pygmt/releases):
  - [x] Edit the draft release notes with the finalized changelog
  - [x] Set the tag version and release title to vX.Y.Z
  - [x] Make a release by clicking the 'Publish Release' button, this will automatically create a tag too
- [x] Manually upload the pygmt-vX.Y.Z.zip and baseline-images.zip files to https://zenodo.org/deposit, ensure that it is filed under the correct reserved DOI

**After release**:
- [x] Update conda-forge [pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) [Usually done automatically by conda-forge's bot] (https://github.com/conda-forge/pygmt-feedstock/pull/17)
- [x] Bump PyGMT version on https://github.com/GenericMappingTools/try-gmt (@meghanrjones, https://github.com/GenericMappingTools/try-gmt/pull/23)
- [x] Announce the release on:
  - [x] GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (https://forum.generic-mapping-tools.org/t/pygmt-v0-4-0-released)
  - [x] [Major/Minor releases only] GMT [website](https://github.com/GenericMappingTools/website) (News) @michaelgrund
  - [x] [ResearchGate](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools) @michaelgrund
  - [x] [Twitter](https://twitter.com/gmt_dev) (https://twitter.com/gmt_dev/status/1406864460124463106)
---

- [x] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by meghanrjones** [comment]
There was discussion at the community meeting about a GMT 6.2.1 release depending on the outcome of https://github.com/GenericMappingTools/gmt/issues/5343. If that ends up being needed, I think we may want to delay PyGMT v0.4.0 so that GMT 6.2.1 is required rather than 6.2.0.

**Comment by weiji14** [comment]
> There was discussion at the community meeting about a GMT 6.2.1 release depending on the outcome of [GenericMappingTools/gmt#5343](https://github.com/GenericMappingTools/gmt/issues/5343). If that ends up being needed, I think we may want to delay PyGMT v0.4.0 so that GMT 6.2.1 is required rather than 6.2.0.

The histogram bug does look bad, but I'm still reluctant to postpone the release any further as SciPy sprints are coming up (17-18 July). There is a degree of flexibility between PyGMT and GMT versions, and `histogram` users could install GMT 6.2.1 (once that gets released) to have the bugfix. But I'll defer to the rest of the team on whether we should wait a bit longer.

P.S. I've reserved the Zenodo DOI for PyGMT v0.4.0 (10.5281/zenodo.4978645).

**Comment by core-man** [comment]
> `histogram` users could install GMT 6.2.1 (once that gets released) to have the bug fix.

I agree with this point, so I also prefer to release the PyGMT as the current plan.

**Comment by michaelgrund** [comment]
> 
> 
> > `histogram` users could install GMT 6.2.1 (once that gets released) to have the bug fix.
> 
> I agree with this point, so I also prefer to release the PyGMT as the current plan.

Same opinion.

**Comment by meghanrjones** [comment]
Sounds good for keeping to the current schedule. I will update the changelog tomorrow.

**Comment by michaelgrund** [comment]
Although I'm limited in time this weekend, I could make the announcements on the webiste and Researchgate.

**Comment by core-man** [comment]
FYI, I made a rough news draft at hackmd: https://hackmd.io/@pygmt/v0-4-0_announcement. I mainly copied it from [v0-3-1_announcement](https://hackmd.io/@pygmt/v0-3-1_announcement), removed some finished tasks and added only a little about v0-4-0.

**Comment by michaelgrund** [comment]
> 
> 
> FYI, I made a rough news draft at hackmd: https://hackmd.io/@pygmt/v0-4-0_announcement. I mainly copied it from [v0-3-1_announcement](https://hackmd.io/@pygmt/v0-3-1_announcement), removed some finished tasks and added only a little about v0-4-0. We could polish it later after we finish #1341.

Already updated some points and added a few comments.

**Comment by weiji14** [comment]
Woohoo, thanks team! PyGMT v0.4.0's Zenodo DOI now works at https://doi.org/10.5281/zenodo.4978645. Let's wait for the conda package update to come in first and then we can make the announcement.

**Comment by michaelgrund** [comment]
Announcements on website (PR needs to be accepted) and Researchgate are done!

**Comment by weiji14** [comment]
Should have mentioned that the forum post needs to go up first :sweat_smile: @core-man do you want to do the forum announcement? I'll do the tweet afterwards.

**Comment by core-man** [comment]
> Should have mentioned that the forum post needs to go up first  @core-man do you want to do the forum announcement? I'll do the tweet afterwards.

Sound good. I can do the forum announcement.

**Comment by michaelgrund** [comment]
> 
> 
> Should have mentioned that the forum post needs to go up first 😅 @core-man do you want to do the forum announcement? I'll do the tweet afterwards.

Ah damn, so the link to the forum post on Researchgate does not work yet 😅.

**Comment by core-man** [comment]
> > Should have mentioned that the forum post needs to go up first sweat_smile @core-man do you want to do the forum announcement? I'll do the tweet afterwards.
> 
> Ah damn, so the link to the forum post on Researchgate does not work yet .

Maybe we should add this point in the release template next time.

**Comment by core-man** [comment]
It seems that I don't have the access to make an announcement now. Could anyone help do it? I could help next time. :smile:
![](https://user-images.githubusercontent.com/50591376/122714770-74204300-d29a-11eb-94aa-ec05b93f5573.png)

**Comment by weiji14** [comment]
> It seems that I don't have the access to make an announcement now. Could anyone help do it @michaelgrund @weiji14? I could help make the announcement for the next release v0.5.0 or v0.4.1 :smile:
> ![](https://user-images.githubusercontent.com/50591376/122714770-74204300-d29a-11eb-94aa-ec05b93f5573.png)
> 

Ah ok, forgot that only moderators can post. I'll do it in a few mins.

**Comment by weiji14** [comment]
Alright, announcements are up at https://forum.generic-mapping-tools.org/t/pygmt-v0-4-0-released and https://twitter.com/gmt_dev/status/1406864460124463106 :partying_face:

**Comment by seisman** [comment]
Great work!

**Comment by meghanrjones** [comment]
Thanks for your hard work, everyone! Great to see this out! I will open a PR updating the maintenance guide and issue template with some lessons from this release cycle, likely later today.
