### ISSUE TITLE
Gallery/tutorial example showing how to use different colormaps for subplots

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1338]
**Description of the desired feature**

I think it would be worthwhile to add @seisman's example from the forum (https://forum.generic-mapping-tools.org/t/different-colorbars-for-subplots/1797/8) or something similar as either a gallery example or part of a tutorial, showing how to use set_panel to apply different colormaps to subplots. This is probably a common use-case case for PyGMT, but not obvious without an example.

**Comment by michaelgrund** [comment]
Fully agree, having an example on this will avoid a lot of confusion, especially for non-experienced GMT users.

**Comment by core-man** [comment]
I will help with this issue but might need some time to finish it so I self-assign it to me if you wouldn't mind. I might prefer a gallery example.

**Comment by meghanrjones** [comment]
> I will help with this issue but might need some time to finish it so I self-assign it to me if you wouldn't mind. I might prefer a gallery example.

Great, thanks @core-man!
