### ISSUE TITLE
Add gallery/tutorial for Figure.contour()

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1340]
The [contour](https://www.pygmt.org/dev/api/generated/pygmt.Figure.contour.html) method currently does not have any gallery plots or tutorial examples that show how it is used. 

The options to fix this include 1) adding a new gallery example for contouring table data or 2) adding a section to the [create a map with contour lines](https://www.pygmt.org/dev/tutorials/contour_map.html) tutorial that shows how to create a contour map from table data rather than gridded data.

Details for adding gallery plots and tutorial examples are in the [contributing guide](https://www.pygmt.org/dev/contributing.html).

**Comment by weiji14** [comment]
Ping @yohaimagen who's requested to work on this issue for the SciPy2021 sprint :smile:

**Comment by yohaimagen** [comment]
I think the [gallery example for contour](https://pygmt-git-fork-yohaimagen-contour-gallery-example-gmt.vercel.app/gallery/lines/contours.html#sphx-glr-gallery-lines-contours-py) is done, let me know if you think there is anything else I should add to it.
