### ISSUE TITLE
Remove the "documentation for other versions" section from the README file

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1358]
The "documentation for other versions" section in the README file is becoming longer as we release more versions:

![image](https://user-images.githubusercontent.com/3974108/123339960-81973080-d519-11eb-814d-22c4691c11d8.png)

Since we already have a version switcher on the main site, and the version switcher is easy to use, I think we can remove the "documentation for other versions" section from the README file.

![image](https://user-images.githubusercontent.com/3974108/123339930-76440500-d519-11eb-83a9-5aa831dfaccf.png)

**Comment by core-man** [comment]
Sound good.
- PyGMT users could find documentation of different versions using the version switcher on the main site.
- PyGMT contributors/maintainers could find the version records at [/doc/_static/version_switch.js](https://github.com/GenericMappingTools/pygmt/blob/master/doc/_static/version_switch.js)

**Comment by seisman** [comment]
I'll mark it as "good first issue" and "first-timer-only" if @GenericMappingTools/pygmt-maintainers have no objections.

**Comment by weiji14** [comment]
Alternatively, we could link to the old version docs page at the Compatibility with GMT/Python/NumPy versions table? I feel like keeping a proper link somewhere is good, since the Javascript dropdown isn't very accessible, and can't be used in some places like the PyPI page.

**Comment by seisman** [comment]
> Alternatively, we could link to the old version docs page at the Compatibility with GMT/Python/NumPy versions table? I feel like keeping a proper link somewhere is good, since the Javascript dropdown isn't very accessible, and can't be used in some places like the PyPI page.

I just recalled your accessibility concern at https://github.com/GenericMappingTools/pygmt/pull/621#discussion_r491674861.

> just pointing out that the dropdown isn't super-accessible. I managed to tab-tab-tab my way to the version changer dropdown (with the benefit of sight), and change to a different version of the documentation by pressing up/down with my arrow keys (only once though, it doesn't seem to allow scrolling through the list of options).

Could you explain more about the dropdown accessibility? What do you expect?

**Comment by weiji14** [comment]
> Could you explain more about the dropdown accessibility? What do you expect?

Thanks for digging up that comment :) I expect that someone using **only** their keyboard can access other versions of PyGMT's documentation.

**Comment by seisman** [comment]
> I expect that someone using **only** their keyboard can access other versions of PyGMT's documentation.

I think it already works, no? I can use `Tab` to navigate the PyGMT site and also use up-down keys to select specific versions.

**Comment by weiji14** [comment]
> > I expect that someone using **only** their keyboard can access other versions of PyGMT's documentation.
> 
> I think it already works, no? I can use `Tab` to navigate the PyGMT site and also use up-down keys to select specific versions.

Maybe it work on your browser? On Firefox for me, I can only use Tab to select one version above or below the current one as mentioned in https://github.com/GenericMappingTools/pygmt/pull/621#discussion_r491674861. If I'm at v0.3.1, it jumps directly to v0.4.0 or v0.3.0 if I press the up or down button (this is before I press Enter). So if I want to go to v0.1.2, I need to tab to the version switcher, press down, let the page reload to the new version, and repeat 4 times to go from v0.4.0 -> v0.3.1 -> v0.3.0 -> v0.2.1 -> v0.1.2.

**Comment by seisman** [comment]
It works well for me on Microsoft Edge, Safari, but not on Firefox.

**Comment by weiji14** [comment]
Ok, if we do want to remove it, maybe we could put the old links at the Compatibility table as I mentioned in https://github.com/GenericMappingTools/pygmt/issues/1358#issuecomment-868808505, so that it looks like this:

![image](https://user-images.githubusercontent.com/23487320/123895540-18e60300-d9b4-11eb-990e-aa795b14dd76.png)

i.e. have every minor version point to the latest patch release, e.g. v0.4.x points to v0.4.0, v0.3.x points to v0.3.1 and so on

```diff
@@ -234,12 +234,12 @@ Documentation for other versions
 Compatibility with GMT and Python/NumPy versions
 ------------------------------------------------
 
-======= ========== ========= =========
-PyGMT   GMT        Python    NumPy
-======= ========== ========= =========
-0.4.x   >=6.2.0    >=3.7     >=1.17.0
-0.3.x   >=6.1.1    >=3.7
-0.2.1   >=6.1.1    >=3.6
-0.2.0   >=6.1.1    3.6 - 3.8
-0.1.x   >=6.0.0    3.6 - 3.8
-======= ========== ========= =========
+========================================== ========== ========= =========
+PyGMT                                      GMT        Python    NumPy
+========================================== ========== ========= =========
+`v0.4.x <https://www.pygmt.org/v0.4.0>`__  >=6.2.0    >=3.7     >=1.17.0
+`v0.3.x <https://www.pygmt.org/v0.3.1>`__  >=6.1.1    >=3.7
+`v0.2.1 <https://www.pygmt.org/v0.2.1>`__  >=6.1.1    >=3.6
+`v0.2.0 <https://www.pygmt.org/v0.2.0>`__  >=6.1.1    3.6 - 3.8
+`v0.1.x <https://www.pygmt.org/v0.1.2>`__  >=6.0.0    3.6 - 3.8
+========================================== ========== ========= =========
```

**Comment by core-man** [comment]
> On Firefox for me (edit: same issue on Brave browser), I can only use Tab to select one version above or below the current one as mentioned in [#621 (comment)](https://github.com/GenericMappingTools/pygmt/pull/621#discussion_r491674861). If I'm at v0.3.1, it jumps directly to v0.4.0 or v0.3.0 if I press the up or down button (this is before I press Enter). So if I want to go to v0.1.2, I need to tab to the version switcher, press down, let the page reload to the new version, and repeat 4 times to go from v0.4.0 -> v0.3.1 -> v0.3.0 -> v0.2.1 -> v0.1.2.

Same with me. I use CentOS7.5 and Google Chrome.

> Ok, if we do want to remove it, maybe we could put the old links at the Compatibility table as I mentioned in #1358 (comment), so that it looks like this:

Sounds good.

**Comment by willschlitzer** [comment]
> Ok, if we do want to remove it, maybe we could put the old links at the Compatibility table as I mentioned in [#1358 (comment)](https://github.com/GenericMappingTools/pygmt/issues/1358#issuecomment-868808505), so that it looks like this:

I think this looks much cleaner than the old version; I'm a fan!

**Comment by seisman** [comment]
> Ok, if we do want to remove it, maybe we could put the old links at the Compatibility table as I mentioned in [#1358 (comment)](https://github.com/GenericMappingTools/pygmt/issues/1358#issuecomment-868808505), so that it looks like this:
> 
> ![image](https://user-images.githubusercontent.com/23487320/123895540-18e60300-d9b4-11eb-990e-aa795b14dd76.png)
> 
> i.e. have every minor version point to the latest patch release, e.g. v0.4.x points to v0.4.0, v0.3.x points to v0.3.1 and so on
> 
> ```diff
> @@ -234,12 +234,12 @@ Documentation for other versions
>  Compatibility with GMT and Python/NumPy versions
>  ------------------------------------------------
>  
> -======= ========== ========= =========
> -PyGMT   GMT        Python    NumPy
> -======= ========== ========= =========
> -0.4.x   >=6.2.0    >=3.7     >=1.17.0
> -0.3.x   >=6.1.1    >=3.7
> -0.2.1   >=6.1.1    >=3.6
> -0.2.0   >=6.1.1    3.6 - 3.8
> -0.1.x   >=6.0.0    3.6 - 3.8
> -======= ========== ========= =========
> +========================================== ========== ========= =========
> +PyGMT                                      GMT        Python    NumPy
> +========================================== ========== ========= =========
> +`v0.4.x <https://www.pygmt.org/v0.4.0>`__  >=6.2.0    >=3.7     >=1.17.0
> +`v0.3.x <https://www.pygmt.org/v0.3.1>`__  >=6.1.1    >=3.7
> +`v0.2.1 <https://www.pygmt.org/v0.2.1>`__  >=6.1.1    >=3.6
> +`v0.2.0 <https://www.pygmt.org/v0.2.0>`__  >=6.1.1    3.6 - 3.8
> +`v0.1.x <https://www.pygmt.org/v0.1.2>`__  >=6.0.0    3.6 - 3.8
> +========================================== ========== ========= =========
> ```

I think we are OK with this solution. I have marked it as "good first issue" and add it to the v0.4.1 milestone.
