### ISSUE TITLE
Typos in the source code and documentation

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1361]
**Description of the problem**

Here are some small typos in the source code and documentation, which are easy to fix.

---

https://github.com/GenericMappingTools/pygmt/blob/8a9f622fc0aaac4bd8a7a4e0fba4b4afd85d615b/doc/maintenance.md#L174

Line 174 in `doc/maintenance.md`: "developement" should be "development".

----

https://github.com/GenericMappingTools/pygmt/blob/8a9f622fc0aaac4bd8a7a4e0fba4b4afd85d615b/examples/gallery/embellishments/solar.py#L6

Line 6 in `examples/gallery/embellishments/solar.py`: "nightime" should be "nighttime".

---

https://github.com/GenericMappingTools/pygmt/blob/8a9f622fc0aaac4bd8a7a4e0fba4b4afd85d615b/examples/tutorials/date_time_charts.py#L158

Line 158 in `examples/tutorials/date_time_charts.py`: "inital" should be "initial".

---

https://github.com/GenericMappingTools/pygmt/blob/8a9f622fc0aaac4bd8a7a4e0fba4b4afd85d615b/examples/tutorials/date_time_charts.py#L210

Line 210 in `examples/tutorials/date_time_charts.py`: "paramater" should be "parameter".

---

https://github.com/GenericMappingTools/pygmt/blob/8a9f622fc0aaac4bd8a7a4e0fba4b4afd85d615b/examples/tutorials/vectors.py#L352

Line 352 in `examples/tutorials/vectors.py`: "begining" should be "beginning".

---

https://github.com/GenericMappingTools/pygmt/blob/8a9f622fc0aaac4bd8a7a4e0fba4b4afd85d615b/pygmt/src/histogram.py#L101

Line 101 in `pygmt/src/histogram.py`: "horizonal" should be "horizontal".

**Comment by Jayita10** [comment]
I am trying to learn how open source work. Can I work on this issue?

**Comment by Jayita10** [comment]
@soham4abc good gesture from you :)

**Comment by soham4abc** [comment]
> @soham4abc good gesture from you :)

I am so sorry! I did not see anyone assigned yet to this issue thus I made a PR. I will be closing my pull Request! Please feel Free to contribute! Welcome to open source!

**Comment by soham4abc** [comment]
@Jayita10  go ahead its yours's!

**Comment by Jayita10** [comment]
Nopes @soham4abc, neither I am assigned to this task. You please reopen your PR. 
For the next time, make sure to check whether anyone claim for the issue or not before making a PR. Thanks :)

**Comment by soham4abc** [comment]
> Nopes @soham4abc, neither I am assigned to this task. You please reopen your PR.
> For the next time, make sure to check whether anyone claim for the issue or not before making a PR. Thanks :)

Done! And once again, sorry!

**Comment by seisman** [comment]
@soham4abc Thanks for your quick contribution.

@Jayita10 We may find another easy issue for you.
