### ISSUE TITLE
Clarify resolutions of Earth relief grids requiring the region parameter

### ISSUE THREAD

**Issue by core-man** [GenericMappingTools/pygmt#1375]
**Description of the problem**

See [load_earth_relief](https://www.pygmt.org/latest/api/generated/pygmt.datasets.load_earth_relief.html#pygmt.datasets.load_earth_relief):

> region (str or list) – The subregion of the grid to load, in the forms of a list [xmin, xmax, ymin, ymax] or a string xmin/xmax/ymin/ymax. Required for Earth relief grids with resolutions higher than 5 arc-minute (i.e., 05m).

https://github.com/GenericMappingTools/pygmt/blob/d90b3fc889b53633deab6b4ab77612ac7a247c1b/pygmt/datasets/earth_relief.py#L94-L95

So, `Higher than  5 arc-minute` means "04m", "03m", "02m", "01m", "30s", "15s", "03s", adn "01s"? But "05m" is actually high resolution relief data.

**Comment by willschlitzer** [comment]
Couldn't this just be rewritten to "with resolutions of 5 arc-minutes or higher"?

**Comment by core-man** [comment]
> Couldn't this just be rewritten to "with resolutions of 5 arc-minutes or higher"?

I think so.

**Comment by willschlitzer** [comment]
@core-man I tagged this as a good first issue; I think documentation fixes are a good introduction to open source contributing.

**Comment by core-man** [comment]
> @core-man I tagged this as a good first issue; I think documentation fixes are a good introduction to open source contributing.

Great.Thanks a lot.

**Comment by weiji14** [comment]
@srijac will be working on this today!
