### ISSUE TITLE
Possible bug with grdtrack?

### ISSUE THREAD

**Issue by hazardgoat** [GenericMappingTools/pygmt#1378]
**Description of the problem**
I have a TIF file with elevation data 0-50m, with small patches that have no elevation data at all. When coordinates from these gaps are used for `grdtrack`, instead of a null value or returning an error, it is returning elevation data that far exceeds what is contained in the TIF.

**Full code that generated the error**

```python
import os
import pygmt
import pandas as pd

main_dir = r'C:\Users\USER\Desktop\Project3'

soil_thickness_grid = os.path.join(main_dir, 'Data', 'soil_thickness.tif')

vs30_data = os.path.join(main_dir, 'Data', 'vs30.csv')

df_vs30_data = pd.read_csv(vs30_data)

points = pd.DataFrame()
points['longitude'] = df_vs30_data.Longitude
points['latitude'] = df_vs30_data.Latitude

track = pygmt.grdtrack(
    points = points, 
    grid = soil_thickness_grid, 
    newcolname = 'bedrock_depth'
)

print(track.loc[track['bedrock_depth'] == track.bedrock_depth.max()])
```

**Output of my program**
![Screenshot_5](https://user-images.githubusercontent.com/74040471/124802055-66aac000-df0c-11eb-99a5-dd19e0b86374.png)

**What ArcGIS says about the TIF and the coordinates**
![Screenshot_4](https://user-images.githubusercontent.com/74040471/124802205-8d68f680-df0c-11eb-85fd-ac5fc3ed114b.png)
![Screenshot_3](https://user-images.githubusercontent.com/74040471/124802237-98bc2200-df0c-11eb-9510-3bc6480b1ca3.png)

**System information**
PyGMT information:
  version: v0.4.0
System information:
  python: 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)]
  executable: C:\Users\USER\miniconda3\envs\project3\python.exe
  machine: Windows-10-10.0.19043-SP0
Dependency information:
  numpy: 1.21.0
  pandas: 1.2.5
  xarray: 0.18.2
  netCDF4: 1.5.7
  packaging: 21.0
  ghostscript: 9.54.0
  gmt: 6.2.0
GMT library information:
  binary dir: C:/Users/USER/miniconda3/envs/project3
  cores: 4
  grid layout: rows
  library path: C:/Users/USER/miniconda3/envs/project3/Library/bin/gmt.dll
  padding: 2
  plugin dir: C:/Users/USER/miniconda3/envs/project3/Library/bin/gmt_plugins
  share dir: c:/programs/gmt6/share
  version: 6.2.0

**Comment by weiji14** [comment]
So `grdtrack` uses bicubic interpolation by default. Could you try setting `interpolation="n"` for nearest neigbour, and see if you get NaN instead?

**Comment by hazardgoat** [comment]
> 
> 
> So `grdtrack` uses bicubic interpolation by default. Could you try setting `interpolation="n"` for nearest neigbour, and see if you get NaN instead?
> 
> You could also try adding `+c` to clip to the range of your grid. See https://docs.generic-mapping-tools.org/latest/gmt.html#n-full for more details.

Thank you! I'm *super new* to statistics and GIS, and I'm not familiar with how interpolation affects stuff. This fixed my problem.

**Comment by weiji14** [comment]
> Thank you! I'm _super new_ to statistics and GIS, and I'm not familiar with how interpolation affects stuff. This fixed my problem.

No problem, and good luck with learning GIS!
