### ISSUE TITLE
Support passing in pathlib.Path into pygmt modules

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#1381]
**Description of the desired feature**

_Originally posted by @liamtoney in https://github.com/GenericMappingTools/pygmt/issues/949#issuecomment-790796932_

> I'd add `Path` objects if they're not already supported. :)

The [`pathlib.Path`](https://docs.python.org/3.9/library/pathlib.html) is a cross-platform way of handling filepaths. Currently PyGMT supports passing in filenames as a `str`, but it would be good to ensure that `pathlib.Path` works too.

## What needs to be done :ballot_box_with_check:

1. This if-statement needs to be modified:

https://github.com/GenericMappingTools/pygmt/blob/11c13012c2c8a70006ac86d62e6f97f437451f82/pygmt/helpers/utils.py#L69-L70

2. Add some unit tests with `pathlib.Path` inputs, best placed in https://github.com/GenericMappingTools/pygmt/blob/master/pygmt/tests/test_info.py.

## How to make the change :monocle_face:

1. First, read up our contributing guidelines at https://www.pygmt.org/v0.4.0/contributing.html#editing-the-documentation
2. Leave a comment below, stating that you will tackle this issue. We will assign you to this issue and you can then start working on it.
3. To edit the utils.py file, go to https://github.com/GenericMappingTools/pygmt/edit/master/pygmt/helpers/utils.py and make the change!. Or you may want to do this in your code editor locally.
4. Submit a pull request, and be sure to fill it up with as much detail as possible.

**Are you willing to help implement and maintain this feature?** Happy to guide someone with some familiarity with Python Path objects to work on this. Will also be a great opportunity for someone wanting to learn how to write unit tests.

**Comment by aitorres** [comment]
Hi there! I could take this issue and make a PR with the changes :-)

**Comment by weiji14** [comment]
Thanks @aitorres, I've assigned you to this issue and will take a look at your PR shortly :)
