### ISSUE TITLE
Add gallery example for grdclip

### ISSUE THREAD

**Issue by willschlitzer** [GenericMappingTools/pygmt#1384]
**Description of the desired feature**

It would be great to have some **gallery examples** on using the `grdclip` function. This will be a follow up to #1261.

## Examples of what you can do

These are just suggestions of things that you can plot. Feel free to come up with other ideas!

1. Plot seafloor bathymetry and clip all land above sea level
2. Plot an island and remove all seafloor data

## How to make the change :monocle_face:

1. First, read up our contributing guidelines at https://www.pygmt.org/v0.4.0/contributing.html#editing-the-documentation
2. Leave a comment below, stating that you will tackle this issue. We will assign you to this issue and you can then start working on it.
3. Go to e.g. https://github.com/GenericMappingTools/pygmt/tree/master/examples/gallery/maps, and click on 'Add File'. Or you may want to do this in your code editor locally.
4. Submit a pull request, and be sure to fill it up with as much detail as possible.

**Are you willing to help implement and maintain this feature?** Yes! I'm happy to help someone learn how to contribute to PyGMT!

**Comment by seisman** [comment]
Closed by #1396.
