### ISSUE TITLE
Add returns section to grdclip docstring

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1388]
The docstring in `pygmt/src/grdclip.py` needs a 'Returns' section.

To fix this issue, copy and paste L82-89 in `pygmt/src/grdcut.py`:
https://github.com/GenericMappingTools/pygmt/blob/9efe3177bb0f3774eb5d0ac0e4b3957ff3eae6e9/pygmt/src/grdcut.py#L81-L89
to add a returns section between L70 and L71 in `pygmt/src/grdclip.py`:
https://github.com/GenericMappingTools/pygmt/blob/9efe3177bb0f3774eb5d0ac0e4b3957ff3eae6e9/pygmt/src/grdclip.py#L70-L71

A local development environment is not needed to address this issue (no installation required) :tada: Just follow these instructions for editing the documentation on GitHub: https://www.pygmt.org/dev/contributing.html#editing-the-documentation-on-github.

**Comment by kadatatlukishore** [comment]
Hey @meghanrjones , I can start on this and PR now. Thanks for the description !
