### ISSUE TITLE
Release PyGMT v0.4.1

### ISSUE THREAD

**Issue by core-man** [GenericMappingTools/pygmt#1402]
**Release**: [v0.4.1](https://github.com/GenericMappingTools/pygmt/milestone/10)
**Scheduled Date**: 2021/08/07
**Pull request due date**: 2021/08/05

**Priority PRs/issues to complete prior to release**
- [x] #1360
- [x] #1396 
- [x] #1358
- [x] #1407

**Before release**:
- [x] Reserve a DOI on [Zenodo](https://zenodo.org) by clicking on "New Version" @weiji14
- [x] Finish up 'Changelog entry for v0.x.x' Pull Request: @core-man
  - [x] Add a new entry in `doc/_static/version_switch.js` for documentation switcher
  - [x] Update citation information https://github.com/GenericMappingTools/pygmt#citing-pygmt
  - [x] Add the documentation link https://github.com/GenericMappingTools/pygmt#compatibility-with-gmtpythonnumpy-versions
  - [x] Add compatibility information https://github.com/GenericMappingTools/pygmt#compatibility-with-gmtpythonnumpy-versions
  - [x] Copy draft changelog from Release Drafter and edit it to look nice ([see maintainers guide for details](https://www.pygmt.org/dev/maintenance.html#updating-the-changelog))

**Release**:
- [x] At the [PyGMT release page on GitHub](https://github.com/GenericMappingTools/pygmt/releases): (@core-man)
  - [x] Edit the draft release notes with the finalized changelog
  - [x] Set the tag version and release title to vX.Y.Z
  - [x] Make a release by clicking the 'Publish Release' button, this will automatically create a tag too
- [x] Manually upload the pygmt-vX.Y.Z.zip and baseline-images.zip files to https://zenodo.org/deposit, ensure that it is filed under the correct reserved DOI

**After release**:
- [x] Update conda-forge [pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) [Usually done automatically by conda-forge's bot] https://github.com/conda-forge/pygmt-feedstock/pull/18
- [x] Bump PyGMT version on https://github.com/GenericMappingTools/try-gmt (after conda-forge update) https://github.com/GenericMappingTools/try-gmt/pull/27
- [x] Announce the release on:
  - [x] GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (do this announcement first! draft on https://hackmd.io/@pygmt. requires moderator status) @michaelgrund 
  - ~~[x] [Major/Minor releases only] GMT [website](https://github.com/GenericMappingTools/website) (News)~~
  - [x] [ResearchGate](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools) (after forum announcement) @core-man
  - [x] [Twitter](https://twitter.com/gmt_dev) (after forum announcement) https://twitter.com/gmt_dev/status/1424998701152444417
---

- [x] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by meghanrjones** [comment]
This was a last minute PR with a lot of text, so I understand if it's not possible, but otherwise it would be helpful to have https://github.com/GenericMappingTools/pygmt/pull/1407 reviewed for v0.4.1 in order to add more good first issues.

**Comment by meghanrjones** [comment]
Do we want https://github.com/GenericMappingTools/pygmt/issues/1358 finished for v0.4.1 or wait until after? I can submit a PR if it's important to include, but do not have a preference about timing.

**Comment by core-man** [comment]
> Do we want #1358 finished for v0.4.1 or wait until after? I can submit a PR if it's important to include, but do not have a preference about timing.

I think you could submit a PR to finish it for v0.4.1. Good first issues can still be found after v0.4.1.

**Comment by core-man** [comment]
I have drafted release news on https://hackmd.io/@pygmt/v0-4-1_announcement using v0.4.0 as a template. Please help polish it :smile: if possible.

**Comment by michaelgrund** [comment]
> 
> 
> I have drafted release news on https://hackmd.io/@pygmt/v0-4-1_announcement using v0.4.0 as a template. Please help polish it 😄 if possible.

Made a few adjustments and added a comment regarding the ESWN dates.

**Comment by weiji14** [comment]
Can you see the draft v0.4.1 release on https://github.com/GenericMappingTools/pygmt/releases @core-man? If not, we might need to get a maintainer like @michaelgrund to do the GitHub release/tag step.

**Comment by core-man** [comment]
> Can you see and edit the draft v0.4.1 release on https://github.com/GenericMappingTools/pygmt/releases @core-man? If not, we might need to get a maintainer like @michaelgrund to do the GitHub release/tag step.

Yes, I can edit it, and am doing it now.

**Comment by core-man** [comment]
> Set the tag version and release title to vX.Y.Z

I find release drafter will automatically set the `tag version` and `release title` so that we could add a note for this step?

**Comment by weiji14** [comment]
Great work @core-man! Zenodo DOI now works at https://doi.org/10.5281/zenodo.5162003 :tada:

> > Set the tag version and release title to vX.Y.Z
> 
> I find release drafter will automatically set the `tag version` and `release title` so that we could add a note for this step (good first issue)?

Yes it should be set to vX.Y.Z automatically. The main thing is to make sure that there is a `v`, so maybe we can change the wording of that step a little bit to clarify that?

> See [#1414 (comment)](https://github.com/GenericMappingTools/pygmt/pull/1414#issuecomment-894634432):
> 
> > Sounds good. Just want to make the 7 Aug 2021 deadline (specifically before it turns 8 Aug at UTC).
> 
> Do we want to set a default and exact time in UTC time for merging a changelog entry PR so that everyone is okay with that time and knows when we will merge the PR? Of course, it could be changed case by case.

Yeah, the timezone hasn't always been very clear in past releases, so we can be more explicit that the date refers to UTC. I think as long as we merge the changelog PR when it is still the day on UTC time (i.e. 7 Aug in this case) it should be fine.

I'm heading to bed now, but will help out with the rest of the post-release tasks tomorrow (8 Aug NZST).

**Comment by core-man** [comment]
> I'm heading to bed now, but will help out with the rest of the post-release tasks tomorrow (8 Aug NZST).

Thanks for your help~~~ Have a good sleep.

> Yes it should be set to vX.Y.Z automatically. The main thing is to make sure that there is a v, so maybe we can change the wording of that step a little bit to clarify that?

Good. I will submit an issue later to suggest revising it to be something like:

Make sure that the tag version and release title are automatically set to vX.Y.Z [there is a **v**]

**Comment by weiji14** [comment]
Ok, conda package is published, and try-gmt has been updated (thanks @seisman)! What's left should be just the announcements.

> > I have drafted release news on https://hackmd.io/@pygmt/v0-4-1_announcement using v0.4.0 as a template. Please help polish it smile if possible.
>
> Made a few adjustments and added a comment regarding the ESWN dates.

I've added in some new figures (gallery, team gallery, AGU abstract image) and moved a few things here and there. Let's wait for @meghanrjones to get back on Monday before posting this, I'm also interested on the ESWN workshop details.

> > Yes it should be set to vX.Y.Z automatically. The main thing is to make sure that there is a v, so maybe we can change the wording of that step a little bit to clarify that?
> 
> Good. I will submit an issue later to suggest revising it to be something like:
> 
> Make sure that the tag version and release title are automatically set to vX.Y.Z [there is a **v**]

:+1:. Also feel free to suggest other things you felt could be done to make the release process smoother (see similar previous PRs at #1346, #907).

**Comment by michaelgrund** [comment]
Except the open point regarding ESWN it looks good to me 😉.

**Comment by meghanrjones** [comment]
I added a comment on the hackmd draft in response to the ESWN workshop item, explaining that the original plan was to open the registration to all applicants. While we discuss if/how to make it even more open, I have generalized the bullet point to reflect that people can expect the final information through the Forum/Twitter.

**Comment by seisman** [comment]
The v0.4.1 announcement looks good to me.

**Comment by core-man** [comment]
The v0.4.1 announcement looks great~ :smile:

**Comment by michaelgrund** [comment]
Looks good to me. Do we want to share it across all our communication channels today?

**Comment by seisman** [comment]
> Looks good to me. Do we want to share it across all our communication channels today?

@michaelgrund I think you already have the permission to make posts in the ["Announcement" cateorgy](https://forum.generic-mapping-tools.org/c/news/), right? Do you want to do it this time?

**Comment by michaelgrund** [comment]
> 
> 
> > Looks good to me. Do we want to share it across all our communication channels today?
> 
> @michaelgrund I think you already have the permission to make posts in the ["Announcement" cateorgy](https://forum.generic-mapping-tools.org/c/news/), right? Do you want to do it this time?

Made the announcement in the [forum](https://forum.generic-mapping-tools.org/t/pygmt-v0-4-1-released).

**Comment by core-man** [comment]
Announcement has been made at [ResearchGate](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools).

**Comment by weiji14** [comment]
> > > Looks good to me. Do we want to share it across all our communication channels today?
> > 
> > 
> > @michaelgrund I think you already have the permission to make posts in the ["Announcement" cateorgy](https://forum.generic-mapping-tools.org/c/news/), right? Do you want to do it this time?
> 
> Made the announcement in the [forum](https://forum.generic-mapping-tools.org/t/pygmt-v0-4-1-released).

Thanks @michaelgrund! Tweet is also up at https://twitter.com/gmt_dev/status/1424998701152444417. Could you do the announcement on ResearchGate please @core-man and we should be able to close this issue :grin:

**Comment by seisman** [comment]
🥳 Nice teamwork! Close the issue and move on to the next release!
