### ISSUE TITLE
Cannot  import pygmt while virtual env not activated

### ISSUE THREAD

**Issue by yohaimagen** [GenericMappingTools/pygmt#1419]
pygmt is trying to use the system GMT instead of the virtual environment GMT if running the virtual environment interpreter while the virtual env is deactivated, and failing in my case because my system GMT version is 6.1. 
 I am installing pygmt as described [here](https://www.pygmt.org/latest/install.html)
```
$ conda create --name test_pygmt --channel conda-forge pygmt python=3.9
$ conda activate test_pygmt
(test_pygmt) $ python -c "import pygmt; pygmt.show_versions()"
PyGMT information:
  version: v0.4.0
System information:
  python: 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:36:15)  [Clang 11.1.0 ]
  executable: /Users/yohai/anaconda3/envs/test_pygmt/bin/python
  machine: macOS-10.14.6-x86_64-i386-64bit
Dependency information:
  numpy: 1.21.1
  pandas: 1.3.1
  xarray: 0.19.0
  netCDF4: 1.5.7
  packaging: 21.0
  ghostscript: 9.50
  gmt: 6.2.0
GMT library information:
  binary dir: /Users/yohai/anaconda3/envs/test_pygmt/bin
  cores: 12
  grid layout: rows
  library path: /Users/yohai/anaconda3/envs/test_pygmt/lib/libgmt.dylib
  padding: 2
  plugin dir: /Users/yohai/anaconda3/envs/test_pygmt/lib/gmt/plugins
  share dir: /Users/yohai/anaconda3/envs/test_pygmt/share/gmt
  version: 6.2.0
```
so far so good. but if I am doing the following:
```
(test_pygmt) $ conda deactivate  
(base) $ ~/anaconda3/envs/test_pygmt/bin/python -c "import pygmt; pygmt.show_versions()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/yohai/anaconda3/envs/test_pygmt/lib/python3.9/site-packages/pygmt/__init__.py", line 57, in <module>
    _begin()
  File "/Users/yohai/anaconda3/envs/test_pygmt/lib/python3.9/site-packages/pygmt/session_management.py", line 16, in begin
    with Session() as lib:
  File "/Users/yohai/anaconda3/envs/test_pygmt/lib/python3.9/site-packages/pygmt/clib/session.py", line 191, in __enter__
    raise GMTVersionError(
pygmt.exceptions.GMTVersionError: Using an incompatible GMT version 6.1.0. Must be equal or newer than 6.2.0.
```
I think that when the virtual env is not activated pygmt trying to run the system GMT instead of the virtual env GMT which is undesirable behavior. I myself encountered the issue when trying to work with the virtual env with PyCharm at least in that working environment when working with a virtual env what it actually doing is running `path/to/virtual/env/python some_pyhon.py` so actually cannot work in Pycharm directly with pygmt for now.

**Comment by weiji14** [comment]
Hi @yohaimagen, can you try following the suggestion at https://forum.generic-mapping-tools.org/t/pygmt-doesnt-run-on-pycharm-but-jupyter/1450/2? I.e. activate the conda environment in Pycharm following https://www.jetbrains.com/help/pycharm/conda-support-creating-conda-virtual-environment.html.

Alternatively, you can set the `GMT_LIBRARY_PATH` environment variable following https://www.pygmt.org/dev/install.html#finding-the-gmt-shared-library. In your case, the command should be `export GMT_LIBRARY_PATH=$HOME/anaconda3/envs/test_pygmt/lib`.

**Comment by yohaimagen** [comment]
> Hi @yohaimagen, can you try following the suggestion at https://forum.generic-mapping-tools.org/t/pygmt-doesnt-run-on-pycharm-but-jupyter/1450/2? I.e. activate the conda environment in Pycharm following https://www.jetbrains.com/help/pycharm/conda-support-creating-conda-virtual-environment.html.

O.K the problem with PyCharm and the conda environment is actually getting solved with the newest PyCharm version.




> Alternatively, you can set the `GMT_LIBRARY_PATH` environment variable following https://www.pygmt.org/dev/install.html#finding-the-gmt-shared-library. In your case, the command should be `export GMT_LIBRARY_PATH=$HOME/anaconda3/envs/test_pygmt/lib`.

this addresses the issue but forces to use the command `export GMT_LIBRARY_PATH=$HOME/anaconda3/envs/test_pygmt/lib` in every new Terminal session or add the command to the `.bashrc`. 

I still encountered the issue when setting up virtual env for Jupyter as [so](https://anbasile.github.io/posts/2017-06-25-jupyter-venv/)

```
$ conda create --name test_pygmt --channel conda-forge pygmt python=3.9
$ conda activate test_pygmt
(test_pygmt) $ conda install ipykernel
(test_pygmt) $ ipython kernel install --user --name=test_pygmt
```

now when opening Jupyter from anywhere I can start a notebook with test_pygmt kernel but cannot import pygmt as described above.

cant we somehow tell the specific pygmt installation where is the relevant GMT libraries?

The following is working 
```
import os
os.environ["GMT_LIBRARY_PATH"] = '/Users/yohai/anaconda3/envs/test_pygmt/lib/'

import pygmt
pygmt.show_versions()
```

I am not too well familiar with `__init__.py` in general, but cant we add 
```
import os
os.environ["GMT_LIBRARY_PATH"] = '/path/to/binded/gmt/libearies'
```
in order to let a specific pygmt installation know where are the relevant libraries?

**Comment by seisman** [comment]
> cant we somehow tell the specific pygmt installation where is the relevant GMT libraries?

I think we can't. There are multiple ways to install the GMT packages (conda, the official installers, or Homebrew on macOS). It's impossible to let PyGMT know these paths.

**Comment by seisman** [comment]
I'm closing the issue because I think there is nothing we can do.

Feel free to reopen it you think there is still something that can be improved.
