### ISSUE TITLE
grdsample alternative in pygmt

### ISSUE THREAD

**Issue by pragyantpradab** [GenericMappingTools/pygmt#1422]
gmt has grdsample function for sampling a grid file with inputs of grid spacing and other parameters.
But pygmt doesn't have grdsample. 

What can I use instead of grdsample in pygmt?

**Comment by weiji14** [comment]
PyGMT will have `grdsample` soon, the feature is being finalized at #1380. You're welcome to review the Pull Request to see if it fits what you need ;)
