### ISSUE TITLE
Add an example of the use of `pygmt.grdgradient`

### ISSUE THREAD

**Issue by yohaimagen** [GenericMappingTools/pygmt#1425]
I noticed that there are no examples of the usage of `pygmt.grdgradient`  and a function without examples is much harder to utiles by new users. 

I suggest adding an example of making an hillshade map using `pygmt.grdgradient`  as so:
```
grid = pygmt.datasets.load_earth_relief(resolution="01m", region=[-14, 30, 35, 60])
dgrid = pygmt.grdgradient(grid=grid, azimuth='90/10')
fig = pygmt.Figure()
pygmt.makecpt(cmap='gray', series=[-1.5, 1, 0.01])
fig.grdimage(grid=dgrid, projection="M5c", frame="a", cmap=True)
fig.colorbar(frame=["a1000", "x+lElevation", "y+lm"])
fig.show()
```
![europe_hilshade](https://user-images.githubusercontent.com/12828255/128730736-eaaf138b-018c-46fd-8d14-9f796d1ef2bf.png)

this example can be an extension to the [Earth relief tutorial](https://github.com/GenericMappingTools/pygmt/blob/85d78d6e1ddfd64dd3906bab0310e573f70ac885/examples/tutorials/earth_relief.py) or as a separate gallery example.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by weiji14** [comment]
Cool, this is a good idea! My only suggestion would be to either 1) use a smaller region rather than the whole of Europe if you want to use a high resolution map or 2) keep things to a low resolution (e.g. 10 arc minutes). Mainly because `grdgradient` can be a processing intensive task that can take some time to run.

**Comment by seisman** [comment]
> I suggest adding an example of making an hillshade map using `pygmt.grdgradient` as so:
> 
> ```
> grid = pygmt.datasets.load_earth_relief(resolution="01m", region=[-14, 30, 35, 60])
> dgrid = pygmt.grdgradient(grid=grid, azimuth='90/10')
> fig = pygmt.Figure()
> pygmt.makecpt(cmap='gray', series=[-1.5, 1, 0.01])
> fig.grdimage(grid=dgrid, projection="M5c", frame="a", cmap=True)
> fig.colorbar(frame=["a1000", "x+lElevation", "y+lm"])
> fig.show()
> ```

If I understand "hillshade" correctly, this script does not produce a hillshade map. Usually, we need to pass the DEM grid to the `grid` parameter and a gradient/intensity grid to the `shading` parameter.
 
> this example can be an extension to the [Earth relief tutorial](https://github.com/GenericMappingTools/pygmt/blob/85d78d6e1ddfd64dd3906bab0310e573f70ac885/examples/tutorials/earth_relief.py) or as a separate gallery example.

I agree we should extend the tutorial to show how to add shading to the earth relief map. I think the easiest way is simply adding `shading=True` to the `grdimage` call.

**Comment by yohaimagen** [comment]
I can do both, extend the tutorial with an example that uses `shading=True` which gives nice output and does not overpopulate the tutorial. from this section of the tutorial, we could refer to a gallery example with more specific use of grdgradient(`shading=True` use grdgradient to produce intensity grid file)
