### ISSUE TITLE
Wrapper for gmtselect

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#1427]
**Description of the desired feature**

Implement [`gmtselect`](https://docs.generic-mapping-tools.org/6.2/gmtselect.html) which "Select data table subsets based on multiple spatial criteria".

Mentioned at https://twitter.com/ATiredGradStdnt/status/1417189659365498884, also partially used before at https://forum.generic-mapping-tools.org/t/gmt-example-18-with-pygmt-volumes-and-spatial-selections/1585.

This function will probably be named `select`, i.e. called using `pygmt.select()`. As a table in, table out function, the implementation would be similar to already wrapped functions like `blockmedian`/`blockmean`. The code snippet would look something like so:

https://github.com/GenericMappingTools/pygmt/blob/31980e8af2bc8074af325fd9caa2355040088084/pygmt/src/blockm.py#L41-L64

Xref table I/O discussion at #1268 and #1318. Best to wrap this module after #1426.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by seisman** [comment]
Can we close the issue, since the initial wrapper has been done in #1429? Or do we still want to keep this issue open to tracking missing aliases, and gallery examples? Keeping the issue open makes me think that it has not been wrapped.

Related to https://github.com/GenericMappingTools/pygmt/issues/1599.

**Comment by weiji14** [comment]
Ok, closing as initial implementation done at #1429. Tracking progress on project board https://github.com/GenericMappingTools/pygmt/projects/9#card-72007028 instead.
