### ISSUE TITLE
Broken links in gmt_module_docs

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#143]
[gmt.info](http://www.gmtpython.xyz/api/gmt.info.html) is linked to http://gmt.soest.hawaii.edu/doc/latest/info.html.
[gmt.which](http://www.gmtpython.xyz/api/gmt.which.html) is linked to http://gmt.soest.hawaii.edu/doc/latest/which.html. 

Both links are broken now.

**Comment by seisman** [comment]
Same issue to `Figure.logo()` if #145 is merged.

**Comment by leouieda** [comment]
@seisman I noticed that this was happening for a few modules that got recent renames. This is a problem on the GMT docs, not really on our side. It will get sorted out as we start to work on cleaning and improving the GMT docs. For now, there isn't much we can do. Let's leave this issue open so we remember to check back again after upstream changes.

**Comment by leouieda** [comment]
I think many of these won't be changed in GMT so it might be best to not have them automatically generated. Maybe we can use the variable to insert only the basename `http://gmt.soest.hawaii.edu/doc/latest/` and then set the module name manually.

**Comment by seisman** [comment]
After #294, we use [extlinks](https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html) to link to GMT documentations. The issue can be closed.
