### ISSUE TITLE
Rename outfile parameter in surface to be outgrid

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#1441]
**Description of the desired feature**

As mentioned at https://github.com/GenericMappingTools/pygmt/pull/1439#discussion_r687251597, most PyGMT functions which return a grid output have a parameter called `outgrid`, but the `surface` function uses `outfile`. It would be best to standardize the name to be `outgrid` instead.

https://github.com/GenericMappingTools/pygmt/blob/ebbb0cc0045454f05db5abdfb3bcb5e1f18e96a7/pygmt/src/surface.py#L23

Should we deprecate the `outfile` parameter in 2 minor versions (at PyGMT v0.7.0) or 4 minor versions (at PyGMT v0.9.0)? Vote :eyes: for 2 and :tada: for 4.

**Are you willing to help implement and maintain this feature?** Someone can follow our deprecation policy steps at https://www.pygmt.org/v0.4.1/maintenance.html#backwards-compatibility-and-deprecation-policy to resolve this issue.

**Comment by meghanrjones** [comment]
This is somewhat related - I am not sure if it's worth a deprecation but I think we should decide on whether the parameter for tabular input is `data` or `table` for all modules moving forward. Currently, this is the distribution:

`data` parameter: surface, wiggle, velo, rose, plot3d, plot, contour
`table` parameter: blockmedian, blockmean, histogram
other: grdtrack (`points`), text (`textfiles`)

It would also be worthwhile to set a consistent order for the positional arguments x, y, [z], data, [outfile]

**Comment by meghanrjones** [comment]
@obaney will be working on this issue!

**Comment by seisman** [comment]
> This is somewhat related - I am not sure if it's worth a deprecation but I think we should decide on whether the parameter for tabular input is `data` or `table` for all modules moving forward. Currently, this is the distribution:
> 
> `data` parameter: surface, wiggle, velo, rose, plot3d, plot, contour
> `table` parameter: blockmedian, blockmean, histogram
> other: grdtrack (`points`), text (`textfiles`)
> 
> It would also be worthwhile to set a consistent order for the positional arguments x, y, [z], data, [outfile]

Perhaps we need to open a separate issue to discuss it.

**Comment by weiji14** [comment]
> > This is somewhat related - I am not sure if it's worth a deprecation but I think we should decide on whether the parameter for tabular input is `data` or `table` for all modules moving forward. Currently, this is the distribution:
> > `data` parameter: surface, wiggle, velo, rose, plot3d, plot, contour
> > `table` parameter: blockmedian, blockmean, histogram
> > other: grdtrack (`points`), text (`textfiles`)
> > It would also be worthwhile to set a consistent order for the positional arguments x, y, [z], data, [outfile]
> 
> Perhaps we need to open a separate issue to discuss it.

Yep, just opened #1479. Let's discuss there.
