### ISSUE TITLE
Function to load NASA Blue and Black marble mosaic images

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#1442]
**Description of the desired feature**

Provide access to cloud-free colour images of the Earth! Specifically, the `@earth_day_` and `@earth_night_` GMT remote data files (see https://docs.generic-mapping-tools.org/6.2/datasets/remote-data.html#global-earth-day-night-images).

![image](https://user-images.githubusercontent.com/23487320/129136166-cc0725bc-9a45-4415-9ec8-32a5f305228d.png)

Context is that I'm using it at #1437, and it would be good to have some sample RGB images. We might as well have a proper function similar to [`pygmt.datasets.load_earth_relief`](https://www.pygmt.org/v0.4.1/api/generated/pygmt.datasets.load_earth_relief.html), but for the Blue and Black Marble images instead.

Note that there is a lot of logic from the [`load_earth_relief`](https://www.pygmt.org/v0.4.1/api/generated/pygmt.datasets.load_earth_relief.html) function that could be reused:

https://github.com/GenericMappingTools/pygmt/blob/ebbb0cc0045454f05db5abdfb3bcb5e1f18e96a7/pygmt/datasets/earth_relief.py#L92-L140

These are some ways I'm considering:

Option 1 - rename the `earth_relief.py` file to `earth_data.py` first, and then separate the re-usable chunk of code into a function called `_load_earth_data` or something and have `load_earth_relief`/`load_earth_day`/`load_earth_night` call that. This is similar to what we did for `blockmean` and `blockmedian` at #1092. Less breakages for users already using `load_earth_relief`, but maybe more work for the devs.

Option 2 - have a single function called `load_earth_data` which accepts a parameter called 'type' that accepts arguments like 'relief'/'day'/'night'. We could then pretty much re-use the existing `load_earth_relief` function though it will need to be renamed to `load_earth_data` I guess. This would involve a deprecation notice for users using `load_earth_relief`, but less work for the devs in terms of not needing to write a new function?

Option 3 - any other ideas?

**Are you willing to help implement and maintain this feature?** Best to discuss first.

**Comment by seisman** [comment]
There are many differences between earth_relief and earth_day/earth_night datasets:

- earth_day/earth_night datasets are in geotiff format, not netcdf. 
  - What's the return type for the `load_earth_day` function? 
  - Does xarray support reading geotiff?
  - If it does support, does the returned DataArray can be passed to the `grdimage` module?
- earth_day/earth_night only provide pixel-registered version, so the `registration` parameter is not needed
- each resolution of earth_day/earth_night is stored in a single file, but earth_relief data higher than 06m resolution are stored in tiles.

I think these differences mean that very few code in the `earth_relief.py` file can be reused.

**Comment by willschlitzer** [comment]
> There are many differences between earth_relief and earth_day/earth_night datasets:
> 
>     * earth_day/earth_night datasets are in geotiff format, not netcdf.
>       
>       * What's the return type for the `load_earth_day` function?
>       * Does xarray support reading geotiff?
>       * If it does support, does the returned DataArray can be passed to the `grdimage` module?
> 
>     * earth_day/earth_night only provide pixel-registered version, so the `registration` parameter is not needed
> 
>     * each resolution of earth_day/earth_night is stored in a single file, but earth_relief data higher than 06m resolution are stored in tiles.
> 
> 
> I think these differences mean that very few code in the `earth_relief.py` file can be reused.

@seisman and @weiji14 I think I have made a fix for problems of no registration or region passed to `_load_remote_dataset`. Would I be able to change the `engine` argument for `load_dataarray` for something that can accept a TIFF file?

**Comment by weiji14** [comment]
> @seisman and @weiji14 I think I have made a fix for problems of no registration or region passed to `_load_remote_dataset`. Would I be able to change the `engine` argument for `load_dataarray` for something that can accept a TIFF file?

Kinda. The tricky part is that Blue/Black Marble are RGB images with 3 bands, whereas the other datasets you've been working on are 1 band datasets. So you would need to use [`rioxarray.open_rasterio`](https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray.open_rasterio) instead.

Now one complication is that these GeoTIFF files store the RGB data in a colormap attribute, and there's no standardized way on how to read these into an `xarray.DataArray` via `rioxarray` yet. I did try for a while at https://github.com/corteva/rioxarray/pull/414, but haven't got around to finishing that Pull Request. If you've got time, it's worth testing a few things and see what works and what doesn't.

**Comment by weiji14** [comment]
FYI, with `GMT_IMAGE` implemented in #3338 and #3128, we no longer need `rioxarray` to open 3-band GeoTIFF images :tada:. I.e., the Blue Marble GeoTIFFs can be read using GMT directly with some special logic that will be implemented in the `load_blue_marble` function that I'll try to finalize in #2235.
