### ISSUE TITLE
dvc add pygmt/tests/baseline rather than individual test files

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1490]
**Description of the problem**

The dvc added baseline test images can no longer be viewed on [DAGsHub](https://dagshub.com/GenericMappingTools/pygmt/src/main/pygmt/tests/baseline). When I recently asked about this on the DAGsHub discord server, the DAGsHub representative said that they limit the number of DVC nodes for speed. They recommended adding the entire directory, rather than individual files, because "you might experience issues with DVC too, since the recommended workflow is if you have a lot of files that you want to add, you should `dvc add` the directory".

The solution proposed in this issue is to dvc remove the individual files and instead dvc add `pygmt/tests/baseline`. Comments welcome.

**Comment by weiji14** [comment]
Crossreferencing from https://github.com/GenericMappingTools/gmt/issues/5724#issuecomment-917304492, I tried running `dvc add pygmt/tests/baseline` (after `git rm -r pygmt/tests/baseline` and all that), and it gave me this `pygmt/tests/baseline.dvc` file:

```
outs:
- md5: 218e4bff86d1d792a28b2405e52cec79.dir
  size: 6048073
  nfiles: 158
  path: baseline
```

The contents of `.dvc/cache/21/8e4bff86d1d792a28b2405e52cec79.dir` is a JSON file which looks like this (truncated):

```json
[
  {
    "md5": "3cf01816fa5dd3fbc1adc602557bb032",
    "relpath": "test_basemap.png"
  },
  {
    "md5": "77dc6e9b11b2fa1cf79c7de525704fca",
    "relpath": "test_basemap_compass.png"
  },
  ...
]
```

Not sure how I feel about having a single `baseline.dvc` file like this. I quite liked having multiple md5 hashes for individual files (feels a bit more concrete). Maybe we could settle for a middle ground and group tests together and organize things into folders like `pygmt/tests/baseline/basemap`, `pygmt/tests/baseline/contour` and so on, and have a `basemap.dvc` and `contour.dvc` file for each of those groups? Or just stick with a single `baseline.dvc` file to handle everything.

**Comment by meghanrjones** [comment]
The GMT repository might be a good test for how the middle-ground structure will scale (GMT has ~800 image based tests versus ~200 for PyGMT). If each function has its own folder, then we may end up with the same issues considering that there are well over 100 GMT modules and we are planning to split up these based on plotting/processing. We could try a different method for grouping multiple functions together (e.g., [splitting used in GMT API docs](https://docs.generic-mapping-tools.org/dev/modules.html#session-management)). So, my suggestion is that we leave this issue open for now while we test with different structures for the GMT image-based tests.

**Comment by meghanrjones** [comment]
I discussed the proposed dvc project structure for GMT (outlined at https://hackmd.io/@meghanj/Hknq8gg4Y) with Dean Pleban (DAGsHub CEO) this morning. The solution for merge conflicts when using a single `basemap.dvc` file would be simple if the only changes are adding new files to the directory but convoluted if multiple files are modified, involving manipulating the `.dir` file in `.dvc/cache` and computing/updating the `md5` in `baseline.dvc`. As @weiji14 suggested, we could reasonably avoid merge conflicts by grouping the baseline images by module. Based on the conversation today, it seems that the resultant ~100 dvc files should not noticeably impact performance. I'll try this out for GMT.

**Comment by weiji14** [comment]
Just noticed that the baseline test images are viewable on DAGsHub again (see https://dagshub.com/GenericMappingTools/pygmt/src/main/pygmt/tests/baseline), so can we close this issue? Saves us time having to migrate everything to a new directory structure :slightly_smiling_face:

![PyGMT baseline test images on DAGsHub](https://user-images.githubusercontent.com/23487320/150572541-91338036-9547-4014-934d-d81382f156c5.png)

I don't know when the change happened, but it seems like DAGsHub recently put out a 2.0 release (https://dagshub.com/blog/launching-dagshub-2-0) and there might have been some changes in the backend that fixed the original file count limit or something.

**Comment by meghanrjones** [comment]
Actually they changes the limit specifically for us 😄
