### ISSUE TITLE
Tutorial notebook for showcasing projections and plot region arguments

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/pygmt#153]
The `first-steps` tutorial is a good length introduction to the basics of the `gmt.Figure` class and what is different from classic GMT.

It would be great to have a separate tutorial notebook with an in-depth look at how GMT handles the region argument (showing the ISO country codes) and how projections work (with coastline plots showing each one). Perhaps including a short table of all projections.

This notebook would live in `doc/tutorials` and it's run automatically by the documentation build process.

**Comment by willschlitzer** [comment]
@leouieda Are you still hoping to get a tutorial like this? I think documenting the projections in a tutorial may be a little redundant now that there is a projection gallery.

**Comment by seisman** [comment]
> I think documenting the projections in a tutorial may be a little redundant now that there is a projection gallery.

I agree.

But I think we still need a tutorial showing how to specify a plot region. Some possible options are:

- Give either `g` or `d` for global region
- A list `[xmin, xmax, ymin, ymax]`
- A string `xmin/xmax/ymin/ymax`
- ISO country code (e.g., `US`) and some modifiers (e.g., `US+r2`)
- and more in the cookbook (https://docs.generic-mapping-tools.org/latest/cookbook/options.html#data-domain-or-map-region-the-r-option).
