### ISSUE TITLE
Move "Reference Documentation" up in sidebar order

### ISSUE THREAD

**Issue by willschlitzer** [GenericMappingTools/pygmt#1535]
Should the "Reference Documentation" sub-section be moved up the sidebar in the PyGMT documentation? GMT has "Getting Started" followed by "Reference Documentation", and I think our sidebar should match it. As the User Guide has expanded, the entire sidebar likely won't fit on most screens and will require scrolling to see the reference documentation.

**Comment by seisman** [comment]
> As the User Guide has expanded, the entire sidebar likely won't fit on most screens and will require scrolling to see the reference documentation.

xref: https://github.com/GenericMappingTools/pygmt/issues/1191

**Comment by meghanrjones** [comment]
@willschlitzer, what's your opinion on this with the new sidebar structure: https://www.pygmt.org/dev/? Would you still prefer for the reference documentation to be before the user guide?

**Comment by willschlitzer** [comment]
I would still prefer the reference documentation up higher, like in the GMT docs, but I think it looks much better now that the tutorial list isn't super long.

**Comment by meghanrjones** [comment]
> I would still prefer the reference documentation up higher, like in the GMT docs, but I think it looks much better now that the tutorial list isn't super long.

I would be fine with this change.

**Comment by seisman** [comment]
> I would still prefer the reference documentation up higher, like in the GMT docs, but I think it looks much better now that the tutorial list isn't super long.

I prefer to keep the "Reference documentation" at the current position (i.e., below the "User Guide"), as what other projects do (e.g., [pandas](https://pandas.pydata.org/), [scipy](https://scipy.github.io/devdocs/index.html), [xarray](http://xarray.pydata.org/en/stable/index.html)).
