### ISSUE TITLE
Axis labels lost when use -RgXmin/Xmax/Ymin/Ymax to indicate a limited geographic domain.

### ISSUE THREAD

**Issue by WXZhao7** [GenericMappingTools/pygmt#1588]
**Description of the problem**

Axis labels lost when use '-RgXmin/Xmax/Ymin/Ymax' to indicate a limited geographic domain.

![image](https://user-images.githubusercontent.com/56864878/138419779-dc3bc395-b9ff-477b-8d15-f031b00a5ee2.png)

**Full code that generated the error**

```python
import pygmt

fig = pygmt.Figure()
region = "g0/10/0/10"
fig.basemap(
    region=region, projection="X5c", frame=["WSNE", "xaf+llon/deg", "yaf+llat/deg"]
    )
fig.show()
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

Please paste the output of `python -c "import pygmt; pygmt.show_versions()"`:

```
PyGMT information:
  version: v0.4.1
System information:
  python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46)  [GCC 9.4.0]
  executable: /home/wxz/Program/miniconda3/envs/seismic/bin/python
  machine: Linux-5.11.0-38-generic-x86_64-with-glibc2.31
Dependency information:
  numpy: 1.21.2
  pandas: 1.3.3
  xarray: 0.19.0
  netCDF4: 1.5.7
  packaging: 21.0
  ghostscript: 9.54.0
  gmt: 6.2.0
GMT library information:
  binary dir: /home/wxz/Program/miniconda3/envs/seismic/bin
  cores: 16
  grid layout: rows
  library path: /home/wxz/Program/miniconda3/envs/seismic/lib/libgmt.so
  padding: 2
  plugin dir: /home/wxz/Program/miniconda3/envs/seismic/lib/gmt/plugins
  share dir: /home/wxz/Program/miniconda3/envs/seismic/share/gmt
  version: 6.2.0

```

**Comment by weiji14** [comment]
Hi @WXZhao7, as mentioned in https://github.com/GenericMappingTools/pygmt/issues/1588#issuecomment-950579254, it isn't possible to label geographic axes in GMT/PyGMT. That said, you can try to use [`fig.text`](https://www.pygmt.org/v0.5.0/api/generated/pygmt.Figure.text.html) to put the annotations manually.

```python
fig = pygmt.Figure()
region = "g0/360/-60/60"
fig.basemap(region=region, projection="X15c", frame=True)
fig.coast(
    borders=["1/0.5p,black"],
    shorelines="0.5p,black",
    land="lightgray",
    water="lightblue",
    resolution="l",
)
fig.text(position="BC", offset="0c/-1.2c", text="lon/deg", no_clip=True)
fig.text(position="LM", offset="-1.2c/0c", text="lat/deg", angle=90, no_clip=True)
fig.plot(x=180, y=0, style=f"W30d/0/360", pen="2p,orange")
fig.savefig("annotated_geo_map.png")
fig.show()
```
produces:

![annotated_geo_map](https://user-images.githubusercontent.com/23487320/140629909-849f71f3-e4f3-425d-ad43-4809b89fcc5f.png)

You might want to play around with the `offset` and `font` parameter to get the position and text size of the labels to look better. I'll close this issue now, but if you have other specific questions, feel free to ask them at https://forum.generic-mapping-tools.org/c/questions/pygmt-q-a/11.
