### ISSUE TITLE
GEOS 3.10.0 breaks GMT on macOS

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#1600]
**Description of the problem**

On macOS, it seems like GMT is broken with GEOS 3.10 (release 22 Oct to conda-forge https://github.com/conda-forge/geos-feedstock/pull/61). See recent failure on `cache_data.yml` at https://github.com/GenericMappingTools/pygmt/runs/4059892997?check_suite_focus=true#step:6:8.

**Full code that generated the error**

```python
from pygmt.helpers.testing import download_test_data
download_test_data()
```

**Full error message**

```python-traceback
dyld: Library not loaded: @rpath/libgeos_c.1.dylib
  Referenced from: /Users/runner/miniconda3/envs/test/lib/libgmt.6.2.0.dylib
  Reason: Incompatible library version: libgmt.6.dylib requires version 16.0.0 or later, but libgeos_c.1.dylib provides version 1.0.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/runner/work/pygmt/pygmt/pygmt/__init__.py", line 70, in <module>
    _begin()
  File "/Users/runner/work/pygmt/pygmt/pygmt/session_management.py", line 16, in begin
    with Session() as lib:
  File "/Users/runner/work/pygmt/pygmt/pygmt/clib/session.py", line 183, in __enter__
    self.create("pygmt-session")
  File "/Users/runner/work/pygmt/pygmt/pygmt/clib/session.py", line 329, in create
    c_create_session = self.get_libgmt_func(
  File "/Users/runner/work/pygmt/pygmt/pygmt/clib/session.py", line 281, in get_libgmt_func
    self._libgmt = load_libgmt()
  File "/Users/runner/work/pygmt/pygmt/pygmt/clib/loading.py", line 59, in load_libgmt
    raise GMTCLibNotFoundError("\n".join(error_msg))
pygmt.exceptions.GMTCLibNotFoundError: Error loading GMT shared library at 'libgmt.dylib'.
dlopen(libgmt.dylib, 6): Library not loaded: @rpath/libgeos_c.1.dylib
  Referenced from: /Users/runner/miniconda3/envs/test/lib/libgmt.6.2.0.dylib
  Reason: Incompatible library version: libgmt.dylib requires version 16.0.0 or later, but libgeos_c.1.dylib provides version 1.0.0
Error: Process completed with exit code 1.
```

**System information**

Please paste the output of `python -c "import pygmt; pygmt.show_versions()"`:

```
pygmt v0.5.0
```

I don't have a macOS computer to test or debug, but workaround may be to downgrade to `geos=5.9` for now using `conda install -c conda-forge geos=3.9`. Feel free to move this issue to upstream GMT if it's better.

Edit: Or maybe it's an issue on the GEOS side :slightly_smiling_face: There is an ongoing migration for GEOS 3.10 on conda-forge, see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2051 and https://conda-forge.org/status/#geos3100

Edit2: A user has reported similar problem on the forum at https://forum.generic-mapping-tools.org/t/import-pygmt-error-after-jupyterlab-installation/2117/4. Might be quite serious...

**Comment by meghanrjones** [comment]
A few notes based on some trials on macOS:
- The problem likely an issue with GMT, because geos is a dependency through gdal, which works as expected through `conda create --name gdal; conda activate gdal; conda install -c conda-forge gdal`.
- `conda install -c conda-forge geos=3.9` solves the problem.
- `conda create --name gmt-test; conda activate gmt-test; conda install -c conda-forge gmt; gmt --version` reproduces the problem without needing to go through PyGMT.

My guess is that something is wrong with the gmt conda recipe because building gmt from source works fine even when using the conda-forge version of gdal and geos dependencies.

**Comment by meghanrjones** [comment]
Since this breaks our macOS CI workflows, I agree that it's a serious issue.

Here's the version information reported by otool for geos 3.10:
```
	@rpath/libgeos_c.1.dylib (compatibility version 1.0.0, current version 1.16.0)
	@rpath/libgeos.3.10.0.dylib (compatibility version 3.10.0, current version 3.10.0)
```
and for geos 3.9:
```
	@rpath/libgeos_c.1.dylib (compatibility version 16.0.0, current version 16.2.0)
	@rpath/libgeos-3.9.1.dylib (compatibility version 0.0.0, current version 0.0.0)
```
I am not that familiar with these libraries. @PaulWessel, do you know if there's a way for us to adapt for the version jump or whether we should find a way to report this to the geos devs?

**Comment by weiji14** [comment]
I saw that the conda-forge geos-feedstock changed from using `cmake` instead of `autotools` (see https://github.com/conda-forge/geos-feedstock/issues/54 and https://github.com/conda-forge/geos-feedstock/pull/61#issuecomment-948140127). Not sure if that had an impact, at least I didn't notice anything out of hand at https://github.com/conda-forge/geos-feedstock/pull/61/files#diff-d10439659fe44156d9eac347f9e9eb6992e5b516d0f7e86df061c8273397fd7d.

Also not clear to me whether the exact problem is at, is it 1) GMT, 2) the conda-forge geos-feedstock or 3) geos? Afraid that I won't be of much help troubleshooting since I don't have a Mac computer either. Most I could help with is to pin the [`gmt-feedstock`](https://github.com/conda-forge/gmt-feedstock) to geos <= 3.9.1 until this is worked out.

**Comment by PaulWessel** [comment]
GMT only started using geos when @joa-quim added it as a conditional library for buffering in **gmtspatial**, if I recall correctly.  So that is the only place.  Help me understand the problem: So libgmt is built with GDAL and GEOS support and it gets the latest version the distribution provides.  Then, when it is loaded in pyGMT there is a conflict with  the geos library? How are the two geos libraries different on the same system? You are building GMT on that system, no?

**Comment by joa-quim** [comment]
There are news of GEOS 3.10 breaking GDAL in Julia as well. I'm having no problems on Windows but probably because I rebuilt GDAL after updating to GEOS 3.10

**Comment by meghanrjones** [comment]
> GMT only started using geos when @joa-quim added it as a conditional library for buffering in **gmtspatial**, if I recall correctly. So that is the only place. Help me understand the problem: So libgmt is built with GDAL and GEOS support and it gets the latest version the distribution provides. Then, when it is loaded in pyGMT there is a conflict with the geos library? How are the two geos libraries different on the same system? You are building GMT on that system, no?

The two GEOS libraries are in separate virtual environments on the same system. In one virtual environment, I installed GDAL with GEOS 3.10 using conda-forge and built gmt from source (no problems). In another, I installed GDAL with GEOS 3.9 and GMT 6.2 using conda-forge (no problems). In a third, I installed GDAL and GEOS 3.10 and GMT 6.2 using conda-forge (`gmt --version` did not work with the error `Incompatible library version: libgmt.dylib requires version 16.0.0 or later, but libgeos_c.1.dylib provides version 1.0.0`).

**Comment by PaulWessel** [comment]
>  In a third, I installed GDAL and GEOS 3.10 and GMT 6.2 using conda-forge (`gmt --version` did not work with the error `Incompatible library version: libgmt.dylib requires version 16.0.0 or later, but libgeos_c.1.dylib provides version 1.0.0`).

So when you install GMT 6.2 using conda-forge you get a build using GEOS 3.9 which does not exist in that environment?

**Comment by meghanrjones** [comment]
> > In a third, I installed GDAL and GEOS 3.10 and GMT 6.2 using conda-forge (`gmt --version` did not work with the error `Incompatible library version: libgmt.dylib requires version 16.0.0 or later, but libgeos_c.1.dylib provides version 1.0.0`).
> 
> So when you install GMT 6.2 using conda-forge you get a build using GEOS 3.9 which does not exist in that environment?

I'm sorry, but I do not fully understand your question. GEOS 3.9 does not exist in that environment. I do not know whether there's anything about the GMT 6.2 build that specifies that it must be GEOS 3.9 such that GEOS 3.10 would not suffice.

**Comment by PaulWessel** [comment]
OK, so, there is nothing in GMT Cmake that says anything about what version GEOS must be.  What does it say it finds when it is running Cmake configure? I.e.

```
...
*  GEOS library               : /opt/local/lib/libgeos_c.dylib
*  GEOS include dir           : /opt/local/include
...
```

what does it say for your failing case?

**Comment by meghanrjones** [comment]
> OK, so, there is nothing in GMT Cmake that says anything about what version GEOS must be. What does it say it finds when it is running Cmake configure? I.e.
> 
> ```
> ...
> *  GEOS library               : /opt/local/lib/libgeos_c.dylib
> *  GEOS include dir           : /opt/local/include
> ...
> ```
> 
> what does it say for your failing case?

I do not know of a way to get this information, since conda distributes a built version and the CI logs have expired. @weiji14, do you think it could be helpful to [rerender the gmt feedstock](https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks)? This situation may meet the criteria 'updates to the build matrix' in their guides for [when to rerender](https://conda-forge.org/docs/maintainer/updating_pkgs.html#when-to-rerender).

Also, I think we should transfer this issue to the gmt-feedstock repository since this seems to be a conda-forge specific problem (I can build GMT fine on macOS with GEOS 3.10.0).

**Comment by PaulWessel** [comment]
OK, so basically conda built a GMT library using 3.9 but on your system there is no 3.9.

**Comment by weiji14** [comment]
> I do not know of a way to get this information, since conda distributes a built version and the CI logs have expired. @weiji14, do you think it could be helpful to [rerender the gmt feedstock](https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks)? This situation may meet the criteria 'updates to the build matrix' in their guides for [when to rerender](https://conda-forge.org/docs/maintainer/updating_pkgs.html#when-to-rerender).

Ok, I'll try to rerender the feedstock and see if it helps. Do you think GEOS should be listed as an explicit runtime dependency at https://github.com/conda-forge/gmt-feedstock/blob/0455a1e5346c23c7bde78c6f0652a75966ac1dab/recipe/meta.yaml#L33-L48? Or should we just treat it as a one-off situation and hope things don't break in the future?

> Also, I think we should transfer this issue to the gmt-feedstock repository since this seems to be a conda-forge specific problem (I can build GMT fine on macOS with GEOS 3.10.0).

I can't transfer the issue because the gmt-feedstock repo isn't in the GenericMappingTools organization. So let's just keep it here for now.

**Comment by seisman** [comment]
> Here's the version information reported by otool for geos 3.10:
> 
> 	@rpath/libgeos_c.1.dylib (compatibility version 1.0.0, current version 1.16.0)
> 	@rpath/libgeos.3.10.0.dylib (compatibility version 3.10.0, current version 3.10.0)
> and for geos 3.9:
> 
> 	@rpath/libgeos_c.1.dylib (compatibility version 16.0.0, current version 16.2.0)
> 	@rpath/libgeos-3.9.1.dylib (compatibility version 0.0.0, current version 0.0.0)

Because the changes of the geos version scheme (`0.0.0` -> `3.10.0`, and `16.2.0` -> `1.16.0`), any packages that link to the geos package need to be rebuilt.

> ​Edit: Or maybe it's an issue on the GEOS side 🙂 There is an ongoing migration for GEOS 3.10 on conda-forge, see [conda-forge/conda-forge-pinning-feedstock#2051](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2051) and [conda-forge.org/status/#geos3100](https://conda-forge.org/status/#geos3100)

Because geos is not listed as a runtime dependency, the conda-forge's geos3100 migration didn't trigger a new build for GMT. I believe https://github.com/conda-forge/gmt-feedstock/pull/169 will fix the issue

**Comment by seisman** [comment]
https://github.com/conda-forge/gmt-feedstock/pull/169 fixed the issue. All tests pass now.

**Comment by EJFielding** [comment]
As I reported on the GMT discussion forum, the new version of `conda-forge/gmt-feedstock` fixed the problem that I had running PyGMT on MacOS. Thanks for the fast work!

**Comment by seisman** [comment]
@weiji14 It reminds me that we need to apply the same patch to the devel branch of the feedstock. Do you want to do it?

**Comment by weiji14** [comment]
> @weiji14 It reminds me that we need to apply the same patch to the devel branch of the feedstock. Do you want to do it?

It's been rebuilt already at https://github.com/conda-forge/gmt-feedstock/pull/170. Same with the v5.x branch.
