### ISSUE TITLE
'double free or corruption (out)' occurred in Python Debug Console of VsCode 

### ISSUE THREAD

**Issue by WXZhao7** [GenericMappingTools/pygmt#1619]
**Description of the problem**

The **Python Debug Console** of VsCode aborted when debug pyGMT.

* Debug python file :heavy_multiplication_x:
![image](https://user-images.githubusercontent.com/56864878/140943642-49a14b3a-0226-433d-9c7d-38b217b71d6d.png)

* Run python file :heavy_check_mark:
![image](https://user-images.githubusercontent.com/56864878/140944065-84257712-b81e-4b00-8e02-c2273d1ea58d.png)

**Full code that generated the error**

[one example](https://www.pygmt.org/latest/gallery/symbols/points.html#sphx-glr-gallery-symbols-points-py)
```python
import numpy as np
import pygmt

# Generate a random set of points to plot
np.random.seed(42)
region = [150, 240, -10, 60]
x = np.random.uniform(region[0], region[1], 100)
y = np.random.uniform(region[2], region[3], 100)

fig = pygmt.Figure()
# Create a 15 cm x 15 cm basemap with a Cartesian projection (X) using the
# data region
fig.basemap(region=region, projection="X15c", frame=True)
# Plot using inverted triangles (i) of 0.5 cm size
fig.plot(x=x, y=y, style="i0.5c", color="black")
# fig.show()
```

**Full error message**

```
double free or corruption (out)
```

**System information** 

Please paste the output of `python -c "import pygmt; pygmt.show_versions()"`:

```
PyGMT information:
  version: v0.4.1
System information:
  python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46)  [GCC 9.4.0]
  executable: /home/wxz/Program/miniconda3/envs/seismic/bin/python
  machine: Linux-5.11.0-38-generic-x86_64-with-glibc2.31
Dependency information:
  numpy: 1.21.2
  pandas: 1.3.3
  xarray: 0.19.0
  netCDF4: 1.5.7
  packaging: 21.0
  ghostscript: 9.54.0
  gmt: 6.2.0
GMT library information:
  binary dir: /home/wxz/Program/miniconda3/envs/seismic/bin
  cores: 16
  grid layout: rows
  library path: /home/wxz/Program/miniconda3/envs/seismic/lib/libgmt.so
  padding: 2
  plugin dir: /home/wxz/Program/miniconda3/envs/seismic/lib/gmt/plugins
  share dir: /home/wxz/Program/miniconda3/envs/seismic/share/gmt
  version: 6.2.0
```

**Comment by weiji14** [comment]
Hi @WXZhao7, I don't use VSCode, but I can't seem to reproduce the crash on my Linux machine. Let's see if someone who uses VSCode can try and see if this is an issue? In the meantime, have you tried deleting the conda environment and reinstalling from scratch?

**Comment by seisman** [comment]
I also can't reproduce your issue using VSCode Debug Console, and the dev PyGMT and GMT.

**Comment by WXZhao7** [comment]
> I also can't reproduce your issue using VSCode Debug Console, and the dev PyGMT and GMT.

I can debug pygmt with VScode, but the debugger can't exit correctly. I reproduce it as below:

## Part 1. recreate environment

* step 1, recreate conda env.
```shell
conda remove -n pygmt --all
conda create --name pygmt --channel conda-forge pygmt
```
* step 2, install VScode insider version (avoid the influence from VScode setting)
```shell
sudo dpkg -i code-insiders_1.63.0-1636638160_amd64.deb
```

* step 3, install python extension in vscode
```
ext install ms-python.python
```

* step 4, add `"terminal.integrated.inheritEnv": false,` to settings.json of VScode. (avoid the influence from inherit env.)

**Now a new enviroment is built.**

![image](https://user-images.githubusercontent.com/56864878/141425744-76ab29bb-9531-4c7b-88b8-74a2789eec31.png)

## Part 2, reproduce the issue

* step 1, add `print(">>>> done")` at end of test code
```python
import numpy as np
import pygmt


# Generate a random set of points to plot
np.random.seed(42)
region = [150, 240, -10, 60]
x = np.random.uniform(region[0], region[1], 100)
y = np.random.uniform(region[2], region[3], 100)

fig = pygmt.Figure()
# Create a 15 cm x 15 cm basemap with a Cartesian projection (X) using the
# data region
fig.basemap(region=region, projection="X15c", frame=True)
# Plot using inverted triangles (i) of 0.5 cm size
fig.plot(x=x, y=y, style="i0.5c", color="black")
# fig.show()
print(">>>> done")
```

* step 2, click `Run and Debug` and select `Debug the currently active python file`

![image](https://user-images.githubusercontent.com/56864878/141428118-f8b15798-dc1c-4b25-88f7-b13d1a1c0c7f.png)

* step 3, I meet the same problem again

![image](https://user-images.githubusercontent.com/56864878/141428520-923355ae-02f2-4429-a295-a7680e0440c7.png)

* step 4, run the code in terminal

![image](https://user-images.githubusercontent.com/56864878/141429169-efb04fde-cdaf-4a5c-9502-52d3cacd0772.png)

 I will try to reproduce it in VMware.

**Comment by WXZhao7** [comment]
Oh, I can't reproduce it in the virtual machine with same OS and kernel!
May be I have to reinstall system :sob: 

![image](https://user-images.githubusercontent.com/56864878/141438268-6139345f-e555-446c-a0cb-6143cdb28356.png)

**Comment by weiji14** [comment]
Maybe try doing a `gmt clear all` and `conda clean --all` after `conda env remove -n pygmt`, sometimes things get corrupted in the conda virtual environment :shrug:

**Comment by WXZhao7** [comment]
> Maybe try doing a `gmt clear all`, and then `conda clean --all` after `conda env remove -n pygmt`, sometimes things get corrupted in the conda virtual environment shrug

I find the source of this problem----zsh!!! :anger: 
This issue will disappear if I change the system shell to bash. I guess that may associate with the system environment. I will try to fix it.
Thanks for your help! @seisman @weiji14

**Comment by WXZhao7** [comment]
The conda initialization caused the `double free or corruption (out)`. I delete it from my `.bashrc` to solve the problem.
```shell
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/wxz/Program/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/wxz/Program/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/wxz/Program/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/wxz/Program/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```
