### ISSUE TITLE
Docs workflow broken with sphinx 4.3.0

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1622]
**Description of the problem**

The docs workflows are currently failing (e.g., https://github.com/GenericMappingTools/pygmt/runs/4185213352?check_suite_focus=true) due to an incompatibility between sphinx-gallery and sphinx 4.3.0 (https://github.com/sphinx-gallery/sphinx-gallery/issues/879). Should we pin to 4.2.0 for now or wait?

**Comment by seisman** [comment]
sphinx-gallery has made a new release which should fix the problem.

**Comment by seisman** [comment]
https://github.com/sphinx-gallery/sphinx-gallery/releases/tag/v0.10.1
