### ISSUE TITLE
Add more sections to documentation for the Figure plotting methods

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1633]
**Description of the desired feature**

There are many methods in the plotting section for the Figure API documentation: https://www.pygmt.org/dev/api/index.html#plotting. I expect it could help people unfamiliar with GMT modules find relevant methods if there were more sections. Here is one idea:

- Plotting tabular data
    - Figure.contour
    - Figure.histogram
    - Figure.meca
    - Figure.plot
    - Figure.plot3d
    - Figure.rose
    - Figure.velo
    - Figure.wiggle
- Plotting gridded data
   -  Figure.grdcontour
    - Figure.grdimage
    - Figure.grdview
    - Figure.image
- Plotting map elements
    - Figure.basemap
    - Figure.coast
    - Figure.colorbar
    - Figure.inset
    - Figure.legend
    - Figure.logo
    - Figure.solar
    - Figure.text
- Configuring layout
    - Figure.set_panel
    - Figure.shift_origin
    - Figure.subplot

Which would look like (in part):

![Proposed structure of Figure API docs](https://user-images.githubusercontent.com/14077947/143086591-c698a960-1902-4d02-8d79-5848676b81cb.png)

What do others think?

**Comment by willschlitzer** [comment]
I think this is a good idea
