### ISSUE TITLE
Functionality: psvelo

### ISSUE THREAD

**Issue by KarineTeran** [GenericMappingTools/pygmt#1637]
**Users need to use the module psvelo to plot velocity vectors, crosses, and
wedges on maps**

Or if this already exists, please tell me and give me an example about how to use this functionality. 
Thanks.

**Comment by michaelgrund** [comment]
This function is already wrapped as **velo**, see the [documentation](https://www.pygmt.org/latest/api/generated/pygmt.Figure.velo.html#pygmt.Figure.velo) for more details. An example is available in the [Gallery](https://www.pygmt.org/latest/gallery/seismology/velo_arrow_ellipse.html#sphx-glr-gallery-seismology-velo-arrow-ellipse-py).

**Comment by KarineTeran** [comment]
Thank you so much @michaelgrund.
