### ISSUE TITLE
Pygmt surface module feature request

### ISSUE THREAD

**Issue by pragyantpradab** [GenericMappingTools/pygmt#1660]
**Description of the desired feature**
pygmt surface function has been missing some important arguments from gmt like -Ll , -Lu , -C, -M, which are vary important when using surface function to create grid data from xyz data.

pygmt surface function has been missing some important arguments from gmt like -Ll , -Lu , -C, -M, which are vary important when using surface function to create grid data from xyz data.

-Lllower and -Luupper
Impose limits on the output solution. llower sets the lower bound. lower can be the name of a grid file with lower bound values, a fixed value, d to set to minimum input value, or u for unconstrained [Default]. uupper sets the upper bound and can be the name of a grid file with upper bound values, a fixed value, d to set to maximum input value, or u for unconstrained [Default]. Grid files used to set the limits may contain NaNs. In the presence of NaNs, the limit of a node masked with NaN is unconstrained.

-Cconvergence_limit[%]
Convergence limit. Iteration is assumed to have converged when the maximum absolute change in any grid value is less than convergence_limit. (Units same as data z units). Alternatively, give limit in percentage of rms deviation by appending %. [Default is scaled 10^-4 to  of the root-mean-square deviation of the data from a best-fit (least-squares) plane.]. This is the final convergence limit at the desired grid spacing; for intermediate (coarser) grids the effective convergence limit is divided by the grid spacing multiplier.

**Are you willing to help implement and maintain this feature?** Yes/No
yes

**Comment by weiji14** [comment]
Hi @pragyantpradab, thanks for opening up this feature request! I agree that those parameters (`-L`, `-C` and `-M`) are often used (I actually use them myself sometimes). Feel free to open a Pull Request to modify the code here:

https://github.com/GenericMappingTools/pygmt/blob/9ef6338dbb9bdd4c31dda94da6d4126852a6cd85/pygmt/src/surface.py#L21-L37

Let us know if you need any help, you can check out the contributing guide at https://www.pygmt.org/v0.5.0/contributing.html as a start :grin:

**Comment by yvonnefroehlich** [comment]
@pragyantpradab after merging @JingHuiTong's PR #2321, aliases for **-C**, **-L**, and **-M** are now available. To [install the development version of PyGMT](https://www.pygmt.org/dev/install.html#using-pip) you may want to have a look in the installation guide at https://www.pygmt.org/dev/install.html. 
I feel, we can close this issue as completed.
