### ISSUE TITLE
Quickinstall in the README?

### ISSUE THREAD

**Issue by jbusecke** [GenericMappingTools/pygmt#1662]
**Description of the desired feature**

I really appreciate the detailed README, but I was wondering if a one liner of the recommended install method, e.g. `conda install -c conda-forge pygmt` would be a useful addition somewhere in the upper part of the file?

**Are you willing to help implement and maintain this feature?** No (just part of https://github.com/pyOpenSci/software-review/issues/43)

**Comment by willschlitzer** [comment]
I think this is a good idea.
