### ISSUE TITLE
Add installing with mamba to docs?

### ISSUE THREAD

**Issue by jbusecke** [GenericMappingTools/pygmt#1663]
**Description of the desired feature**
I just tried to install pygmt on the pangeo cloud deployment with conda, and it took quite long. I actually cancelled the install and used mamba instead. It was leaps and bounds faster. 

I think it would really improve the user experience if you could add `mamba install -c conda-forge pygmt` (maybe with a short link to the mamba docs) to the install docs.

**Comment by seisman** [comment]
This issue is labeled "good first issue", but it's unclear to me what's the best way to add the information of mamba? Should we add a new subsection or a short note on the installation page?
