### ISSUE TITLE
Replace pkg_resources with importlib.metadata

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1672]
**Description of the problem**

https://github.com/GenericMappingTools/pygmt/blob/24600ee8dfaf66948fef300fcb2469378b84d6fd/pygmt/__init__.py#L23

In `__init__.py`, we use the `get_distribution` function from the pkg_resources module to get the version string of the PyGMT package. 

It seems, `pkg_resources` is no longer recommended.

https://setuptools.pypa.io/en/latest/pkg_resources.html

> Use of pkg_resources is discouraged in favor of importlib.resources, importlib.metadata, and their backports (resources, metadata). Please consider using those libraries instead of pkg_resources.

https://github.com/pypa/setuptools_scm#retrieving-package-version-at-runtime

> Alternatively, you can use pkg_resources which is included in setuptools (but has a significant runtime cost):

I think we should use `importlib.metadata` instead:
```
from importlib.metadata import version
__version__ = version("pygmt")
```

The `importlib.metadata` module was added in Python 3.8, but PyGMT currently still supports Python 3.7. Luckily, we're going to drop Python 3.7 support on Dec. 26, 2021 as per [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table), so it won't be a problem for us.

**Comment by weiji14** [comment]
Closed by #1674
