### ISSUE TITLE
dvc pull issues on macOS latest CI

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1693]
**Description of the problem**

The tests on macOS-latest are frequently timing out on the `dvc pull` step, which is detrimental to noticing actual problems. Here is a short summary of the issue:

- Issue first started ~Nov 14, 2021
- CI runs ubuntu-latest, macOS-latest, and windows-latest with Python 3.8 or Python 3.9. The problem only occurs on [macOS-latest](https://github.com/actions/virtual-environments/blob/macOS-11/20220322.1/images/macos/macos-11-Readme.md), independent of the Python version.
- dvc is installed using [mambaforge with conda-forge dependencies](https://github.com/GenericMappingTools/pygmt/blob/0aa04d79dfd5d1aeaec9e4b2e4b43850bd6c0299/.github/workflows/ci_tests.yaml#L80-L100)
- Latest CI jobs run with dvc 2.9.5
- The verbose output indicates that it always fails on the step ``Querying 159 hashes via object_exists``
- We temporarily pinned dvc to 2.8.2 in https://github.com/GenericMappingTools/pygmt/pull/1694, but that did not solve the issue

**Comment by seisman** [comment]
Yes to me.

**Comment by meghanrjones** [comment]
Unfortunately pinning to dvc 2.8.2 does not seem to have fixed the issue based on https://github.com/GenericMappingTools/pygmt/runs/4809376001?check_suite_focus=true.

**Comment by meghanrjones** [comment]
Maybe. Let's close it and re-open if it is noticed again.
