### ISSUE TITLE
Examples to make earthquake profile line

### ISSUE THREAD

**Issue by ecastillot** [GenericMappingTools/pygmt#1767]
Hi everyone,

Do you have an example to make an earthquake profile line. In GMT, normally I used psxy to do this task. How could I do in pygmt?

Thanks.
Regards

**Comment by weiji14** [comment]
Hi @ecastillot! Have a look at https://forum.generic-mapping-tools.org/t/help-me-with-cross-section-plot/2391/4 and see if that is what you're after. If not, I would suggest posting your question on the forum (because GitHub is mainly for reporting bugs and asking for feature requests).
