### ISSUE TITLE
SEGY Functionality

### ISSUE THREAD

**Issue by tluckie13** [GenericMappingTools/pygmt#179]
Implement SEGY data plotting functionality (pssegy, segy2grd, etc.) to allow seismic data to be plotted using gmt-python

Cheers

**Comment by leouieda** [comment]
@tluckie13 could you be a bit more specific about your use case? I haven't used the GMT segy programs before so I'm not sure for what they are used. Is this for 2D data only? Is it plotting wiggles or images? If it's plotting images, would grdimage suffice if you can load the SEGY using another Python library?

**Comment by tluckie13** [comment]
@leouieda I'm looking to use gmt-python to plot a series of SEGY wiggles to make a shot gather. Plotting them as an image would be one way to do this, but being able to plot individual wiggles helps visualize the data more effectively in my case. [Here's an example of what I'd like to plot](http://www.subsurfwiki.org/images/3/3f/Example_shot_gather.jpg).

**Comment by seisman** [comment]
No feedbacks and no volunteers in two years. This PR is in very low priority. 

I'm closing the issue, and feel free to reopen it if you still want the feature implemented.
