### ISSUE TITLE
Enable auto staging after adding a file to dvc?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1803]
When running `dvc add pygmt/tests/baseline/test_meca_dict_offset.png`, I see the following message:
```
To track the changes with git, run:

    git add pygmt/tests/baseline/test_meca_dict_offset.png.dvc

To enable auto staging, run:

	dvc config core.autostage true
```

If I understand it correctly, if we configure `core.autostage` to `true`, when we add a file to dvc, the corresponding `.dvc` file will be automatically added to git. It seems useful and one less command to run. Do you think we should enable it?

**Comment by weiji14** [comment]
Maybe not, but you can set this config locally or globally according to https://dvc.org/doc/command-reference/config.

**Comment by seisman** [comment]
> set this config locally or globally according to [dvc.org/doc/command-reference/config](https://dvc.org/doc/command-reference/config).

Sounds good to me. Closing the issue.
