### ISSUE TITLE
Format and test-gmt-dev slash commands not working properly

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#1816]
**Description of the problem**

The `/format` and `/test-gmt-dev` slash commands added in #646 and #831 respectively seem to have stopped working like they used to, and probably for a while now to be honest. I think GitHub made some changes in regard to bot permissions some time ago (though I can't pin an exact date), and a lot of these tools with auto-commit functionality just broke.

To be specific:
1. For the `/format` command, an action is triggered and runs to completion, but no formatting commit actually happens. E.g.:
  - https://github.com/GenericMappingTools/pygmt/pull/1719#issuecomment-1065125258
  - https://github.com/GenericMappingTools/pygmt/pull/1812#issuecomment-1066258411
2. The `/test-gmt-dev` command, I think it does run (?), but you have to jump to the 'Actions' tab to see it run which is very inconvenient. From memory, I think there was another problem with how it wasn't testing the changes in the PR branch properly, but some rebased commit instead? E.g.:
  - https://github.com/GenericMappingTools/pygmt/pull/1577#issuecomment-944877093
  - https://github.com/GenericMappingTools/pygmt/pull/517#issuecomment-777194521

So, we'll either need to update these convenience slash commands, or remove them.

**Comment by seisman** [comment]
> 2\. The `/test-gmt-dev` command, I think it does run (?), but you have to jump to the 'Actions' tab to see it run which is very inconvenient.

Possible solution at https://github.com/peter-evans/slash-command-dispatch/issues/87#issuecomment-712577685.
