### ISSUE TITLE
Make it clear in the tutorials that they assume that you're using a notebook

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/pygmt#182]
The tutorials all assume that the user is running Jupyter with the many `fig.show()` calls. There should be a warning in the beginning of each tutorial stating that this works on notebooks and giving options for the terminal prompt (`fig.show(external=True)`) and in scripts `fig.savefig('figname.pdf', show=True)`.

**Comment by willschlitzer** [comment]
@GenericMappingTools/python Is this something we still want, and if so, should it be in the doc strings/lead section of every tutorial and gallery example?

**Comment by seisman** [comment]
The issue will become invalid after #529 is merged. That PR is almost working, however, I haven't found much time to finish it.

**Comment by willschlitzer** [comment]
Sounds good. Do you think it will be done before the v0.3 release? I'm not trying to hurry you, but I think if it's not the tutorials should at least be updated for the next release, and then removed once your pull request is merged.

**Comment by seisman** [comment]
> Do you think it will be done before the v0.3 release?

Not sure if I can find some time before v0.3 release. 

> I can submit a PR for this if it looks like it's the case that it won't be ready in time.

Go ahead, please.
