### ISSUE TITLE
Consistent format for author affiliations?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1825]
We have two files that list author affiliations. 

In the [`CITATION.cff`](https://github.com/GenericMappingTools/pygmt/blob/main/CITATION.cff) file, the affiliations generally follow the format "affiliation name, country" format (e.g, `University of Hawai'i at Mānoa, USA`), but some affiliations don't have the country information (e.g., `Tel Aviv University`). 

In the [`AUTHORS.md`](https://github.com/GenericMappingTools/pygmt/blob/main/AUTHORS.md) file, only the affiliation names are listed. The country information is not shown.

I suggest we can use a consistent format "affilation name, country" in both files.

Thoughts?

**Comment by michaelgrund** [comment]
Agree!
