### ISSUE TITLE
Should we say "coast" module, or "coast" method?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1828]
In GMT, `coast` is called a "module", which makes sense because GMT is a CLI program. In PyGMT, sometimes we say "the coast method", but sometimes we also say "the coast module" (for example, https://www.pygmt.org/dev/get-started/first_figure.html).

In the Python world, a [`module`](https://docs.python.org/3/tutorial/modules.html) usually means a Python file with some functions, and one can import the functions in the module using `from xxmodule import yyfunc`, but that's not the case for a PyGMT "module". I'm afraid it may cause some confusion for non-GMT users.

Should we not say "the coast module", and consitenly say "the coast method" instead?

**Comment by meghanrjones** [comment]
I agree with using Python-oriented language in the PyGMT docs (i.e., methods/functions) unless specifically referring to the GMT CLI.

**Comment by willschlitzer** [comment]
I think "method" words better than "module" to align this with Python lingo.
