### ISSUE TITLE
coupe 

### ISSUE THREAD

**Issue by JingHuiTong** [GenericMappingTools/pygmt#1829]
**Description of the desired feature**
Hi all, 
I try to cut a profile to plot my shear-wave splitting results to observe the fast-direction & splitting time difference. 
However, I appear that "coupe" hasn't been achieved so far. 
I don't know where is my station location in my new profile.
Moreover, coupe in GMT 6.2.0 only can plot focal mechanism. 
Can we plot another data? 
 
Thanks

**Are you willing to help implement and maintain this feature?** Yes/No

**Comment by seisman** [comment]
@JingHuiTong Perhaps the `project` module is what you need? See the GMT's [`project` documentation](https://docs.generic-mapping-tools.org/dev/project.html) or PyGMT's [`project` wrapper](https://www.pygmt.org/v0.6.0/api/generated/pygmt.project.html).

For more general questions, please go to the [GMT forum](https://forum.generic-mapping-tools.org/) instead.
