### ISSUE TITLE
Migrate settings from setup.py/setup.cfg to pyproject.toml

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1836]
As mentioned in https://github.com/GenericMappingTools/pygmt/issues/1797#issuecomment-1067056606, it's better to remove `setup.py`/`setup.cfg` and move all project metadata and packaging/buiding to `pyproject.toml`.

Here are some related resources I found on the internet:

### PEPs

- [PEP 517 – A build-system independent format for source trees](https://peps.python.org/pep-0517/)
- [PEP 518 – Specifying Minimum Build System Requirements for Python Projects](https://peps.python.org/pep-0518/)
- [PEP 621 – Storing project metadata in pyproject.toml](https://peps.python.org/pep-0621/)
- [PEP 631 – Dependency specification in pyproject.toml based on PEP 508](https://peps.python.org/pep-0631/)

#### General

- https://chadsmith.dev/python-packaging/
- https://bernat.tech/posts/pep-517-and-python-packaging/
- https://bernat.tech/posts/pep-517-518/

#### Setuptools

- https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
- https://github.com/pypa/setuptools/issues/1688
- https://discuss.python.org/t/help-testing-experimental-features-in-setuptools/13821
- https://github.com/pypa/setuptools/issues/2816
- 
### Poetry

- https://python-poetry.org/
- https://github.com/mtkennerly/poetry-dynamic-versioning
- https://github.com/GenericMappingTools/pygmt/pull/1055
- https://github.com/python-poetry/roadmap/issues/3

### Flit

- https://flit.pypa.io/en/latest/
- https://github.com/pypa/flit/issues/257

**Comment by weiji14** [comment]
So what's the next step after #1845? Migrating the `flake8` configuration in setup.cfg to pyproject.toml (xref https://github.com/GenericMappingTools/pygmt/issues/948#issuecomment-802939679)? I see you've discovered flakeheaven at https://github.com/flakeheaven/flakeheaven/issues/68, so we could move from flake8 -> flakeheaven once there's a proper conda-forge package?
