### ISSUE TITLE
BlockMean excludes datapoints with certain projections

### ISSUE THREAD

**Issue by kiyoomogi** [GenericMappingTools/pygmt#1878]
**Description of the problem**

I am trying to use the BlockMean function, which works fine when I don't specify any projection. However, when I specify certain projections (e.g. I use M4i), certain datapoints are excluded in the Mean calculations. On the attached pictures it can be seen that a lot of my datapoints don't generate a mean value. 

If anyone knows how to fix it, that would be amazing! 
Thanks in advance.

**Full code that generated the error**

```python
path = "..."
insar = pd.read_csv(path, delim_whitespace=True)

if path[48:51] == 'vel':
    data3 = "vel"
    subtext = "velocity [m/yr]"
else: 
    data3 = "displ"
    subtext = "displacement [m]"

data = insar[["long", "lat",data3]]

# Set the region for the plot
region = [-22.749375, -22.609891, 63.793357, 63.86]
#region = [-22.7343772,-22.6408409, 63.802192,63.8486304] 

# Define spacing in x and y direction (150 by 150 minute blocks)
spacing = '0.093k/0.105k'

fig = pygmt.Figure()

df = pygmt.blockmean(data=data, region=region, spacing=spacing)

# convert to grid
grd = pygmt.xyz2grd(data=df, region=region, spacing=spacing)

projection = None     #or "M4i"

fig.grdimage(
    projection=projection,
    grid=grd,
    region=[-22.749375, -22.609891, 63.793357, 63.86],
    frame=["af", '+t"%s - %s"'%(title1, title2)],
    cmap="haxby",
)

fig.plot(projection=projection,
    x=data.long, y=data.lat, style="c0.05c", color="white", pen="0.1p,black"
)
```

**System information**
PyGMT information:
  version: v0.5.0
System information:
  python: 3.10.2 | packaged by conda-forge | (main, Mar  8 2022, 16:02:23) [Clang 11.1.0 ]
  executable: ...
  machine: ...
Dependency information:
  numpy: 1.22.3
  pandas: 1.4.1
  xarray: 2022.3.0
  netCDF4: 1.5.8
  packaging: 21.3
  ghostscript: 9.54.0
  gmt: 6.3.0
GMT library information:
  binary dir: ...
  cores: 4
  grid layout: rows
  library path: ...
  padding: 2
  plugin dir: ...
  share dir: ...
  version: 6.3.0

```
PASTE THE OUTPUT HERE
```
<img width="457" alt="Schermafbeelding 2022-04-11 om 14 52 33" src="https://user-images.githubusercontent.com/101344020/162770501-842f62c2-ba2b-46e5-bd1b-3cfe4d42e286.png">

<img width="523" alt="Schermafbeelding 2022-04-11 om 14 52 15" src="https://user-images.githubusercontent.com/101344020/162770474-4663765c-10df-4646-bb34-d4c1f13fd8b0.png">

**Comment by seisman** [comment]
> projection = None     #or "M4i"

From what I see, `projection` is only used in your `grdimage` call, not in `blockmean`. So setting `projection` to `None` or `M4i` should NOT affect your `blockmean` output. Perhaps it's something wrong with the `grdimage` call?

It would be easier to help if you can share your data points with us.

**Comment by kiyoomogi** [comment]
Hello @seisman
Attached here is a csv file with the datapoints. 
It is indeed strange that the projection call that is done after the blockmean calculation somehow affects the outhput. 

[insar_data.csv](https://github.com/GenericMappingTools/pygmt/files/8465778/insar_data.csv)

**Comment by kiyoomogi** [comment]
Adding `projection = "M4i"` in `grd = pygmt.xyz2grd(data=df, region=region, spacing=spacing,projection="M4i")` also does not seem to fix the problem.

**Comment by seisman** [comment]
The CSV file you provided doesn't have the head information, so `pd.read_csv` reports the following error for me:
```
KeyError: "None of [Index(['long', 'lat', 'displ'], dtype='object')] are in the [columns]"
```

**Comment by kiyoomogi** [comment]
It should be fixed now. Had to convert it from ascii to csv. 

[insar_data.csv](https://github.com/GenericMappingTools/pygmt/files/8465932/insar_data.csv)

**Comment by kiyoomogi** [comment]
@seisman I installed the GMT dev version and I can recreate the correct blockmean image that you previously showed. 
Thanks a lot for the help! Glad to see this issue is fixed in the dev version.
