### ISSUE TITLE
Missing alias for option -F in basemap

### ISSUE THREAD

**Issue by jackbeagley** [GenericMappingTools/pygmt#1893]
**Description of the problem**

I am trying to add a filled background behind my mapscale, similar to the examples in the GMT documentation here: https://docs.generic-mapping-tools.org/dev/cookbook/features.html#placing-map-scales. From what I understand, when adding the map_scale, I should be able to simultaneously add a frame option specifying the fill parameters, like in my example code below, using the options from the GMT documentation. The code below runs when 'frame' isn't specified, but of course no background is generated behind the map_scale. I would be very appreciative if someone could point me in the right direction or let me know if this is in fact a bug. Thanks!

**Full code that generated the error**

```python
import pygmt

fig = pygmt.Figure()
fig.coast(
    # Set the x-range from 10E to 20E and the y-range to 35N to 45N
    region=[10, 20, 35, 45],
    projection="M12c",
    land="lightgray",
    water="white",
    borders="1/0.5p",
    shorelines="1/0.5p",
    frame="ag",
)
fig.basemap(map_scale='jBR+c36N+w100k+l+f', frame='+p1p+i+gwhite+c0.1i')
fig.show()
```

**Full error message**

```
pygmt.exceptions.GMTCLibError: Module 'basemap' failed with status code 72:
basemap [ERROR]: Option -B: Found frame setting modifiers (+b|g|i|n|o|t|w|x|y|z) mixed with axes settings!
basemap [ERROR]: Option -B parsing failure. Correct syntax:
basemap [ERROR]: Offending option -B+p1p+i+gwhite+c0.1i
```

**System information**

Please paste the output of `python -c "import pygmt; pygmt.show_versions()"`:

```
PyGMT information:
  version: v0.6.1
System information:
  python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:24:38)  [Clang 12.0.1 ]
  executable: /opt/homebrew/Caskroom/miniforge/base/bin/python
  machine: macOS-12.3.1-arm64-arm-64bit
Dependency information:
  numpy: 1.22.3
  pandas: 1.4.2
  xarray: 2022.3.0
  netCDF4: 1.5.7
  packaging: 21.3
  geopandas: 0.10.2
  ghostscript: 9.56.1
  gmt: 6.3.0
GMT library information:
  binary dir: /opt/homebrew/Caskroom/miniforge/base/bin
  cores: 10
  grid layout: rows
  library path: /opt/homebrew/Cellar/gmt/6.3.0_2/lib/libgmt.dylib
  padding: 2
  plugin dir: /opt/homebrew/Cellar/gmt/6.3.0_2/lib/gmt/plugins
  share dir: /opt/homebrew/Cellar/gmt/6.3.0_2/share/gmt
  version: 6.3.0
```

**Comment by michaelgrund** [comment]
The background color of the scale can be defined via the ``-F`` flag for which no alias is available so far in PyGMT. So, the following will do the job:

```
fig.basemap(map_scale = "jBR+c36N+w100k+l+f", F = "+glightcyan+c0+p")
```

<img src="https://user-images.githubusercontent.com/23025878/164613191-c4e091f5-998c-41f7-a5e9-afdda5a9395b.png" width="500">

**Comment by jackbeagley** [comment]
Far out that was easy... thanks @michaelgrund! @seisman what would this look like as a feature request? Could we have a method specifically for making map_scales? something like `fig.map_scale(...)`?

**Comment by seisman** [comment]
> what would this look like as a feature request? Could we have a method specifically for making map_scales? something like `fig.map_scale(...)`?

We just need to add an alias `F="box"` to the `@use_alias` decorator in the `basemap` function:

https://github.com/GenericMappingTools/pygmt/blob/555cd310b0afbb79330df02a5679ccf5358f5343/pygmt/src/basemap.py#L17-L34

then you can use:
```
fig.basemap(map_scale = "jBR+c36N+w100k+l+f", box="+glightcyan+c0+p")
```

**Comment by jackbeagley** [comment]
> > what would this look like as a feature request? Could we have a method specifically for making map_scales? something like `fig.map_scale(...)`?
> 
> We just need to add an alias `F="box"` to the `@use_alias` decorator in the `basemap` function:
> 
> https://github.com/GenericMappingTools/pygmt/blob/555cd310b0afbb79330df02a5679ccf5358f5343/pygmt/src/basemap.py#L17-L34
> 
> then you can use:
> 
> ```
> fig.basemap(map_scale = "jBR+c36N+w100k+l+f", box="+glightcyan+c0+p")
> ```

This seems very straightforward... are you happy if I have a crack at it?
