### ISSUE TITLE
Implement subplot command

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/pygmt#20]
This is a very cool new command.

**Comment by GengPeiLin** [comment]
Hi Leo,

Is there any progress to use gmt.Figure() with subplot?
Really love to see it works!!

GP

**Comment by leouieda** [comment]
Sorry, @GengPeiLin. No progress on that front yet. I've been busy with other things and haven't had much time for expanding the features yet.

**Comment by weiji14** [comment]
Just mentioning that @JFordHydro was interested in this feature during the [FOSS4G 2019 Oceania workshop](https://github.com/GenericMappingTools/foss4g2019oceania). Will see if we can get a Pull Request in tomorrow during [Community Day](https://2019.foss4g-oceania.org/community-day/) tomorrow!
