### ISSUE TITLE
Add a tutorial explaining the usage of octal codes

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2000]
Inspired by the question in https://github.com/GenericMappingTools/pygmt/issues/1994, we need to add a tutorial explaining how to correctly use [octal codes](https://docs.generic-mapping-tools.org/latest/cookbook/octal-codes.html) in PyGMT.

**Comment by seisman** [comment]
Related to https://github.com/GenericMappingTools/pygmt/issues/2204.

**Comment by JingHuiTong** [comment]
Hi @seisman, 
So far, I want to add the tutorial to examples/tutorials/basics/text.py 
I have some ideas to show 
1) incorrect v.s. correct usage 
2) correct usage with setting PS_CHAR_ENCODING to Standard+ or ISOLatin1+ 
Do you have other idea to show the example ?

**Comment by seisman** [comment]
> * incorrect v.s. correct usage
> * correct usage with setting PS_CHAR_ENCODING to Standard+ or ISOLatin1+
>   Do you have other idea to show the example ?

Sounds good. Also need to teach users how to read the big octal tables.
