### ISSUE TITLE
Inconsitent author lists of PyGMT version 0.7.0

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2002]
The author lists of _PyGMT_ version 0.7.0 differ between the [Zenodo upload]( https://zenodo.org/record/6702566#.YssouDfP1PY) and the [GitHub README](https://github.com/GenericMappingTools/pygmt#citing-pygmt) / the [Webpage 'Citing PyGMT' section](https://www.pygmt.org/v0.7.0/#citing-pygmt). The authors 'Andre Belem' and 'Yvonne Fröhlich' are missing in / were not added to the `README.rst` file :wink:.

**Comment by yvonnefroehlich** [comment]
I am sorry, did not see @weiji14's comment https://github.com/GenericMappingTools/pygmt/pull/1981#discussion_r917498998 until now.

**Comment by seisman** [comment]
Could you please open a PR to fix it?
