### ISSUE TITLE
Inconsistent handling of whitespaces in titles and labels across gallery and tutorial examples

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2013]
Up on [#1487](https://github.com/GenericMappingTools/pygmt/pull/1487) it is no longer required to use additional quotes for titles and labels containing whitespaces (`'+t"my title"'` or `'+l"my label"'`). In [#1950](https://github.com/GenericMappingTools/pygmt/pull/1950) the Intro to PyGMT [Making your first figure](https://www.pygmt.org/dev/get-started/first_figure.html#add-a-title) is already updated. However, several older gallery and tutorial examples still use this trick. To avoid confusion and for consistency, I think, we should adjust these examples.

**Comment by seisman** [comment]
I agree.

**Comment by yvonnefroehlich** [comment]
I can give it a try and work on it over time.
