### ISSUE TITLE
Unclear introduction sentence of Tutorial 'Frames, ticks, titles, and labels'

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2021]
The introduction sentence of the tutorial [Frames, ticks, titles, and labels](https://www.pygmt.org/dev/tutorials/basics/frames.html#frames-ticks-titles-and-labels) makes no sense and is incomplete:

> Setting the style of the map frames, ticks, etc, is handled by the frame parameter that all plotting methods of pygmt.Figure.

Probably / At least the verb is missing, maybe something like "have" or "contain"? I did not control, if all methods of the class [`pygmt.Figure`](https://www.pygmt.org/dev/api/generated/pygmt.Figure.html#pygmt.Figure) have the `frame` parameter. Maybe this formulation can be indirectly misleading regarding the method [`pygmt.Figure.colorbar`](https://www.pygmt.org/dev/api/generated/pygmt.Figure.colorbar.html#pygmt.Figure.colorbar), since there the `frame`parameter manipulates not the frame of the map, but the frame of the colorbar.

**Comment by seisman** [comment]
> Probably / At least the verb is missing, maybe something like "have" or "contain"?

Yes to me.

> Maybe this formulation can be indirectly misleading regarding the method [`pygmt.Figure.colorbar`](https://www.pygmt.org/dev/api/generated/pygmt.Figure.colorbar.html#pygmt.Figure.colorbar), since there the `frame`parameter manipulates not the frame of the map, but the frame of the colorbar.

Feel free to make changes as you like. I think at least we can change `all plotting modules` to `most plotting modules`.

**Comment by yvonnefroehlich** [comment]
Sounds like a plan. Try to work on this in the next days / week :wink:
