### ISSUE TITLE
Tests fail with xarray 2022.6.0 + numpy 1.20

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2022]
**Description of the problem**

See the latest test report https://github.com/GenericMappingTools/pygmt/runs/7478048802?check_suite_focus=true.

xarray 2022.6.0 was released on Jul 23, 2022. It seems the new release breaks our tests for Python 3.8.

Let's wait for a few days and see if they have a fix.

**Comment by seisman** [comment]
Upstream bug report at https://github.com/pydata/xarray/issues/6818

**Comment by weiji14** [comment]
Xarray has patched this in https://github.com/pydata/xarray/pull/6821, but it will be a while before an xarray 2022.8.0 or 2022.9.0 release is made, we've workaround this by setting the CI Tests to run on NumPy 1.21 instead in #2057.
