### ISSUE TITLE
Inconsistent usage of 'function' and 'method'

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2029]
It seems that the terms 'function' and 'method' are used exchangeable in the tutorial and gallery examples.

From my understanding, in Python a method belongs to a class and is associated with / called on an object. This is consistent to the API Documentation of the [`pygmt.Figure`](https://www.pygmt.org/dev/api/generated/pygmt.Figure.html) class.

However,
- there are examples which use 'function' for the methods of the `pygmt.Figure` class, e.g.:
  - [Making subplots](https://www.pygmt.org/dev/tutorials/advanced/subplots.html#define-subplot-layout): The `pygmt.Figure.subplot` function
- there are examples which use 'method' for the tabular and raster data processing functions, e.g.:
  - [Generate points along great circles](https://www.pygmt.org/dev/gallery/lines/great_circles.html#generate-points-along-great-circles): The `pygmt.project` method
  - [Create ‘wet-dry’ mask grid](https://www.pygmt.org/dev/gallery/images/grdlandmask.html#create-wet-dry-mask-grid): The `pygmt.grdlandmask` method
  - [Blockmean](https://www.pygmt.org/dev/gallery/histograms/blockm.html#blockmean): The `pygmt.blockmean` method

I think, we should be precise and consistent with the terminology (at least in the way that something is always either a function or a method) to avoid confusions.

**Comment by maxrjones** [comment]
Good catch @yvonnefroehlich! Glad to review a PR for this if you want to submit a correction for these misnomers.

**Comment by yvonnefroehlich** [comment]
I try to work on this over time.
