### ISSUE TITLE
Missing colorbars in examples

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2030]
In two examples a colormap is used but the corresponding colorbar is missing.

- [Creating a map with contour lines](https://www.pygmt.org/dev/tutorials/advanced/contour_map.html)
- [Sampling along tracks](https://www.pygmt.org/dev/gallery/images/track_sampling.html#sphx-glr-gallery-images-track-sampling-py)

This limits the interpretability of the  figures (especially for [Sampling along tracks](https://www.pygmt.org/dev/gallery/images/track_sampling.html#sphx-glr-gallery-images-track-sampling-py)).  Thus, I think a colorbar should be added.

**Comment by seisman** [comment]
I agree with you on both examples. Ping the original authors for comments before making the changes @willschlitzer @weiji14.

**Comment by yvonnefroehlich** [comment]
May I ask what the status of this issue is? Meaning, is it welcome by the original authors @willschlitzer and @weiji14 that colorbars are added to their examples, or should these two examples remain unchanged? In the first case, is it fine that I work on this, if I have time? Or do you prefer to make these changes on your own, which is of course totally fine for me?

**Comment by weiji14** [comment]
Oh yes, you are welcome to add colorbars to both examples. Let me assign you to the issue, and thanks for volunteering to help out!

**Comment by yvonnefroehlich** [comment]
> Oh yes, you are welcome to add colorbars to both examples. Let me assign you to the issue, and thanks for volunteering to help out!

Thanks @weiji14. Is it fine, if I split this issue into two PRs, one per example?

**Comment by weiji14** [comment]
> > Oh yes, you are welcome to add colorbars to both examples. Let me assign you to the issue, and thanks for volunteering to help out!
> 
> Thanks @weiji14. Is it fine, if I split this issue into two PRs, one per example?

Two in one PR should be fine for this.

**Comment by yvonnefroehlich** [comment]
_Original posts_ by @weiji14 (https://github.com/GenericMappingTools/pygmt/pull/2190#pullrequestreview-1231163134) and @seisman (https://github.com/GenericMappingTools/pygmt/pull/2190#issuecomment-1366626976) regarding gallery example `track_sampling.py`
> The original intention of the `track_sampling.py` gallery example added in #308 was to showcase the `grdtrack` data processing function, rather than as a proper 'map' per se.
> 
> Personally, I feel that having just one colorbar (the normalized elevation one) would be enough, since the background grayscale earth_relief elevation is just for context. But I also find normalized elevation to be hard to interpret (see my comment below), so not sure what's a good plan forward 😅 What are your thoughts?

Perhaps we can rewrite the grdtrack example to something like (https://docs.gmt-china.org/latest/examples/ex026/):
![image](https://user-images.githubusercontent.com/3974108/209814577-9197fd6a-1878-4393-8f1a-a2de1e0510cb.png)

**Comment by weiji14** [comment]
Probably better to mention the `grdtrack` gallery example redesign in a separate issue. Can you open one @yvonnefroehlich?

**Comment by yvonnefroehlich** [comment]
> Probably better to mention the `grdtrack` gallery example redesign in a separate issue. Can you open one @yvonnefroehlich?

Yep, sure, please see https://github.com/GenericMappingTools/pygmt/issues/2282.
