### ISSUE TITLE
More precise names for Oblique Mercator projection examples

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2031]
GMT seems to support three variants of the Oblique Mercator projection. In the [Projection Table](https://www.pygmt.org/dev/projections/index.html?highlight=Oblique#projection-table) they are distinguished by '1: origin and azim' (`oa|oA` or `Oa|OA` ), '2: two points' (`ob|oB` or `Ob|OB`), and '3: origin and pole' (`oc|oC` or `Oc|OC` ). I think it would be helpful to add these specifications also to the titles of the corresponding examples above. Currently, there are three examples with the same name 'Oblique Mercator'  (see https://www.pygmt.org/dev/projections/index.html?highlight=Oblique#cylindric-projections).

**Comment by seisman** [comment]
Sounds good.
