### ISSUE TITLE
Use yaml configured issue forms?

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/pygmt#2050]
**Description of the desired feature**

The [YAML configured issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) are nice because they provide more obvious structure relative to the markdown issue templates and automatically format Python code. I could convert the current markdown issue templates to yaml if people agree that this would be a good change. An example of the 'new issue' format using yaml is below (from xarray):
![image](https://user-images.githubusercontent.com/14077947/184189692-edec01a2-ac47-4d9c-865e-468e58bcd92a.png)

**Are you willing to help implement and maintain this feature?** Yes

**Comment by weiji14** [comment]
Can I work on this @maxrjones? Got some time to spare right now so I can open a PR.

**Comment by maxrjones** [comment]
> Did we want to also use YAML configured issue forms for feature requests or any of the other items under https://github.com/GenericMappingTools/pygmt/issues/new/choose?

I generally prefer the rendering of the YAML configuration. Please go ahead with any of them. Thanks for working on this 🚀

**Comment by seisman** [comment]
Do we really need to convert the "Bump GMT version checklist" and "PyGMT release checklist" templates to YAML format? The original Markdown format looks easier to maintain than the YAML foramt.

**Comment by maxrjones** [comment]
> Do we really need to convert the "Bump GMT version checklist" and "PyGMT release checklist" templates to YAML format? The original Markdown format looks easier to maintain than the YAML foramt.

I agree that these seem fine as is
