### ISSUE TITLE
Inconsistent syntax for projections in documentation

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2059]
For some of the [Py]GMT projections the syntax is inconsistent between the [PyGMT overview table](https://www.pygmt.org/dev/projections/index.html#projection-table) and the specific documentation page, e.g.:
- [Mercator projection](https://www.pygmt.org/dev/projections/cyl/cyl_mercator.html)
- [Transverse Mercator projection](https://www.pygmt.org/dev/projections/cyl/cyl_transverse_mercator.html)
- [Cylindrical stereographic](https://www.pygmt.org/dev/projections/cyl/cyl_stereographic.html)
- [Equidistant cylindrical](https://www.pygmt.org/dev/projections/cyl/cyl_equidistant.html)

**Comment by yvonnefroehlich** [comment]
I could work on this, but I can't grant to finish it immediately...

I think it would be good to also submit a PR for the upstream GMT documentation, as there are also typos for some projections in the [overview table](https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html) or the specific documentation sections. Here is a list of typos I have found so far:
- [Lambert azimuthal equal area](https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html#ja) (`A`): `/` missing
- [Polar](https://docs.generic-mapping-tools.org/dev/cookbook/coordinate-transformations.html#jp) (`P`): `]` to much
- [Transverse Mercator](https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html#jt) (`T`): adjust syntax in overview table
- [Mercator](https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html#jm) (`M`): adjust syntax in overview table

**Comment by yvonnefroehlich** [comment]
@GenericMappingTools/pygmt-maintainers do you expect me to get this into the PyGMT v0.8.0 release, or should we leave this issue as good first issue and bump it back to a later release?

**Comment by willschlitzer** [comment]
@yvonnefroehlich In general we try to leave the `good first issue` issues until we get close to our next release, and then we get them done shortly before a PR. I submitted one for some of the issues above.

I'm not sure about the issues in `polar` and `lambert azimuthal equal area`; I see the inconsistencies in slashes/brackets between the GMT and PyGMT documentation, but I don't think the PyGMT syntax is necessarily the incorrect one.

**Comment by yvonnefroehlich** [comment]
> @yvonnefroehlich In general we try to leave the `good first issue` issues until we get close to our next release, and then we get them done shortly before a PR. I submitted one for some of the issues above.
> 
Thanks @willschlitzer for this background information and directly submitting a PR. (My question was not meant in a way that you or somebody else should immediately work  on this.)

> I'm not sure about the inconsistencies in `polar` and `lambert azimuthal equal area`; I see the inconsistencies in slashes/brackets between the GMT and PyGMT documentation, but I don't think the PyGMT syntax is necessarily the incorrect one.

Correct. Partly the upstream GMT table or documentation contains the typos (please see my comment https://github.com/GenericMappingTools/pygmt/issues/2059#issuecomment-1219454780). Thus, we also need a PR for the upstream documentation 🙂.

**Comment by yvonnefroehlich** [comment]
@GenericMappingTools/pygmt-maintainers I have started working on this in #2269.
