### ISSUE TITLE
(Incomplete) inline code examples of pygmt.Figure class

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2084]
Maybe the inline code examples for the [pygmt.Figure](https://www.pygmt.org/dev/api/generated/pygmt.Figure.html#pygmt.Figure) class are incomplete:
```python
fig = Figure()
fig.basemap(region=[0, 360, -90, 90], projection="W7i", frame=True)
fig.savefig("my-figure.png")
# Make sure the figure file is generated and clean it up
import os
os.path.exists("my-figure.png")
os.remove("my-figure.png")
```

```python
fig = Figure()
fig.basemap(region="JP", projection="M3i", frame=True)
# The fig.region attribute shows the WESN bounding box for the figure
print(", ".join(f"{i:.2f}" for i in fig.region))
```

From my understanding, these examples should be directly executable. In case this is correct, I feel these two examples can be improved:
```python
from pygmt import Figure
fig = Figure()

# OR

import pygmt
fig = pygmt.Figure()
```

**Comment by seisman** [comment]
I think you're right. These codes work well as doctests because `Figure` is already imported in the Python codes, but they're incomplete as inline code examples.
