### ISSUE TITLE
missing color palette

### ISSUE THREAD

**Issue by Sarenrenegade** [GenericMappingTools/pygmt#2087]
**Description of the problem**
 

**Full code that generated the error**

```python
def plot_map(trace, region_of_interest):
    
    """ This function will generate one frame for each step point of the seismogram for n stations
    
    INPUT : array (n lines, m+2 columns), column 1 : longitude of station, column 2: latitude of station, column 3 to m: seismogram
            region of interest : [min longitude, max long, min lat, max lat], type: list
            
    OUTPUT : n images classified sequentially in your working directory
    
    USER INPUT : cmap_value
               ( optionnal : resize of the region )
    !!! warning !!! : for the video to work the images must be named sequentially (eg : 0001 for the  first image if you have over 1000 image for the video. Do not change output name. """ 
                                                                               
    lon=trace[:,0]
    lat=trace[:,1]
    t=trace[:,2:trace.shape[1]-2]
    
    fig = pygmt.Figure()
    j=int(trace.shape[1]/2)
    fig.basemap(region=region_of_interest, projection="M15c", frame=True)
    fig.coast(land="grey")
    cmap_value=eval(input('Please enter a maximum value to set the colormap : '))
    pygmt.makecpt(cmap="polar", series=[-cmap_value, cmap_value]) # Amatrice filtered twice : 1.2*1e4
    fig.plot(x=lon, y=lat,color=t[:,j],cmap=True, style="c0.1c")
    fig.colorbar(position="JMR+o0.5c/0c+w5c/0.3c+n", scale=1e-3, frame=['af+lDéplacement_(z)','y+lmm'])
    fig.savefig('test.png')
    
    fig.show()
    keep_going=input('Are you satisfied with the plot ? (yes/no) ')
    
    while keep_going!='yes':
        reset_region=input('Do you wish to reset the region ? (yes/no) ')
        reset_cmap=input('Do you wish to reset the cmap boundary ? (yes/no) ')
        if reset_region == 'yes':
            region_of_interest=input('New region [min longitude, max long, min lat, max lat]: ')
            region_of_interest = region_of_interest.strip('[]').replace('"', '').replace(' ', '').split(',')
        if reset_cmap=='yes':
            cmap_value=eval(input('Please enter a maximum value to set the colormap : '))
            
        fig = pygmt.Figure()
        fig.basemap(region=region_of_interest, projection="M15c", frame=True)
        fig.coast(land="grey")
        
        pygmt.makecpt(cmap="polar", series=[-cmap_value, cmap_value]) # Amatrice filtered twice : 1.2*1e4
        
        fig.plot(x=lon, y=lat,color=t[:,j],cmap=True, style="c0.1c")
        fig.colorbar(position="JMR+o0.5c/0c+w5c/0.3c+n", scale=1e-3, frame=['af+lDéplacement_(z)','y+lmm'])   
        fig.show()
        keep_going=input('Are you satisfied with the plot? (yes/no) ')
    
    
    plot_all=input(str(t.shape[1])+' figures will be generated. Do you wish to plot and save all figures ? (yes/no) ')
    
    fig = pygmt.Figure()
    fig.basemap(region=region_of_interest, projection="M15c", frame=True)
    fig.coast(land="grey")
    pygmt.makecpt(cmap="polar", series=[-cmap_value, cmap_value]) # Amatrice filtered twice : 1.2*1e4
    
    if plot_all=='yes':
        print('Processing... (abort : crtl+c)')
        for n in range (0, t.shape[1]):
            fig.plot(x=lon, y=lat,color=t[:,n],cmap=True, style="c0.1c")
            fig.colorbar(position="JMR+o0.5c/0c+w5c/0.3c+n", scale=1e-3, frame=['af+ldéplacement_(z)','y+lmm'])
            
            if n<10:
                fig.savefig('filtered_00000'+str(n)+'.png')
            elif 10<=n<=99:
                fig.savefig('filtered_0000'+str(n)+'.png')
            elif 100<=n<=999:
                fig.savefig('filtered_000'+str(n)+'.png')
            elif 1000<=n<=9999:
                fig.savefig('filtered_00'+str(n)+'.png')
            elif 10000<=n<=99999:
                fig.savefig('filtered_0'+str(n)+'.png')
            elif 100000<=n<=999999:
                fig.savefig('filtered_'+str(n)+'.png')
trace=np.loadtxt('Amatrice_2016_filtered_normalized.txt')
region=[-11, 30, 35, 36]
plot_map(trace, region)
#input user cmap amatrice : 1.2*1e4
```

**Full error message**

```
makecpt [ERROR]: File c:/programs/gmt6/share/matlab/polar.cpt was not found
makecpt [ERROR]: Cannot find file c:/programs/gmt6/share/matlab/polar.cpt
makecpt [ERROR]: File c:/programs/gmt6/share/matlab/polar.cpt not found
[Session pygmt-session (62)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
Traceback (most recent call last):

  File "C:\Users\maure\anaconda3\envs\GMV\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "d:\gmv\main.py", line 92, in <module>
    f.plot_map(normalized_filtered, region_of_interest)

  File "D:\GMV\util\functions.py", line 271, in plot_map
    pygmt.makecpt(cmap="polar", series=[-cmap_value, cmap_value]) # Amatrice filtered twice : 1.2*1e4

  File "C:\Users\maure\anaconda3\envs\GMV\lib\site-packages\pygmt\helpers\decorators.py", line 585, in new_module
    return module_func(*args, **kwargs)

  File "C:\Users\maure\anaconda3\envs\GMV\lib\site-packages\pygmt\helpers\decorators.py", line 725, in new_module
    return module_func(*args, **kwargs)

  File "C:\Users\maure\anaconda3\envs\GMV\lib\site-packages\pygmt\src\makecpt.py", line 159, in makecpt
    lib.call_module(module="makecpt", args=arg_str)

  File "C:\Users\maure\anaconda3\envs\GMV\lib\site-packages\pygmt\clib\session.py", line 506, in call_module
    raise GMTCLibError(

GMTCLibError: Module 'makecpt' failed with status code 16:
makecpt [ERROR]: File c:/programs/gmt6/share/matlab/polar.cpt was not found
makecpt [ERROR]: Cannot find file c:/programs/gmt6/share/matlab/polar.cpt
makecpt [ERROR]: File c:/programs/gmt6/share/matlab/polar.cpt not found
```

**System information**

Please paste the output of `python -c "import pygmt; pygmt.show_versions()"`:

```
PyGMT information:
  version: v0.7.0
System information:
  python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:30:19) [MSC v.1929 64 bit (AMD64)]
  executable: C:\Users\maure\anaconda3\envs\GMV\python.exe
  machine: Windows-10-10.0.19043-SP0
Dependency information:
  numpy: 1.23.2
  pandas: 1.4.3
  xarray: 2022.6.0
  netCDF4: 1.6.0
  packaging: 21.3
  geopandas: None
  ghostscript: 9.54.0
  gmt: 6.4.0
GMT library information:
  binary dir: C:/Users/maure/anaconda3/envs/GMV
  cores: 8
  grid layout: rows
  library path: C:/Users/maure/anaconda3/envs/GMV/Library/bin/gmt.dll
  padding: 2
  plugin dir: C:/Users/maure/anaconda3/envs/GMV/Library/bin/gmt_plugins
  share dir: c:/programs/gmt6/share
  version: 6.4.0
```

**Comment by Sarenrenegade** [comment]
Hello, apparently the description of the problem doesn't display above, here it is:
When I try to create a colormap, pygmt seems to be looking for the cpt in the wrong directory share/matlab instead of share/cpt.
I resolved the problem by creating the matlab folder but I was wondering if somathong is wrong with my install, 
Thanks a lot.

**Comment by seisman** [comment]
What happens if you run the raw GMT command `gmt makecpt -Cpolar -T0/10` in CMD?

**Comment by Sarenrenegade** [comment]
It works:
(base) saren@LAPTOP-J7SO0S5F:~$ gmt makecpt -Cpolar -T0/10
0       blue    5       white
5       white   10      red
B       black
F       white
N       127.5

**Comment by seisman** [comment]
Could you please run the following simple script and post the long debugging messsages:
```
import pygmt

pygmt.config(GMT_VERBOSE="d")
pygmt.makecpt(cmap="polar", series=[0, 10])
```

**Comment by Sarenrenegade** [comment]
gmtset [DEBUG]: gmtlib_get_graphics_item: Fig: 6 Subplot: 2 Panel: () Inset: 0
pygmt-session [DEBUG]: Exit:  gmt_reload_settings
pygmt-session [DEBUG]: Enter: gmtlib_plot_C_format
pygmt-session [DEBUG]: Exit:  gmtlib_plot_C_format
pygmt-session [DEBUG]: Enter: gmtinit_get_history
pygmt-session [DEBUG]: gmtlib_get_graphics_item: Fig: 6 Subplot: 2 Panel: () Inset: 0
pygmt-session [DEBUG]: Enter: gmt_hash_init
pygmt-session [DEBUG]: Exit:  gmt_hash_init
Exception ignored on calling ctypes callback function: <function Session.create.<locals>.print_func at 0x00000227CC4BD1B0>
Traceback (most recent call last):
  File "C:\Users\maure\anaconda3\envs\GMV\lib\site-packages\pygmt\clib\session.py", line 353, in print_func
    message = message.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 69: invalid continuation byte
pygmt-session [DEBUG]: Exit:  gmtinit_get_history
pygmt-session [DEBUG]: Initialize FFTW with 8 threads.
pygmt-session [DEBUG]: GMT_Create_Session initialized GMT structure
pygmt-session [DEBUG]: Shared Library # 0 (core). Path = C:/Users/maure/anaconda3/envs/GMV/Library/bin/gmt.dll
pygmt-session [DEBUG]: Loading GMT plugins from: C:/Users/maure/anaconda3/envs/GMV/Library/bin/gmt_plugins
pygmt-session [DEBUG]: Shared Library # 1 (supplements). Path = C:/Users/maure/anaconda3/envs/GMV/Library/bin/gmt_plugins/supplements.dll
pygmt-session [DEBUG]: GMT now running in modern mode [Session ID = 9676]
pygmt-session [DEBUG]: GMT_Call_Command string: gmt makecpt -Cpolar -T0/10
pygmt-session [DEBUG]: Revised options: -Cpolar -T0/10
makecpt [DEBUG]: Look for file 0/10 in C:/Users/maure/.gmt
makecpt [DEBUG]: Look for file 0/10 in C:/Users/maure/.gmt/cache
makecpt [DEBUG]: Look for file 0/10 in C:/Users/maure/.gmt/server
makecpt [INFORMATION]: Prepare CPT via the master file polar
makecpt [DEBUG]: Look for file polar in C:/Users/maure/.gmt
makecpt [DEBUG]: Look for file polar in C:/Users/maure/.gmt/cache
makecpt [DEBUG]: Look for file polar in C:/Users/maure/.gmt/server
makecpt [DEBUG]: GMT: 0. Will try to find subdir=cpt stem = matlab/polar suffix=.cpt
makecpt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
makecpt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR C:/Users/maure/.gmt
makecpt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir C:/Users/maure/.gmt/cpt
makecpt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir c:/programs/gmt6/share/cpt
makecpt [DEBUG]: GMT: 5. gmt_getsharepath trying SHAREDIR c:/programs/gmt6/share
makecpt [DEBUG]: GMT: 6. gmt_getsharepath failed
makecpt [ERROR]: File c:/programs/gmt6/share/matlab/polar.cpt was not found
makecpt [ERROR]: Cannot find file c:/programs/gmt6/share/matlab/polar.cpt
makecpt [ERROR]: File c:/programs/gmt6/share/matlab/polar.cpt not found
[Session pygmt-session (66)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
Traceback (most recent call last):

  File "C:\Users\maure\AppData\Local\Temp\ipykernel_14896\496565120.py", line 4, in <cell line: 4>
    pygmt.makecpt(cmap="polar", series=[0, 10])

  File "C:\Users\maure\anaconda3\envs\GMV\lib\site-packages\pygmt\helpers\decorators.py", line 585, in new_module
    return module_func(*args, **kwargs)

  File "C:\Users\maure\anaconda3\envs\GMV\lib\site-packages\pygmt\helpers\decorators.py", line 725, in new_module
    return module_func(*args, **kwargs)

  File "C:\Users\maure\anaconda3\envs\GMV\lib\site-packages\pygmt\src\makecpt.py", line 159, in makecpt
    lib.call_module(module="makecpt", args=arg_str)

  File "C:\Users\maure\anaconda3\envs\GMV\lib\site-packages\pygmt\clib\session.py", line 506, in call_module
    raise GMTCLibError(

GMTCLibError: Module 'makecpt' failed with status code 16:
makecpt [ERROR]: File c:/programs/gmt6/share/matlab/polar.cpt was not found
makecpt [ERROR]: Cannot find file c:/programs/gmt6/share/matlab/polar.cpt
makecpt [ERROR]: File c:/programs/gmt6/share/matlab/polar.cpt not found

**Comment by seisman** [comment]
It seems that you have two GMT installed, one in the `C:/programs/gmt6` directory and one in the conda installation path (`C:/Users/maure/anaconda3/envs/GMV/Library/`).

Maybe installing two GMT versions causes the trouble.

**Comment by seisman** [comment]
BTW, could you please check if `c:/programs/gmt6/share/cpt/matlab/polar.cpt` exists?

**Comment by Sarenrenegade** [comment]
> Maybe installing two GMT versions causes the trouble.

That's what I thought but when I install pygmt in a virtual env through conda, by default it creates a new install of gmt in the virtual env. When I go in  `C:\Users\maure\anaconda3\envs\GMV\Library\share\gmt\cpt\` there is  a matlab directory with polar.cpt but not in `c:/programs/gmt6/share/cpt/`

Does this mean that I have to remove gmt from the program directory and access it in the virtual env?
And if I do so, will I still be able to use gmt from CMD?

**Comment by seisman** [comment]
> Does this mean that I have to remove gmt from the program directory and access it in the virtual env?

I think you can remove either of them.

> And if I do so, will I still be able to use gmt from CMD?

If you remove the GMT in the program directory, you can still use GMT from CMD after activating the "GMV" virtual env.

**Comment by Sarenrenegade** [comment]
Removing gmt from the ` c:/programs/` directory seems to do the trick, that's good to know. Thanks again!
