### ISSUE TITLE
pip >=21.3 is required for editable install 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2100]
**Description of the problem**

I just had a fresh install of the latest miniconda. It now ships Python 3.9.13 and pip 21.2.4 in the base environment by default.

Installing PyGMT in editable mode fails with the following error:
```
$ pip install --no-deps -e .
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/seisman/OSS/gmt/pygmt
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```
After upgrading pip to 21.3 or newer, the installation works again. 

It's related to a new feature in pip 21.3 (https://pip.pypa.io/en/stable/news/#v21-3), which was released on 2021-10-11.

> Support editable installs for projects that have a pyproject.toml and use a build backend that supports [PEP 660](https://peps.python.org/pep-0660/). ([#8212](https://github.com/pypa/pip/issues/8212))

So, it means that users who have pip<21.3 cannot install pygmt in editable mode.

**Comment by seisman** [comment]
Adding an empty `setup.cfg` file to the repository root directory can fix the issue. So, do we want to have `setup.cfg` back for users who have pip<21.3?

**Comment by weiji14** [comment]
If we want to add back a setup.cfg file, how long do we want to keep it for? Until PyGMT v0.9.0? v0.10.0?

**Comment by seisman** [comment]
I think we should keep it until the latest miniconda/Anaconda ships pip>=21.3 by default.

**Comment by seisman** [comment]
I'm reopening the issue so that we won't forge to remove the `setup.cfg` in the future.

**Comment by seisman** [comment]
The latest Anaconda/miniconda release in Oct. 2022 ships pip 22.2.2 by default (see the [Anaconda changelog](https://docs.anaconda.com/anaconda/reference/release-notes/#anaconda-2022-10-october-18-2022) and the [Anaconda package lists](https://docs.anaconda.com/anaconda/packages/pkg-docs/). Now it's time to remove the `setup.cfg` file.
