### ISSUE TITLE
ctypes and cffi?

### ISSUE THREAD

**Issue by paugier** [GenericMappingTools/pygmt#211]
It is just a small and fast question. I see in the documentation: "Interface with the GMT C API directly using ctypes (no system calls)."

I understood that now, cffi was just better than ctypes for new projects (see for example https://www.quora.com/How-can-I-decide-between-using-ctypes-and-CFFI-in-Python).

I was wondering if there is a reason why gmt-python doesn't use [cffi](https://cffi.readthedocs.io) instead of ctypes?

**Comment by leouieda** [comment]
Hi @paugier, thanks for the link! I hadn't seen that post.

Basically, I didn't really know about CFFI until recently. I've been having a good experience with ctypes and [numpy arrays have builtin support for it](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ctypes.html). Right now, I don't know if it's worth the trouble of switching if ctypes is working. But I'm open to suggestions if there is anything specific that CFFI can address. 

Thanks for taking the time to give feedback! I really appreciate it.

**Comment by seisman** [comment]
Can we close this 2.5-year-old issue? I don't think we will switch to cffi in the next few years.

**Comment by weiji14** [comment]
Yep, close it as wontfix. But feel free to reopen if someone wants to work on it :slightly_smiling_face:

**Comment by seisman** [comment]
Just tried cffi. The following example shows how to call the API function `GMT_Get_Enum`:
```python
>>> from cffi import FFI
>>> ffi = FFI()
>>> ffi.cdef("int GMT_Get_Enum (void *V_API, char *key);")
>>> lib = ffi.dlopen("libgmt.dylib")
>>> lib.GMT_Get_Enum(ffi.NULL, b"GMT_VF_LEN")
32
```
For comparison, the ctypes version is 
https://github.com/GenericMappingTools/pygmt/blob/50145914b5f42710f8f0ac3a7a676195d8a054c4/pygmt/clib/session.py#L263-L280
