### ISSUE TITLE
import pygmt raises ModuleNotFoundError in Jupyter

### ISSUE THREAD

**Issue by jason996cj** [GenericMappingTools/pygmt#2113]
Hello, thank you and your team for a job well done !My PYGMT does not work properly. Modulenotfounderror will appear when it is called after installation. However, when I go to PIP or Conda to install it, it says that it has been installed. 
And  I'm using windows 10 professional, cpu is 11th Gen Inter i7-11700. python software I'm using conda 4.14.0 platform, current python version is 3.9.12. GMT version installed on computer is 6.4.0, pygmt installed during debugging is latest version v0.7.0. During debugging I have used python 3.10, 3.8, 3.7 and other virtual environments, none of them will make pygmt work.

I failed to solve the problem by following some solutions on the Internet, so I had to turn to your development team for help, thank you!
my email: [cjungeo@163.com](mailto:cjungeo@163.com) ,looking forward to your reply or email !

**Comment by seisman** [comment]
Please provide more information so that we can help you:

1. How do you install Python?
2. How do you install PyGMT and GMT?
3. Please post the full error messages when your python raises "ModuleNotFoundError"

**Comment by jason996cj** [comment]
Hello Professor Tian, my situation is as follows.
1. python 3.9.12 installed with anaconda 4.14.0.
2. pygmt installed with the 6.4.0 installer downloaded from the gmt website; then pygmt installed with the “conda install --channel conda-forge pygmt” statement.
3. The error message says “ModuleNotFoundError: No module named 'pygmt'”, but checking the package will find that pygmt is already installed, and the error message is as shown.
 ![屏幕截图 2022-09-08 195505](https://user-images.githubusercontent.com/58262284/189115793-e34ea7ad-a10b-4fee-8c4c-506ad4a0b678.png)

**Comment by seisman** [comment]
Did you restart the kernel or Jupyter after installing pygmt? If not, you should try it.

**Comment by jason996cj** [comment]
Yes, I've restart them. I've restart and reinstalled many times.

**Comment by weiji14** [comment]
Cool, I'm starting to think these instructions should go into the installation page as we've seen this ModuleNotFoundError pop up 5 or more times already. Let's close this issue once we've added the documentation.

**Comment by seisman** [comment]
> Cool, I'm starting to think these instructions should go into the installation page as we've seen this ModuleNotFoundError pop up 5 or more times already. Let's close this issue once we've added the documentation.

I've never had any problems like this on Linux and macOS.

**Comment by weiji14** [comment]
Looking at the forum posts, it seems to be mostly Anaconda Windows users? Maybe something different in the setup. Still, the instructions also work for Linux/macOS so won't hurt I guess.

**Comment by jason996cj** [comment]
> > 酷，我开始认为这些说明应该进入安装页面，因为我们已经看到此 ModuleNotFoundError 弹出 5 次或更多次。一旦我们添加了文档，让我们关闭这个问题。
> 
> 我在 Linux 和 macOS 上从来没有遇到过这样的问题。

I ran into the same problem on my m1 Macbook this past July, but I didn't try to ask anyone else about it at the time, and I thought it might be a problem with the installation rules for the new version of anaconda.

**Comment by jason996cj** [comment]
> > Cool, I'm starting to think these instructions should go into the installation page as we've seen this ModuleNotFoundError pop up 5 or more times already. Let's close this issue once we've added the documentation.
> 
> I've never had any problems like this on Linux and macOS.

I ran into the same problem on my m1 Macbook this past July, but I didn't try to ask anyone else about it at the time, and I thought it might be a problem with the installation rules for the new version of anaconda.

**Comment by jason996cj** [comment]
> 



> Looking at the forum posts, it seems to be mostly Anaconda Windows users? Maybe something different in the setup. Still, the instructions also work for Linux/macOS so won't hurt I guess.

Tomorrow I'll try this method to solve the same problem on my Macbook, maybe the problem is in the anconda.

**Comment by jason996cj** [comment]
> > Cool, I'm starting to think these instructions should go into the installation page as we've seen this ModuleNotFoundError pop up 5 or more times already. Let's close this issue once we've added the documentation.
> 
> I've never had any problems like this on Linux and macOS.

I still decided to test it before going to bed so I brought the Mac back to my dorm room and it installed in one go with no errors.
Professor Tian, I'm sorry for my misremembering, I solemnly apologize for that, I think it was something else that failed me in July.
Probably the same as what @weiji14 said: (Maybe something different in the setup. Still, the instructions also work for Linux/macOS so won't hurt.).

<img width="1197" alt="截屏2022-09-09 00 15 41" src="https://user-images.githubusercontent.com/58262284/189174405-e981b460-5f6c-4487-864a-dc4c72dd7ba0.png">
