### ISSUE TITLE
GMT on Ubuntu 18.04

### ISSUE THREAD

**Issue by MartinThoma** [GenericMappingTools/pygmt#215]
I wanted to build GMT from source. I looked at http://gmt.soest.hawaii.edu/projects/gmt/wiki/BuildingGMT#UbuntuDebian, but got

> E: Unable to locate package libgdal1-dev

Installing only

> sudo apt-get install subversion build-essential cmake libcurl4-gnutls-dev libnetcdf-dev libfftw3-dev libpcre3-dev liblapack-dev libblas-dev

worked. I guessed that `libgdal-dev` was ment and installed it.

Then I followed http://gmt.soest.hawaii.edu/projects/gmt/wiki/BuildingGMT#Building-GMT-from-source

Although I set `export GMT_LIBRARY_PATH=$HOME/GitHub/gmt-dev/build/src` (where I built gmt-dev and where the libgmt.so is), I get the error

## Full code/command that generated the error

    >>> import gmt

## Full error message

```
---------------------------------------------------------------------------
GMTCLibError                              Traceback (most recent call last)
<ipython-input-3-bc3c7e33fc1a> in <module>()
----> 1 import gmt  # https://www.gmtpython.xyz/latest/install.html

~/.local/lib/python3.6/site-packages/gmt/__init__.py in <module>()
     15 
     16 # Start our global modern mode session
---> 17 _begin()
     18 # Tell Python to run _end when shutting down
     19 _atexit.register(_end)

~/.local/lib/python3.6/site-packages/gmt/session_management.py in begin()
     15     """
     16     prefix = 'gmt-python-session'
---> 17     with LibGMT() as lib:
     18         lib.call_module('begin', prefix)
     19 

~/.local/lib/python3.6/site-packages/gmt/clib/core.py in __init__(self)
    155 
    156     def __init__(self):
--> 157         self._libgmt = load_libgmt()
    158         self._session_id = None
    159         self._session_name = 'gmt-python-session'

~/.local/lib/python3.6/site-packages/gmt/clib/core.py in load_libgmt(libname)
    122     try:
    123         libgmt = ctypes.CDLL('.'.join([libname, clib_extension()]))
--> 124         check_libgmt(libgmt)
    125     except OSError as err:
    126         msg = ' '.join([

~/.local/lib/python3.6/site-packages/gmt/clib/core.py in check_libgmt(libgmt)
     69                 "Couldn't access function GMT_{}.".format(func),
     70             ])
---> 71             raise GMTCLibError(msg)
     72 
     73 

GMTCLibError: Error loading libgmt. Couldn't access function GMT_Get_Enum.
```

## System information

* Operating system: Ubuntu 18.04
* Python installation (Anaconda, system, ETS):
* Version of GMT/Python: 3.6.5
* How you installed GMT/Python: pre-installed python

*If this is a **question or feature request**, delete the above lines and instead:*

* Describe the feature you desire in as much detail as possible:

* Are you willing to try to implement and maintain this feature? 
  We'll help you through the process.

**Comment by leouieda** [comment]
Hi @MartinThoma :wave:, thanks for reporting this issue! I think you're the first one to try to do this :)

That's a strange error. It's happening when we check if the GMT library has some common functions: https://github.com/GenericMappingTools/gmt-python/blob/master/gmt/clib/loading.py#L137

I've actually never see this fail before. Could you please post the output of `gmt --version`?  I'll try to reproduce your error on my machine.

**Comment by janjaapmeijer** [comment]
I get a similar error message like this, when I follow the exact instruction from: https://www.gmtpython.xyz/latest/install.html.

**Comment by akshmakov** [comment]
@MartinThoma @janjaapmeijer  I believe this may be due to same API change issue identified in #222, depending on revision built. Revision of gmt 6.0.0 after r20437 will not work without using the code proposed in pr #224. The timing is convenient, this issue was opened 19 days ago, which is 2 days after `r20437` was pushed.

**Comment by Khalilsqu** [comment]
I am getting the same error.

I am using windows linux subsystem.

distribution anaconda python 3.6.5
gmt is installed using pip.

`pip install gmt-python`

conda installation also gives the same error.

```
Traceback (most recent call last):
  File "/home/khalil/anaconda3/lib/python3.6/site-packages/gmt/clib/core.py", line 123, in load_libgmt
    libgmt = ctypes.CDLL('.'.join([libname, clib_extension()]))
  File "/home/khalil/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgmt.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/kalho/Desktop/ubuntu/Untitled.py", line 1, in <module>
    import gmt
  File "/home/khalil/anaconda3/lib/python3.6/site-packages/gmt/__init__.py", line 17, in <module>
    _begin()
  File "/home/khalil/anaconda3/lib/python3.6/site-packages/gmt/session_management.py", line 17, in begin
    with LibGMT() as lib:
  File "/home/khalil/anaconda3/lib/python3.6/site-packages/gmt/clib/core.py", line 157, in __init__
    self._libgmt = load_libgmt()
  File "/home/khalil/anaconda3/lib/python3.6/site-packages/gmt/clib/core.py", line 132, in load_libgmt
    raise GMTCLibNotFoundError(msg)
gmt.exceptions.GMTCLibNotFoundError: Couldn't find the GMT shared library 'libgmt'. Have you tried setting the LD_LIBRARY_PATH environment variable?
Original error message:

    libgmt.so: cannot open shared object file: No such file or directory
```

**Comment by seisman** [comment]
I think this issue can be closed, since our travis tests now build GMT from source and pass.
