### ISSUE TITLE
Update instructions for checking README syntax for release

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/pygmt#2173]
**Description of the desired feature**

The instructions from the maintenance guide for [checking the README syntax](https://www.pygmt.org/latest/maintenance.html#check-the-readme-syntax) prior to a release are outdated since we no longer use setup.py.

We should be able to use [twine to check the long description](https://twine.readthedocs.io/en/stable/#twine-check) instead, ideally as part of the CI rather than as a manual part of the release process.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by weiji14** [comment]
> We should be able to use [twine to check the long description](https://twine.readthedocs.io/en/stable/#twine-check) instead, ideally as part of the CI rather than as a manual part of the release process.

Sounds good, maybe put the `twine` check somewhere in https://github.com/GenericMappingTools/pygmt/blob/v0.7.0/.github/workflows/publish-to-pypi.yml following what you did in https://github.com/xarray-contrib/xbatcher/pull/108?

**Comment by seisman** [comment]
As I understand it, `twine check` only checks if the long description will render correctly, which may not help if someone mistypes `*abc*` as `**abc*`.

Perhaps we can simply visit the TestPyPI release history page (https://test.pypi.org/project/pygmt/#history), and click to the README page of the latest dev release (e.g., https://test.pypi.org/project/pygmt/0.7.1.dev130/ now).

**Comment by maxrjones** [comment]
> Just found a issue by visiting the latest dev version on the TestPyPI page (https://test.pypi.org/project/pygmt/0.7.1.dev157/).

> The maintainer information are not correctly shown

From https://packaging.python.org/en/latest/specifications/core-metadata/#maintainer:

> Note that this field is intended for use when a project is being maintained by someone other than the original author: it should be omitted if it is identical to Author.

I see this in many packages, but I think we should not have separate maintainers metadata because it is identical to authors.
