### ISSUE TITLE
Support non-ASCII characters in PyGMT arguments and text in Figure.text

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2204]
## Problems

Due to the limitation of the PostScript language, GMT can only work with ASCII characters and a small set of non-ASCII characters. See https://docs.generic-mapping-tools.org/latest/cookbook/octal-codes.html for the full list of characters that PostScript/GMT/PyGMT can accept.

These non-ASCII characters must be specified using their [octal codes](https://docs.generic-mapping-tools.org/latest/cookbook/octal-codes.html) or [character escape sequence](https://docs.generic-mapping-tools.org/latest/cookbook/features.html#character-escape-sequences). A few non-ASCII characters (e.g., ü, Î) are allowed and GMT can substitute these non-ASCII characters with the correct PostScript octal codes.

Users who don't know the limitations may pass non-ASCII characters directly in the arguments. For example:
```
import pygmt
fig = pygmt.Figure()
fig.basemap(region=[0, 10, 0, 5], projection="x1c", frame="WSen+tTime (s) vs Distance (°)")
fig.show()
```
The above script produces this "surprising" figure:

![non-ascii](https://user-images.githubusercontent.com/3974108/203463340-bad4d200-252d-477e-8428-0a451fe0c7b0.png)

So, if users want to add a non-ASCII character to a plot, they must know the limitations and have to go to this page https://docs.generic-mapping-tools.org/latest/cookbook/octal-codes.html, look for the character in the four tables, and figure out the corresponding octal code (`\260` for the symbol `°`), which is tedious and not easy.

After finding the octal code, users may think changing `°` to `\260` should work: 
```
import pygmt
fig = pygmt.Figure()
fig.basemap(region=[0, 10, 0, 5], projection="x1c", frame="WSen+tTime (s) vs Distance (\260)")
fig.show()
```
but it still produces the same "surprising" figure, because the Python interpreter recognizes `\260` first, and converts it to `°` before passing it to the GMT API. So, users have to use double backslashes or raw strings:
```
frame="WSen+tTime (s) vs Distance (\\260)"
```
or
```
frame=r"WSen+tTime (s) vs Distance (\260)"
```

## Solutions

Since Python works well with non-ASCII characters (acutally it works with any unicode characters), it's possible to pass `°` in Python, and PyGMT should substitute the non-ASCII characters with the corresponding octal codes.

Here are some tests in Python:

```python
# Python support non-ASCII characters
>>> "WSen+tTime (s) vs Distance (°)"
'WSen+tTime (s) vs Distance (°)'

# Python knows how to convert \260 to °
>>> "WSen+tTime (s) vs Distance (\260)"
'WSen+tTime (s) vs Distance (°)'

# replace ° with \\260
>>> "WSen+tTime (s) vs Distance (°)".replace("°", "\\260")
'WSen+tTime (s) vs Distance (\\260)'

# how to convert ° to \\260. It should work for other non-ASCII characters
>>> oct(ord("°")).replace("0o", '\\')
'\\260'
```
So, if we can do the substitutions/conversions internally, we can support non-ASCII characters better. The simplest solution is to define a big dictionary that maps non-ASCII characters (e.g., `°`) to octal codes (e.g., `\260`). Better and more clever solutions are also possible.

## Notes about the possible limitations of the solutions

Non-ASCII characters can be used in many cases:

1. PyGMT arguments, e.g., `frame="WSen+tTime (s) vs Distance (°)"`
2. Text strings as input data, e.g., `fig.text(x=0, y=0, text="Distance (°)")`
3. Text strings in a plaintext file, e.g., a plaintext file with a record like `0 0 Distance (°)`

The above solution should work well for case 1, may work or not work (depending on the implentation)
for case 2, and likely don't work for case 3.

**Are you willing to help implement and maintain this feature?**

Yes, but more discussions are needed.

**Comment by seisman** [comment]
TODO list after PR #2584:

- [ ] Check PS_CHAR_ENCODING so it also works with Standard+ character set?
- [ ] Check arguments that are not processed by build_arg_string (e.g., text in Figure.text)
- [ ] Add a gallery example or a tutorial?

**Comment by weiji14** [comment]
Was trying to get the character [ā](https://en.wikipedia.org/wiki/%C4%80) (Latin small letter a with macron) to plot using either ISO-8859-4/ISO-8859-10/ISO-8859-13 in https://github.com/GenericMappingTools/pygmt/pull/2641#discussion_r1305245499, but doesn't work when setting `pygmt.config(PS_CHAR_ENCODING="ISO-8859-4")`, because we need to use `--PS_CHAR_ENCODING` inline according to https://docs.generic-mapping-tools.org/6.4/gmt.conf.html#term-PS_CHAR_ENCODING:

> **Note**: Normally the character set is written as part of the PostScript header. If you need to switch to another character set for a later overlay then you must use **--PS_CHAR_ENCODING**=encoding on the command line and not via gmt [gmtset](https://docs.generic-mapping-tools.org/6.4/gmtset.html).

Workaround was to use the composite character `@!a\225` following https://docs.generic-mapping-tools.org/6.4/tutorial/session-2.html#plotting-text-strings. I'm not sure if it's worth adding `--PS_CHAR_ENCODING` as an option to plotting methods to make it easier. I think we discussed a while ago not to support double-dash `--` inline options?

**Comment by seisman** [comment]
After PRs #2584, #2638, #3192, and #3199, PyGMT already provides basic support for non-ASCII characters.

In short, we're maintaining a big dictionary mapping non-ASCII characters to their octal codes.  So users can pass a character like `ɑ` (alpha) and PyGMT will map it to `@~\\141@~`. There is no direct way to type `ɑ` using a keyboard (maybe there are shortcuts, but who can remember them all?), so users usually need to copy and paste from another source. However, many characters look similar. For example, this page (https://www.compart.com/en/unicode/search?q=alpha#characters) lists many alpha-like characters. Guess which one is supported by PyGMT? The answer is [U+03B1](https://www.compart.com/en/unicode/U+03B1). Users may use the "incorrect" one and then get surprising results.

To solve the problem, we need character tables that users can copy. The official GMT documentation provides the tables (https://docs.generic-mapping-tools.org/dev/reference/octal-codes.html) in PNG/PDF format but they're not easy to copy. Better tables are available at

- https://www.compart.com/en/unicode/charsets/Adobe-Symbol-Encoding
- https://www.compart.com/en/unicode/charsets/Adobe-Standard-Encoding
- https://www.compart.com/en/unicode/charsets/x-Adobe-Zapf-Dingbats-Encoding

However, these tables are "incomplete" (some characters are missing) compared to the GMT ones. For example, in the **Symbol** table, `\322` is `©`, but in https://www.compart.com/en/unicode/charsets/Adobe-Symbol-Encoding, it's mapped to Unicode character [U+F6DA](https://www.compart.com/en/unicode/U+F6DA), which belongs to the "Private Use Area" block (I guess there must be some historical reasons behind). So, instead of using the private, invisible U+F6DA, we should map `©` ([U+00A9](https://www.compart.com/en/unicode/U+00A9)) to `@~\\322@~`. It also means we need to maintain our own character tables.

I'm working on creating these character tables at https://github.com/seisman/GMT-octal-codes. Here is a sample output based on the official mapping file (https://www.unicode.org/Public/MAPPINGS/VENDORS/ADOBE/symbol.txt, last updated in 2011). Characters displayed like &#xf8e5; are the "incorrect" characters that belong to the Private Use Area block. They should be manually maintained. 

| octal | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
|---|---|---|---|---|---|---|---|---|
| \04x | &#xa0; | &#x21; | &#x2200; | &#x23; | &#x2203; | &#x25; | &#x26; | &#x220b;|
| \05x | &#x28; | &#x29; | &#x2217; | &#x2b; | &#x2c; | &#x2212; | &#x2e; | &#x2f;|
| \06x | &#x30; | &#x31; | &#x32; | &#x33; | &#x34; | &#x35; | &#x36; | &#x37;|
| \07x | &#x38; | &#x39; | &#x3a; | &#x3b; | &#x3c; | &#x3d; | &#x3e; | &#x3f;|
| \10x | &#x2245; | &#x391; | &#x392; | &#x3a7; | &#x2206; | &#x395; | &#x3a6; | &#x393;|
| \11x | &#x397; | &#x399; | &#x3d1; | &#x39a; | &#x39b; | &#x39c; | &#x39d; | &#x39f;|
| \12x | &#x3a0; | &#x398; | &#x3a1; | &#x3a3; | &#x3a4; | &#x3a5; | &#x3c2; | &#x2126;|
| \13x | &#x39e; | &#x3a8; | &#x396; | &#x5b; | &#x2234; | &#x5d; | &#x22a5; | &#x5f;|
| \14x | &#xf8e5; | &#x3b1; | &#x3b2; | &#x3c7; | &#x3b4; | &#x3b5; | &#x3c6; | &#x3b3;|
| \15x | &#x3b7; | &#x3b9; | &#x3d5; | &#x3ba; | &#x3bb; | &#x3bc; | &#x3bd; | &#x3bf;|
| \16x | &#x3c0; | &#x3b8; | &#x3c1; | &#x3c3; | &#x3c4; | &#x3c5; | &#x3d6; | &#x3c9;|
| \17x | &#x3be; | &#x3c8; | &#x3b6; | &#x7b; | &#x7c; | &#x7d; | &#x223c; |  |
| \24x | &#x20ac; | &#x3d2; | &#x2032; | &#x2264; | &#x2215; | &#x221e; | &#x192; | &#x2663;|
| \25x | &#x2666; | &#x2665; | &#x2660; | &#x2194; | &#x2190; | &#x2191; | &#x2192; | &#x2193;|
| \26x | &#xb0; | &#xb1; | &#x2033; | &#x2265; | &#xd7; | &#x221d; | &#x2202; | &#x2022;|
| \27x | &#xf7; | &#x2260; | &#x2261; | &#x2248; | &#x2026; | &#xf8e6; | &#xf8e7; | &#x21b5;|
| \30x | &#x2135; | &#x2111; | &#x211c; | &#x2118; | &#x2297; | &#x2295; | &#x2205; | &#x2229;|
| \31x | &#x222a; | &#x2283; | &#x2287; | &#x2284; | &#x2282; | &#x2286; | &#x2208; | &#x2209;|
| \32x | &#x2220; | &#x2207; | &#xf6da; | &#xf6d9; | &#xf6db; | &#x220f; | &#x221a; | &#x22c5;|
| \33x | &#xac; | &#x2227; | &#x2228; | &#x21d4; | &#x21d0; | &#x21d1; | &#x21d2; | &#x21d3;|
| \34x | &#x25ca; | &#x2329; | &#xf8e8; | &#xf8e9; | &#xf8ea; | &#x2211; | &#xf8eb; | &#xf8ec;|
| \35x | &#xf8ed; | &#xf8ee; | &#xf8ef; | &#xf8f0; | &#xf8f1; | &#xf8f2; | &#xf8f3; | &#xf8f4;|
| \36x |   | &#x232a; | &#x222b; | &#x2320; | &#xf8f5; | &#x2321; | &#xf8f6; | &#xf8f7;|
| \37x | &#xf8f8; | &#xf8f9; | &#xf8fa; | &#xf8fb; | &#xf8fc; | &#xf8fd; | &#xf8fe; |  |

Here is a list of things that I think we can/should do:

- [ ] Maintain a "correct" mapping file based on the official ones (https://www.unicode.org/Public/MAPPINGS/VENDORS/ADOBE/)
- [ ] Create characters tables like the one above and put them in the PyGMT docs
- [ ] Update the `non_ascii_to_octal` function using the new mapping file to make sure that the characters in the function match those in the tables

**Comment by seisman** [comment]
@GenericMappingTools/pygmt-maintainers 

After a series of PRs, I think we already provide good support for non-ASCII characters. 

Things to note are:

- We're assuming that users are using the `ISOLatin1+` encoding by default
- The "Standard" or "Standard+" encodings are not supported

Supporting "Standard"/"Standard+" or allowing any default encoding can be tricky because we need to inquire about the current character encoding using `lib.get_default["PS_CHAR_ENCODING"]` in some places (e.g., in the `non_ascii_to_octal` function). 

We have some options:

1. Do nothing. Then we can close this issue. 
2. In `pygmt.begin()`, check the current `PS_CHAR_ENCODING`. Raise a warning if `PS_CHAR_ENCODING`!=`ISOLatin1+` and set `PS_CHAR_ENCODING=ISOLatin1+`. Assuming that users don't change `PS_CHAR_ENCODING` in the middle of a script.
3. Try hard to support "Standard"/"Standard+" encodings, which likely means we need to inquire the current character encoding in `non_ascii_to_octal`/`_check_encoding`, or we have to keep track of the changes of character encoding in a global variable.

I prefer option 2 and will work it if there are no objections or further comments in one week.

**Comment by seisman** [comment]
Acutally, there is option 4, i.e., adding `--PS_CHAR_ENCODING=<encoding>` even if the text string encoding is `ISOLatin1+`. I have implemented this option in https://github.com/GenericMappingTools/pygmt/pull/3611. Please see that PR for details.
