### ISSUE TITLE
Suggested improvement for api/generated/pygmt.select

### ISSUE THREAD

**Issue by mdtanker** [GenericMappingTools/pygmt#2209]
Please describe what could be improved about this page or the typo/mistake that you found:

It seems that `pygmt.select` allows `registration` to be set, while `gmtselect` does not recognize the `-r` flag. 

Should `registration` not be included as a parameter in `pygmt.select`?

**Comment by seisman** [comment]
You're right. Are you willing to submit a pull request to fix it? The source code of the `select` method is https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/select.py.

**Comment by mdtanker** [comment]
Thanks for fixing that, sorry I didn't get around to doing it myself!
