### ISSUE TITLE
[pygmt.surface] tension_factor

### ISSUE THREAD

**Issue by JingHuiTong** [GenericMappingTools/pygmt#2222]
### Description of the desired feature

Hello, 
I want to request the feature about surface-tension_factor (-T)
Due to this problem, we need to transfer pygmt to GMT6.2.0 now. 
Hoping the feature in GMT can implement in pygmt in the future.

Thanks! 

### Are you willing to help implement and maintain this feature?

Maybe

**Comment by weiji14** [comment]
Hi @JingHuiTong. This isn't documented, but you can try using

```python
grid = pygmt.surface(...,  T=0.35)
```

See e.g. example at https://www.generic-mapping-tools.org/egu22pygmt/lidar_to_surface.html#turn-points-into-a-grid.

If you do want to implement this feature, please add the `T="tension"` alias to the [`pygmt/src/surface.py` file](https://github.com/GenericMappingTools/pygmt/edit/main/pygmt/src/surface.py#L19-L33) at https://github.com/GenericMappingTools/pygmt/blob/8854774eedd2da092cbf2ee623b159ce8310b40a/pygmt/src/surface.py#L19-L33
