### ISSUE TITLE
Incorrect build documentation due to identical file names of examples 

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2250]
It seems like it is not allowed by Sphinx-Gallery that two examples have identical filenames, even when they are saved in different folders. Currently, this is the case for:
- Intro to PyGMT - **Create a contour map**: https://www.pygmt.org/dev/get_started/contour_map.html
- Tutorials - **Creating a map with contour lines**: https://www.pygmt.org/dev/tutorials/advanced/contour_map.html

When running `make html` to build the documentation locally, the following warning occurs:
```
WARNING: Duplicate example file name(s) found. Having duplicate file names will break some links.
List of files: ['../examples/get_started/contour_map.py']
```

According to this the documentation for the tutorial is wrongly build:
- correct - v0.7.0: https://www.pygmt.org/latest/tutorials/advanced/contour_map.html
- wrong - dev after adding "Create a contour map": https://www.pygmt.org/dev/tutorials/advanced/contour_map.html

Thus, we have to rename one of these two example files.

**Comment by seisman** [comment]
Ping @willschlitzer, author of the two examples .
