### ISSUE TITLE
Rewrite gallery example "track_sampling.py"

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2282]
_Original posts_ by @weiji14 (https://github.com/GenericMappingTools/pygmt/pull/2190#pullrequestreview-1231163134) and @seisman (https://github.com/GenericMappingTools/pygmt/pull/2190#issuecomment-1366626976) regarding gallery example [`track_sampling.py`](https://www.pygmt.org/dev/gallery/images/track_sampling.html#sphx-glr-gallery-images-track-sampling-py):
> The original intention of the `track_sampling.py` gallery example added in #308 was to showcase the `grdtrack` data processing function, rather than as a proper 'map' per se.
> 
> Personally, I feel that having just one colorbar (the normalized elevation one) would be enough, since the background grayscale earth_relief elevation is just for context. But I also find normalized elevation to be hard to interpret (see my comment below), so not sure what's a good plan forward 😅 What are your thoughts?

Perhaps we can rewrite the grdtrack example to something like (https://docs.gmt-china.org/latest/examples/ex026/):
![image](https://user-images.githubusercontent.com/3974108/209814577-9197fd6a-1878-4393-8f1a-a2de1e0510cb.png)

**Comment by yvonnefroehlich** [comment]
Do we simply want to re-write the example at https://docs.gmt-china.org/latest/examples/ex026/ to PyGMT, or are there some ideas on how to change the existing gallery example [track_sampling.py](https://www.pygmt.org/dev/gallery/images/track_sampling.html#sphx-glr-gallery-images-track-sampling-py)?

**Comment by weiji14** [comment]
> Do we simply want to re-write the example at https://docs.gmt-china.org/latest/examples/ex026/ to PyGMT, or are there some ideas on how to change the existing gallery example [track_sampling.py](https://www.pygmt.org/dev/gallery/images/track_sampling.html#sphx-glr-gallery-images-track-sampling-py)?

Yes, it would be good to add ex026 as a new example for making cross-section plots along a transect. I would prefer to keep the existing track_sampling.py example intact if possible (because it's been surprisingly useful for catching bugs in the past, see e.g. #531), but no strong opinions on simply modifying it.

**Comment by yvonnefroehlich** [comment]
> > Do we simply want to re-write the example at https://docs.gmt-china.org/latest/examples/ex026/ to PyGMT, or are there some ideas on how to change the existing gallery example [track_sampling.py](https://www.pygmt.org/dev/gallery/images/track_sampling.html#sphx-glr-gallery-images-track-sampling-py)?
> 
> Yes, it would be good to add ex026 as a new example for making cross-section plots along a transect.

I started working on this in PR #2515.

> I would prefer to keep the existing track_sampling.py example intact if possible (because it's been surprisingly useful for catching bugs in the past, see e.g. #531), but no strong opinions on simply modifying it.

From my side we can keep the `track_sampling.py` example. Just got the impression, that we want either the `track_sampling.py` example or the one from https://docs.gmt-china.org/latest/examples/ex026/.
