### ISSUE TITLE
Let the build_arg_string function handle GMT configurations

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2299]
_Originally posted by @seisman in https://github.com/GenericMappingTools/pygmt/pull/2208#discussion_r1060271964_

When working on the `Figure.timestamp` function, I feel sometimes we may need to pass GMT's configurations directly to the GMT C API, i.e., passing a string like `--FONT_LABEL=xxxx` to the `call_module` function. 

I propose to add a new parameter (e.g., `confdict`) to the `build_arg_string` function, which takes a dict and convert key-value pairs to the form of `--key=value`, e.g., 

```
build_arg_string(kwdict, confdict={"FONT_LOGO": font, "FORMAT_TIME_STAMP": timefmt}

**Comment by seisman** [comment]
Ping @GenericMappingTools/pygmt-maintainers for comments on this enhancement before I start to work on it.

**Comment by michaelgrund** [comment]
> Ping @GenericMappingTools/pygmt-maintainers for comments on this enhancement before I start to work on it.

Sounds good from my side!

**Comment by weiji14** [comment]
Just to be clear, do you intend the `--FONT_LABEL` options to be internal only, or should users be allowed to do something like `fig.timestamp(..., FONT_LABEL="xxxx")`? By the way, this seems similar to what was discussed in #455.

**Comment by seisman** [comment]
> do you intend the `--FONT_LABEL` options to be internal only, or should users be allowed to do something like `fig.timestamp(..., FONT_LABEL="xxxx")`?

It's only for internal use.

**Comment by weiji14** [comment]
> > do you intend the `--FONT_LABEL` options to be internal only, or should users be allowed to do something like `fig.timestamp(..., FONT_LABEL="xxxx")`?
> 
> It's only for internal use.

Ok, that sounds good.
