### ISSUE TITLE
Remove the deprecated load_xx functions in v0.9.0 (deprecated since v0.6.0)

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2302]
In PR https://github.com/GenericMappingTools/pygmt/pull/1685, we added a single `load_sample_data` function to load sample data used in tutorials and examples, and deprecated `load_xx` functions like `load_japan_quakes` in v0.6.0. These deprecated functions will be removed in v0.9.0.

Since our next targeted release is v0.9.0, now it's time to remove these deprecated functions. IMHO, we should remove these deprecated functions **as early as possible**, rather than removing them a few days before we make the v0.9.0 release. In this way, we can have more time (3 months vs a few days) to know whether removing these functions would cause any unexpected problems.

This issue is created to track the progress of removing these functions.

- [x] Remove `load_japan_quakes`: https://github.com/GenericMappingTools/pygmt/pull/2301
- [x] Remove `load_sample_bathymetry` https://github.com/GenericMappingTools/pygmt/pull/2305
- [x] Remove `load_fractures_compilation` https://github.com/GenericMappingTools/pygmt/pull/2303
- [x] Remove `load_hotspots` https://github.com/GenericMappingTools/pygmt/pull/2309
- [x] Remove `load_mars_shape` #2304 
- [x] Remove `load_ocean_ridge_points` https://github.com/GenericMappingTools/pygmt/pull/2308
- [x] Remove `load_usgs_quakes` #2306 

I've made the PR https://github.com/GenericMappingTools/pygmt/pull/2301 to remove the deprecated `load_japan_quakes` function. This PR could be used as a reference if anyone wants to work on other deprecated functions.

**Comment by willschlitzer** [comment]
@michaelgrund Since we're working at the same time, I'm holding off on `load_hotspots` and assuming you're working on it. Let me know if you want me to add a PR to remove it!

**Comment by yvonnefroehlich** [comment]
In this context, I feel it would be helpful to also work on issue #1774 and the related PR #1814 by @maxrjones for adding a list or an overview of the available sample datasets 🙂. Currently, users do not know directly from the documentation which sample datasets are available via `datasets.load_sample_data` and have to run `datasets.list_sample_data`.
