### ISSUE TITLE
Adding feature of legend and colorbar

### ISSUE THREAD

**Issue by palgunadi1993** [GenericMappingTools/pygmt#231]
I wasn't able to plot my **legend and colorbar** since it is very important issues, I think it's good to have a feature like that. I really appreciate from what you've done so far, I know it's still ongoing progress. However, it seems to have a promising result in the near future. Good Job

**Comment by jbrussell** [comment]
I would like to bump this feature request. Although I'm able to quickly make beautiful maps using this amazing tool, without the ability to add a color bar or legend they cannot be used for research purposes. Very much looking forward to this crucial update!

**Comment by ardiansyahfauzi** [comment]
I have been trying GMT/Python for one week and I found that this is a cool method to use GMT software in an easy way. However, in my case, legend and color bar are badly in need. I am looking forward to these features. Good job!!

**Comment by liamtoney** [comment]
@weiji14 I think we can close this now.

**Comment by weiji14** [comment]
Oh yes, definitely! Everyone subscribed to this thread, `legend` and `colorbar` is implemented, and we're working on some gallery examples. stay tuned!
