### ISSUE TITLE
Add project keywords to the pyproject.toml file

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2314]
https://github.com/GenericMappingTools/pygmt/blob/a7d96b40c4c585c4748d778737cd3fa64e2e3371/pyproject.toml#L12

The `keywords` metadata in the `pyproject.toml` file is empty. We need to add some keywords for this project.

**Comment by yvonnefroehlich** [comment]
Maybe we can also add the same or similar keywords to the Zenodo record?

**Comment by seisman** [comment]
> Maybe we can also add the same or similar keywords to the Zenodo record?

Sounds good.

**Comment by seisman** [comment]
> Maybe we can also add the same or similar keywords to the Zenodo record?

Maybe only @weiji14 can do this?

**Comment by weiji14** [comment]
Ok, I've added the keywords from #2315 to the PyGMT v0.8.0 Zenodo release at https://zenodo.org/record/7481934. These keywords should be automatically included in the upcoming v0.9.0 release too, so I'll close this issue.

P.S. If I ever get super bored, I'll add the keywords to PyGMT v0.1.0 to v0.7.0 as well :laughing:
