### ISSUE TITLE
Default CPTs for GMT remote datasets

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2325]
Most GMT remote datasets have a default CPT. When plotting a dataset without specifying a CPT, the default CPT will be used. For example, the default CPT for `earth_age` dataset is `@earth_age.cpt`. 

The following command plots the `earth_age_01d_g.nc` grid using the default `@earth_age.cpt` file.
```
gmt grdimage @earth_age_01d_g -png map
```
![map](https://user-images.githubusercontent.com/3974108/212524297-a4a04643-efe6-4b7e-aada-acc11749d1ba.png)

In the following PyGMT script, a grid file name is directly passed to `Figure.grdimage`. This script produces the indentical image:
```python
import pygmt
fig = pygmt.Figure()
fig.grdimage(grid="@earth_age_01d_g")
fig.colorbar(frame=True)
fig.savefig("map.png")
```
![map](https://user-images.githubusercontent.com/3974108/212524386-061e3312-6291-4420-ab7e-a2fed9ce87a9.png)

However, if we load the dataset into a xarray.DataArray and pass it to `Figure.grdimage`, the default CPT changes to "turbo" (GMT's default CPT for any grid data).
```python
import pygmt
from pygmt.datasets import load_earth_age

grid = load_earth_age()
fig = pygmt.Figure()
fig.grdimage(grid=grid)
fig.colorbar()
fig.savefig("map.png")
```
![map](https://user-images.githubusercontent.com/3974108/212524252-5b5bed38-fc7a-4fc3-9000-b42b0a3afd94.png)

It would be good if PyGMT can use the specific CPT when a CPT is not specified, although it's technically difficult. At least we should document the default CPT for each dataset and add an example showing how to use the default dataset CPT.

**Comment by michaelgrund** [comment]
Agree, would be nice to have at least examples to show the most suitable CPT for each dataset.

**Comment by maxrjones** [comment]
This mechanism was discussed a bit in https://github.com/GenericMappingTools/gmt/pull/6178#discussion_r777270574. I think it would take detecting whether the user has set the current CPT and evaluating the grid for a cpt attr, then setting an argument to -C if only the latter is true. It would be worth evaluating the overhead for those checks. At least, documenting GMT's defaults seems useful.

**Comment by weiji14** [comment]
> ```python
> grid = load_earth_age()
> fig = pygmt.Figure()
> fig.grdimage(grid=grid)
> ```

Could we store the default cmap in an xarray accessor (#499) or attribute, and then let `grdimage` default to that cmap if `cmap=None`?

Or, if we don't want to add the extra logic to `grdimage`, we could attempt to add it in the `.gmt.imshow()` function at #2372.

**Comment by seisman** [comment]
> Could we store the default cmap in an xarray accessor (#499) or attribute, and then let `grdimage` default to that cmap if `cmap=None`?

xarray accessor has known limitations (https://github.com/GenericMappingTools/pygmt/pull/2375) and the cpt information will be lost after some operations.

**Comment by yvonnefroehlich** [comment]
> @seisman: [...] add an example showing how to use the default dataset CPT.

Should such a gallery example focus on one remote dataset? E.g. `earth_age`:
_Code example_:
```python
import pygmt

# #############################################################################
# Use "@earth_age_01d_g" to download the remote dataset `earth_age_01d_g`
# directly within the method pygmt.Figure.grdimage.

fig = pygmt.Figure()

fig.grdimage(grid="@earth_age_01d_g", frame=True)
fig.colorbar(frame="+lage / Myr")

fig.show()
# fig.savefig("datasets_cpt_example_at.png")
     

# #############################################################################
# Use `pygmt.datasets.load_earth_age()` to download the remote dataset 
# `earth_age` into a `xarray.DataArray`.

grid_earth_age = pygmt.datasets.load_earth_age()  

fig = pygmt.Figure()

# Left: Use GMT's overall default colormap turbo
fig.grdimage(grid=grid_earth_age, frame=["af", "WSne"])
fig.colorbar(frame="+lage / Myr")

fig.shift_origin(xshift="16c")

# Right: Use GMT's default colormap for the earth_age remote dataset
fig.grdimage(grid=grid_earth_age, cmap="@earth_age.cpt", frame=["af", "wSne"])
fig.colorbar(frame="+lage / Myr")

fig.show()
# fig.savefig("datasets_cpt_example_load.png")
````
_Output figues_:
![datasets_cpt_example_at](https://github.com/GenericMappingTools/pygmt/assets/94163266/15d3fce1-ea0a-4350-a32d-707d3c58b4b7)

![datasets_cpt_example_load](https://github.com/GenericMappingTools/pygmt/assets/94163266/fc2b903b-bd37-48fd-ac7f-e77156db2e6a)

------------------
> @michaelgrund: Agree, would be nice to have at least examples to show the most suitable CPT for each dataset.

Or do we want any kind of overview, which shows / compares the colormaps for all remote datasets?
(Regarding the unexpected display of the remote dataset `earth_mask` see issue #2629, please.)
![datasets_compare_cpts_twocol](https://github.com/GenericMappingTools/pygmt/assets/94163266/739fd5c2-5071-49a4-92fb-685366066a55)

**Comment by seisman** [comment]
> Agree, would be nice to have at least examples to show the most suitable CPT for each dataset.

Here are my thoughts. Instead of creating a huge image with too many datasets as done in https://github.com/GenericMappingTools/pygmt/issues/2325#issuecomment-1679583764, I think we have two options:

1. In the [Remote Datasets](https://www.generic-mapping-tools.org/remote-datasets/) site, each dataset already has an overview image. So we can just directly include these images on the API documentation page of the datasets. For examples, adding the following codes to https://www.pygmt.org/dev/api/generated/pygmt.datasets.load_earth_age.html
```
.. image:: https://www.generic-mapping-tools.org/remote-datasets/_images/GMT_age.png
```

2. Just like the [Projections](https://www.pygmt.org/dev/projections/index.html) gallery, we can create a gallery for all available datasets. 

I prefer to option 1, because it's much simpler, and we don't have to add so many scripts for these datasets, which also slowdown the documentation building. The Remote Datasets site should be the central place to show all the available datasets.

**Comment by yvonnefroehlich** [comment]
> > Agree, would be nice to have at least examples to show the most suitable CPT for each dataset.
> 
> Here are my thoughts. Instead of creating a huge image with too many datasets as done in [#2325 (comment)](https://github.com/GenericMappingTools/pygmt/issues/2325#issuecomment-1679583764), I think we have two options:
> 
> 1. In the [Remote Datasets](https://www.generic-mapping-tools.org/remote-datasets/) site, each dataset already has an overview image. So we can just directly include these images on the API documentation page of the datasets. For examples, adding the following codes to https://www.pygmt.org/dev/api/generated/pygmt.datasets.load_earth_age.html
> 
> ```
> .. image:: https://www.generic-mapping-tools.org/remote-datasets/_images/GMT_age.png
> ```
> 
> 2. Just like the [Projections](https://www.pygmt.org/dev/projections/index.html) gallery, we can create a gallery for all available datasets.
> 
> I prefer to option 1, because it's much simpler, and we don't have to add so many scripts for these datasets, which also slowdown the documentation building. The Remote Datasets site should be the central place to show all the available datasets.

I also prefer option 1.
