### ISSUE TITLE
Fix binder online demo UnsatisfiableError at try.gmtpython.xyz

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#234]
Hi there,

I'm starting an issue to fix the broken binder build at http://try.gmtpython.xyz. Appears to have been reported first at https://gitter.im/GenericMappingTools/gmt-python?at=5b76938b0825690ea2e125eb more than a year ago?!

**Full error message**

```
UnsatisfiableError: The following specifications were found to be in conflict:
    gmt=6.0.0a16
Use "conda info <package>" to see the dependencies for each package.
```

I'll open a pull request on https://github.com/GenericMappingTools/try-gmt-python to fix this (basically update the conda packages) using this [gist](https://gist.github.com/weiji14/f13a7fbde5855bbbeb036c4b1187f675) I made. Just tracking it here for better visibility :smiley:

**Comment by leouieda** [comment]
Thanks @weiji14. We're not gonna support the demo until GMT has officially release version 6.0 (see #264).

**Comment by weiji14** [comment]
Noted. Is there a timeline on when GMT 6.0 will be released?

**Comment by leouieda** [comment]
I think by the end of 2019 at the latest. But ideally sooner.
