### ISSUE TITLE
import error help me please!!!!!

### ISSUE THREAD

**Issue by DohyeonKn** [GenericMappingTools/pygmt#2350]
### Description of the problem

i installed pygmt done, but it occur import error 
my notebook has 
device name:	DESKTOP-P24KFOA
processor	Intel(R) Pentium(R) CPU  N3540  @ 2.16GHz   2.16 GHz
RAM	8.00GB(7.88GB 사용 가능)
device ID	5FE6493D-C196-468B-AAB1-5F2E138F5535
제품 ID	00325-80669-00204-AAOEM
system	64bit 운영 체제, x64 기반 프로세서

### Minimal Complete Verifiable Example

```python
import pygmt
```

### Full error message

```python-traceback
[WinError -1073741795] Windows Error 0xc000001d
```

### System information

```bash
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_24260/1053626842.py in <module>
----> 1 import pygmt
      2 pygmt.show_versions()

~\anaconda3\envs\ga\lib\site-packages\pygmt\__init__.py in <module>
     68 
     69 # Start our global modern mode session
---> 70 _begin()
     71 # Tell Python to run _end when shutting down
     72 _atexit.register(_end)

~\anaconda3\envs\ga\lib\site-packages\pygmt\session_management.py in begin()
     14     """
     15     prefix = "pygmt-session"
---> 16     with Session() as lib:
     17         lib.call_module("begin", prefix)
     18         # pygmt relies on GMT modern mode with GMT_COMPATIBILITY at version 6

~\anaconda3\envs\ga\lib\site-packages\pygmt\clib\session.py in __enter__(self)
    181             raising the exception.
    182         """
--> 183         self.create("pygmt-session")
    184         # Need to store the version info because 'get_default' won't work after
    185         # the session is destroyed.

~\anaconda3\envs\ga\lib\site-packages\pygmt\clib\session.py in create(self, name)
    360         session_type = self["GMT_SESSION_EXTERNAL"]
    361 
--> 362         session = c_create_session(name.encode(), padding, session_type, print_func)
    363 
    364         if session is None:

OSError: [WinError -1073741795] Windows Error 0xc000001d
```

**Comment by weiji14** [comment]
Hi there, could you describe how you installed PyGMT? Was it through pip, conda, or other? Our installation guide is at https://www.pygmt.org/v0.8.0/install.html for reference.

**Comment by DohyeonKn** [comment]
I installed by conda also followed your guide line

**Comment by yvonnefroehlich** [comment]
Hey @DohyeonKn, 
it seems like you are using Jupyter Notebook or Jupyter Lab. Can you please try running 
```python
python -c "import pygmt; pygmt.show_versions()"
```
directly in your console (not within Jupyter Notebook or Lab) and post the complete output.

**Comment by DohyeonKn** [comment]
![pygmt error](https://user-images.githubusercontent.com/124335854/216542860-c452c838-36ae-4ea8-80a4-8ae3b9946709.PNG)
Like this?

**Comment by DohyeonKn** [comment]
pygmt.show_versions() isn't work 
i think it doesn't previous work Import pygmt

**Comment by seisman** [comment]
https://wikifixes.com/errors/0x/0xc000001d/

Is it likely something wrong with your operating system?

**Comment by seisman** [comment]
@DohyeonKn Any progress on this?

**Comment by DohyeonKn** [comment]
@seisman  it's still like that.... can you solve this problem?

**Comment by seisman** [comment]
Can you please try opening CMD and run the command `gmt --version` and see if it works?

**Comment by DohyeonKn** [comment]
![캡처](https://user-images.githubusercontent.com/124335854/218011368-68ecda85-8b08-4def-88f5-71b729873c0f.PNG)
is it right?

**Comment by seisman** [comment]
No, it doesn't look correct. Any output if you run `gmt --version -Vd`?

**Comment by DohyeonKn** [comment]
![캡처](https://user-images.githubusercontent.com/124335854/218017352-38bcc5fd-c194-4bcf-aea7-2251274186c4.PNG)
@seisman

**Comment by seisman** [comment]
For unknown reasons, it seems your GMT installation is broken. You can try to reinstall GMT (or reinstall everything including PyGMT and even conda) to see if it helps.

**Comment by seisman** [comment]
I'm closing the issue because it's very likely this is not a PyGMT issue.
