### ISSUE TITLE
Add a package-level variable __gmt_version__ for development use

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2362]
### Description of the desired feature

As we're supporting multiple GMT versions, sometimes we need to check the current GMT version and see if it has a specific bug or provides a new feature.

To check the GMT version, we need to write codes like:
```
from packaging.version import Version
from pygmt import clib

with clib.Session() as _lib:                                                    
	gmt_version = Version(_lib.info["version"])

if gmt_version >= Version("6.4.0"):
    ...
```

The same code is being used in many places, so it's better to write a function for it. The function will be like this:
```python
from packaging.version import Version
from pygmt import clib

def get_gmt_version():
	with clib.Session() as _lib:                                                    
	    return Version(_lib.info["version"])
```

### Are you willing to help implement and maintain this feature?

Yes, but the details need more discussions.

**Comment by seisman** [comment]
After thinking more about it, I think it makes more sense to return the GMT version string, rather than a `Version` object.
```
from pygmt import clib

def get_gmt_version():
	with clib.Session() as _lib:                                                    
	    return _lib.info["version"]
```
Then in other scripts, we can use:
```
from pygmt.somewhere import get_gmt_version
from packaging.version import Version

gmt_version = get_gmt_version()
if Version(gmt_version) >= Version("6.5.0"):
    ...
```

**Comment by maxrjones** [comment]
A utility function that reduces code redundancy sounds good to me, but I think it should be a private function (e.g., `_get_gmt_version()`) and users should still use `pygmt.show_versions()` to report the information rather than introducing another way to accomplish the same purpose.

**Comment by seisman** [comment]
A package-level variable `__gmt_version__` will be added in https://github.com/GenericMappingTools/pygmt/pull/2366.
