### ISSUE TITLE
Add a quick example in the quickstart section of the README file?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2364]
Currently, the [Quickstart](https://github.com/GenericMappingTools/pygmt#quickstart) section in the README file only have one subsection with quick installation instructions. I think a real quickstart section should also have a simple working example so that users have a quick idea about how PyGMT works. So I propose to add a simple example in the quickstart section, like:

```
import pygmt
fig = pygmt.Figure()
fig.coast(projection="H10c", region="g", frame=True, land="gray")
fig.show()
```

**Comment by yvonnefroehlich** [comment]
I think such a subsection makes sense and is an improvement.
Maybe we can call it "Getting started"? Maybe we should also mention the gallery and tutorials regarding more examples, even both are already mentioned at the top of the README? Something like this using the code example by @seisman:

## Getting started

```python
import pygmt
fig = pygmt.Figure()
fig.coast(projection="H10c", region="g", frame=True, land="gray")
fig.show()
```

For more examples, please have a look at the [PyGMT Gallery](https://www.pygmt.org/latest/gallery/index.html) and [Tutorials](https://www.pygmt.org/latest/tutorials/index.html).
