### ISSUE TITLE
Recommend mambaforge + mamba in the installation instructions and contributing guides

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2368]
In the [installation instructions](https://www.pygmt.org/dev/install.html#which-python), we recommend using Anaconda:

> We recommend using the [Anaconda](https://www.anaconda.com/distribution) Python distribution to ensure you have all dependencies installed and the [conda](https://docs.conda.io/projects/conda/en/latest/) package manager is available. Installing Anaconda does not require administrative rights to your computer and doesn’t interfere with any other Python installations on your system.

Here is a comparison between Anaconda and miniconda:  https://stackoverflow.com/a/45421527.

From my own experience, Anaconda packages too many packages by default, which causes slow installation, large disk spaces and potential package conflicts.

I wonder if we should recommend miniconda instead.

**Comment by maxrjones** [comment]
Yes, I think we should recommend miniconda or micromamba. 

IMO we should also recommend mamba for contributors in https://www.pygmt.org/latest/contributing.html#setting-up-your-environment, since the conda solver can get tedious with the number of development dependencies that we have.

**Comment by seisman** [comment]
> IMO we should also recommend mamba for contributors in [pygmt.org/latest/contributing.html#setting-up-your-environment](https://www.pygmt.org/latest/contributing.html#setting-up-your-environment), since the conda solver can get tedious with the number of development dependencies that we have.

I agree.

> Yes, I think we should recommend miniconda or micromamba.

micromamba is not a good option, because (https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html):

> Still at early stage, it’s main usage is in continous integration pipelines: since it’s a single executable, it reduces dramatically bandwidth usage and provide fast operations.

**Comment by weiji14** [comment]
Related thread at https://discourse.pangeo.io/t/mamba-mature-enough/3154/4 on how `mamba` is pretty stable already. Agree that `micromamba` isn't a good option (mostly because you'd have to call commands using `micromamba install` instead of `mamba install`), but I'd prefer mambaforge instead of miniconda as recommended by https://mamba.readthedocs.io/en/stable/installation.html#fresh-install.

**Comment by seisman** [comment]
> Related thread at [discourse.pangeo.io/t/mamba-mature-enough/3154/4](https://discourse.pangeo.io/t/mamba-mature-enough/3154/4) on how `mamba` is pretty stable already. Agree that `micromamba` isn't a good option (mostly because you'd have to call commands using `micromamba install` instead of `mamba install`), but I'd prefer mambaforge instead of miniconda as recommended by [mamba.readthedocs.io/en/stable/installation.html#fresh-install](https://mamba.readthedocs.io/en/stable/installation.html#fresh-install).

Sounds great. mambaforge + mamba is the way to go.

**Comment by weiji14** [comment]
Kinda unrelated, but I just found out about https://prefix.dev/blog/online_environment_solving today and was playing with solving a PyGMT development environment (conda-lock.yml file) at https://prefix.dev/envs/weiji14/pygmt. This is today's resolved environment at https://prefix.dev/envs/weiji14/pygmt/285fy5jawbs0, installable using `micromamba create -f https://prefix.dev/envs/weiji14/pygmt/285fy5jawbs0/conda-lock.yml -n pygmt`:

![image](https://user-images.githubusercontent.com/23487320/222333049-2e262228-d9bf-4faa-9f7b-1b0e68380c77.png)

It's still a very young project built by the `mamba` folks, but it might be useful for your own projects if you ever need to quickly test out solving an environment without messing with your local environment, or do cross-platform solves. They also do versioning of generated `conda-lock.yml`, which might be useful for reproducibility.

P.S. Couldn't get `linux-aarch64` nor `linux-ppc64le` to solve for some reason, but that's for another issue.
