### ISSUE TITLE
Release PyGMT v0.9.0

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/pygmt#2424]
**Release**: [v0.9.0](https://github.com/GenericMappingTools/pygmt/milestones/0.9.0)
**Scheduled Date**: 2023/03/31
**Pull request due date**: 2023/03/27

**Priority PRs/issues to complete prior to release**
- [x] https://github.com/GenericMappingTools/pygmt/pull/2394
- [ ] ~~https://github.com/GenericMappingTools/pygmt/pull/2421~~
- [x] https://github.com/GenericMappingTools/pygmt/pull/2420
- [x] https://github.com/GenericMappingTools/pygmt/pull/2417
- [x] https://github.com/GenericMappingTools/pygmt/pull/2381
- [x] https://github.com/GenericMappingTools/pygmt/pull/2373
- [x] https://github.com/GenericMappingTools/pygmt/pull/2354
- [ ] ~https://github.com/GenericMappingTools/pygmt/pull/2130~
- [ ] ~https://github.com/GenericMappingTools/pygmt/pull/1779~

**Before release**:
- [x] Check to ensure that:
  - [x] All tests pass in the ["GMT Legacy Tests" workflow](https://github.com/GenericMappingTools/pygmt/actions/workflows/ci_tests_legacy.yaml)
  - [x] All tests pass in the ["GMT Dev Tests" workflow](https://github.com/GenericMappingTools/pygmt/actions/workflows/ci_tests_dev.yaml)
  - [x] Deprecations and related tests are removed for this version by running `grep --include="*.py" -r 'remove_version="vX.Y.Z"' pygmt` from the base of the repository (@seisman)
- [x] Reserve a DOI on [Zenodo](https://zenodo.org) by clicking on "New Version" @weiji14 `10.5281/zenodo.7772533`
- [x] Finish up 'Changelog entry for v0.x.x' Pull Request: #2469
  - [x] Add a new entry in `doc/_static/version_switch.js` for documentation switcher
  - [x] Update `CITATION.cff` and BibTeX at https://github.com/GenericMappingTools/pygmt#citing-pygmt
    - [x] Update authorship list
    - [x] Update DOI (and url for BibTeX)
    - [x] Update version
    - [x] Update date released
  - [x] Add the documentation link https://github.com/GenericMappingTools/pygmt#compatibility-with-gmtpythonnumpy-versions
  - [x] Add compatibility information https://github.com/GenericMappingTools/pygmt#compatibility-with-gmtpythonnumpy-versions
  - [x] Copy draft changelog from Release Drafter and edit it to look nice ([see maintainers guide for details](https://www.pygmt.org/dev/maintenance.html#updating-the-changelog))

**Release**:
- [x] At the [PyGMT release page on GitHub](https://github.com/GenericMappingTools/pygmt/releases):
  - [x] Edit the draft release notes with the finalized changelog
  - [x] Set the tag version and release title to vX.Y.Z
  - [x] Make a release by clicking the 'Publish Release' button, this will automatically create a tag too
- [x] Manually upload the pygmt-vX.Y.Z.zip and baseline-images.zip files to https://zenodo.org/deposit, ensure that it is filed under the correct reserved DOI

**After release**:
- [x] Update conda-forge [pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) [Done automatically by conda-forge's bot, but remember to pin NEP29 versions] https://github.com/conda-forge/pygmt-feedstock/pull/26
- [x] Bump PyGMT version on https://github.com/GenericMappingTools/try-gmt (after conda-forge update) https://github.com/GenericMappingTools/try-gmt/pull/46
- [x] Announce the release on:
  - [x] GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (do this announcement first! draft on https://hackmd.io/@pygmt. requires moderator status)
  - [ ] ~~[ResearchGate](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools) (after forum announcement)~~
  - [x] [Twitter](https://twitter.com/gmt_dev) (after forum announcement)
---

- [ ] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by seisman** [comment]
@weiji14 Could you please reserve a Zenodo DOI for this release?

**Comment by weiji14** [comment]
> @weiji14 Could you please reserve a Zenodo DOI for this release?

Yep, DOI for v0.9.0 will be `10.5281/zenodo.7772533`.

**Comment by seisman** [comment]
I think PRs https://github.com/GenericMappingTools/pygmt/pull/2130 and https://github.com/GenericMappingTools/pygmt/pull/1779 need more time for review, so I have removed them from this release.

**Comment by yvonnefroehlich** [comment]
> > I think PRs #2130 and #1779 need more time for review, so I have removed them from this release.
> 
> Sounds good - it seems like all the other PRs on the list have already been merged. If anyone has last minute additions, please add them today. Otherwise I'll go through the next steps on the list tomorrow.

From my side, it is only PR #2461. But this is only a small change / addition to the documentation. Finishing the tutorial for the Cartesian histograms in #2445 appears a bit too optimistic for me 🙁.

**Comment by weiji14** [comment]
Thanks Max for tagging the release! The Zenodo upload is now available at https://doi.org/10.5281/zenodo.7772533, and conda-forge PR is merged. I'll need to rush to the airport, but can help out with the forum post next week :smile:

**Comment by yvonnefroehlich** [comment]
Thanks @maxrjones for handling this release :tada:! And of course all for their contributions, efforts, and help over the last three months :rocket:!

**Comment by weiji14** [comment]
Starting to draft the PyGMT v0.9.0 release annoucement at https://hackmd.io/@pygmt/v0-9-0_announcement

**Comment by maxrjones** [comment]
> Starting to draft the PyGMT v0.9.0 release annoucement at https://hackmd.io/@pygmt/v0-9-0_announcement

Thanks @weiji14! Looks great! I just made a few small edits

**Comment by yvonnefroehlich** [comment]
> > Starting to draft the PyGMT v0.9.0 release annoucement at https://hackmd.io/@pygmt/v0-9-0_announcement
> 
> Thanks @weiji14! Looks great! I just made a few small edits

Thanks @weiji14 for starting a draft and @maxrjones for proofreading it! Hope also @weiji14 is happy with me changes on Monday 🙂. For me, the draft looks quite finished. @GenericMappingTools/pygmt-maintainers it would be nice if somebody else can have a look at it, please. Btw @seisman do you have still problems to access / use Hackmd?

**Comment by michaelgrund** [comment]
Thanks for the draft @weiji14. Looks good!

**Comment by seisman** [comment]
Quite busy in the last few days. I just had a look at the announcement. It looks good to me.

**Comment by maxrjones** [comment]
Great, thanks everyone! @weiji14 would you prefer to publish the announcement or for me to?

**Comment by weiji14** [comment]
Thanks everyone for editing the draft, great teamwork!

> Great, thanks everyone! @weiji14 would you prefer to publish the announcement or for me to?

Best if you can publish it on the forum. I feel like the last few sections like 'Roadmap' and 'Conferences' could use a few more points perhaps? Is there anything from https://github.com/GenericMappingTools/pygmt/milestone/16 that people would like to see in PyGMT v0.10.0?

**Comment by yvonnefroehlich** [comment]
> I feel like the last few sections like 'Roadmap' and 'Conferences' could use a few more points perhaps? Is there anything from https://github.com/GenericMappingTools/pygmt/milestone/16 that people would like to see in PyGMT v0.10.0?

I added a few more aspects under the "Roadmap" section.

> Also, should we mention dropping Python 3.8 (#2300) in the 'Deprecation' section?

In my opinion yes. 
What's about the GMT version? Do we still support GMT 6.3.0 and 6.4.0 in PyGMT v0.10.0?

**Comment by seisman** [comment]
> What's about the GMT version? Do we still support GMT 6.3.0 and 6.4.0 in PyGMT v0.10.0?

I think yes, we should support old GMT versions like 6.3.0.

**Comment by weiji14** [comment]
Cool, thanks @yvonnefroehlich for the edits! Should be ready to post the announcement on the forum @maxrjones!

**Comment by maxrjones** [comment]
[Forum](https://forum.generic-mapping-tools.org/t/pygmt-v0-9-0-released/3830) and [twitter](https://twitter.com/gmt_dev/status/1644456730837807104) announcements are out! Thanks again for all your contributions, everyone!
