### ISSUE TITLE
Add PyGMT to the "Who uses Sphinx-Gallery" list in the sphinx-gallery repository

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2446]
Just found that sphinx-gallery has a project list that uses Sphinx-Gallery (https://github.com/sphinx-gallery/sphinx-gallery#who-uses-sphinx-gallery and https://sphinx-gallery.github.io/stable/projects_list.html).

The PyGMT documentation heavily rely on sphinx-gallery, and I think we should also add PyGMT to the list.

**Comment by yvonnefroehlich** [comment]
I think adding PyGMT to this Sphinx-Gallery list makes sense and is fair.

**Comment by yvonnefroehlich** [comment]
I can submitte a PR. I suggest to use the link to the PyGMT gallery https://www.pygmt.org/latest/gallery/index.html (there is no link to "User Guide"). Is this fine?

**Comment by seisman** [comment]
> I suggest to use the link to the PyGMT gallery https://www.pygmt.org/latest/gallery/index.html

Sounds good.

**Comment by yvonnefroehlich** [comment]
Submitted PR https://github.com/sphinx-gallery/sphinx-gallery/pull/1114.

**Comment by seisman** [comment]
The PR has been merged. Thanks @yvonnefroehlich
