### ISSUE TITLE
negative numbers in frame

### ISSUE THREAD

**Issue by ivanrojasch** [GenericMappingTools/pygmt#2467]
### Description of the desired feature

Hello all
I'm trying to make a grdimage, and currently my code looks something like this:

```python
grid = pygmt.datasets.load_earth_relief(resolution="15s", region=[-77.0,-71.0,-18.0,-13.0])
fig = pygmt.Figure()
pygmt.makecpt(cmap="globe", series=(-7800,7800,10),continuous=True)
fig.grdimage(grid=grid, projection="M5.5i", frame=["WSNE","a1.0f0.5"],shading=True)
fig.show()
```

What I need the code to do is to show annotations in all 4 sides of the frame, in the form of negative numbers, instead of "74°W" or "13°S".

The research I have done about this topic has been fruitless so far, so I hope somebody can help me achieve this. Thanks in advance

### Are you willing to help implement and maintain this feature?

No

**Comment by weiji14** [comment]
Hi @ivanrojasch, thanks for trying out PyGMT! Following https://forum.generic-mapping-tools.org/t/removing-cardinal-directions-from-axis-ticks/1974, you can set negative decimal degrees using the [`FORMAT_GEO_MAP`](https://docs.generic-mapping-tools.org/6.4/gmt.conf.html#term-FORMAT_GEO_MAP) setting like so

```python
fig = pygmt.Figure()
pygmt.makecpt(cmap="globe", series=(-7800, 7800, 10), continuous=True)
with pygmt.config(
    MAP_FRAME_TYPE="plain", FORMAT_GEO_MAP="ddd:mm:ss", FORMAT_FLOAT_OUT="%.2e"
):
    fig.grdimage(grid=grid, projection="M5.5i", frame=["WSNE", "a1f0.5"], shading=True)
fig.show()
```
produces

![map](https://user-images.githubusercontent.com/23487320/228673039-2f3c433b-b552-4b08-9857-96518240acb6.png)

Feel free to close this issue if it works for you. Also next time, it'll be better to post questions on our forum at https://forum.generic-mapping-tools.org/c/questions/pygmt-q-a/11 (can use your GitHub login to sign up).

**Comment by ivanrojasch** [comment]
> Hi @ivanrojasch, thanks for trying out PyGMT! Following https://forum.generic-mapping-tools.org/t/removing-cardinal-directions-from-axis-ticks/1974, you can set negative decimal degrees using the [`FORMAT_GEO_MAP`](https://docs.generic-mapping-tools.org/6.4/gmt.conf.html#term-FORMAT_GEO_MAP) setting like so
> 
> ```python
> fig = pygmt.Figure()
> pygmt.makecpt(cmap="globe", series=(-7800, 7800, 10), continuous=True)
> with pygmt.config(FORMAT_GEO_MAP="ddd:mm:ss"):
>     fig.grdimage(grid=grid, projection="M5.5i", frame=["WSNE", "a1f0.5"], shading=True)
> fig.show()
> ```
> 
> produces
> 
> ![map](https://user-images.githubusercontent.com/23487320/228673723-2910d7e6-1031-496b-aa47-0579ae501184.png)
> 
> Feel free to close this issue if it works for you. Also next time, it'll be better to post questions on our forum at https://forum.generic-mapping-tools.org/c/questions/pygmt-q-a/11 (can use your GitHub login to sign up).

thank you very much!
