### ISSUE TITLE
GMTCLibNotFoundError after pip install

### ISSUE THREAD

**Issue by veenstrajelmer** [GenericMappingTools/pygmt#2510]
### Description of the problem

After a `pip install pygmt`, running the test code snippet results in `GMTCLibNotFoundError`. I have read the https://www.pygmt.org/latest/install.html#finding-the-gmt-shared-library, but this libraries are nowhere to be found in the environment folder. I expect this would work when installing with `conda`, but I was actually looking for a pip-installable alternative for `cartopy`.

### Minimal Complete Verifiable Example

```python
import pygmt
pygmt.show_versions()

fig = pygmt.Figure()
fig.coast(region="g", frame=True, shorelines=1)
fig.show()
```

### Full error message

```python-traceback
GMTCLibNotFoundError: Error loading GMT shared library at 'gmt.dll'.
Could not find module 'gmt.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Error loading GMT shared library at 'gmt_w64.dll'.
Could not find module 'gmt_w64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Error loading GMT shared library at 'gmt_w32.dll'.
Could not find module 'gmt_w32.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

### System information

```bash
The error above is raised also. Hope this helps:
Windows 10
Python 3.8
pygmt 0.9.0
```

**Comment by seisman** [comment]
PyGMT relies on GMT, which is not a Python package and can't be installed via `pip`. Thus, if you use `pip install pygmt`, you still need to install GMT yourself, either by conda/mamba or use the official standalone installer (https://github.com/GenericMappingTools/gmt/releases/tag/6.4.0), which should also work.

**Comment by veenstrajelmer** [comment]
I was under the impression that also non-python dependencies can be made pip installable. I know of packages with c++ dependencies that are correctly handled via wheels. But I am not experienced with it, so I cannot judge. At least for me it is not a convenient alternative to cartopy at the moment.

**Comment by weiji14** [comment]
> I was under the impression that also non-python dependencies can be made pip installable. I know of packages with c++ dependencies that are correctly handled via wheels. But I am not experienced with it, so I cannot judge. At least for me it is not a convenient alternative to cartopy at the moment.

Yes it is possible to have C dependencies like GMT in the PyPI wheels for PyGMT, but it is rather complicated to do so, see the discussion at #1853.
