### ISSUE TITLE
Separate high-level and low-level API in docs

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#254]
**Description of the desired feature**

Currently, all public APIs are listed on the same page (https://www.gmtpython.xyz/latest/api/index.html). 

The "Exceptions" and "GMT C API" won't be used by most users. We probably should put these low-level APIs on a separate page.

**Are you willing to help implement and maintain this feature?** No

**Comment by leouieda** [comment]
I'm not sure we need a separate page for these. I put them at the bottom for this reason. But we'll see as the size of the API grows it might be better to do that. Keeping this open for reference.

**Comment by weiji14** [comment]
The API page at https://www.pygmt.org/v0.3.0/api/index.html isn't very long yet (as of early 2021), so probably fine to close this issue for now. Feel free to reopen in the future.
