### ISSUE TITLE
Adding colorbar -Q 

### ISSUE THREAD

**Issue by JingHuiTong** [GenericMappingTools/pygmt#2607]
### Description of the desired feature

adding alias Q=''logscale" in colorbar.py

### Are you willing to help implement and maintain this feature?

Yes

**Comment by seisman** [comment]
Sounds like a reasonable request. 

We may want to follow GMT.jl and use `log` for this option (https://www.generic-mapping-tools.org/GMT.jl/dev/#GMT.colorbar).

**Comment by JingHuiTong** [comment]
@seisman  No problem! It's a great suggestion.
