### ISSUE TITLE
Add released PyGMT versions in RG via code category

### ISSUE THREAD

**Issue by michaelgrund** [GenericMappingTools/pygmt#2621]
I was thinking about how newly released PyGMT versions can get more attention across the community. What do @GenericMappingTools/pygmt-maintainers think about adding each PyGMT version as an individual reasearch contribution via the **code** category in Researchgate?

*Add your research* -> *Data* -> *code*

![grafik](https://github.com/GenericMappingTools/pygmt/assets/23025878/648d4a73-d686-46b2-985d-443e495d13a7)

Each contribution requires at least a single file to be added (e.g. this could be the corresponding ``CITATION.cff``). Additionally, the zenodo DOI can simply be added for each entry.

**Comment by yvonnefroehlich** [comment]
I agree that announcing new releases of PyGMT via ResearchGate will increase the attention across the community.

Beside the `CITATION.cff`, maybe also the `changes.md` could be added. As this `code` category works probably analogous to the other categories, it should be possible to add figures, or? E.g., some figures showing the new examples and tutorials, similar as this was done within the updates of the `PyGMT Project` and is done on the GMT forum. 

Do we also want to add the old releases of PyGMT for the seek of completeness?

I am wondering whether there is any possibility to have the items related to PyGMT somehow bundled, like this was possible via the `Projects` feature.

**Comment by weiji14** [comment]
Or we could just add the entire zipfile stored on Zenodo perhaps? It seems to be treated almost like a publication unit, and we'll need to add all the authors manually, but yes, we could do it 

![image](https://github.com/GenericMappingTools/pygmt/assets/23487320/cdbc9b76-4c21-4fbf-ac76-5cec6eee633d)

> Do we also want to add the old releases of PyGMT for the seek of completeness?

We could, but it's a lot of work to upload every release file, and add all the co-authors it seems :slightly_smiling_face:

> I am wondering whether there is any possibility to have the items related to PyGMT somehow bundled, like this was possible via the `Projects` feature.

Doesn't seem so, it looks more like every release would be treated almost like a 'publication' with no linkage between them.

**Comment by michaelgrund** [comment]
Thanks for your replies @weiji14  and @yvonnefroehlich. 

> Or we could just add the entire zipfile stored on Zenodo perhaps? It seems to be treated almost like a publication unit, and we'll need to add all the authors manually, but yes, we could do it

Sounds good! Before eventually adding all versions I would suggest to test it with the latest one v0.9.0. However, I would prefer to hear the opinions of the other @GenericMappingTools/pygmt-maintainers.

**Comment by yvonnefroehlich** [comment]
> Before eventually adding all versions I would suggest to test it with the latest one v0.9.0.

Yes, of course, before deciding to add more / or all PyGMT releases, we should test this with one version 🙂.

**Comment by michaelgrund** [comment]
What do others think, should we also add the other versions?

**Comment by weiji14** [comment]
> I added a test case for v0.9.0. However, since I'm not following all contributors available on RG (and vice versa), the corresponding profiles are not linked at the moment.

Yes, I do worry about this a bit, because anyone wanting to add the ResearchGate entry properly (with all the names) will need to follow everyone else, and this doesn't scale linearly :slightly_smiling_face:

> Seems like some papers citing v0.9.0 are already linked.

Haha yeah, 7 citations already at https://www.researchgate.net/publication/372980578_PyGMT_A_Python_interface_for_the_Generic_Mapping_Tools_v090 :laughing: Looks like the key is to add the DOI in, so we'll need to do it after the Zenodo release.

> What do others think, should we also add the other versions?

Not sure about old versions (because it's a lot of work), but we can add it to the release checklist at https://github.com/GenericMappingTools/pygmt/blob/855f6fa1b533c106d1e0fe5b68a92e1e7ef5df27/.github/ISSUE_TEMPLATE/release_checklist.md?plain=1#L43-L48 See previous wording when we deleted the line at #2477
