### ISSUE TITLE
Problem with dataframe parser with pygmt.project

### ISSUE THREAD

**Issue by shicks-seismo** [GenericMappingTools/pygmt#2626]
### Description of the problem

Hello, I'm running a loop in which `project` commands are being run to generate image snapshots which will then be turned into an animation. I'm having an inconsistent issue with the project command failing due to an error raised by the parser. I am running the latest version of pygmt on my Mac OSX.
I had a little look at the source code, and I think it is a problem with writing or reading the temporary csv file that is made by project.

### Minimal Complete Verifiable Example

```python
df_proj = pygmt.project(
              data=np.array([cat_df["lon"], cat_df["lat"], cat_df["depth"], cat_df["mag"], 
              cat_df["alphas"], cat_df.index.values]).T,
              center=x_sectionA["center"], endpoint=x_sectionA["endpoint"],
              unit=True, length=x_sectionA["length"], convention="xypqrsz")
```

### Full error message

```---------------------------------------------------------------------------
EmptyDataError                            Traceback (most recent call last)
Cell In[9], line 10
      8     continue
      9 print(starttime)
---> 10 plot_map_xsection_movie(df_evt_filt_early_sst_coh, plot_stations=False, plot_faults=False, out_img_prefix=f"snapshots_ssst_coh/{i}", zlim=15,
     11                         max_date=starttime, combine_subplots=True, show=False, sym_size=4)
     12 #except:
     13 #    starttime = starttime + timedelta(hours=1)
     14 #    continue
     15 starttime = starttime + timedelta(hours=1)

Cell In[8], line 167, in plot_map_xsection_movie(cat_df, out_img_prefix, plot_stations, plot_faults, plot_ellipses, plot_fms, plot_T_axis, plot_P_axis, scale_mag, sym_size, zlim, plot_z_err_xsection, color_time, max_date, show, combine_subplots)
    164     ax3 = fig.add_subplot(gs[1, 0])
    165     ax4 = fig.add_subplot(gs[1, 1])
--> 167 df_proj = pygmt.project(
    168     data=np.array([cat_df["lon"], cat_df["lat"], cat_df["depth"], cat_df["mag"], cat_df["alphas"], cat_df.index.values]).T,
    169     center=x_sectionA["center"], endpoint=x_sectionA["endpoint"],
    170     unit=True, length=x_sectionA["length"], convention="xypqrsz")
    172 df_proj.drop([3, 4, 5], axis=1, inplace=True)
    173 df_proj.columns = ["lon", "lat", "proj_l", "depth", "mag", "alphas", "index"]

File ~/opt/anaconda3/envs/geoenv3/lib/python3.10/site-packages/pygmt/helpers/decorators.py:598, in use_alias.<locals>.alias_decorator.<locals>.new_module(*args, **kwargs)
    591     msg = (
    592         "Parameters 'Y' and 'yshift' are deprecated since v0.8.0. "
    593         "and will be removed in v0.12.0. "
    594         "Use Figure.shift_origin(yshift=...) instead."
    595     )
    596     warnings.warn(msg, category=SyntaxWarning, stacklevel=2)
--> 598 return module_func(*args, **kwargs)

File ~/opt/anaconda3/envs/geoenv3/lib/python3.10/site-packages/pygmt/helpers/decorators.py:738, in kwargs_to_strings.<locals>.converter.<locals>.new_module(*args, **kwargs)
    736             kwargs[arg] = separators[fmt].join(f"{item}" for item in value)
    737 # Execute the original function and return its output
--> 738 return module_func(*args, **kwargs)

File ~/opt/anaconda3/envs/geoenv3/lib/python3.10/site-packages/pygmt/src/project.py:248, in project(data, x, y, z, outfile, **kwargs)
    246         result = pd.read_csv(tmpfile.name, sep="\t", names=column_names)
    247     else:
--> 248         result = pd.read_csv(tmpfile.name, sep="\t", header=None, comment=">")
    249 # return None if outfile set, output in outfile
    250 elif outfile != tmpfile.name:

File ~/opt/anaconda3/envs/geoenv3/lib/python3.10/site-packages/pandas/util/_decorators.py:211, in deprecate_kwarg.<locals>._deprecate_kwarg.<locals>.wrapper(*args, **kwargs)
    209     else:
    210         kwargs[new_arg_name] = new_arg_value
--> 211 return func(*args, **kwargs)

File ~/opt/anaconda3/envs/geoenv3/lib/python3.10/site-packages/pandas/util/_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File ~/opt/anaconda3/envs/geoenv3/lib/python3.10/site-packages/pandas/io/parsers/readers.py:950, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    935 kwds_defaults = _refine_defaults_read(
    936     dialect,
    937     delimiter,
   (...)
    946     defaults={"delimiter": ","},
    947 )
    948 kwds.update(kwds_defaults)
--> 950 return _read(filepath_or_buffer, kwds)

File ~/opt/anaconda3/envs/geoenv3/lib/python3.10/site-packages/pandas/io/parsers/readers.py:605, in _read(filepath_or_buffer, kwds)
    602 _validate_names(kwds.get("names", None))
    604 # Create the parser.
--> 605 parser = TextFileReader(filepath_or_buffer, **kwds)
    607 if chunksize or iterator:
    608     return parser

File ~/opt/anaconda3/envs/geoenv3/lib/python3.10/site-packages/pandas/io/parsers/readers.py:1442, in TextFileReader.__init__(self, f, engine, **kwds)
   1439     self.options["has_index_names"] = kwds["has_index_names"]
   1441 self.handles: IOHandles | None = None
-> 1442 self._engine = self._make_engine(f, self.engine)

File ~/opt/anaconda3/envs/geoenv3/lib/python3.10/site-packages/pandas/io/parsers/readers.py:1753, in TextFileReader._make_engine(self, f, engine)
   1750     raise ValueError(msg)
   1752 try:
-> 1753     return mapping[engine](f, **self.options)
   1754 except Exception:
   1755     if self.handles is not None:

File ~/opt/anaconda3/envs/geoenv3/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:79, in CParserWrapper.__init__(self, src, **kwds)
     76     kwds.pop(key, None)
     78 kwds["dtype"] = ensure_dtype_objs(kwds.get("dtype", None))
---> 79 self._reader = parsers.TextReader(src, **kwds)
     81 self.unnamed_cols = self._reader.unnamed_cols
     83 # error: Cannot determine type of 'names'

File ~/opt/anaconda3/envs/geoenv3/lib/python3.10/site-packages/pandas/_libs/parsers.pyx:554, in pandas._libs.parsers.TextReader.__cinit__()

EmptyDataError: No columns to parse from file
```

### System information

```bash
PyGMT information:
  version: v0.9.0
System information:
  python: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:10:28) [Clang 15.0.7 ]
  executable: /Users/sph1r17/opt/anaconda3/envs/geoenv4/bin/python
  machine: macOS-13.4.1-x86_64-i386-64bit
Dependency information:
  numpy: 1.25.2
  pandas: 2.0.3
  xarray: 2023.7.0
  netCDF4: None
  packaging: 23.1
  contextily: None
  geopandas: 0.13.2
  ghostscript: 9.50
GMT library information:
  binary version: 6.4.0
  cores: 10
  grid layout: rows
  image layout:
  library path: /Users/sph1r17/opt/anaconda3/envs/geoenv3/lib/libgmt.dylib
  padding: 2
  plugin dir: /Users/sph1r17/opt/anaconda3/envs/geoenv3/lib/gmt/plugins
  share dir: /Users/sph1r17/opt/anaconda3/envs/geoenv3/share/gmt
  version: 6.4.0
```

**Comment by shicks-seismo** [comment]
Update: I tried setting `outfile=` in project to see what was happening. Sometimes this file is completely empty, sometimes it works, even with the same input data and parameters. So for some reason, `project` is occasionally failing. Really weird.

**Comment by shicks-seismo** [comment]
Here is the debug output from `project`:

> project [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
> project [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
> project [INFORMATION]: Processing input table data
> project [DEBUG]: gmtapi_init_import: Passed family = Data Table and geometry = Point
> project [DEBUG]: gmtapi_init_import: Added 1 new sources
> project [DEBUG]: GMT_Init_IO: Returned first Input object ID = 0
> project [DEBUG]: GMT_Begin_IO: Mode value 1 not considered (ignored)
> project [DEBUG]: GMT_Begin_IO: Initialize record-by-record access for Input
> project [DEBUG]: gmtapi_next_io_source: Selected object 0
> project [INFORMATION]: Reading Data Table from Input memory location via matrix
> project [DEBUG]: GMT_Begin_IO: Input resource access is now enabled [record-by-record]
> project [DEBUG]: gmtapi_init_export: Passed family = Data Table and geometry = Point
> project [DEBUG]: Object ID 1 : Registered Data Table File tmp3.dat as an Output resource with geometry Point [n_objects = 2]
> project [DEBUG]: gmtapi_init_export: Added 1 new destination
> project [DEBUG]: GMT_Init_IO: Returned first Output object ID = 1
> project [DEBUG]: GMT_Begin_IO: Mode value 1 not considered (ignored)
> project [DEBUG]: GMT_Begin_IO: Initialize record-by-record access for Output
> project [DEBUG]: gmtapi_next_io_source: Selected object 1
> project [INFORMATION]: Writing Data Table to file tmp3.dat
> project [DEBUG]: GMT_Begin_IO: Output resource access is now enabled [record-by-record]
> project [DEBUG]: GMT_End_IO: Input resource access is now disabled
> project [DEBUG]: GMT_End_IO: Output resource access is now disabled
> project [INFORMATION]: 2054 read, 0 used
> project [DEBUG]: gmtlib_unregister_io: Unregistering object no 1 [n_objects = 1]
> 2022-05-25 00:00:00

As you can see, it says "2054 read, 0 used". When the command works, the number of used values is >0.

**Comment by shicks-seismo** [comment]
Another update: everything seems to be working fine if I instead pass the input data as an ascii input file rather than as a numpy array in the memory.

**Comment by seisman** [comment]
Could you please post the ASCII input file so that we can try to reproduce the issue?

**Comment by shicks-seismo** [comment]
[input.csv](https://github.com/GenericMappingTools/pygmt/files/12313474/input.csv) - CSV for the original dataframe that was being passed in memory and was causing problems.
[input.txt](https://github.com/GenericMappingTools/pygmt/files/12313478/input.txt) - ASCII version of the csv that worked.

**Comment by seisman** [comment]
Please also provide the values of `x_sectionA["center"]`, `x_sectionA["endpoint"]` and `x_sectionA["length"]`.

**Comment by yvonnefroehlich** [comment]
Looking at the file `input.csv` I can not finde a column named `alphas` within the header line:
`,lat,lon,depth,datetime,min_dist,az_gap,stations,rms,hyp_file,mag,ell_min,ell_max,ell_max_az,z_err,days`
However, it seems to required in your code:
`data=np.array([cat_df["lon"], cat_df["lat"], cat_df["depth"], cat_df["mag"], cat_df["alphas"], cat_df.index.values]).T`

**Comment by shicks-seismo** [comment]
Hello, the `alphas` column is just being made after the dataframe was written but you can set `cat_df["alphas"] = 1`.
Here are the section parameters:

>     x_sectionA = {"center": [-28.17, 38.7], "endpoint": [-28.15, 38.78], "length": "-10/10"}
>     x_sectionB = {"center": [-28.18, 38.681], "endpoint": [-28.05, 38.645], "length": "-12/12"}

The problem is very sporadic and doesn't seem to be happening all the time.

**Comment by seisman** [comment]
I tried the following script several times on macOS. It always works for me without a crash.
```python
import pygmt
import pandas as pd
import numpy as np

cat_df = pd.read_csv("input.csv")
cat_df["alphas"] = 1.0

df_proj = pygmt.project(
    data=np.array(
        [
            cat_df["lon"],
            cat_df["lat"],
            cat_df["depth"],
            cat_df["mag"],
            cat_df["alphas"],
            cat_df.index.values,
        ]
    ).T,
    center=[-28.17, 38.7],
    endpoint=[-28.15, 38.78],
    unit=True,
    length="-10/10",
    convention="xypqrsz",
    verbose=True,
)
print(df_proj)
```

**Comment by yvonnefroehlich** [comment]
I tried nearly the same code example as @seisman on Windows with both `sectionA` and `section B` and so far I do not face the issue reported by @shicks-seismo.

**Comment by shicks-seismo** [comment]
Many thanks for trying, both. For me, the problem was very intermittent - sometimes it worked with exactly the same data and parameters; sometimes it didn't work. Must be a sporadic issue to do with writing the array to memory and/or to the temp file?
Anyway, writing the input to an ASCII file, and then reading this file in solved the problem for me.
