### ISSUE TITLE
Remove the `pygmt.test` function from pygmt/__init__.py?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2633]
The `pygmt/__init__.py` file provides a `test` function:

https://github.com/GenericMappingTools/pygmt/blob/e4ee800e8045aa5f94ddaf7ad821421d007ab279/pygmt/__init__.py#L187

With this test function, users can run `pygmt.test()` to run the full tests. 

I think we should remove this function based on the following reasons:

1. The function was first added in commit https://github.com/GenericMappingTools/pygmt/commit/ef1fa9cee54f75b911f2d0c2a715166a034040eb in 2017, and there is almost no changes/maintenance since then (https://github.com/GenericMappingTools/pygmt/blame/main/pygmt/__init__.py#L187).
2. The `pygmt.test()` is useless for regular users, because the baseline images hosted by DVC are not available in regular pip/conda packages.
3. For PyGMT maintainers, the Makefile provides more powerful targets like `test`/`fulltest`/`doctest`/`test_no_images` to test PyGMT, and no one has used `pygmt.test` before.
4. The `pygmt.test()` function is not documented in the current documentation, so removing it won't cause any backward-incompatibility. Related PR: https://github.com/GenericMappingTools/pygmt/issues/1200

Let's have a vote: 👍 for removing it and 👎 for keeping it. Or you can leave your thoughts/comments here.

**Comment by weiji14** [comment]
> The `pygmt.test()` function is not documented in the current documentation, so removing it won't cause any backward-incompatibility.

Actually, we do have it documented at https://www.pygmt.org/v0.9.0/api/generated/pygmt.test.html, but I don't think it would be a breaking change since `pygmt.test` isn't used to process data or produce figures. We could skip the deprecation cycle, and just decide to remove it?

**Comment by seisman** [comment]
> > The `pygmt.test()` function is not documented in the current documentation, so removing it won't cause any backward-incompatibility.
> 
> Actually, we do have it documented at https://www.pygmt.org/v0.9.0/api/generated/pygmt.test.html, but I don't think it would be a breaking change since `pygmt.test` isn't used to process data or produce figures. We could skip the deprecation cycle, and just decide to remove it?

Yes to me.
