### ISSUE TITLE
Release PyGMT v0.10.0

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#2640]
**Release**: [v0.10.0](https://github.com/GenericMappingTools/pygmt/milestones/16)
**Scheduled Date**: 2023/09/01
**Pull request due date**: 2023/08/30

**Priority PRs/issues to complete prior to release**
- [x] #2641
- [x] #2638
- [x] #2636
- [x] #2428
- [x] #2383
- [x] #2466 
- [x] #2642

**Before release**:
- [x] Check [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) to see if we need to bump the minimum Python and NumPy versions
- [ ] Check to ensure that:
  - [ ] All tests pass in the ["GMT Legacy Tests" workflow](https://github.com/GenericMappingTools/pygmt/actions/workflows/ci_tests_legacy.yaml)
  - [ ] All tests pass in the ["GMT Dev Tests" workflow](https://github.com/GenericMappingTools/pygmt/actions/workflows/ci_tests_dev.yaml)
  - [x] Deprecations and related tests are removed for this version by running `grep --include="*.py" -r 'remove_version="vX.Y.Z"' pygmt` from the base of the repository
- [x] Reserve a DOI on [Zenodo](https://zenodo.org) by clicking on "New Version" `10.5281/zenodo.8303186`
- [x] Finish up 'Changelog entry for v0.x.x' Pull Request: https://github.com/GenericMappingTools/pygmt/pull/2651
  - [x] Add a new entry in `doc/_static/version_switch.js` for documentation switcher
  - [x] Update `CITATION.cff` and BibTeX at https://github.com/GenericMappingTools/pygmt#citing-pygmt
    - [x] Update authorship list
    - [x] Update DOI (and url for BibTeX)
    - [x] Update version
    - [x] Update date released
  - [x] Add the documentation link https://github.com/GenericMappingTools/pygmt#compatibility-with-gmtpythonnumpy-versions
  - [x] Add compatibility information https://github.com/GenericMappingTools/pygmt#compatibility-with-gmtpythonnumpy-versions
  - [x] Copy draft changelog from Release Drafter and edit it to look nice ([see maintainers guide for details](https://www.pygmt.org/dev/maintenance.html#updating-the-changelog))

**Release**:
- [x] At the [PyGMT release page on GitHub](https://github.com/GenericMappingTools/pygmt/releases):
  - [x] Edit the draft release notes with the finalized changelog
  - [x] Set the tag version and release title to vX.Y.Z
  - [x] Make a release by clicking the 'Publish Release' button, this will automatically create a tag too
- [x] Manually upload the pygmt-vX.Y.Z.zip and baseline-images.zip files to https://zenodo.org/deposit, ensure that it is filed under the correct reserved DOI

**After release**:
- [x] Update conda-forge [pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) [Done automatically by conda-forge's bot, but remember to pin NEP29 versions] https://github.com/conda-forge/pygmt-feedstock/pull/28
- [x] Bump PyGMT version on https://github.com/GenericMappingTools/try-gmt (after conda-forge update) https://github.com/GenericMappingTools/try-gmt/pull/51
- [ ] Announce the release on:
  - [x] GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (do this announcement first! draft on https://hackmd.io/@pygmt. requires moderator status) https://forum.generic-mapping-tools.org/t/pygmt-v0-10-0-released/4223
  - [x] [ResearchGate](https://www.researchgate.net) (after forum announcement, add new version as research item via the *code* category, be sure to include the corresponding new Zenodo DOI) https://www.researchgate.net/publication/373659077_PyGMT_A_Python_interface_for_the_Generic_Mapping_Tools_v0100
  - [ ] [Twitter](https://twitter.com/gmt_dev) (after forum announcement)
---

- [ ] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by weiji14** [comment]
> * [ ]  All tests pass in the ["GMT Legacy Tests" workflow](https://github.com/GenericMappingTools/pygmt/actions/workflows/ci_tests_legacy.yaml)

Last run on 29 Aug 2023 failed with 19 tests at https://github.com/GenericMappingTools/pygmt/actions/runs/6006384122/job/16290821746. Should have been fixed with #2636, though I haven't tested this manually.

> * [ ]  All tests pass in the ["GMT Dev Tests" workflow](https://github.com/GenericMappingTools/pygmt/actions/workflows/ci_tests_dev.yaml)

Dev Tests are not running now due to an `AttributeError: `np.unicode_` was removed in the NumPy 2.0 release. Use `np.str_` instead.` when importing xarray with numpy 2.0. See logs at https://github.com/GenericMappingTools/pygmt/actions/runs/6043991082/job/16401918043#step:16:40 and upstream bug report at https://github.com/pydata/xarray/issues/8133. Run from last week on 25 Aug 2023 (see https://github.com/GenericMappingTools/pygmt/actions/runs/5970439928/job/16198037215) failed with the 19 remote dataset tests.

Shall we just assume that things are good enough and skip those checkmarks for this PyGMT v0.10.0 release?

**Comment by seisman** [comment]
> > * [ ]   All tests pass in the ["GMT Legacy Tests" workflow](https://github.com/GenericMappingTools/pygmt/actions/workflows/ci_tests_legacy.yaml)
> 
> Last run on 29 Aug 2023 failed with 19 tests at https://github.com/GenericMappingTools/pygmt/actions/runs/6006384122/job/16290821746. Should have been fixed with #2636, though I haven't tested this manually.

Looks good to me.

> > * [ ]   All tests pass in the ["GMT Dev Tests" workflow](https://github.com/GenericMappingTools/pygmt/actions/workflows/ci_tests_dev.yaml)
> 
> Dev Tests are not running now due to an `AttributeError: `np.unicode_`was removed in the NumPy 2.0 release. Use`np.str_` instead.` when importing xarray with numpy 2.0. See logs at https://github.com/GenericMappingTools/pygmt/actions/runs/6043991082/job/16401918043#step:16:40 and upstream bug report at [pydata/xarray#8133](https://github.com/pydata/xarray/issues/8133). Run from last week on 25 Aug 2023 (see https://github.com/GenericMappingTools/pygmt/actions/runs/5970439928/job/16198037215) failed with the 19 remote dataset tests.
> 
> Shall we just assume that things are good enough and skip those checkmarks for this PyGMT v0.10.0 release?

Looks good.

**Comment by weiji14** [comment]
Ok, Zenodo upload is up at https://doi.org/10.5281/zenodo.8303186 :tada: Now to wait for the conda-forge bot and all that. If someone can work on the forum announcement draft (https://hackmd.io/@pygmt/v0-10-0_announcement) in the meantime, that would be great. No rush though, we can post it on Monday.

**Comment by seisman** [comment]
Great work @weiji14. I just made some edits to the announcement draft.

**Comment by seisman** [comment]
PyGMT has been updated to v0.10.0 on conda-forge and try-gmt!

**Comment by yvonnefroehlich** [comment]
@weiji14 the forum announcement draft looks already very good 🙂. So far I just made same edits regarding consistency.

**Comment by EJFielding** [comment]
The conda-forge version worked for me to run `conda update pygmt`. Thanks for all the work folks have done!

**Comment by weiji14** [comment]
Awesome, cheers everyone for updating the draft announcement. Will post it later today if there aren't any extra things to add.

On the workshops/conferences section, I put a note that we don't have anything planned yet, but is anyone interested in running one for [EGU24](https://www.egu24.eu) next year (short course session proposal deadline is 14 Sep 2023), AGU, or some other conference? We can discuss more on the forum if anyone is interested.

**Comment by weiji14** [comment]
Ok, forum announcement is at https://forum.generic-mapping-tools.org/t/pygmt-v0-10-0-released/4223. Can someone do the ResearchGate announcement? I'll try to post this on Twitter later too...

**Comment by michaelgrund** [comment]
> Ok, forum announcement is at https://forum.generic-mapping-tools.org/t/pygmt-v0-10-0-released/4223. Can someone do the ResearchGate announcement/post? I'll try to post this on Twitter later too...

I'll do the RG post later.

**Comment by weiji14** [comment]
Thanks @michaelgrund!

> I'll try to post this on Twitter later too...

Just tried to do the post, but [Tweetdeck](https://en.wikipedia.org/wiki/TweetDeck) which was used to access the `gmt_dev` account is now X Pro, and requires a ~€10/month subscription. I'd say we skip the Twitter/X announcement, and think of a way to expedite the transition to Mastodon/Fediverse https://github.com/GenericMappingTools/pygmt/issues/2244#issuecomment-1368280782.

**Comment by EJFielding** [comment]
> Thanks @michaelgrund!
> 
> > I'll try to post this on Twitter later too...
> 
> Just tried to do the post, but [Tweetdeck](https://en.wikipedia.org/wiki/TweetDeck) which was used to access the `gmt_dev` account is now X Pro, and requires a ~€10/month subscription. I'd say we skip the Twitter/X announcement, and think of a way to expedite the transition to Mastodon/Fediverse [#2244 (comment)](https://github.com/GenericMappingTools/pygmt/issues/2244#issuecomment-1368280782).

Let me know if you want any help with creating a Mastodon/Fediverse account. I have been using it extensively since October 31, 2022 when the ownership of the former bird site changed.

**Comment by EJFielding** [comment]
I don't know how organizations work around the management of a "teams" account on Mastodon. I have only used my own personal account. I can ask my followers on Mastodon.

**Comment by seisman** [comment]
I'm not an active Twitter and never used Mastodon. The migration from Twitter to Mastodon may take days to months. For this release, maybe @maxrjones can login the Twitter account and post the news?

**Comment by EJFielding** [comment]
I started a discussion over on the GMT forum since I understand that there is or was a shared GMT and PyGMT account on Twitter. 
https://forum.generic-mapping-tools.org/t/gmt-and-pygmt-mastodon-migration/4227

**Comment by seisman** [comment]
I'm closing the issue and moving forward to v0.11.0 release.
