### ISSUE TITLE
Use a consistent title unterline in the examples (gallery, tutorials, intro)

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2672]
So far, we are inconsistently using `----` and `====` below the title of the examples in the gallery, tutorials, and intro:
- Gallery: `----` (exception [Cross-section along a transect](https://github.com/GenericMappingTools/pygmt/pull/2659/commits/8b92c14b83fc6a132efc884d9b6f5eac0bf9c4c1))
- Projections: `=====`
- Tutorials and intros: `=====` below the title and `----` below the subsections (exception [Plotting data points](https://github.com/GenericMappingTools/pygmt/pull/2659/commits/e2e444498aab03c91aa3ad5cba06c74bb8c79c11))

This was first recognized in PR #2659. I feel it would be nice to have this consistent across all examples. Should we use `====` below the title and `----` below the subsections? What do others think? After deciding for one way and  finishing PR #2662, I can update the examples accordingly.

**Comment by seisman** [comment]
I prefer to `=====`.
