### ISSUE TITLE
Add PyGMT to pyviz.org

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2685]
Originally proposed by @chhei-s in the [forum post](https://forum.generic-mapping-tools.org/t/pygmt-v0-10-0-released/4223/2?u=seisman):

> Just piggy-backing on this thread - colleagues mentioned https://pyviz.org/tools.html as nice overview page for Python-related plotting modules/libraries. I haven’t seen PyGMT on that list yet - maybe worthwhile adding?
> 
> The header text says
> 

> > This page lists OSS libraries for visualizing data in Python. If you see any missing Python tools, please open a [PR](https://help.github.com/en/articles/about-pull-requests) for [tools.yml](https://github.com/pyviz/pyviz.org/blob/master/tools/tools.yml). Tools are sorted in each category according to their total downloads (pypi + conda) per month when added to the list

> 
> Cheers,
> Christian

It sounds a good idea. What do you think @GenericMappingTools/pygmt-maintainers?

**Comment by yvonnefroehlich** [comment]
> It sounds a good idea. What do you think https://github.com/orgs/GenericMappingTools/teams/pygmt-maintainers?

I agree that this is a good idea, and it is worthwhile adding PyGMT, maybe under the "geospatial" category (even users can also create histograms, time charts, and "normal" [Cartesian] plots).

**Comment by seisman** [comment]
> maybe under the "geospatial" category

Sounds good. @yvonnefroehlich  Would you like to submit a PR to pyviz？

**Comment by yvonnefroehlich** [comment]
> > maybe under the "geospatial" category
> 
> Sounds good. @yvonnefroehlich Would you like to submit a PR to pyviz？

Yes, I can do this 🙂.
@GenericMappingTools/pygmt-maintainers What do we want to state in the `builtons`  field? There no python plotting / visualization packages PyGMT builds on, but maybe we should add GMT there?
```
    - repo: GenericMappingTools/pygmt
      site: https://www.pygmt.org
      conda_channel: conda-forge
      badges: pypi, conda, codecov
      builtons: [gmt]
```

**Comment by seisman** [comment]
> What do we want to state in the `builtons` field? There no python plotting / visualization packages PyGMT builds on, but maybe we should add GMT there?
> 
> ```
>     - repo: GenericMappingTools/pygmt
>       site: https://www.pygmt.org
>       conda_channel: conda-forge
>       badges: pypi, conda, codecov
>       builtons: [gmt]
> ```

Sounds good to me. 

To add "gmt" to `builtons`, you also need to update this file https://github.com/pyviz/pyviz.org/blob/master/tools/builtons.yml.

**Comment by yvonnefroehlich** [comment]
So, I submitted a PR at https://github.com/pyviz/pyviz.org/pull/167.

**Comment by seisman** [comment]
PR https://github.com/pyviz/pyviz.org/pull/167 has been merged. Closing.

**Comment by chhei** [comment]
Thanks all!

**Comment by yvonnefroehlich** [comment]
> Thanks all!

Thanks @chhei  for mention this overview page on the GMT Forum!

> To add "gmt" to builtons, you also need to update this file https://github.com/pyviz/pyviz.org/blob/master/tools/builtons.yml.

Thanks @seisman for pointing this out (would be good to save _all_ files with changes before pushing back to GitHub 🙈...)!
