### ISSUE TITLE
Four tilemap tests fail likely due to upstream changes

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2699]
See the failures in the recent CI runs: https://github.com/GenericMappingTools/pygmt/actions/runs/6270258961/job/17027947064

Here is one failing test:

| Expected | Actual |
|---|---|
|  ![baseline](https://github.com/GenericMappingTools/pygmt/assets/3974108/6574aeae-7092-4503-bf80-79340fb46dce) | ![result](https://github.com/GenericMappingTools/pygmt/assets/3974108/1ebf3a99-955c-45df-a7c4-fa2ba2f7c8b7) |

Likely some changes in the original tiff files returned from the tile server?

**Comment by weiji14** [comment]
> Likely some changes in the original tiff files returned from the tile server?

Ah yes, Stamen has moved their tiles to Stadia and that came with a bit of a redesign, see https://stamen.com/here-comes-the-future-of-stamen-maps. We should also see what contextily is doing - https://github.com/geopandas/contextily/issues/220, or switch to a non-Stamen basemap for the unit tests.

**Comment by weiji14** [comment]
We'll also need to change the second example at https://www.pygmt.org/v0.10.0/gallery/maps/tilemaps.html that uses Stamen Watercolor, after Stamen stops redirecting to Stadia's servers on 31 October 2023 according to https://maps.stamen.com/stadia-partnership.
