### ISSUE TITLE
Remove gmt-python from pypi

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#270]
We should remove gmt-python from pypi (https://pypi.org/project/gmt-python/), to make things less confusing for others.

**Comment by leouieda** [comment]
Done.

Also, @seisman I'd like to add you as an owner of the PyPI package just in case. We don't need to do anything there usually and things happen automatically from Travis. But who knows. Do you have an account? If so, could you tell me the user name?

**Comment by seisman** [comment]
My pypi account user name is seisman.

**Comment by leouieda** [comment]
Thanks! Added.
