### ISSUE TITLE
Shorten the list of supported argument types in docstrings

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2718]
I'll take the `spacing` parameter as an example, which is used in the [`xyz2grd`](https://www.pygmt.org/dev/api/generated/pygmt.xyz2grd.html) and many other functions.

Here is the source code of the `spacing` docstrings:
https://github.com/GenericMappingTools/pygmt/blob/5b4d5c37b9196299b5ff43fd07aff30f9d654211/pygmt/helpers/decorators.py#L300-L302

Here is what it looks like:
<img width="612" alt="image" src="https://github.com/GenericMappingTools/pygmt/assets/3974108/902aa566-615d-472b-90fc-5348482b26e9">

As you can see, currently, `spacing` is documented to support 5 types: int, float, str, list and tuple.

My thoughts:

1. Simplify `int or float` to `float`. If an argument can accept float (e.g., 1.0), it definitely can accept int (e.g., 1). It's not necessary to list both. 
2. Simplify `list or tuple` to `list` or `tuple` or something else.

**Comment by yvonnefroehlich** [comment]
>1. Simplify `int or float` to `float`. If an argument can accept float (e.g., 1.0), it definitely can accept int (e.g., 1). It's not necessary to list both.

I aggree, if `float` is accepted, it is clear also `int` can be passed.

> 2. Simplify `list or tuple` to list or tuple or something else.

I believe we already often only mention `list` in the documentation, even though "tuple" is also allowed, and use `list` more often in the examples (?). Thus, if we summarize `list or tuple` to one term, I think we should use `list`.  

A third point, which is a bit related to this: We write inconsistently `or` (e.g., [`pygmt.xyz2grd`](https://www.pygmt.org/dev/api/generated/pygmt.xyz2grd.html)) or commas (e.g., [`pygmt.Figure.meca`](https://www.pygmt.org/dev/api/generated/pygmt.Figure.meca.html)) between more than two input types. I feel it would be nice to have this conistent. The comma version seem to be a bit shorter.

**Comment by seisman** [comment]
> A third point, which is a bit related to this: We write inconsistently `or` (e.g., [`pygmt.xyz2grd`](https://www.pygmt.org/dev/api/generated/pygmt.xyz2grd.html)) or commas (e.g., [`pygmt.Figure.meca`](https://www.pygmt.org/dev/api/generated/pygmt.Figure.meca.html)) between more than two input types. I feel it would be nice to have this conistent. The comma version seem to be a bit shorter.

That's a good point. I also prefer the comma version, which is also used by pandas (e.g., https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)
