### ISSUE TITLE
Add the Japanese "PyGMT-HOWTO" tutorial to "External Resources"

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2727]
Website: https://tktmyd.github.io/pygmt-howto-jp/pygmt.html
Repository: https://github.com/tktmyd/pygmt-howto-jp

I found this Japanese tutorial online. It looks pretty good to me. Do you think it's good enough to be added to the ["External Resources"](https://www.pygmt.org/dev/external_resources.html) page?

Please vote here. 👍  or 👎 

If agreed, then we can ping the original author to ask if he/she is willing to do it.

**Comment by seisman** [comment]
@yvonnefroehlich Comments?

**Comment by yvonnefroehlich** [comment]
> @yvonnefroehlich Comments?

Now I had some time to look at it in more detail. For me this tutorial looks really good and it has a lots of practial tips how to do things. I aggree it's good engouth to be added to the "External Resources page".

**Comment by seisman** [comment]
Hi @tktmyd, I recently discovered your fantastic PyGMT tutorial in Japanese (https://github.com/tktmyd/pygmt-howto-jp). I believe it would be a valuable addition to the "[External Resources](https://www.pygmt.org/dev/external_resources.html)" section on the PyGMT documentation, for both Japanese and non-Japanese readers.

Would you be interested in having your tutorial listed in the 'External Resources' section? If so, please let us know.

**Comment by tktmyd** [comment]
Hi @seisman and all, thank you very much for finding my tutorial. Yes, I would be very happy if you could include my tutorial on your External Resouces page. Thank you very much.

**Comment by yvonnefroehlich** [comment]
Great 🙂! I can submit a corresponding PR if this is welcome (there is the `help wanted` label). But if @tktmyd likes to add this tutorial, feel free to edit the file https://github.com/GenericMappingTools/pygmt/blob/main/doc/external_resources.md.
 
I would place this tutorial under the [Tutorials](https://www.pygmt.org/dev/external_resources.html#tutorials) section and link to the webpage (not the repro itself). For the thumbnail image, I would select one of the figures stored in the folder https://github.com/tktmyd/pygmt-howto-jp/tree/main/docs/_images, e.g., https://github.com/tktmyd/pygmt-howto-jp/blob/main/docs/_images/inf_on_map_12_0.png. @tktmyd please indicate if you have a preferred image that should be used as thumbnail image.
