### ISSUE TITLE
Allow multiple aliases for the same option flag

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2751]
See https://github.com/GenericMappingTools/gmt/pull/7923 for context.

In PyGMT, `-j` is aliased to `distcal`, but upstream GMT suggests `metric`. 

We need to discuss if we want to allow multiple aliases or deprecate `distcal` to `metric`.

**Comment by yvonnefroehlich** [comment]
At the moment, I prefer to have exactly one alias for one option flag. I personally find it confusing to have multiple aliases, as it indicates a difference that actually does not exist. However, the Julia wrapper seems to allow for multiple aliases. Hm... Is there a "Pythonic rule" regarding this issue or decision?

I agree that it is confusing to have different aliases between GMT and PyGMT, and we should try to focus on consistency.

In case we decide on multiple aliases, how is this realized in the examples? Do we want to define a "preferred" or "recommended" alias, which is then used in all examples? Or do we have to update the examples to mention all available aliases? If we used different aliases across the examples for the same thing, I feel that at least new users would definitely get confused.

**Comment by seisman** [comment]
I think multiple aliases cause more trouble than benefits. Closing the issue and feel free to reopen the issue if you don't argee.
