### ISSUE TITLE
Unexpected behavior when placing fig.colorbar

### ISSUE THREAD

**Issue by mlees0209** [GenericMappingTools/pygmt#2767]
### Description of the problem

The justify options do not seem to exhibit the expected behavior, with justify TL and TR giving almost identically placed colorbars. See example code below and attached images.

Top right justified colorbar:
![TR_justify](https://github.com/GenericMappingTools/pygmt/assets/48367782/0244f7bd-e151-4e95-a8e2-26de6a945999)

Top left justified colorbar:
![TL_justify](https://github.com/GenericMappingTools/pygmt/assets/48367782/fc028167-b532-49f8-8a78-6e294825ffb9)

This may be a deeper GMT issue as opposed to Pygmt specific.

### Minimal Complete Verifiable Example

```python
import pygmt
region_plot = [-121.85,-118.2,34.0,38.55]

topo = pygmt.datasets.load_earth_relief(resolution='15s',region=region_plot)
toporange=[-4000,4000,250]

fig = pygmt.Figure()
fig.basemap(region=region_plot,projection='M6i',frame=['WSne','xa1f0.5','ya1f0.5'])
pygmt.makecpt(cmap='terra',series=toporange,no_bg=True)
fig.grdimage(topo,cmap=True)
fig.colorbar(frame=['a1000f250','y+lm','x+l"Elevation"'],position='jTR+w2.5i+jTR',box='+gtan@50+pblack') # make the colorbar
fig.show()


fig = pygmt.Figure()
fig.basemap(region=region_plot,projection='M6i',frame=['WSne','xa1f0.5','ya1f0.5'])
pygmt.makecpt(cmap='terra',series=toporange,no_bg=True)
fig.grdimage(topo,cmap=True)
fig.colorbar(frame=['a1000f250','y+lm','x+l"Elevation"'],position='jTR+w2.5i+jTL',box='+gtan@50+pblack') # make the colorbar
fig.show()
```

### Full error message

```python-traceback
N/A
```

### System information

```bash
PyGMT information:
  version: v0.10.0
System information:
  python: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
  executable: /home/anaconda3/envs/pygmt_Oct23/bin/python
  machine: Linux-5.4.0-150-generic-x86_64-with-glibc2.27
Dependency information:
  numpy: 1.24.4
  pandas: 2.1.1
  xarray: 2023.9.0
  netCDF4: 1.6.4
  packaging: 23.2
  contextily: None
  geopandas: None
  IPython: 8.16.1
  rioxarray: None
  ghostscript: 9.56.1
GMT library information:
  binary version: 6.4.0
  cores: 12
  grid layout: rows
  image layout: 
  library path: /home/anaconda3/envs/pygmt_Oct23/lib/libgmt.so
  padding: 2
  plugin dir: /home/anaconda3/envs/pygmt_Oct23/lib/gmt/plugins
  share dir: /home/anaconda3/envs/pygmt_Oct23/share/gmt
  version: 6.4.0
```

**Comment by yvonnefroehlich** [comment]
Hello @mlees0209,

`+j` sets the anchor point and refers to the colorbar itself, not to the box around the colorbar. As a vertical colorbar is normally thin, the distance between the left and the right boundaries is small. Thus, the change in the placement of the colorbar is small when changing the anchor point from `*L` to `*R`.

I wrote a general code example to demonstrate the behaviour:

```python
import pygmt

size = 1

fig = pygmt.Figure()

# Set justification (+j) or anchor point
for anchor in ["TL", "TC", "TR"]:

    fig.basemap(
        region=[-size, size, -size, size],
        projection="X10c",
        frame=["WSNE+t+j" + anchor, "a1fg1"],
    )

    # thick colorbar
    fig.colorbar(cmap="jet", position="jTR+j" + anchor + "+w7c/2c")
    # thin colorbar
    # fig.colorbar(cmap="jet", position="jTR+j" + anchor + "+w7c/0.5c")
    
    fig.shift_origin(xshift="14c")

fig.show()
# fig.savefig(fname="colorbar_thick_anchorpoint.png")
# fig.savefig(fname="colorbar_thin_anchorpoint.png")
``` 

_Output figures_:
**Thick colorbar**
![colorbar_thick_anchorpoint](https://github.com/GenericMappingTools/pygmt/assets/94163266/eaeb8793-d426-4204-b8c8-29bf73fcb72a)

**Thin colorbar**
![colorbar_thin_anchorpoint](https://github.com/GenericMappingTools/pygmt/assets/94163266/33a15053-2f4c-4d38-bf73-bd8d3fec3102)

**Comment by weiji14** [comment]
This is giving me a Top Left colorbar:

```python
fig = pygmt.Figure()
fig.basemap(region=region_plot,projection='M6i',frame=['WSne','xa1f0.5','ya1f0.5'])
pygmt.makecpt(cmap='terra',series=toporange,no_bg=True)
fig.grdimage(topo,cmap=True)
fig.colorbar(frame=['a1000f250','y+lm','x+l"Elevation"'],position='jTL+w2.5i+jTL',box='+gtan@50+pblack') # make the colorbar
fig.show()
```
produces

![temp](https://github.com/GenericMappingTools/pygmt/assets/23487320/e5200a8c-bf33-472f-8c32-93b96155a173)

Might need to use `+o` to offset the colorbar a little bit from the edge.

To explain things a little bit from https://www.pygmt.org/v0.10.0/api/generated/pygmt.Figure.colorbar.html and https://www.pygmt.org/v0.10.0/gallery/embellishments/colorbar.html, the first argument to `position` is  `jTL`, which would set the position relative to the map, whereas the second `+jTL is setting the anchor point (i.e. the point on your colorbar box that you want the first justified position to apply to.

**Comment by weiji14** [comment]
No worries, and thanks also for providing a short reproducible example! I'll close this now, but feel free to ask further questions on our forum at https://forum.generic-mapping-tools.org, or report bugs here on GitHub if you encounter any!
