### ISSUE TITLE
Release Drafter: Automatically replace GitHub handles with real names and links

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2775]
Currently, the Release Drafter shows the contributors as a comma-separated list of GitHub handles, e.g., https://github.com/GenericMappingTools/pygmt/releases:

<img width="701" alt="image" src="https://github.com/GenericMappingTools/pygmt/assets/3974108/721c9bb6-7831-407c-87cc-ccf578594a7f">

When we make a release, we prefer to have a bulleted list with contributors' real names and links, like:

<img width="216" alt="image" src="https://github.com/GenericMappingTools/pygmt/assets/3974108/ba6a06ba-4352-4458-a228-4a8907b181d8">

So we have to make the conversions manually which is tedious.

The Release Drafter provides the [`replacers`](https://github.com/release-drafter/release-drafter#replacers) option, which can search and replace content in the generated changelog body. I think we can use this option to automatically replace GitHun handles with real names and links. This can be done by adding something like below to the `.github/release-drafter.yml` file:
```
replacers:
  - search: '@seisman'
    replace: '[Dongdong Tian](https://github.com/seisman)'
```

**Comment by yvonnefroehlich** [comment]
Then we only have to convert the comma separated list to a bullet point list, correct?

**Comment by seisman** [comment]
> Then we only have to convert the comma separated list to a bullet point list, correct?

Yes, we still need to do the handle-name conversion manually for new contributors.

**Comment by weiji14** [comment]
Could we try:

> replacers:
>   - search: '@seisman'
>     replace: '- [Dongdong Tian](https://github.com/seisman)\n'

i.e. add the `hyphen` (for making a markdown list) and a newline character at the end?

> Yes, we also need to do the handle-name conversion manually for new contributors.

The search seems to work with regex too, so we could potentially set up something like:

```
replacers:
  - search: `@(.+)`
    replace: '- [Name](https://github.com/$1)\n' 
```

But the name will still need to be manually copied. Still, saves us from having to maintain a list of contributors.

P.S. Test the regex statement at https://regex101.com/r/CV1Am0/1

**Comment by seisman** [comment]
> The search seems to work with regex too, so we could potentially set up something like:
> 
> ```
> replacers:
>   - search: `@(.+)`
>     replace: '- [Name](https://github.com/$1)\n' 
> ```

Release-drafter produces a list like this:
```
@maxrjones, @michaelgrund, @seisman, @weiji14 and @yvonnefroehlich
```
so the above search-replace won't work.

The following regex works (https://regex101.com/r/IfV49k/1):
```
replaces:
-  search: '@(\w+)(,\s| and )?'
   replace: '- [@$1](https://github.com/$1)\n'
```
It converts the comma-separated list to:
```
- [@maxrjones](https://github.com/maxrjones)
- [@michaelgrund](https://github.com/michaelgrund)
- [@seisman](https://github.com/seisman)
- [@weiji14](https://github.com/weiji14)
- [@yvonnefroehlich](https://github.com/yvonnefroehlich)
```

The [`replacers`](https://github.com/release-drafter/release-drafter#replacers) documentation says:

> Each replacer is applied in order.

So, we can have:
```
replaces:
-  search: '@(\w+)(,\s| and )?'
   replace: '- [@$1](https://github.com/$1)\n'
-  search: '@seisman'
   replace: 'Dongdong Tian'
```
