### ISSUE TITLE
ruff: Enable NPY (NumPy-specific) rules

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2779]
Currently, ruff provides three NumPy-specific rules (https://docs.astral.sh/ruff/rules/#numpy-specific-rules-npy), which can help us avoid deprecated NumPy functions.

To enable NumPy-specific rules, we just need to add `NPY` to the `select` option below:

https://github.com/GenericMappingTools/pygmt/blob/8f1d476e0144fd51827a5a27d9fa387f622bb823/pyproject.toml#L91-L97 

After enabling the `NPY` rules, running `make format` gives many [NPY002]*https://docs.astral.sh/ruff/rules/numpy-legacy-random/) warnings, like:
```
examples/gallery/histograms/histogram.py:15:1: NPY002 Replace legacy `np.random.seed` call with `np.random.Generator`
   |
13 | import pygmt
14 |
15 | np.random.seed(100)
   | ^^^^^^^^^^^^^^ NPY002
16 |
17 | # Generate random elevation data from a normal distribution
   |
```
The usage of `np.random.seed(100)` is deprecated. We should use something like below instead:
```
rng = np.random.default_rng(100)
rng.random()
```

**Comment by yvonnefroehlich** [comment]
Should we split this into three PRs?
1. Update pyproject.toml: PR #2782
2. Update the examples: PR #2781
3. Update the tests: PR #xyz
