### ISSUE TITLE
pygmt.grdclip doesn't work with GMT dev version

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2785]
Originally reported in the forum (https://forum.generic-mapping-tools.org/t/grdclip-not-working-after-updating-to-dev/4383).
 
Here is a modified version:
```python
import pygmt

# work on a grid file directly
grid = pygmt.grdclip("@earth_relief_01d_p", above=[0.0, 0.0])
print(grid.data.min(), grid.data.max())

# work on a xarray.DataArray object
grid = pygmt.datasets.load_earth_relief(resolution="01d", registration="pixel")
grid = pygmt.grdclip(grid, above=[0.0, 0.0])
print(grid.data.min(), grid.data.max())
```

With GMT 6.4, it produces:
```
-8190.5 0.0
-8600.5 0.0
```
With GMT dev (`6.5.0_f30bd45_2023.10.20`), it produces:
```
-8190.5 0.0
-8600.5 5559.0
```

@PaulWessel This looks like an upstream bug. Could you verify it?

**Comment by PaulWessel** [comment]
```
gmt grdclip @earth_relief_01d_p -Sa0/0 -Gt.grd
gmt grdinfo t.grd -C
t.grd	-180	180	-90	90	-8190.5	0	1	1	360	180	1	1
```


So grdclip is doing the right thing,  Your second call passes grid as input and that is a matrix?

**Comment by seisman** [comment]
> So grdclip is doing the right thing, Your second call passes grid as input and that is a matrix?

Yes, passing a grid file works, but passing a matrix doesn't work.

**Comment by PaulWessel** [comment]
If you run the failing one with the equivalent of -M, any difference?

**Comment by seisman** [comment]
> If you run the failing one with the equivalent of -M, any difference?

You meant `grdinfo -M`?

```
import pygmt

grid = pygmt.datasets.load_earth_relief(resolution="01d")
grid = pygmt.grdclip(grid, above=[0.0, 0.0])
print(pygmt.grdinfo(grid, per_column=True, minmax_pos=True))
```
It gives `-180 180 -90 90 -8600.5 5559 1 1 361 181 142 34 85 30 0 0 1`.

**Comment by PaulWessel** [comment]
OK, following debug for PyGMT/XCode but 

```
base) pwessel@MacAttack-2:~-> conda active pygmt
usage: conda [-h] [-v] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'active' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'content-trust', 'doctor', 'env')
```

What am I forgetting?

**Comment by seisman** [comment]
Should be `conda activate pygmt`.

**Comment by PaulWessel** [comment]
Good grief.  Thanks!

**Comment by seisman** [comment]
Closed by Paul in https://github.com/GenericMappingTools/gmt/pull/7989.
