### ISSUE TITLE
Improve the CI tests speed via Codecov Automated Test Selection

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2791]
I haven't read the full documentation carefully, but it seems the new codecov tool, [Automated Test Selection](https://docs.codecov.com/docs/automated-test-selection) can help improve the tests speed significantly:

> Automated Test Selection is a Codecov feature that ensures your CI pipeline only runs the tests needed to completely exercise the diff of a commit. Automated Test Selection is intended to greatly reduce the time needed to run test suites without compromising on test coverage or having to invest in creating the complex CI pipelines and tools (e.g., Bazel) that are typically required to facilitate test selection.

> Testing tools typically have a stage of collecting tests followed by a stage of executing tests. The idea behind Automated Test Selection is to live exactly between those 2 stages as a filter to decide which tests necessarily need to be executed, considering the diff of the commit being tested.

I think it may be worth a try.

**Comment by weiji14** [comment]
Linking to #584. I mentioned something similar with [`pytest-fastest`](https://github.com/kstrauser/pytest-fastest) before, but maybe this is easier to set-up.

Ok to try this Automated Test Selection for Pull Requests, but run full tests still on the `main` branch (and also for release PRs)? Looking at https://docs.codecov.com/docs/automated-test-selection-quick-start, it sounds like the GitHub Action is only tested on Linux and macOS, so need to check if Windows (our slowest tests) works. We could file an issue at https://github.com/codecov/codecov-ats requesting for Windows support if it doesn't.
