### ISSUE TITLE
Use "--skip=" to exclude specific files from the typo and misspelling checks by codespell

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#2804]
Currently, running `make codespell` checks all files regarding typos and misspellings, including *.html and *.js files:
```
(pygmt02) yfroe@gpiseis16:~/Documents/01_GitHub/github_pygmt/pygmt> make codespell
...
./doc/_build/html/contributing.html:786: nd ==> and, 2nd
./doc/_build/html/contributing.html:885: nd ==> and, 2nd
./doc/_build/html/index.html:271: nd ==> and, 2nd
./doc/_build/html/maintenance.html:346: nd ==> and, 2nd
./doc/_build/html/maintenance.html:347: nd ==> and, 2nd
./doc/_build/html/maintenance.html:348: nd ==> and, 2nd
./doc/_build/html/maintenance.html:349: nd ==> and, 2nd
./doc/_build/html/searchindex.js:1: abov ==> above
./doc/_build/html/searchindex.js:1: absolut ==> absolute
./doc/_build/html/searchindex.js:1: achiev ==> achieve
./doc/_build/html/searchindex.js:1: activ ==> active
./doc/_build/html/searchindex.js:1: advantag ==> advantage
./doc/_build/html/searchindex.js:1: agre ==> agree
./doc/_build/html/searchindex.js:1: amplitud ==> amplitude
./doc/_build/html/searchindex.js:1: appar ==> appear
./doc/_build/html/searchindex.js:1: assum ==> assume
./doc/_build/html/searchindex.js:1: attribut ==> attribute
./doc/_build/html/searchindex.js:1: beauti ==> beauty
./doc/_build/html/searchindex.js:1: becaus ==> because
./doc/_build/html/searchindex.js:1: befor ==> before
./doc/_build/html/searchindex.js:1: beginn ==> begin
./doc/_build/html/searchindex.js:1: bridg ==> bridge
./doc/_build/html/searchindex.js:1: cach ==> catch, cache
...
```
 However, these entries in the quite long list are no typos or misspellings. Thus, I am wondering whether we should use `--skip=*.html,*.js` to exclude these files (and maybe others):
https://github.com/GenericMappingTools/pygmt/blob/10c434ffa7c67dc1746b03c77b4df3b91346d0f5/Makefile#L74-L75

**Comment by seisman** [comment]
These files are generated when building documentation and are not tracked by git. It's easy to remove them by running `cd doc; make clean`.

I don't think using `--skip=*.html,*.js` is a good idea, because there are git-tracked JS files (e.g., `doc/_static/version_switch.js`) and codespell should also check them.

**Comment by yvonnefroehlich** [comment]
> These files are generated when building documentation and are not tracked by git. It's easy to remove them by running `cd doc; make clean`.

Yes, I know this. But I find it a bit inconvenient to first remove these files and then build the complete documentation again.

> I don't think using `--skip=*.html,*.js` is a good idea, because there are git-tracked JS files (e.g., `doc/_static/version_switch.js`) and codespell should also check them.

OK, I am fine with leaving it as is.
