### ISSUE TITLE
Figures plotting only half in Jupyter

### ISSUE THREAD

**Issue by EJFielding** [GenericMappingTools/pygmt#291]
I managed to buiild GMT from source (kind of like the old days when editing the configuration file and building source was the only way). I installed pygmt and got it to import in my Jupyter notebook. When I try to make a simple plot like the "first-figure" example, it only plots the left half of the figure and chops off the top a little. This is the same for the Jupyter notebook and the saved png file. Here is the example saved:
![central-america-shorelines](https://user-images.githubusercontent.com/7253576/54081698-98b8a280-42bd-11e9-8159-397028da6357.png)

**Comment by liamtoney** [comment]
Thanks for posting, @EJFielding. Could you please provide the Python code you used to generate the above plot? I'm wondering if this is a figure width / portrait mode issue.

**Comment by EJFielding** [comment]
Thanks for the quick reply. Yes, if I set the `projection="M4i"` then I see more of the figure, but not quite all. I am a beginning Jupyter user, so I don't have any idea what controls the width of the figure. For some reason, I can only plot figures that are about 3 inches wide.

It  is good that the saved file is the same, so "what you see is what you get".

**Comment by seisman** [comment]
> it only plots the left half of the figure and chops off the top a little. This is the same for the Jupyter notebook and the saved png file.

@EJFielding Could you try following GMT commands in your terminal and check if the generated PNG file is correct?
```
gmt begin map png
gmt basemap -R-90/-70/0/20 -JM8i -B
gmt coast -W
gmt end
```

Could you also please provide your GMT version (`gmt --version`) and gs version (`gs --version`)?

**Comment by EJFielding** [comment]
I ran those GMT commands in the shell command line and I get the complete map.

`fielding% gmt --version
6.0.0_2f22074_2019.03.09` 
`gs --version
9.26`

**Comment by seisman** [comment]
Could you please paste the output of following Python codes?
```python
import pygmt
pygmt.print_clib_info()
```

**Comment by EJFielding** [comment]
From Jupyter notebook, I get this:

> Loaded libgmt:
  binary dir: /opt/local/Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS
  cores: 8
  grid layout: rows
  library path: /Users/fielding/tools/gmt/lib/libgmt.dylib
  padding: 2
  plugin dir: /Users/fielding/tools/gmt/lib/gmt/plugins
  share dir: /Users/fielding/tools/gmt/share
  version: 6.0.0

**Comment by EJFielding** [comment]
I use MacPorts to install Python 3.6, so I kept my pygmt installation in my home directory tree to avoid messing with the MacPorts files, in case that makes a difference.

**Comment by seisman** [comment]
It looks OK to me. I have no idea where the problem is. Let's wait for @leouieda.

**Comment by leouieda** [comment]
@EJFielding this is interesting. From GenericMappingTools/gmt#497 it seems to be a problem with the plot units. Could you share your cmake config for building GMT?

**Comment by EJFielding** [comment]
Sure, I attach my config file.

[ConfigUser.cmake.txt](https://github.com/GenericMappingTools/pygmt/files/2955172/ConfigUser.cmake.txt)

**Comment by leouieda** [comment]
:thinking: I don't see anything wrong with the setup. It doesn't seem to be a problem on the Python side. I can't reproduce the effect. Which version of ghostscript do you have?

**Comment by EJFielding** [comment]
I have gs --version 9.26

**Comment by joa-quim** [comment]
When you do
```
gmtdefaults -D | grep PROJ_LENGTH_UNIT
PROJ_LENGTH_UNIT               = cm
```
it prints ``cm`` or ``inch``? (Because the GMT 497 issue seems to be related to the use of inches)

**Comment by EJFielding** [comment]
I have this default when I do that on the command line:

> PROJ_LENGTH_UNIT               = cm

I am not sure how to check the defaults within the Jupyter notebook.

**Comment by leouieda** [comment]
It should be the same since we're using the same GMT library that the command line program uses.

**Comment by leouieda** [comment]
From the discussion in GenericMappingTools/gmt#497, do you have a `gmt.conf` file in the current directory? The new GMT modern mode sets the `PS_MEDIA` to a huge page and then crops the plot down when exporting it afterwards. If you're setting `PS_MEDIA` and forcing it to be letter or A4, then this would be a problem.

**Comment by EJFielding** [comment]
Thanks! Yes, I have a gmt.conf in this directory because I was running GMT5. It has `PS_MEDIA letter` in it.

**Comment by EJFielding** [comment]
I removed the `gmt.conf` file and tried the `'first-figure.py` plot again and it shows the whole thing. Here is the saved PNG:
![central-america-shorelines](https://user-images.githubusercontent.com/7253576/54408071-8fed1580-469d-11e9-8279-7ede6860d6b6.png)

**Comment by EJFielding** [comment]
I think you can close this issue. Maybe it would help to put something in the documentation to remove any `gmt.conf` left over from previous GMT5 runs.

**Comment by leouieda** [comment]
Thanks, Eric! It's good to know. We're actually discussing a better solution that wouldn't require the user to take action at GenericMappingTools/gmt#497
