### ISSUE TITLE
Convert documentation source files from ReStructuredText to Markdown

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2928]
Currently, some documentations are written in Markdown while some are in ReStructuredText. I think it's better to use a consistent format so that new contributors won't be confused.

Here are the `.rst` files in the repository:
```
$ find . -name '*.rst'
./README.rst
./doc/install.rst
./doc/overview.rst
./doc/index.rst
./doc/api/index.rst
./doc/_templates/autosummary/module.rst
./doc/_templates/autosummary/class.rst
./doc/_templates/autosummary/exception.rst
./doc/_templates/autosummary/method.rst
./doc/_templates/autosummary/base.rst
./doc/_templates/autosummary/function.rst
```
I think at least the following three files should be converted to markdown:

- [ ] `README.rst` #3059 
- [x] `doc/install.rst` #2992 
- [x] `doc/overview.rst` #2953

Comments?

**Comment by yvonnefroehlich** [comment]
I agree that we should work towards using a consistent format (when possible).

Did people have specific reasons to use ReStructuredText for these files when writing them?

Regarding `README.rst`, we have this in the Maintainers Guide (https://www.pygmt.org/dev/maintenance.html#check-the-readme-syntax):
> Check the README Syntax
GitHub is a bit forgiving when it comes to the RST syntax in the README, but PyPI is not. To check the README syntax, visit the [PyGMT TestPyPI release history](https://test.pypi.org/project/pygmt/#history), select the latest commit, and review the left sidebar and project description for any errors.

Thus, I am wondering whether PyPI expects ReStructuredText or there are some issues with Markdown.

**Comment by seisman** [comment]
> Did people have specific reasons to use ReStructuredText for these files when writing them?

These must be some historical reasons. If you're familiar with both ReST and Markdown, you will see that ReST is more powerful and is suitable for writing technical documentation for big projects. Instead, the original Markdown syntax is much simpler and is most suitable for writing short documentation like a blog post. However, in recent years, the [MyST Markdown](https://jupyterbook.org/en/stable/content/myst.html) has been mature enough to be as powerful as ReST and is becoming popular.



> Regarding `README.rst`, we have this in the Maintainers Guide (https://www.pygmt.org/dev/maintenance.html#check-the-readme-syntax):
> 
> > Check the README Syntax
> > GitHub is a bit forgiving when it comes to the RST syntax in the README, but PyPI is not. To check the README syntax, visit the [PyGMT TestPyPI release history](https://test.pypi.org/project/pygmt/#history), select the latest commit, and review the left sidebar and project description for any errors.
> 
> Thus, I am wondering whether PyPI expects ReStructuredText or there are some issues with Markdown.

PyPI started to support Markdown (https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/#creating-a-readme-file) since 2018.

**Comment by yvonnefroehlich** [comment]
Maybe I will find the time to work on re-writting the README, as I am already working on moving the compatibility table to a separate file. In this context we also discussed re-writing this table in Markdown (https://github.com/GenericMappingTools/pygmt/issues/2858#issuecomment-1847098634 and https://github.com/GenericMappingTools/pygmt/issues/2858#issuecomment-1847109766).

**Comment by seisman** [comment]
> Maybe I will find the time to work on rewriting the README, as I am already working on moving the compatibility table to a separate file. In this context, we also discussed rewriting this table in Markdown ([#2858 (comment)](https://github.com/GenericMappingTools/pygmt/issues/2858#issuecomment-1847098634) and [#2858 (comment)](https://github.com/GenericMappingTools/pygmt/issues/2858#issuecomment-1847109766)).

I think we need to address #2863 and #2858 before working on the README file.

**Comment by seisman** [comment]
> In this context, we also discussed rewriting this table in Markdown ([#2858 (comment)](https://github.com/GenericMappingTools/pygmt/issues/2858#issuecomment-1847098634) and [#2858 (comment)](https://github.com/GenericMappingTools/pygmt/issues/2858#issuecomment-1847109766)).

Done in https://github.com/GenericMappingTools/pygmt/pull/3056.

> Maybe I will find the time to work on rewriting the README, as I am already working on moving the compatibility table to a separate file. 

@yvonnefroehlich Now we can start working on the README file. Let me know if you'd like to work on it. Just in case you didn't know yet, [pandoc](https://pandoc.org/) is a tool that can convert ReST to Markdown automatically. The command is:
```
pandoc README.rst -t markdown
```
Of course, after the pandoc conversion, you may still need to make some manual edits to make it better.

**Comment by yvonnefroehlich** [comment]
> > Maybe I will find the time to work on rewriting the README, as I am already working on moving the compatibility table to a separate file.
> 
> @yvonnefroehlich Now we can start working on the README file. Let me know if you'd like to work on it. Just in case you didn't know yet, [pandoc](https://pandoc.org/) is a tool that can convert ReST to Markdown automatically. The command is:
> 
> ```
> pandoc README.rst -t markdown
> ```
> 
> Of course, after the pandoc conversion, you may still need to make some manual edits to make it better.

Thanks @seisman for pointing out this tool :slightly_smiling_face:. I just started working on converting the REAMDE to markdown in PR #3059.
