### ISSUE TITLE
Policy for minimum supported GMT versions

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2967]
With GMT 6.5.0 released, now PyGMT supports three GMT minor versions, 6.3, 6.4 and 6.5, although old GMT versions may have some bugs and miss some features. Supporting multiple GMT versions is a big burden for us maintainers, so we need to decide our policy for the minimum supported GMT versions.

Here are a few options:

1. No policy, i.e., try our best to support the oldest GMT version, unless there is no way or very difficult to be backward-compatible
2. Follow SPEC 0's recommendations for Python versions (#2863), and support for GMT versions to be dropped 3 years after their initial release. 
3. Follow SPEC 0's recommendations for core package dependencies (#2863), and support for GMT versions to be dropped 2 years after their initial release. 

FYI, GMT usually has one release per year (https://github.com/GenericMappingTools/gmt/tags). 

- GMT 6.3.0 was released on Nov 19, 2021 
- GMT 6.4.0 was released on Jun 16, 2022 
- GMT 6.5.0 was released on Jan 7, 2024

**Comment by weiji14** [comment]
We can probably support about 2-3 minor GMT versions at a time, so maybe go with Option 2 (drop GMT versions after 3 years)? That's assuming that GMT continues to have a minor release every year, which means PyGMT will support at least 2 (or more) GMT minor versions at a time.

**Comment by seisman** [comment]
I'm also in favor of option 2. Ping @GenericMappingTools/pygmt-maintainers for comments.

**Comment by seisman** [comment]
Ping @yvonnefroehlich @willschlitzer @michaelgrund for comments. Otherwise, we will go with option 2.

**Comment by yvonnefroehlich** [comment]
I feel PyGMT should support the last 2-3 GMT versions. From my experience, many users are not updating GMT immediately after a new release. I personally prefer to stay with the same GMT version for a publication, which can easily take a year (or more) to be finally published. So, I think option 2 is a fair compromise between supporting older GMT versions and the work for developers and maintainers.

**Comment by seisman** [comment]
I think we will go for option 2. Need to document the policy in README, `doc/maintenance.md`, `doc/minversions.rst` and also need to update the release checklist.
