### ISSUE TITLE
The conda-forge badge shows incorrect PyGMT version

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2983]
For unknown reasons, the conda-badge shows PyGMT v0.9.0, not v0.10.0:
<img width="766" alt="image" src="https://github.com/GenericMappingTools/pygmt/assets/3974108/a71365b2-105c-4ddc-a605-f6581e1b13af">

Related links:

- https://anaconda.org/conda-forge/pygmt
- https://github.com/conda-forge/pygmt-feedstock

**Comment by yvonnefroehlich** [comment]
Currently, this appears quite strange to me. I Just looked at a screenshot I made in December, approx. 2023/12/16 or a bit earlier, and there the the conda-forge badge shows the correct PyGMT version:

![pygmt_anaconda_badge_20231216](https://github.com/GenericMappingTools/pygmt/assets/94163266/beb3c70b-93b3-4aa5-bf6d-f22d146174df)

**Comment by seisman** [comment]
After releasing pygmt v0.11.0, now the conda-forge badge shows the correct version.

<img width="770" alt="image" src="https://github.com/GenericMappingTools/pygmt/assets/3974108/d911179c-28b6-40cc-82eb-3b9abc04be33">
