### ISSUE TITLE
API documentations generated by sphinx 2.x are unreadable 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#305]
**Description of the problem**

See https://www.pygmt.org/dev/api/generated/pygmt.Figure.basemap.html or the screenshot below:
![image](https://user-images.githubusercontent.com/3974108/57091679-b7448400-6cd7-11e9-9aca-650f1f5a7aea.png)

This is caused by the recent update of sphinx 2.x and the inconsistence between sphinx 2.x and sphinx_rtd_theme. See https://github.com/rtfd/sphinx_rtd_theme/issues/752 for the description of the bug.

We should use sphinx<=1.8.5 now.

**Comment by seisman** [comment]
The documentations are still buggy.

**Comment by seisman** [comment]
The API lists are not still rendered correctly. 
![image](https://user-images.githubusercontent.com/3974108/57166317-c99deb00-6dc7-11e9-8268-092fd8797cc9.png)

See https://www.pygmt.org/dev/api/index.html#plotting

**Comment by leouieda** [comment]
You're right. I hand't notice when that I downgraded. I'll try 1.8.3

**Comment by seisman** [comment]
1.8.5 works locally for me.

**Comment by leouieda** [comment]
From numpy/numpydoc#215 this problem seems to be a combination of sphinx, numpydoc, and the rtd theme. I get the same thing locally. For now, this is not good but not terrible. Let's keep this open so we know to fix it but I don't want to worry too much about it now.

**Comment by weiji14** [comment]
I'll close this as it should be resolved by the move to using the napolean sphinx extension in #383. Screenshot of https://www.pygmt.org/dev/api/generated/pygmt.Figure.basemap.html and https://www.pygmt.org/dev/api/index.html#plotting below:

![basemap docs with new napolean sphinx](https://user-images.githubusercontent.com/23487320/77483831-ff3f3d00-6e8d-11ea-94d7-04b1ee2e3db6.png)

![plotting api docs with new napolean sphinx](https://user-images.githubusercontent.com/23487320/77483996-59400280-6e8e-11ea-9193-c149ab0610f7.png)
