### ISSUE TITLE
Not working with GMT 6.0.0rc1

### ISSUE THREAD

**Issue by claudiodsf** [GenericMappingTools/pygmt#310]
Hi, I just installed `GMT 6.0.0rc1` on macOS through [homebrew](https://github.com/Homebrew/homebrew-core/pull/41119) and `pygmt` from source, but when try importing `pygmt`, I get the following error:

```
GMTVersionError: Using an incompatible GMT version 6.0.0rc1. Must be newer than 6.0.0.
```

**Comment by claudiodsf** [comment]
The problem can be reduced to this:
```python
>>> from packaging.version import Version
>>> Version('6.0.0rc1') < Version('6.0.0')
True
```

**Comment by claudiodsf** [comment]
By the way, the error message should say:
```
Must be equal or newer than 6.0.0.
```

**Comment by seisman** [comment]
Yes, 6.0.0rc1 is a pre-release version. I think the solution is to change the `required_version` to `6.0.0rc1`.

https://github.com/GenericMappingTools/pygmt/blob/997b88c855c12ffacd2c4b911f3fa83244ce8d7b/pygmt/clib/session.py#L114-L115

**Comment by claudiodsf** [comment]
Yep, I agree.

**Comment by seisman** [comment]
Could you submit a PR?

**Comment by claudiodsf** [comment]
Ok
