### ISSUE TITLE
Switch to official GitHub action for managing app tokens

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#3164]
Currently, we're using the [`tibdex/github-app-token` action](https://github.com/tibdex/github-app-token) to generate PAT tokens which are used in the `/format` slash command (initially proposed in https://github.com/GenericMappingTools/pygmt/pull/645#discussion_r502327175).

It seems that GitHub now provides an official action for this purpose (https://github.com/actions/create-github-app-token). I think we should try to switch to the official one. Looking at this PR (https://github.com/dependabot/dependabot-core/pull/9340), it seems we just need to update the action name and the action input names.

xref: 

- https://github.com/tibdex/github-app-token/issues/99
- https://github.com/actions/create-github-app-token

**Comment by yvonnefroehlich** [comment]
Meaning changing https://github.com/GenericMappingTools/pygmt/blob/16339753634de75b0b165bc8a1beead37d1c3ad2/.github/workflows/format-command.yml#L13-L18
to
```python
      # Generate token from GenericMappingTools bot
      - uses: actions/create-github-app-token@v1.9
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
```

**Comment by yvonnefroehlich** [comment]
> Yes, that should work.

Thank! I summited PR #3165 with this change.
