### ISSUE TITLE
FOSS4G Oceania 2019 outreach

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#317]
So my city ([Wellington, New Zealand](https://en.wikipedia.org/wiki/Wellington)) is hosting the next [FOSS4G SotM Oceania](https://2019.foss4g-oceania.org/) conference from November 12-15, 2019, and I'd like to put my hand up :wave: to do some outreach for PyGMT (or even GMT in general). I know you're all busy with the [UNAVCO Short Course](https://github.com/GenericMappingTools/2019-unavco-course) at the moment but I'd like to mention this FOSS4G conference now so you might have it in the back of your heads, and also because the Call for Presentation/Workshops just opened up (early bird tickets on sale now too).

![FOSS4G SotM Oceania Wellington 2019 banner](https://user-images.githubusercontent.com/23487320/61566541-b0583100-aad0-11e9-8d49-937e00d9fd46.png)

Key dates (NZ Standard Time, GMT+12):

- 17 August [Call for Workshops](https://submit-workshops.foss4g-oceania.org/fso2019w/cfp) deadline.
- 31 August [Call for Presentations](https://submit-talks.foss4g-oceania.org/fso2019/cfp) deadline.
- 1-15 September: Community vote (on what workshops/presentations get selected)
- 21 September: Presentations selected, conference program announced

**Are you willing to help implement and maintain this feature?** **Yes!**

Depending on how much time/resources we have, there's a range of things we can do:

- 5 min lightning :zap: talk (quick advertisement for PyGMT)
- 18 min presentation :woman_teacher: (more in-depth showcase of PyGMT, welcome more community contributors)
- 3.5 hour workshop :keyboard: (guide people around using PyGMT at their computers)
- [Community Day](https://twitter.com/mapmakerdavid/status/1151068594438123520) (~9-5pm) code sprint :computer: (get new contributors working on some pull requests!)

Personally I'd be keen on hosting a workshop and I've got some computer lab tutoring experience that should make it work. It would also be fantastic if one of you are willing to come over and we can set up a code sprint to finish some of those longstanding pull requests!

I actually know some of the organizers here at the university it should be easy-ish to set the software side of things up or we can just use [Binder](https://mybinder.readthedocs.io/en/latest/)/[Google Colaboratory](https://colab.research.google.com/). Once GMT 6 is released, we should work on getting a proper PyPI release out for PyGMT too and I'll try to get some more sphinx-gallery/jupyter notebook examples ready for the incoming tide :laughing:.

Comments/Questions?

**Comment by leouieda** [comment]
Hi @weiji14 this is a great idea! Sadly, I don't know if any of us can make it down for the conference but would you be willing to host something yourself? If so, then feel free to choose whichever format you think best. 

We can surely help with developing the material and anything that can be done remotely. We'll surely have GMT 6 by then and as soon as that is out I want to get a 0.1.0 of PyGMT out on PyPI and conda-forge. 

What do you think?

**Comment by weiji14** [comment]
Cool, I'll definitely submit an abstract and see how that goes. Still debating on whether a presentation or workshop would be better. Having done the [Scipy2017](https://github.com/GenericMappingTools/scipy2017) and [UNAVCO2019 Short Course ](https://github.com/GenericMappingTools/2019-unavco-course) what do you think worked better in terms of outreach @leouieda? Any lessons learnt from those 2 that might be helpful this time round?

I've also emailed to ask about the Community Day thing (still waiting to hear back) but I feel that it would really complement an introductory presentation/workshop - having people working on the code itself! It would be good to have a few more [good first issues](https://github.com/GenericMappingTools/pygmt/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) on our list, plus get that 'try-gmt' repo set up as you mentioned in https://github.com/GenericMappingTools/try-gmt-python/pull/1#issuecomment-505239306.

**Comment by weiji14** [comment]
I've sent in the workshop abstract! See https://submit-workshops.foss4g-oceania.org/fso2019w/talk/review/ECVJ8X9MBE8JSGWX7XAWGLNFLXRZTLHS.

**Comment by weiji14** [comment]
Hi @leouieda, just following up on this since the PyGMT workshop is now 2 weeks away! There's about 6 people signed up so far and possibly more coming! It would be great if you and the @GenericMappingTools/python-contributors team could find some time to review the features I've tagged [`v0.1.0`](https://github.com/GenericMappingTools/pygmt/pulls?q=is%3Aopen+is%3Apr+milestone%3A0.1.0).

I'll start to set up a FOSS4G Oceania repo and populate some jupyter notebook tutorials, but it'll be great if those Pull Requests can get merged in on time for the workshop. Could definitely use some help with getting a 0.1.0 release out of the door :rocket:

**Comment by weiji14** [comment]
Ok, I've set up a repository at https://github.com/GenericMappingTools/foss4g2019oceania, but am having hitting another permissions issue. Pushing to the repo from my computer gives this error:

```bash
ERROR: Permission to GenericMappingTools/foss4g2019oceania.git denied to weiji14.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Not sure if it's because I'm using SSH instead of HTTPS to do git push/pull (I have 2FA enabled which is why I need to use SSH). I've changed the repo permissions to 'maintain' for @GenericMappingTools/python but it's still not allowing me to `git push`. I think it might be because of the default GMT organization permissions:

![image](https://user-images.githubusercontent.com/23487320/67644037-b5a40200-f982-11e9-8247-701707b97438.png)

Keyword: **regardless** of the team and collaborator access as specified below.

**Comment by seisman** [comment]
It's really weird that you create the repository and you're the admin, but cannot push to this repository.

This is the description of the default permission. The settings of the foss4g2019oceania repository should override the default permission.

![image](https://user-images.githubusercontent.com/3974108/67648097-0bd55e80-f90b-11e9-87f8-3f520832dc06.png)

**Comment by weiji14** [comment]
That is very strange indeed. I guess I could just make a fork and keep on submitting Pull requests then...

**Comment by seisman** [comment]
I just revoked the permission of the python-contributors team. Now the permission setting is almost the same as the pygmt repository. Could you try again?

**Comment by weiji14** [comment]
Nope, doesn't work. Does it matter if I'm in both the python-contributors and python team?

**Comment by leouieda** [comment]
@weiji14 @seisman the permissions are handled through the teams. The way I've been doing it is giving the `python` team admin rights to all Python related repositories. It shouldn't matter that you are in both. The `python-contributors` team is mostly to keep track of people who've contributed sporadically but not taken on a more definite role in the project.

**Comment by leouieda** [comment]
That's strange because the organization settings page states:

>  Since organization members can have permissions from multiple sources, members and collaborators who have been granted a higher level of access than the base permissions will retain their higher permission privileges. 

But I'm guessing this has been fixed now?

**Comment by weiji14** [comment]
Thanks for the permissions troubleshooting everyone. Moving on...

I've got **8** confirmed attendees and have just churned out my 2nd tutorial at https://github.com/GenericMappingTools/foss4g2019oceania/pull/7. Just started working on my 3rd tutorial on processing point clouds last night, and could really use someone time to review `blockmedian` #349 and `grdview` #330 by this weekend, especially `grdview` as I've promised 3D plotting in my abstract and it's also (quite frankly) the killer app for PyGMT.

**Comment by weiji14** [comment]
Closing as workshop is now over. Rendered jupyter notebooks of the workshop can now be found at https://github.com/GenericMappingTools/foss4g2019oceania. Just note that the version of PyGMT used in the [Pangeo binder](https://binder.pangeo.io) environment is from a 'foss4g2019oceania' branch at https://github.com/GenericMappingTools/pygmt/tree/foss4g2019oceania. I.e. `pip install https://github.com/GenericMappingTools/pygmt/archive/foss4g2019oceania.zip`.
