### ISSUE TITLE
When will command “text” be added?

### ISSUE THREAD

**Issue by chdwql** [GenericMappingTools/pygmt#319]
**We need to mark the text on the figure**

**Are you willing to help implement and maintain this feature?** No

**Comment by weiji14** [comment]
Hi/你好 @chdwql, unfortunately this is not implemented yet, though it has been mentioned before in https://github.com/GenericMappingTools/pygmt/issues/122 back in Jan 2018.

@leouieda, you mentioned some 'virtual file machinery' changes in https://github.com/GenericMappingTools/pygmt/issues/122#issuecomment-358436386 that was needed for `pstext`/`text` to be wrapped, I'm assuming that has been implemented already?

I've got some free time this week (university servers getting migrated) and might be able to put in a pull request for this :wave:.

**Comment by weiji14** [comment]
@chdwql, we've just implemented `text` in PyGMT at #321. You should be able to use [install PyGMT from Github](https://www.pygmt.org/dev/install.html#installing-pygmt) and use it now :tada:. Let us know if you need any help using it.
