### ISSUE TITLE
[Easy typo fix] #dropthedot from py.test

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#336]
**Description of the problem**

First-timers :one: only!! This should be about as simple as it gets. You'll literally be removing just a dot `.` from `py.test` in the [Testing plots section in CONTRIBUTING.md](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md#testing-plots).

In other words, change:
```
py.test --mpl-generate-path=baseline pygmt/tests/NAME_OF_TEST_FILE.py
```
to
```
pytest --mpl-generate-path=baseline pygmt/tests/NAME_OF_TEST_FILE.py
```

You can [edit the file online on Github :octocat: here](https://github.com/GenericMappingTools/pygmt/edit/master/CONTRIBUTING.md) or in your Text Editor or [Integrated Development Environment (IDE)](https://en.wikipedia.org/wiki/Integrated_development_environment).

For some background on why we've decided to #dropthedot, see https://stackoverflow.com/questions/39495429/py-test-vs-pytest-command and https://twitter.com/davehunt82/status/756080181085872129. Basically it's because `py.test` will be go away/be deprecated at some point in the future.

**How to get help**

You can check out our [CONTRIBUTING.md](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md) file (that's the file you'll be fixing by the way!) or this website https://firstcontributions.github.io/ on how to make your first contribution. Leave a comment below if you'd like to start working on this and feel free to ask for help! It's actually as much of a learning experience for us (guiding new people) as it will be for you :smile:

**Stretch goals**

There's actually another place in the repository that refers to `py.test` instead of `pytest`. Can you find it and fix that too?

**Comment by Dovacody** [comment]
Hello, I just submitted a pull request that fixed this typo. Thank you for posting something to help us new to all of this!
