### ISSUE TITLE
Some potential improvements of the installation instructions

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#3371]
Looking at the [Installation Instructions](https://www.pygmt.org/dev/install.html#dependencies), currently four optional dependencies are listed
 
> - [IPython](https://ipython.org/): For embedding the figures in Jupyter notebooks (recommended).
> - [Contextily](https://contextily.readthedocs.io/): For retrieving tile maps from the internet.
> - [GeoPandas](https://geopandas.org/): For using and plotting GeoDataFrame objects.
> - [RioXarray](https://corteva.github.io/rioxarray): For saving multi-band rasters to GeoTIFFs.

Here are my thoughts:

1. Install the optional dependencies in the [Installing GMT and other dependencies](https://www.pygmt.org/v0.12.0/install.html#installing-gmt-and-other-dependencies) step to have a full-feature PyGMT. There are two options: (1) add optional dependencies when creating the virtual environment; (2) add a separate command: `mamba install ipython contextily geopandas rioxarray` to install the optional packages after creating the virtual environment.

2. Are IPython and GeoPandas considered optional dependencies? (1) PyGMT supports GeoPandas objects as inputs but GeoPandas is not imported anywhere in the PyGMT source codes; (2) IPython is needed for embedding figures in Jupyter Notebooks, but as long as users are in a Notebook environment, IPython is always available since it's a dependency of Jupyter. 

3. Some packages like GeoPandas/Shapely/PyArrow, are not directly used in PyGMT, but it's good to let users know that PyGMT supports them.

**Comment by seisman** [comment]
Ping @GenericMappingTools/pygmt-maintainers

**Comment by weiji14** [comment]
> 1. ... (2) add a separate command: `mamba install ipython contextily geopandas rioxarray` to install the optional packages after creating the virtual environment.

Sure, we can add a tip admonition to show this, similar to how we're showing `pip install pygmt[all]` here:

https://github.com/GenericMappingTools/pygmt/blob/89021cdb1bfea805780612e52ced974e1afdc216/doc/install.md?plain=1#L218-L221

> 3\. Some packages like GeoPandas/Shapely/PyArrow, are not directly used in PyGMT, but it's good to let users know that PyGMT supports them.

Maybe we could add a section under the [Technical References](https://www.pygmt.org/v0.13.0/techref/index.html) page or somewhere else to mention these integrations? Some of these are hiding in old issues:

- Geopandas - https://github.com/GenericMappingTools/pygmt/issues/608
- PyArrow - https://github.com/GenericMappingTools/pygmt/issues/2800
- ObsPy (unimplemented) - https://github.com/GenericMappingTools/pygmt/issues/967

Examples of others around the Scientific Python Ecosystem:

- 1 sentence for each optional dependency
  - https://docs.xarray.dev/en/v2024.09.0/ecosystem.html#xarray-related-projects (one sentence for each dependency)
- A paragraph for each optional dependency:
  - https://pandas.pydata.org/community/ecosystem.html
  - https://geopandas.org/en/v1.0.0/community/ecosystem.html#optional-dependencies (a paragraph for each dependency)
