### ISSUE TITLE
Improve the "GMT Map Projections" table

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#3405]
Here are some issues and potential improvements for the ["GMT Map Projections" table](https://github.com/GenericMappingTools/pygmt/blob/main/doc/techref/projections.md):

1. Projection code `A` (the first row) is incorrectly linked to code `E`
2. Currently, the link to the documentation is written like:
```
{doc}`Albers conic equal area </projections/conic/conic_albers>`
```
It can be simplified to 
```
{doc}`/projections/conic/conic_albers`
```
In this short version, the documentation title (`Albers Conic Equal Area`) will be displayed, so we don't have to maintain the projection name in two places (I think the only exception if the Cartesian projection).

3. If we decide to use the short links as proposed in point 2, then we need to make sure the title of each projection example is suitable. Currently, we still have some inconsistencies, for example, the projection code `E` has a name "Azimuthal gnomonic" in the table but the example title is "Gnomonic".
4. It would be better to use consistent title cases. Currently, we use mixed title cases. For example, "Albers Conic Equal Area" vs "Equidistant conic".

@yvonnefroehlich Are you OK with working on this issue?

**Comment by yvonnefroehlich** [comment]
The points 3. and 4. are probably also relevant for the upstream [GMT documentation](https://docs.generic-mapping-tools.org/dev/reference/map-projections.html).
