### ISSUE TITLE
Gallery example / tutorial: Show how to plot OSMnx related `MultiDiGraph` objects within PyGMT Figure instance

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#3430]
Following this [GMT Forum post](https://forum.generic-mapping-tools.org/t/adding-osmnx-plot-to-pygmt-figure/5203) I am wondering if it makes sense to add an example / a tutorial showing that [OSMnx](https://github.com/gboeing/osmnx) related `MultiDiGraph` objects can be plotted into a PyGMT Figure instance after converting them to a geopandas `GeoDataFrame` or a tuple of `GeoDataFrames` (https://forum.generic-mapping-tools.org/t/adding-osmnx-plot-to-pygmt-figure/5203/3?u=yvonnefroehlich).

Partly related to  issue #1374.

**Comment by seisman** [comment]
I don't think we should add this gallery example. Users who read the PyGMT documentation carefully should already know that PyGMT supports objects like DataFrame and GeoDataFrame. What they should do is find out whether their Python objects can be converted to DataFrame/GeoDataFrame.

**Comment by michaelgrund** [comment]
Agree with @seisman. If it's possible to tackle a problem by using geopandas before using PyGMT, this should be the way users should go. In my opinion it's not efficient to support several other raw-data sources especially regarding maintenance from the PyGMT side.

**Comment by yvonnefroehlich** [comment]
Based on this feedback I am thinking we are not doing this gallery example / tutorial I am closing this issue as not planned.
