### ISSUE TITLE
DOC/projections: Consistent design of examples

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#3458]
While working on PR #3451 I was wondering whether we should use a consistent design for all projection examples, especially the identical colors for land and water masses. I feel generating all examples in the same design looks better and more professional.

| Current version | Suggested update 01 (one design for all examples) | Suggested update 02 (one design per category) |
| --- | --- | --- |
| ![projections_colored](https://github.com/user-attachments/assets/0f1cbb87-81cc-439b-ba8d-17d899fe94e7) | ![projections_gray](https://github.com/user-attachments/assets/b7791cf7-1810-4391-8351-9597d0d2f63f) | ![projections_color_per_category](https://github.com/user-attachments/assets/a7c7b025-b950-4caa-804f-04f597fc69d9) |

**Comment by seisman** [comment]
In the GMT 4 cookbook (https://www.soest.hawaii.edu/gmt/gmt/html/GMT_Docs.html#x1-990006), most projection examples are in white and black/gray. I guess Paul and others updated these examples to make them more eye-catching and also demonstrate how to specify colors by different ways in GMT.

I prefer to keep these examples unchanged, but let's hear from other people's thoughts.

**Comment by yvonnefroehlich** [comment]
Interesting (I started with GMT 5.x). Maybe having one color per category is a compromise here?

**Comment by seisman** [comment]
> Maybe having one color per category is a compromise here?

Not bad.

**Comment by yvonnefroehlich** [comment]
Ping at the other @GenericMappingTools/pygmt-maintainers for their thoughts🙂.

**Comment by weiji14** [comment]
Yep, I'm ok with one color per category too (but not that yellow-ish palette please).
