### ISSUE TITLE
 pygmt does not run due to error loading library

### ISSUE THREAD

**Issue by thovdl** [GenericMappingTools/pygmt#353]
**Description of the problem**

pygmt does not run due to error loading the library gmt_w64.dll.
There is no file gmt_w64.dll.
I have tried making Python refer to gmt.dll, which is available, but this was unsuccessful.

**Full code that generated the error**

```python
import pygmt
```

**Full error message**

```
GMTCLibNotFoundError: Error loading the GMT shared library 'gmt_w64.dll':
[WinError 126] The specified module could not be found
```

**System information**

* Operating system: Windows10 64 bit
* Python installation (Anaconda, system, ETS): miniconda
* Version of GMT: gmt=6.0.0rc*
* Version of Python: Python 3.7
* Version of this package: unknown
* If using conda, paste the output of `conda list` below:

<details>
<summary>output of conda list</summary>
<pre>
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0
affine                    2.3.0                      py_0
alabaster                 0.7.12                   py37_0
anaconda                  custom                   py37_1
anaconda-client           1.7.2                    py37_0
anaconda-project          0.8.4                      py_0
appdirs                   1.4.3                    pypi_0    pypi
asn1crypto                1.2.0                    py37_0
astroid                   2.3.2                    py37_0
astropy                   3.2.2            py37he774522_0
atomicwrites              1.3.0                    py37_1
attrs                     19.3.0                     py_0
babel                     2.7.0                      py_0
backcall                  0.1.0                    py37_0
backports                 1.0                        py_2
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
basemap                   1.2.0            py37hd3253e1_3    conda-forge
beautifulsoup4            4.8.1                    py37_0
bitarray                  1.0.1            py37he774522_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blosc                     1.16.3               h7bd577a_0
bokeh                     1.3.4                    py37_0
boto                      2.49.0                   py37_0
bottleneck                1.2.1            py37h452e1ab_1
bs4                       0.0.1                    pypi_0    pypi
bzip2                     1.0.8                he774522_0
ca-certificates           2019.10.16                    0
certifi                   2019.9.11                py37_0
cffi                      1.13.0           py37h7a1dbc1_0
cftime                    1.0.3.4         py37h8c2d366_1001
chardet                   3.0.4                 py37_1003
click                     7.0                      py37_0
click-plugins             1.1.1                      py_0
cligj                     0.5.0                    py37_0
cloudpickle               1.2.2                      py_0
clyent                    1.2.2                    py37_1
colorama                  0.4.1                    py37_0
comtypes                  1.1.7                    py37_0
console_shortcut          0.1.1                         3
contextlib2               0.6.0                      py_0
cryptography              2.8              py37h7a1dbc1_0
cssselect                 1.1.0                    pypi_0    pypi
curl                      7.65.3               h2a8f88b_0
cycler                    0.10.0                   py37_0
cython                    0.29.13          py37ha925a31_0
cytoolz                   0.10.0           py37he774522_0
dask                      2.6.0                      py_0
dask-core                 2.6.0                      py_0
decorator                 4.4.0                    py37_1
defusedxml                0.6.0                      py_0
descartes                 1.1.0                      py_3
distributed               2.6.0                      py_0
docutils                  0.15.2                   py37_0
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                    py37_0
expat                     2.2.5                he025d50_0
fake-useragent            0.1.11                   pypi_0    pypi
fastcache                 1.1.0            py37he774522_0
fastscapelib              0.1.3             h1ad3211_1000    conda-forge
fastscapelib-python       0.1.3           py37h830ac7b_1000    conda-forge
filelock                  3.0.12                     py_0
fiona                     1.8.4            py37h22081e2_0
flask                     1.1.1                      py_0
freetype                  2.9.1                ha9979f8_1
freexl                    1.0.5                hfa6e2cd_0
fsspec                    0.5.2                      py_0
gdal                      2.3.3            py37hdf43c64_0
geopandas                 0.4.1                      py_0
geos                      3.7.1                h33f27b4_0
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.4.0            py37he774522_0
glob2                     0.7                        py_0
greenlet                  0.4.15           py37hfa6e2cd_0
h5py                      2.9.0            py37h5e291fa_0
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.1                      py_0
html5lib                  1.0.1                    py37_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imageio                   2.6.1                    py37_0
imagesize                 1.1.0                    py37_0
importlib_metadata        0.23                     py37_0
intel-openmp              2019.4                      245
ipykernel                 5.1.2            py37h39e3cac_0
ipython                   7.8.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
isort                     4.3.21                   py37_0
itsdangerous              1.1.0                    py37_0
jdcal                     1.4.1                      py_0
jedi                      0.15.1                   py37_0
jinja2                    2.10.3                     py_0
joblib                    0.13.2                   py37_0
jpeg                      9b                   hb83a4c4_2
json5                     0.8.5                      py_0
jsonschema                3.1.1                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.6.0                    py37_0
jupyterlab                1.1.4              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0
kealib                    1.4.7                h07cbb95_6
keyring                   18.0.0                   py37_0
kiwisolver                1.1.0            py37ha925a31_0
krb5                      1.16.1               hc04afaa_7
lazy-object-proxy         1.4.2            py37he774522_0
libarchive                3.3.3                h0643e63_5
libboost                  1.67.0               hd9e427e_4
libcurl                   7.65.3               h2a8f88b_0
libgdal                   2.3.3                h10f50ba_0
libiconv                  1.15                 h1df5818_7
libkml                    1.3.0                he5f2a48_4
liblief                   0.9.0                ha925a31_2
libnetcdf                 4.6.1                h411e497_2
libpng                    1.6.37               h2a8f88b_0
libpq                     11.2                 h3235a2c_0
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.8.5                h6538335_2
libspatialite             4.3.0a              hc36aec2_19
libssh2                   1.8.2                h7a1dbc1_0
libtiff                   4.0.10               hb898794_2
libxml2                   2.9.9                h464c3ec_0
libxslt                   1.1.33               h579f668_0
llvmlite                  0.30.0           py37ha925a31_0
locket                    0.2.0                    py37_1
lxml                      4.4.1            py37h1350720_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mapclassify               2.0.1                      py_0
markupsafe                1.1.1            py37he774522_0
matplotlib                3.1.0            py37hc8f65d3_0
matplotlib-base           3.1.1            py37h2852a4a_1    conda-forge
mccabe                    0.6.1                    py37_1
menuinst                  1.4.16           py37he774522_0
mistune                   0.8.4            py37he774522_0
mkl                       2019.4                      245
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.14           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
mock                      3.0.5                    py37_0
more-itertools            7.2.0                    py37_0
mpmath                    1.1.0                    py37_0
msgpack-python            0.6.1            py37h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py37_0
munch                     2.3.2                    py37_0
nbconvert                 5.6.0                    py37_1
nbformat                  4.4.0                    py37_0
netcdf4                   1.4.2            py37h812ae01_0
networkx                  2.4                        py_0
nltk                      3.4.5                    py37_0
nose                      1.3.7                    py37_2
notebook                  6.0.1                    py37_0
numba                     0.46.0           py37hf9181ef_0
numexpr                   2.7.0            py37hdce8814_0
numpy                     1.16.5           py37h19fb1c0_0
numpy-base                1.16.5           py37hc3f5095_0
numpydoc                  0.9.1                      py_0
olefile                   0.46                     py37_0
openpyxl                  3.0.0                      py_0
openssl                   1.1.1d               he774522_3
packaging                 19.2                       py_0
pandas                    0.25.2           py37ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parse                     1.12.1                   pypi_0    pypi
parso                     0.5.1                      py_0
partd                     1.0.0                      py_0
path.py                   12.0.1                     py_0
pathlib2                  2.3.5                    py37_0
patsy                     0.5.1                    py37_0
pcre                      8.43                 ha925a31_0
pep8                      1.7.1                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    6.2.0            py37hdc69c19_0
pip                       19.3.1                   py37_0
pkginfo                   1.5.0.1                  py37_0
pluggy                    0.13.0                   py37_0
ply                       3.11                     py37_0
powershell_shortcut       0.0.1                         2
proj4                     5.2.0                ha925a31_1
prometheus_client         0.7.1                      py_0
prompt_toolkit            2.0.10                     py_0
psutil                    5.6.3            py37he774522_0
psycopg2                  2.8.3            py37h7a1dbc1_0
py                        1.8.0                    py37_0
py-lief                   0.9.0            py37ha925a31_2
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.19                     py37_0
pycrypto                  2.6.1            py37hfa6e2cd_9
pycurl                    7.43.0.3         py37h7a1dbc1_0
pyee                      6.0.0                    pypi_0    pypi
pyflakes                  2.1.1                    py37_0
pygments                  2.4.2                      py_0
pygmt                     0.0.1a0+49.g882dbba          pypi_0    pypi
pylint                    2.4.3                    py37_0
pyodbc                    4.0.27           py37ha925a31_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.4.2                      py_0
pyppeteer                 0.0.25                   pypi_0    pypi
pyproj                    1.9.6            py37h6782396_0
pyqt                      5.9.2            py37h6538335_2
pyquery                   1.4.0                    pypi_0    pypi
pyreadline                2.1                      py37_1
pyrsistent                0.15.4           py37he774522_0
pyshp                     2.1.0                      py_0
pysocks                   1.7.1                    py37_0
pytables                  3.5.2            py37h1da0976_1
pytest                    5.2.1                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.5.0                    py37_0
pytest-doctestplus        0.4.0                      py_0
pytest-openfiles          0.4.0                      py_0
pytest-remotedata         0.3.2                    py37_0
python                    3.7.4                h5263a28_0
python-dateutil           2.8.0                    py37_0
python-libarchive-c       2.8                     py37_13
pytz                      2019.3                     py_0
pywavelets                1.1.1            py37he774522_0
pywin32                   223              py37hfa6e2cd_1
pywinpty                  0.5.5                 py37_1000
pyyaml                    5.1.2            py37he774522_0
pyzmq                     18.1.0           py37ha925a31_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.6.0                      py_0
qtconsole                 4.5.5                      py_0
qtpy                      1.9.0                      py_0
rasterio                  1.0.21           py37h6bd7d87_0
requests                  2.22.0                   py37_0
requests-html             0.10.0                   pypi_0    pypi
rope                      0.14.0                     py_0
rtree                     0.8.3                    py37_0
ruamel_yaml               0.15.46          py37hfa6e2cd_0
scikit-image              0.15.0           py37ha925a31_0
scikit-learn              0.21.3           py37h6288b17_0
scipy                     1.3.1            py37h29ff71c_0
seaborn                   0.9.0                    py37_0
selenium                  3.141.0          py37he774522_0
send2trash                1.5.0                    py37_0
setuptools                41.4.0                   py37_0
shapely                   1.7a2                    pypi_0    pypi
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h6538335_0
six                       1.12.0                   py37_0
snappy                    1.1.7                h777316e_3
snowballstemmer           2.0.0                      py_0
snuggs                    1.4.7                      py_0
sortedcollections         1.1.2                    py37_0
sortedcontainers          2.1.0                    py37_0
soupsieve                 1.9.3                    py37_0
sphinx                    2.2.0                      py_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.1                      py_0
sphinxcontrib-devhelp     1.0.1                      py_0
sphinxcontrib-htmlhelp    1.0.2                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.2                      py_0
sphinxcontrib-serializinghtml 1.1.3                      py_0
sphinxcontrib-websupport  1.1.2                      py_0
spyder                    3.3.6                    py37_0
spyder-kernels            0.5.2                    py37_0
sqlalchemy                1.3.10           py37he774522_0
sqlite                    3.30.1               he774522_0
statsmodels               0.10.1           py37h8c2d366_0
sympy                     1.4                      py37_0
tblib                     1.4.0                      py_0
terminado                 0.8.2                    py37_0
testpath                  0.4.2                    py37_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.10.0                     py_0
tornado                   6.0.3            py37he774522_0
tqdm                      4.36.1                     py_0
traitlets                 4.3.3                    py37_0
unicodecsv                0.14.1                   py37_0
urllib3                   1.24.2                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
w3lib                     1.21.0                   pypi_0    pypi
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
websockets                8.0.2                    pypi_0    pypi
werkzeug                  0.16.0                     py_0
wheel                     0.33.6                   py37_0
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0                    py37_0
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py37he774522_0
xarray                    0.12.3                   pypi_0    pypi
xerces-c                  3.2.2                ha925a31_0
xlrd                      1.2.0                    py37_0
xlsxwriter                1.2.2                      py_0
xlwings                   0.16.0                   py37_0
xlwt                      1.3.0                    py37_0
xtensor                   0.18.3            h1ad3211_1000    conda-forge
xtl                       0.4.16            h1ad3211_1000    conda-forge
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.1                h33f27b4_3
zict                      1.0.0                      py_0
zipp                      0.6.0                      py_0
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0
</pre>
</details>

**Comment by seisman** [comment]
How did you install GMT on Windows? Did you use the Windows installer (i.e. gmt-6.0.0rc5-w64.exe)? 

You should find a GMT library file in GMT's bin directory. What's the name of the GMT library? `gmt.dll`, `gmt_w64.dll` or any others?

Did you set the environmental variable `GMT_LIBRARY_PATH` to your GMT library, e.g. `C:/programs/gmt6/bin` or `C:/programs/gmt6/lib`?

**Comment by seisman** [comment]
> I used "conda create --name pyGMT python=3.7 pip numpy pandas xarray packaging gmt=6.0.0rc*"

Did you follow the [install instruction](https://www.pygmt.org/dev/install.html#installing-gmt-and-other-dependencies)? I expect to see `gmt` in your output of `conda list`.

> In my bin directory there was a gmt.dll, none others

What's the bin path of your GMT's bin directory? Is it `C:\programs\gmt6\bin`?

**Comment by thovdl** [comment]
I did follow the install instruction

Conda installed GMT with the packages in C:\Users\myname\AppData\Local\Continuum\miniconda3\pkgs\GMT

**Comment by leouieda** [comment]
Hi @thovdl we've actually been struggling with Windows and never got around to fixing #313. We should have a new release in the next couple of days and will try to revisit that. Right now, PyGMT really doesn't work on Windows. Sorry for the inconvenience.

**Comment by weiji14** [comment]
Closed with #434, until we release pygmt v0.1.1 or v0.2.0, please follow workaround at #431 to set `GMT_LIBRARY_PATH` and `GMT_SHAREDIR`.

**Comment by saeedghanbarifar** [comment]
how can i fix this Error loading the GMT shared library 'gmt.dll, gmt_w64.dll, gmt_w32.dll': in pygmt runing?
Im new gmt and python user

**Comment by saeedghanbarifar** [comment]
do we nead installing of gmt.exe for running pygmt ?
i followed installing structure but i have many problem with that...:((((
fore example i downloaded GitHub package but when I execute examples file, its result  have many error.

**Comment by agusms** [comment]
Some body please help  me on projecting hypocenter  in line AA1, to be used on plotting cross-section seismicity.
I have try following pygmt gallery  but always unsuccesfull.  The following is py pygmt script, and the resuting figure.

import pygmt
import pandas as pd
data=pd.read_csv("G:/LAT_JUPYTER/PyGMT/sumatra_eq.csv")
fig = pygmt.Figure()
fig.basemap(region=[94, 108, -7, 7], projection="M8i", frame="a2g")
fig.coast(shorelines="1.5p,black")

fig.plot(
    x=data.longitude,
    y=data.latitude,
    size=0.15*data.magnitude,
    style="cc",
    color="red",
    pen="black")

fig.plot(x=[96,103],y=[-3,2],pen="2p,black")
fig.text(text="A", x=95.5, y=-3, font="24p,Helvetica-Bold,black")
fig.text(text="A1", x=103.2, y=2.5, font="24p,Helvetica-Bold,black")

#pygmt.project(output="cross.dat",
#    x=data.longitude,
#    y=data.latitude,
#    z=data.depth,
#    center=["-C96/-3"],
#    endpoint=["-E103/2"],
#    width="-W-100/100")

fig.show()
fig.savefig("G:/LAT_JUPYTER/PyGMT/sumatra.pdf")

[sumatra.pdf](https://github.com/GenericMappingTools/pygmt/files/7618213/sumatra.pdf)

**Comment by agusms** [comment]
Some body please help me using pygmt,  projecting hypocenter to A-A1 line  and to plot the cross-section along A-A1.
The following is my pygmt script  and the resulting figure.
Thank...
import pygmt
import pandas as pd
data=pd.read_csv("G:/LAT_JUPYTER/PyGMT/sumatra_eq.csv")
fig = pygmt.Figure()
fig.basemap(region=[94, 108, -7, 7], projection="M8i", frame="a2g")
fig.coast(shorelines="1.5p,black")

fig.plot(
    x=data.longitude,
    y=data.latitude,
    size=0.15*data.magnitude,
    style="cc",
    color="red",
    pen="black")

fig.plot(x=[96,103],y=[-3,2],pen="2p,black")
fig.text(text="A", x=95.5, y=-3, font="24p,Helvetica-Bold,black")
fig.text(text="A1", x=103.2, y=2.5, font="24p,Helvetica-Bold,black")

pygmt.project(output="cross.dat",
    x=data.longitude,
    y=data.latitude,
    z=data.depth,
    center=["-C96/-3"],
    endpoint=["-E103/2"],
    width="-W-100/100")

fig.show()
fig.savefig("G:/LAT_JUPYTER/PyGMT/sumatra.pdf")

[sumatra.pdf](https://github.com/GenericMappingTools/pygmt/files/7618238/sumatra.pdf)

**Comment by leouieda** [comment]
👋🏽 Hi @agusms please post questions on the GMT forum instead: https://forum.generic-mapping-tools.org/

**Comment by agusms** [comment]
Thanks Dr. Leo..

**Comment by muyeqingfeng** [comment]
When I try to import pygmt using pycharm, there are the above problems. But using CONDA runs smoothly.
