### ISSUE TITLE
PyGMT website: Drop-down menu for selection version disappears for selection "dev"

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#3542]
I just found that the drop-down menu for selecting the version on the PyGMT website disappears when having "dev" selected. I think this is somehow new and is still not the case for the GMT website (https://docs.generic-mapping-tools.org/dev/index.html).

| [<= v0.13.0](https://www.pygmt.org/v0.13.0/index.html) | [latest](https://www.pygmt.org/latest/index.html) | [dev](https://www.pygmt.org/dev/index.html) |
| --- | --- | --- |
| ![website_pygmt_select_version_v0130](https://github.com/user-attachments/assets/26664df6-109f-4a5c-aed1-cfd7407dac23) | ![website_pygmt_select_version_LATEST](https://github.com/user-attachments/assets/8848af59-eec8-45a5-8c9e-3eb847a33455) | ![website_pygmt_select_version_DEV](https://github.com/user-attachments/assets/63433a02-896c-4c88-a75c-35d77f41bf01) |

**Comment by seisman** [comment]
It's likely because breaking changes in sphinx_rtd_theme v3.x (https://github.com/readthedocs/sphinx_rtd_theme/tags).

**Comment by yvonnefroehlich** [comment]
Maybe this iusse is related by the newly introduced `version_selector ` (  and https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-version_selector).

**Comment by yvonnefroehlich** [comment]
> We probably should pin sphinx_rtd_theme to 2.x temporarily and wait to see if there are any upstream changes (xref: [readthedocs/sphinx_rtd_theme#1624](https://github.com/readthedocs/sphinx_rtd_theme/issues/1624)).

I did not see this issue yet. Thanks for pointing it out! This looks like that there are some issues with this newly added `version_selector`. So trying to pin `sphinx_rtd_theme` makes sense to me. We can still make changes to the config file.

**Comment by seisman** [comment]
reopen so that we can better track possible upstream changes.
