### ISSUE TITLE
Another solution to "Error loading GMT shared library at …" using $DYLD_LIBRARY_PATH environmental variable

### ISSUE THREAD

**Issue by seanricardoford** [GenericMappingTools/pygmt#3569]
### Description of the problem

In the ["Error loading GMT shared library at …"](https://www.pygmt.org/latest/install.html#error-loading-gmt-shared-library-at) subsection of the [Install](https://www.pygmt.org/latest/install.html#installing) section of the user documentation, suggest adding another solution to the error:

For Linux/macOS, try adding the following line or lines to your shell configuration file (usually ~/.bashrc for Bash on Linux and ~/.zshrc for Zsh on macOS):

`export GMT_LIBRARY_PATH=$HOME/miniforge3/envs/pygmt/lib`

or

`export LD_LIBRARY_PATH=$GMTHOME/lib:$LD_LIBRARY_PATH`  
`export DYLD_LIBRARY_PATH=$GMTHOME/lib:$DYLD_LIBRARY_PATH`

### System information

```bash
PyGMT information:
  version: v0.13.0
System information:
  python: 3.12.6 (v3.12.6:a4a2d2b0d85, Sep  6 2024, 16:08:03) [Clang 13.0.0 (clang-1300.0.29.30)]
  executable: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
  machine: macOS-14.7.1-arm64-arm-64bit
Dependency information:
  numpy: 2.1.1
  pandas: 2.2.3
  xarray: 2024.9.0
  netCDF4: 1.7.1.post2
  packaging: 24.1
  contextily: None
  geopandas: None
  IPython: 8.23.0
  rioxarray: None
  gdal: None
  ghostscript: 10.02.1
GMT library information:
  version: 6.5.0
  padding: 2
  share dir: /Applications/GMT-6.5.0.app/Contents/Resources/share
  plugin dir: /Applications/GMT-6.5.0.app/Contents/Resources/lib/gmt/plugins
  library path: /Applications/GMT-6.5.0.app/Contents/Resources/lib/libgmt.dylib
  cores: 24
  grid layout: rows
  image layout: 
  binary version: 6.5.0
```

**Comment by seisman** [comment]
Thanks for providing this solution. Changing `LD_LIBRARY_PATH` (on Linux) or `DYLD_LIBRARY_PATH` (on macOS) definitely works, but it sometimes may cause system-wide conflicts,  especially if other libraries/software depend on them. So, I still prefer the `GMT_LIBRARY_PATH` solution which can make things safer and more isolated.
