### ISSUE TITLE
Extend the CI jobs in the "GMT Tests" workflow

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#3615]
Currently, in the "GMT Tests" workflow, we have 7 CI jobs:

- Python 3.10 + core packages (pinned to minimum versions) [Linux/macOS/Windows]
- Python 3.12 + core packages (pinned to maximum versions) + optional packages [Linux/macOS/Windows]
- Python 3.11 + core packages (pinned to specific versions) + a few optional packages [Linux only, mainly for testing old versions of optional packages]

As you can see, the CI jobs can't guarantee that PyGMT works with Python 3.10 + optional packages.

What about extending the number of the CI jobs to 9:

- Python 3.10 + core packages (pinned to minimum versions) + optional packages (pinned to the minimum supported version if any, related to #3456) [Linux/macOS/Windows]
- Python 3.12 + core packages (pinned to maximum versions) + optional packages [Linux/macOS/Windows]
- Python 3.11 + core packages [Linux/macOS/Windows]

**Comment by weiji14** [comment]
> * Python 3.10 + core packages (pinned to minimum versions) + optional packages (pinned to the minimum supported version if any, related to

I've been wanting to create a matrix build using something like `uv`'s [`--resolution lowest` flag](https://docs.astral.sh/uv/concepts/resolution/#resolution-strategy) that will install the lowest possible version for all dependencies, both direct and indirect (transitive), or `--resolution lowest-direct` that will use the lowest compatible versions for all direct dependencies, while using the latest compatible versions for all other dependencies.

The main complication is that we have non-PyPI dependencies - GMT. We _could_ set up a build such that GMT is pulled from conda-forge, and the rest are installed via `uv`, but that might need to be in a separate file to `ci_tests.yaml`.

**Comment by seisman** [comment]
Maybe we can try [pixi](https://pixi.sh/), which can install packages from both conda-forge and PyPI (using `uv`). 

Some related posts: 

- https://prefix.dev/blog/pixi_a_fast_conda_alternative
- https://prefix.dev/blog/uv_in_pixi

**Comment by weiji14** [comment]
Yes, I thought about `pixi`, but it doesn't support a mode similar to uv's `--lowest resolution` yet. I've tried searching the issues but couldn't find it documented anywhere, though there is some work on integrating `uv` as the PyPI resolver in `pixi` at https://github.com/prefix-dev/pixi/issues/1295.
