### ISSUE TITLE
Update to GMT 6.0.0

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#362]
GMT 6.0.0 is released, and the conda-forge package has been updated to 6.0.0. 

Install GMT6 via conda is much easier now, and the `conda-forge/label/dev` channel is no longer needed.
```
conda install gmt -c conda-forge
```

We should update the minimum required GMT version to 6.0.0, installation instructions, and also the CI settings.

**Comment by weiji14** [comment]
I'll get on to it.
