### ISSUE TITLE
Transparency of colormap does not apply to color-coding for using `Figure.grdimage`

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#3629]
### Description of the problem

It's possible to add transparency directly to a colormap while creating it via `pygmt.makecpt`.

When using this colormap for plotting data points with color-coding via `Figure.plot`, this transparency is considered, but when plotting a grid with color-coding via `Figure.grdimage` it is ignored. A workaround is specifying the `transparency` parameter (with the same value) again for `Figure.grdimage`.

| (I) data points (pandas.DataFrame) via `Figure.plot`| (II) grid (Xarray.DataArray) via `Figure.grdimage` |
| --- | --- |
| ![cmap_transp_datapoints](https://github.com/user-attachments/assets/40940cc5-d6d6-4bc2-bfce-9b01a5c75211) | ![cmap_transp_grid](https://github.com/user-attachments/assets/612e7c78-beb3-48e0-a85c-da1285a1db94) |

### Minimal Complete Verifiable Example

```python
# (I) Plotting data points with color-coding
import pygmt

df = pygmt.datasets.load_sample_data(name="japan_quakes")

fig = pygmt.Figure()
fig.basemap(region=[135, 150, 35, 50], projection="M10c", frame=True)

pygmt.makecpt(cmap="viridis", series=[0, 600], transparency=50)
fig.plot(
    x=df.longitude,
    y=df.latitude,
    size=[0.5] * len(df),
    fill=df.depth_km,
    cmap=True,
    style="cc",
)
fig.colorbar(frame=True)

fig.show()

# -----------------------------------------------------------------
# (II) Plotting a grid with color-coding
import pygmt

grid = pygmt.datasets.load_earth_relief()

fig = pygmt.Figure()
fig.basemap(region=[-10, 10, -10, 10], projection="M10c", frame=True)

pygmt.makecpt(cmap="oleron", series=[-1000, 500], transparency=50)
fig.grdimage(grid=grid, cmap=True)
fig.colorbar(frame=True)

fig.show()
```

### Full error message

```python-traceback
Not applicable.
```

### System information

```bash
import pygmt; pygmt.show_versions()
PyGMT information:
  version: v0.13.0
System information:
  python: 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)]
  executable: C:\ProgramData\Anaconda3\envs\pygmt_env_dev_650\python.exe
  machine: Windows-10-10.0.19045-SP0
Dependency information:
  numpy: 1.26.4
  pandas: 2.2.2
  xarray: 2024.3.0
  netCDF4: 1.6.5
  packaging: 24.0
  contextily: 1.6.0
  geopandas: 0.14.3
  IPython: 8.22.2
  rioxarray: 0.15.4
  gdal: 3.8.2
  ghostscript: 10.03.0
GMT library information:
  version: 6.5.0
  padding: 2
  share dir: C:/Program Files (x86)/gmt6/share
  plugin dir: C:/ProgramData/Anaconda3/envs/pygmt_env_dev_650/Library/bin/gmt_plugins
  library path: C:/ProgramData/Anaconda3/envs/pygmt_env_dev_650/Library/bin/gmt.dll
  cores: 4
  grid layout: rows
  image layout: 
  binary version: 6.5.0
```

**Comment by seisman** [comment]
@joa-quim I have the impression that CPT with transparency doesn't work for `grdimage` due to technical difficulties. Is it correct?

**Comment by joa-quim** [comment]
I guess not. Since images do not support transparency in PostScript, it would need to receive the same patch work that is done with the alpha layer and true transparency. And that consists in creating square for each pixel and fill it with the image color, plus the transparency. In other words, making an image out a figure like the left one above but with squares that filled the entire plotting area.

Now that you bring this, I may be not that far to be able to do it in GMT.jl with my work on 3D meshes (but don't have transparency there yet).

**Comment by seisman** [comment]
> And that consists in creating square for each pixel and fill it with the image color, plus the transparency. In other words, making an image out a figure like the left one above but with squares that filled the entire plotting area.

It sounds complicated and maybe slow. 

@yvonnefroehlich I think it's a missing upstream feature and unlikely it will be implemented soon in the future. I guess we can close this?

**Comment by joa-quim** [comment]
Yes, slow and huge PS files as for each pixel we need the coordinates of their four corners + color + transparency.
The current alternative is to something like what is done in the `transp_mix.sh` test

**Comment by yvonnefroehlich** [comment]
> > And that consists in creating square for each pixel and fill it with the image color, plus the transparency. In other words, making an image out a figure like the left one above but with squares that filled the entire plotting area.
> 
> It sounds complicated and maybe slow.
> 
> @yvonnefroehlich I think it's a missing upstream feature and unlikely it will be implemented soon in the future. I guess we can close this?

Thanks @joa-quim for looking at this issue! As this seem to be complicated, an upstream issue, and specifying the same transparency value within `Figure.grdimage` is a simple workaround, I closing this issue is fine with me.
