### ISSUE TITLE
Short- and long-form kwargs can coexist silently

### ISSUE THREAD

**Issue by liamtoney** [GenericMappingTools/pygmt#377]
**Description of the problem**

Python doesn't allow keyword arguments to be repeated. Our current setup _does_ allow for e.g. the following, however:
```python
import pygmt
fig = pygmt.Figure()
fig.basemap(region=[0, 1, 0, 1], B='+tbar', frame='+tfoo')
fig.show(method='external')
```
This example produces

![ex](https://user-images.githubusercontent.com/38269494/68518447-83bf5500-0238-11ea-9247-95e3a5295c07.png)

silently overriding the `B='+tbar'` "repeated" argument. I feel like we should raise a `SyntaxError` in this case, like what Python does for repeated kwargs. I think this would involve modifying the `use_alias()` decorator, but I'm not totally sure. This addresses the discussion in https://github.com/GenericMappingTools/pygmt/pull/359#discussion_r343539273. If #262 were implemented, this could be a non-issue.

(I'm not sure if this is a bug or a feature request; I chose bug.)

**Comment by weiji14** [comment]
Let's mark it down as a bug :laughing: Hopefully our users spot this.
