### ISSUE TITLE
fig.legend() method ignores fill color option

### ISSUE THREAD

**Issue by firstkingofrome** [GenericMappingTools/pygmt#396]
Hello, when I try and make a legend using the fig.legend() option the fill color is ignored (I attached a simple script below that causes the problem, given that I specify F="+gred" I expect that background of the legend to be filled with red, however no fill is applied).

Thank You for helping me to resolve this issue!

import pygmt as gmt
REGION = "0/100/0/40"
SCALE = "7.5i/-5i"
buildingLocations = {"Location54":(12.000,50.000),"Location17":(18.000,52.000)}

fig = gmt.Figure()
#fig.grdimage(grid="temp.grd",R=REGION,frame=True)
fig.plot(x=buildingLocations["Location54"][1],y=buildingLocations["Location54"][0],
         R=REGION,style="s0.5",color="yellow",pen="thin,black",label="Location54")

fig.plot(x=buildingLocations["Location17"][1],y=buildingLocations["Location17"][0],
         R=REGION,style="s0.5",color="white",pen="thin,black",label="Location17")

fig.legend(F="+gred",position="JTR+jTR+o0.2c", box=True)

fig.show()

**Comment by firstkingofrome** [comment]
I forgot to specify, I am using version '0.0.1a0+69.g320a728'

**Comment by seisman** [comment]
Argument `box` is the more readable alias of `-F` option in the command line. So your command is equivalent to command `gmt legend -F -F+gred`.

The code below should work.
```
fig.legend(position="JTR+jTR+o0.2c", box="+gred")
```

**Comment by firstkingofrome** [comment]
Thank You, that worked (I did not know about that syntax!)
