### ISSUE TITLE
Migrate Travis CI from Services to Github Apps

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#403]
**Description of the problem**

Some travis CI test statuses are not being reported back to GIthub (see https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798), basically because we're using the deprecated 'Services' integration:

![Deprecated Travis CI Service image](https://user-images.githubusercontent.com/23487320/77591531-03825d80-6f55-11ea-9db9-e777c3ab7def.png)

So we'll need to move to install the new [Github Apps integration](https://github.com/marketplace/travis-ci). Instructions can be found at https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/. Also should take a look at our `.travis.yml` which has some [deprecated keys](https://docs.travis-ci.com/user/build-config-validation/#deprecated_key).

**Comment by weiji14** [comment]
Oops, sorry @GenericMappingTools/python, if anyone received an email from Travis about installing something, just ignore it for now. I was trying to install things on travis.**com** when really we should be on travis.**org** :joy:

**Comment by weiji14** [comment]
Ok, there should be a new request to install the Travis CI GIthub App for PyGMT. If one of you can approve it, that would be great.

**Comment by seisman** [comment]
I still see travis-ci.com. Is it correct?
![image](https://user-images.githubusercontent.com/3974108/77600632-df843500-6ede-11ea-8408-2d3dbbd5e6dc.png)

**Comment by weiji14** [comment]
Yes, I think they're migrating everything to .com now. See https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com

**Comment by seisman** [comment]
Looks good. I think I approved a few minutes ago,

**Comment by weiji14** [comment]
Cool, I can see it under Settings -> Integrations & services now. Will try to trigger some builds and see how it goes.
