### ISSUE TITLE
Add PyGMT AGU 2019 poster to website

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#416]
**Description of the desired feature**

The [presentations on our website](https://www.pygmt.org/dev/overview.html#presentations) are slightly out of date, and we'll need someone to help add the [2019 AGU Poster](https://www.leouieda.com/posters/agu2019.html) to the page!

![PyGMT AGU 2019 poster](https://github.com/leouieda/website/raw/master/images/poster-agu2019.jpg)

We'll need [edit the overview page](https://github.com/GenericMappingTools/pygmt/edit/master/doc/overview.rst) to add the details of the new poster including:

- Poster title
- Authors
- Presented at 'Conference'
- DOI link

Next is to [upload a static figure](https://github.com/GenericMappingTools/pygmt/upload/master/doc/_static) of the poster, You can find the JPG file at https://github.com/leouieda/website/blob/master/images/poster-agu2019.jpg.

You can follow the format of the old examples, and be sure to give a shout out if you need help! Find out more about contributing in our [CONTRIBUTING.md](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md) docs. Once you create a pull request, we'll be able to preview any changes you made and guide you along :smile:

**Are you willing to help implement and maintain this feature?** Yes/No

**Comment by leouieda** [comment]
Thanks for this, @weiji14!
