### ISSUE TITLE
Release PyGMT 0.1.0

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#418]
**Release**: [v0.1.0](https://github.com/GenericMappingTools/pygmt/milestone/1)
**Scheduled Date**: 2020/05/03

**Before release**:
- [x] Reserve a DOI on [Zenodo](https://zenodo.org) (@leouieda @seisman)
- [x] Update Changelog (@weiji14 #420)
- [x] Update installation instructions from PyPI and conda-forge (@weiji14 #421)

**Release**:
- [x] Make a tag and push it to github
```
git tag x.x.x
git push --tags
```
- [x] Go to [GitHub Release](https://github.com/GenericMappingTools/pygmt/releases) and make a release (https://github.com/GenericMappingTools/pygmt/releases/tag/v0.1.0)
- [x] Announce release on the GMT [forum](https://forum.generic-mapping-tools.org/t/pygmt-v0-1-0-released/442/1) and [website](https://www.generic-mapping-tools.org) (News)

**After release**:
- [x] Create branch 0.x for bug-fixes if this is a minor release (i.e. create branch 0.1 after 0.1.0 is released)
- [ ] Commit changes to Github

**3rd party update**:
- [x] Update conda-forge [pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) (@moorepants https://github.com/conda-forge/staged-recipes/pull/11468)

---

- [ ] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by weiji14** [comment]
Team, feel free to edit the top post to add/edit stuff (and add your `@username` tag next to it if you'd like to work on it). I'll need help reserving a DOI on [Zenodo](https://zenodo.org) for instance.

**Comment by liamtoney** [comment]
I just noticed that [https://www.pygmt.org/](https://www.pygmt.org/) currently redirects to [https://www.pygmt.org/dev/](https://www.pygmt.org/dev/). Should that be the case, or should it be redirecting to [https://www.pygmt.org/latest/](https://www.pygmt.org/latest/) or [https://www.pygmt.org/v0.1.0/](https://www.pygmt.org/v0.1.0/)?

**Comment by seisman** [comment]
> I just noticed that https://www.pygmt.org/ currently redirects to https://www.pygmt.org/dev/. Should that be the case, or should it be redirecting to https://www.pygmt.org/latest/ or https://www.pygmt.org/v0.1.0/?

Nice catch. Addressed in #423.

**Comment by seisman** [comment]
> Update links on the GMT website (News, Download & Documentation)

Perhaps adding news is enough. I don't think we should update the download and documentation pages for PyGMT releases.

**Comment by weiji14** [comment]
Fair enough. I was going to wait for the `pygmt` conda package release before we announce it on the website though.

**Comment by seisman** [comment]
The conda recipe looks good. Are we waiting for approval from someone?

**Comment by moorepants** [comment]
> The conda recipe looks good. Are we waiting for approval from someone?

Yes, the conda forge core team.

**Comment by weiji14** [comment]
Cool, the conda-forge package is up at https://anaconda.org/conda-forge/pygmt, woohoo! Really appreciate all your effort @moorepants :raised_hands: !!

Currently only Linux/Windows packages with Python 3.6 and 3.7. I've just merged in https://github.com/conda-forge/pygmt-feedstock/pull/1 so Python 3.8 should be available shortly.

**Comment by seisman** [comment]
I added the news of PyGMT v0.1.0 release to the GMT main site (https://github.com/GenericMappingTools/website/pull/53), and created the 0.1 branch (https://github.com/GenericMappingTools/pygmt/tree/0.1) for further bug fixes. The 0.1 branch is protected like master branch.

**Comment by seisman** [comment]
> Commit changes to Github

I'm not sure what it means. I think we're done with the PyGMT v0.1.0 release. @weiji14 @leouieda

**Comment by weiji14** [comment]
Yep, thanks @seisman! I'll close this now. The next release will be tracked at https://github.com/GenericMappingTools/pygmt/milestone/2.

**Comment by moorepants** [comment]
Thanks everyone, we are now making pygmt available on the UC Davis cluster for various geography courses. They'll be excited!
