### ISSUE TITLE
Load .csv or .dat file in PyGMT 

### ISSUE THREAD

**Issue by zulfakriza** [GenericMappingTools/pygmt#426]
**Description of the problem**

Hi, 
I am a new user on PyGMT, before I used GMT 5 to create some map and plotting the EQ data.
But in PyGMT I had a bit issue when trying to load data (.csv or .dat) in my map.

Is there any clue how to load .csv or .dat data format in PyGMT? 

Thank you

**Full code that generated the error**

```python
PASTE CODE HERE
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system:
* Python installation (Anaconda, system, ETS):
* Version of GMT:
* Version of Python:
* Version of this package:
* If using conda, paste the output of `conda list` below:

<details>
<summary>output of conda list</summary>
<pre>
PASTE OUTPUT OF CONDA LIST HERE
</pre>
</details>

**Comment by weiji14** [comment]
Hi @zulfakriza,

For .csv files, you can follow the answer outlined at https://forum.generic-mapping-tools.org/t/how-to-load-data-into-pygmt/392, basically by using pandas. I actually made an example using earthquake data from GNS, New Zealand at https://github.com/GenericMappingTools/foss4g2019oceania/blob/master/2_pydata_and_pygmt.ipynb.

 As for .dat files, you might need to upload an example as it's quite a generic format. Is it a binary format, ASCII text format, or something else?

**Comment by zulfakriza** [comment]
Hi @weiji14 

Many thanks for your response, then for the .dat file, I mean ASCII text format 

Regards

**Comment by weiji14** [comment]
If it's just text, then [pandas.read_csv](https://pandas.pydata.org/docs/user_guide/io.html#csv-text-files) should work on that .dat file too. There's options to skip header lines, set column names, etc.

That said, some of the [Data Processing](https://www.pygmt.org/latest/api/index.html#data-processing) functions allow you to pass the filename into PyGMT directly. So it depends on what you want to do :smile:

**Comment by zulfakriza** [comment]
Hi @weiji14 

Thanks a lot, I will try it

Cheers
Zulfakriza

**Comment by seisman** [comment]
Closing the issue. Please post general questions on the [GMT Community Forum](https://forum.generic-mapping-tools.org/).
