### ISSUE TITLE
PyGMT sprints at SciPy 2020

### ISSUE THREAD

**Issue by liamtoney** [GenericMappingTools/pygmt#433]
[SciPy 2020](https://www.scipy2020.scipy.org/) is virtual this year. However, [remote sprints](https://www.scipy2020.scipy.org/sprints-schedule) are still taking place on July 11–12. What if we sign up for PyGMT sprints? I'm imagining we could do something simple and tangible, such as addressing #292. It would also be a cool way to expose more folks to PyGMT.

@GenericMappingTools/python-contributors what do you think? I'd be happy to start us off by filling out the [form](https://docs.google.com/forms/d/e/1FAIpQLSfGR2-d_YRNYJ8063JqBQfjumLJ6-sOf6N325JrnrHKeR5cTw/viewform). But I'll likely need help to prepare for this as well as assist during the sprints.

**Comment by weiji14** [comment]
That sounds awesome, go for it!

> @GenericMappingTools/python-contributors what do you think? I'd be happy to start us off by filling out the [form](https://docs.google.com/forms/d/e/1FAIpQLSfGR2-d_YRNYJ8063JqBQfjumLJ6-sOf6N325JrnrHKeR5cTw/viewform). But I'll likely need help to prepare for this as well as assist during the sprints.

If you need a 'guide' for filling the form, you can refer to my old abstract at https://2019.foss4g-oceania.org/community-day, or refer to #317. Happy to share any materials or lessons learnt from that previous workshop too.

**Comment by liamtoney** [comment]
Okay, I've filled out the form for this! I've emphasized contributions to the gallery / examples. I state that one of the goals is to introduce more folks to PyGMT.

**Comment by weiji14** [comment]
Hi @liamtoney, just checking in here to see if we need to prepare anything else beforehand? I can see that we're listed on the [Sprints Schedule](https://www.scipy2020.scipy.org/sprints-schedule).

Been thinking whether we should cut a v0.1.2 release to get the documentation up to scratch (e.g. https://github.com/GenericMappingTools/pygmt/issues/479#issuecomment-646327633) before the sprint. Also might be good to have a version that supports GMT 6.0.0 before we shift everything to GMT 6.1.0. We could set up a Zoom/Jitsi call to discuss other matters too.

**Comment by liamtoney** [comment]
Yeah, I saw that they added us. I don't see any super critical need to have the release ready prior to the sprint specifically, though releases are of course a good thing. :)

Zoom would be great. Could you flick me an email please? Rightmost icon on my [personal site](https://liam.earth/).

**Comment by weiji14** [comment]
Cool @liamtoney, as discussed during the meeting (minutes at https://forum.generic-mapping-tools.org/t/pygmt-community-meeting-jun-27-utc-19-30/589/2), we've added you to the @GenericMappingTools/python team and you'll be a moderator on the forum too! :tada: You can start labeling issues on Github and do all sorts of other stuff. We kinda wanted to have an induction guide as mentioned in #346 but haven't got around to it. If you feel something is weird (e.g. missing permissions), just give us a shout on that issue.

**Comment by seisman** [comment]
FYI, in b74bc3ef18ba7b3f3753ce8554f1dafbc14df9ba, I bumped the minimum required GMT version to 6.1.0. Some outdated baseline images are untouched, so there are still ~27 failures. These failures are currently ignored by marking them `@pytext.mark.xfail`. A few tests may crash on Windows, so I also disabled the Windows builds temporarily.

**Comment by weiji14** [comment]
A bit late to the game (timezones are tricky), but if there's anyone in the Asia Pacific timezone (or anywhere in the world really) looking at where to [start contributing to PyGMT](https://github.com/GenericMappingTools/pygmt/contribute), have look at our  issues labelled [scipy-sprint](https://github.com/GenericMappingTools/pygmt/issues?q=is%3Aissue+label%3Ascipy-sprint+), or come up with your own as @tjnewton is doing in #516!

Just a note that you're not forced to submit a PR. [Opening a feature request issue](https://github.com/GenericMappingTools/pygmt/issues/new?template=feature_request.md) is also great, and maybe someone will look at it and decide to implement it for you! Feel free to leave a comment below too if that's easier. Happy sprinting everyone :tada:

**Comment by liamtoney** [comment]
Thanks to all who participated in our sprint! We had several folks learning how to use PyGMT, and lots of interest from conference attendees. Special thanks to @tjnewton for his contribution wrapping `meca` so we can plot focal mechanisms! 🎾

**Comment by tjnewton** [comment]
> Thanks to all who participated in our sprint! We had several folks learning how to use PyGMT, and lots of interest from conference attendees. Special thanks to @tjnewton for his contribution wrapping `meca` so we can plot focal mechanisms! 🎾

My pleasure! Thanks for you guidance.
