### ISSUE TITLE
Update the maintainers guide

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#443]
**Description of the problem**

Some content of the [mainteners guide](https://github.com/GenericMappingTools/pygmt/blob/master/MAINTENANCE.md) is outdated. We should update the guide based on our experience of releasing PyGMT v0.1.1.

The updated guide may or may not be included in the v0.1.1 release.

**Comment by seisman** [comment]
Closed in #446.

**Comment by weiji14** [comment]
Not sure if this is completely done, for example in https://github.com/GenericMappingTools/pygmt/blob/master/MAINTENANCE.md#continuous-integration, we haven't mentioned anything about using Azure Pipelines.
