### ISSUE TITLE
Add a PyGMT release checklist

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#444]
**Description of the desired feature**

Like [what we did in the GMT repository](https://github.com/GenericMappingTools/gmt/blob/master/.github/ISSUE_TEMPLATE/release_checklist.md), we could have a release checklist  for PyGMT, which can simplify/standardize the process of new releases.

The checklist template should be placed in the `.github/ISSUE_TEMPLATE` directory.

**Comment by weiji14** [comment]
I'll add it to the PR at #442 if that's ok? Or it is better to have a separate one?

**Comment by weiji14** [comment]
Actually I'll open up a standalone PR, would be good to add https://github.com/apps/release-drafter as well to simplify the changelog writing.
