### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by ganesheshwar** [GenericMappingTools/pygmt#46]
You have mentioned that this has been tested in Unix and OSX. I tried intalling in Windows through cloning the repo. However when I import gmt in Jupyter, it gave me the following error.

GMTOSError: Unknown operating system: win32

Any solution for a Windows support?

**Comment by leouieda** [comment]
Hi @ganesheshwar, the main thing holding us back from Windows is getting a GMT conda package for Windows working (see https://github.com/conda-forge/gmt-feedstock/pull/15 for some work that @ocefpaf is doing).

But if you can get the current development version of GMT (trunk) built on your machine, you might be able to get this working. I'll have to include a flag for finding the Windows dll. But I haven't tested this under Windows yet and things might break mysteriously. 

If you're willing to give it a shot, I'd really appreciate it. 

Another option is to use the [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/about) that came out for Windows 10. Then everything should work as a normal Linux terminal for you. This might be the most painless option.

**Comment by ganesheshwar** [comment]
HI @leouieda , I will try to build it from the repo and try out. Once @ocefpaf is up with the working version in Windows, it should be really helpful. 

Thanks for the reply. I will stay in loop to track the progress.

**Comment by sgcrews** [comment]
Really interested in this project, @**leouieda**.  I'm a geologist and long-time Matlab user, just joining the Python world.  I do a lot with topography/bathymetry and maps in general--I loved the slide in you SciPy talk where you showed a map of the Moho in South America!
I'm using Windows and iOS so I eagerly await your conda package...
--steve

**Comment by leouieda** [comment]
Hi Steve, thanks for writing in!

I was hoping to get the conda package soon but I think it's going to take a while. I have no experience with Windows and it's hard to debug the problems with the build. But it will move forward and get done before we make an official release. 

For now, if you have Windows 10 you can access the bash shell from Ubuntu directly. That would allow you to use the Linux packages from inside your Windows machine (see link in my previous post). I'd be interested to know if that works. 

PS: The figures in that paper took [a lot of code](http://nbviewer.jupyter.org/github/pinga-lab/paper-moho-inversion-tesseroids/blob/master/code/paper-figures.ipynb) to make. I can't wait to be able to use GMT6 for this.
