### ISSUE TITLE
Add show_versions function for easier bug reporting

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#460]
**Description of the desired feature**

Quite a few PyData projects have a `show_versions` methods that prints out a list of versions for Python packages (see e.g. https://github.com/geopandas/geopandas/issues/899, https://github.com/corteva/rioxarray/issues/106). This would make it easier for people filing bug reports to submit their system information (as required in our [bug report template](https://github.com/GenericMappingTools/pygmt/blob/v0.1.1/.github/ISSUE_TEMPLATE/bug_report.md)).

Currently we have `pygmt.print_clib_info()` that prints GMT specific information, but not Python packages. At a minimum, we should have it print the versions for:

- Operating System
- `python`
- `pygmt`
- `gmt`
- `numpy`
- `pandas`
- `xarray`
- `netcdf`
- etc

For examples on how this could be implemented, see https://github.com/pydata/xarray/pull/1485, https://github.com/pandas-dev/pandas/blob/v1.0.3/pandas/util/_print_versions.py#L61-L124, etc. Should update the bug report template to use this new `pygmt.show_versions()` function too.

**Are you willing to help implement and maintain this feature?**

Would be happy to review a Pull Request, as long as you [don't put it into utils.py](https://breadcrumbscollector.tech/stop-naming-your-python-modules-utils/) :wink:

**Comment by seisman** [comment]
It sounds a good idea.
