### ISSUE TITLE
maps using PyGMT

### ISSUE THREAD

**Issue by Ruaa93** [GenericMappingTools/pygmt#465]
**Description of the problem**

I'm trying to create a gravity map (for example Bouguer anomaly) using PyGMT, is there any similar codes or toturials to show how can gravity or magnatic maps can be created?

**Full code that generated the error**

```python
PASTE CODE HERE
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system:
* Python installation (Anaconda, system, ETS):
* Version of GMT:
* Version of Python:
* Version of this package:
* If using conda, paste the output of `conda list` below:

<details>
<summary>output of conda list</summary>
<pre>
PASTE OUTPUT OF CONDA LIST HERE
</pre>
</details>

**Comment by weiji14** [comment]
HI @Ruaa93, if you could post your question on the forum at https://forum.generic-mapping-tools.org/, that would be great (you can login with your Github account). You'll get better visibility from the community compared to just a handful of people here who might not work with gravity/magnetics. The Github site is for bug reports and feature requests.

**Comment by Ruaa93** [comment]
@weiji14 done, thanks!
