### ISSUE TITLE
Only document the long-form arguments

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#473]
**Description of the problem**

GMT command line and its C API only accept single-character arguments, e.g., **-B** and **-J**, whereas Python and PyGMT users mostly would prefer long-form arguments instead, e.g., **frame** for **-B**, **projection** for **-J**. Currently, PyGMT supports both single-character and long-form arguments, but we definitely will disallow single-character arguments in the future. See issue #262 for the reasons.

Currently, the documentation is pretty confusing. Take the documentation of `Figure.coast()` as an example. Below is what it looks like now:
![image](https://user-images.githubusercontent.com/3974108/83383818-e8e4be80-a3b3-11ea-8979-02209a42f721.png)

For PyGMT users who never used GMT before, it's not clear what the aliases mean. I believe most of them are confused about the inconsistency of the single-character arguments in the coast documentation and the long-form arguments in the tutorials and gallery. 

It will be a lot of work to fully implement #262, but at least now we should stop documenting single-character arguments and document long-form arguments instead.

What we can do:

- Replace all single-character arguments with the corresponding long-form arguments, e.g., **B**->**frame**, **J**->**projection**.
- Remove the aliases from the docstring

**Comment by weiji14** [comment]
A quick way to catch most of these is by fixing the common aliases (e.g. R=region, J=projection) listed in https://github.com/GenericMappingTools/pygmt/blob/master/pygmt/helpers/decorators.py. Should add a few others as well (e.g. l=label for legend, and c=axes for subplot once #412 is sorted). We can then slowly handle all of the other edge cases.
