### ISSUE TITLE
How to add scale bar and North arrow to a map using pygmt

### ISSUE THREAD

**Issue by LiangChen3519** [GenericMappingTools/pygmt#477]
Hi, dear all, is there any way to add add scale bar and North arrow to a map ?

**Comment by weiji14** [comment]
Hi @LiangChen3519. In PyGMT v0.1.1, you can use [`fig.basemap`](https://www.pygmt.org/latest/api/generated/pygmt.Figure.basemap.html#pygmt.Figure.basemap)'s `L` option to set a map scale, and `Td` to set a north arrow. The full option is at https://docs.generic-mapping-tools.org/latest/basemap.html#l, and it's a bit complicated so just as an example:

```python
fig = pygmt.Figure()
fig.basemap(
    region=[0, 4, 8, 12],
    projection="u2c",
    frame=True,
    L="jBL+c2:10N+f+w100k+u+o1c",
    Td='jTR+o0.1c+w1c',
)
fig.savefig("mapscale_and_northarrow.png")
fig.show()
```

produces:

![mapscale_and_northarrow](https://user-images.githubusercontent.com/23487320/84721134-0a5cc180-afd4-11ea-8d4b-b509ab6213e3.png)


P.S. The Github page is for bug reports/feature requests, please post future question to https://forum.generic-mapping-tools.org/ (you can login with your Github account). I'll close this issue in a few days if there's no further questions.

**Comment by LiangChen3519** [comment]
> Hi @LiangChen3519. In PyGMT v0.1.1, you can use [`fig.basemap`](https://www.pygmt.org/latest/api/generated/pygmt.Figure.basemap.html#pygmt.Figure.basemap)'s `L` option to set a map scale, and `Td` to set a north arrow. The full option is at https://docs.generic-mapping-tools.org/latest/basemap.html#l, and it's a bit complicated so just as an example:
> 
> ```python
> fig = pygmt.Figure()
> fig.basemap(
>     region=[0, 4, 8, 12],
>     projection="u2c",
>     frame=True,
>     L="jBL+c2:10N+f+w100k+u+o1c",
>     Td='jTR+o0.1c+w1c',
> )
> fig.savefig("mapscale_and_northarrow.png")
> fig.show()
> ```
> 
> produces:
> 
> ![mapscale_and_northarrow](https://user-images.githubusercontent.com/23487320/84721134-0a5cc180-afd4-11ea-8d4b-b509ab6213e3.png)
> 
> P.S. The Github page is for bug reports/feature requests, please post future question to https://forum.generic-mapping-tools.org/ (you can login with your Github account). I'll close this issue in a few days if there's no further questions.

Thanks a alot.

**Comment by De-Guo** [comment]
How to change the background color of the scale bar?
