### ISSUE TITLE
Error opening HKLM key

### ISSUE THREAD

**Issue by QuinnQian** [GenericMappingTools/pygmt#478]
after running the codes, yes, I can get the plots. But there is always an error message 'psconvert [ERROR]: Error opening HKLM key'
pygmt version: 0.1.1
Python 3.7.4
Win 10
![图片](https://user-images.githubusercontent.com/29096644/84793471-b7145e80-b027-11ea-8b62-e95250e51433.png)

**Comment by seisman** [comment]
@PaulWessel @joa-quim It seems psconvert can't find Ghostscript in the Windows registries, but can find it in the **PATH**. Perhaps we should change it to a debug message?

**Comment by seisman** [comment]
Ping @PaulWessel and @joa-quim for thoughts on the error message.

**Comment by PaulWessel** [comment]
This is a task for @joa-quim.  But certainly, if this is not a fatal error then it needs to be downgraded to either a warning (if it actually identifies something wrong), Information (if this is good to know), or debug (just for us).  May need to change the actual message to correspond to that severity, e.g., "GS path not found in registry, revert to PATH" etc.

**Comment by joa-quim** [comment]
Up until 6.0 the ghost was a mandatory option, and if it was not found (via elaborated registry fishing) an error message was issued. Now we distribute the ghost for Win that is used when an *official* version is not found, so the message is not about a fatal error anymore. Changing it to "No GS found in your system, resorting to GMT provided version" and make it **-Vd** should be good.

**Comment by seisman** [comment]
> "No GS found in your system, resorting to GMT provided version"

That's not exactly true here. Most PyGMT users install everything, including GMT and Ghostscript, from the conda-forge channel. I believe the Ghostscript from conda-forge doesn't change the Windows registries, but is installed to the **PATH**.

> "GS path not found in registry, revert to PATH"

This one looks better.

Anyway, I'll mark the issue as an upstream bug.

**Comment by joa-quim** [comment]
> I believe the Ghostscript from conda-forge doesn't change the Windows registries

That's an annoying thing that those system practice pretending they live in a parallel universe. IMO, that's their problem.

**Comment by seisman** [comment]
This is a upstream bug, fixed in GMT 6.1.0. Closing this issue.
