### ISSUE TITLE
Add examples for plotting lines 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#493]
**Description of the desired feature**

There are already have nice tutorials for plotting [data points of various sizes and colors](https://www.pygmt.org/dev/tutorials/plot.html), but no examples for plotting lines.

It would be good to add some examples showing 

- how to plot lines
- how to specify line attributes (pen thickness, color, and pen style)
- plot lines with various colors as determined by a CPT file

Unfortunately, PyGMT currently can't handle multi-segments data as in GMT. To plot multiple lines, we still have to call `fig.plot()` multiple times.

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/pygmt/pull/604#issuecomment-709696963

> Also, was just looking at the GMT.jl AGU gallery examples at https://www.generic-mapping-tools.org/GMT.jl/latest/gallery/tables/, looks like there's a lot of decorated arrows/curved line examples we can follow.
> 
> ![image](https://user-images.githubusercontent.com/23487320/96206927-77a25280-0fc6-11eb-99a5-d2e405e5a6e3.png)

**Comment by willschlitzer** [comment]
I'll work on this.

**Comment by willschlitzer** [comment]
I'm trying to figure out how to add a specific CPT, but I'm not getting it to plot on the actual line. I tried setting a specific CPT to `cmap`, and also tried adding `"red,green"` to add specific colors, but no luck.

**Comment by weiji14** [comment]
Yeah it's complicated, took me a while to figure it out recently too. Try this for inspiration:

```python
import pygmt
import numpy as np

fig = pygmt.Figure()
fig.basemap(frame=["WSne", "af"], region=[20, 30, -10, 10])
pygmt.makecpt(cmap="batlow", series=[0, 10, 1])
x = np.arange(start=20, stop=30, step=0.2)
for zvalue in range(0, 10):
    y = zvalue * np.sin(x)
    fig.plot(x=x, y=y, cmap=True, zvalue=zvalue, pen=f"thick,+z,-")

fig.show()
```

![sine curve with different colors](https://user-images.githubusercontent.com/23487320/102444216-8623ed80-408d-11eb-91b2-4ba890b3bb8d.png)

**Comment by willschlitzer** [comment]
@weiji14 Impressive find, but that seems like a big step up in complexity from the rest of the tutorial. I've been out of geoscience for 8+ years so I don't keep up with what people want in their plots, but this seems out of place for a basic "How to plot lines" tutorial. My opinion is something like this belongs in a gallery example.

**Comment by willschlitzer** [comment]
@seisman Are you looking to have anything else added to these line plotting examples before closing the issue? As stated above, I think the custom CPT example provided by @weiji14 may be a bit advanced for a basic tutorial.

**Comment by seisman** [comment]
@weiji14's example is pretty good and could be added to the gallery (https://www.pygmt.org/dev/gallery/index.html#lines).

**Comment by willschlitzer** [comment]
@weiji14 Are you planning on adding your code to the gallery? I can submit a pull request for it if you're too busy.

**Comment by weiji14** [comment]
I literally came up with that in 5 minutes :sweat_smile:, but yeah, feel free  to adapt it into the gallery.

**Comment by willschlitzer** [comment]
Sounds good! Didn't want to step on your toes; I'll type it up in the next day or so.

**Comment by willschlitzer** [comment]
@seisman Are we good to close this issue now that #741 and #774 have been merged?

**Comment by seisman** [comment]
> @seisman Are we good to close this issue now that #741 and #774 have been merged?

There are some lines/arrows we may want to add in the gallery. See https://github.com/GenericMappingTools/pygmt/issues/493#issuecomment-709697692

**Comment by core-man** [comment]
So we still want more line examples?
- error bar? Do error bar belong to lines?
- mat angles
- bezier
- decorated
- decorated text

Which one is on the top
priority? @seisman

**Comment by seisman** [comment]
I'm closing the issue, because I feel that the `Figure.plot()` method is becoming too complicated and may need some re-design. I prefer **NOT** to add more complicated (and less used) examples (e.g., decorated text) before we have some more discussions about `Figure.plot()`.
