### ISSUE TITLE
Add blackdoc and docformatter to wrap docstrings to 79 chars

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#497]
**Description of the desired feature**

[`blackdoc`](https://github.com/keewis/blackdoc) is like [`black`](https://github.com/psf/black), but for docstrings! This will help with applying #384, and make our docstrings consistent with our code. 

Would prefer for someone new-ish to take this on. Some knowledge of git commit-hooks would be useful, but you can see https://github.com/pydata/xarray/pull/4177 as an example on how another library has implemented it.

**Are you willing to help implement and maintain this feature?** No

**Comment by seisman** [comment]
Just tried blackdoc. I think it can only format the codes in docstrings, but can't wrap other non-code docstrings.

**Comment by leouieda** [comment]
The problem with formatting the dosctring text is that it’s restructuredtext, not Python. So the rules are different. But even if blackdoc does only the doctests, it would be nice to have automated 👍

**Comment by weiji14** [comment]
A quick search turns up [docformatter](https://github.com/myint/docformatter) that follows [PEP 257](https://www.python.org/dev/peps/pep-0257) (didn't realize there's a docstring convention)! We might be able to mix both, but not sure how well they play nicely with one another. There's also [PEP 287](https://www.python.org/dev/peps/pep-0287/) which is specifically for RestructuredText, and [blacken-docs](https://github.com/asottile/blacken-docs) that looks similar to blackdoc. I found most of this quoted over at https://github.com/psf/black/issues/144.

**Comment by leouieda** [comment]
Yes but our docstrings follow the NumPy style, not necessarily PEP257 😔 I haven’t seen those other tools, though. Might be worth investigating.

**Comment by weiji14** [comment]
There's some similarities between the standards (see this [stackoverflow answer](https://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format/24385103#24385103) for an overview), but yes, let's stick to numpydoc.

Actually after some thought, it might be better to make this an **optional** tool, since we already have `black` and `pylint`. Adding one more into the mix might act as a barrier to new contributors (who often face dozens of lint errors on their first Pull Request).
