### ISSUE TITLE
Remove the Stickler CI service

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#532]
**Description of the problem**

[Stickler CI](https://stickler-ci.com/) checks the code style for each PR, and leaves comments if there are any styling issues. The configuration file is [.stickler.yml](https://github.com/GenericMappingTools/pygmt/blob/master/.stickler.yml). It's configured to run "flake8" to check code styles.

When we submit a PR, we usually don't care about the code style until it's ready to merge. That's why I find the comments annoying. As we already have a CI checking code styles, all PRs won't be merged if they don't follow the code styles. 

I think it's safe to remove the Stickler CI service and rely on the github action style checking job instead.

**Comment by weiji14** [comment]
Yes it can be quite annoying. Also not a good experience for new contributors opening a Pull Request and getting dozens of linter warnings. So +1 from me for removing it, though I'm happy to consider other less-annoying Github linters, e.g. one that could be triggered manually using an inline comment like `/lintcode` or something.
