### ISSUE TITLE
Add tutorial for plotting datetime inputs

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#549]
**Description of the desired feature**

Following on from #464, we'll need help adding a gallery/tutorial on how to pass in datetime inputs to [plot](https://www.pygmt.org/v0.1.2/api/generated/pygmt.Figure.plot.html)!

## Simple goal ([gallery](https://www.pygmt.org/latest/gallery/index.html) example):

Start by taking a look at the top post of #464. The example should cover at least 4 types of Python datetime inputs:

- [ ] [numpy.datetime64](https://numpy.org/doc/stable/reference/arrays.datetime.html)
- [ ] [pandas.DateTimeIndex](https://pandas.pydata.org/docs/user_guide/timeseries.html)
- [ ] Raw datetime strings in both ISO and non-ISO formats, e.g., `2010-01-01`, `1/1/2018`, `Jul 5, 2019`
- [ ] Python's [built-in datetime and date](https://docs.python.org/3/library/datetime.html)

You can adapt the example from the following code:

https://github.com/GenericMappingTools/pygmt/blob/a2258a5c252bb13407297d92c0a28f01eb2f43ba/pygmt/tests/test_plot.py#L294-L325

![Datetime plot](https://raw.githubusercontent.com/GenericMappingTools/pygmt/a2258a5c252bb13407297d92c0a28f01eb2f43ba/pygmt/tests/baseline/test_plot_datetime.png)

It would also be good to show how datetime-like arguments can be passed in the 'region' argument of `fig.basemap`, see #562.

## Stretch goal (full [tutorial](https://www.pygmt.org/latest/tutorials/))

Learn how to use [pygmt.config](https://www.pygmt.org/v0.1.2/api/generated/pygmt.config.html) to configure [Calendar/Time Parameters](https://docs.generic-mapping-tools.org/6.1/gmt.conf.html#calendar-time-parameters)!

This is a bit more involved, but you can do amazing stuff like abbreviate Sunday to Sun. Example code/figure:

https://github.com/GenericMappingTools/pygmt/blob/a2258a5c252bb13407297d92c0a28f01eb2f43ba/pygmt/tests/test_config.py#L77-L90

![format time map example](https://raw.githubusercontent.com/GenericMappingTools/pygmt/v0.1.2/pygmt/tests/baseline/test_config_format_time_map.png)

See also GMT Gallery Example 21 "Time-series of RedHat stock price" at https://docs.generic-mapping-tools.org/6.1/gallery/ex21.html for what is possible!

**Are you willing to help implement and maintain this feature?** Let's have someone new tackle this!

**Comment by michaelgrund** [comment]
As the gallery example was merged into master in #779 could you adjust the issue title @weiji14 to only address the missing tutorial?

**Comment by weiji14** [comment]
Continuing from https://github.com/GenericMappingTools/pygmt/issues/1078#issuecomment-812651912 (ping @munzekm, @noorbuchi, @cklima616, @Nathandloria), I think adding a datetime tutorial would be a nice follow up to #1070 since you're already familiar with how to write up a tutorial for PyGMT. There's a few challenging aspects to it, but I'm sure that a team of three will make short work of it! These are some sections you could do (but do feel free to come up with new ideas):

1. Different datetime-like Python inputs into [`fig.basemap`](https://www.pygmt.org/v0.3.1/api/generated/pygmt.Figure.basemap.html), see also https://www.pygmt.org/v0.3.1/gallery/symbols/datetime_inputs.html
2. Using [`pygmt.info`](https://www.pygmt.org/v0.3.1/api/generated/pygmt.info.html) to get the min/max time for passing into the `region` parameter, but note potential bug at #597
3. Setting a primary and secondary time axis. See https://github.com/weiji14/deepicedrain/blob/v0.4.1/deepicedrain/vizplots.py#L376-L403 for an example (pardon if it's messy), below is a screenshot of how it should look like:

![image](https://user-images.githubusercontent.com/23487320/113787333-f1094980-978e-11eb-9a0c-a10859e3b222.png)

As usual, free to ask any questions, and/or start a draft PR to work on this issue. And thanks again for your continued contributions!

**Comment by munzekm** [comment]
Thank you @weiji14 for the information about this issue. We would be happy to start working on it. We do have a few questions: Would you want us to create a new python file inside the tutorial folder or use an existing one? Do you want us to work on the existing gallery file as well? Also, how would you like us to set up this tutorial. Our group just wants to make sure we fully understand what we are focusing on.

**Comment by weiji14** [comment]
> Would you want us to create a new python file inside the tutorial folder or use an existing one? Do you want us to work on the existing gallery file as well?

Please make a new python file for the tutorial, and no, the existing gallery example doesn't need to be worked on.

> Also, how would you like us to set up this tutorial. Our group just wants to make sure we fully understand what we are focusing on.

The tutorial is intended to walk someone new to make a date-time plot for time-series data. Feel free to discuss within the group and structure things as you see fit (since you're all new to datetime plotting in PyGMT, presumably you would have a list of things you want to know about **how** to plot time-series data). To be honest, we don't have a strict set of rules on how it needs to be done. But if you're looking for ideas, check out the other tutorials like https://www.pygmt.org/v0.3.1/tutorials/text.html, and see https://github.com/GenericMappingTools/pygmt/issues/549#issuecomment-814486879 for suggestions on what could be included.
