### ISSUE TITLE
Support datetime types in region argument

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#561]
**Description of the desired feature**

Support passing in 'datetime' like inputs into the 'region' or '-R' argument in `plot`.

>> * The `region` argument doesn't work with numpy `datetime64` objects, have to convert to a string using [`np.datetime_as_string`](https://numpy.org/devdocs/reference/generated/numpy.datetime_as_string.html) in order to set the map frame bounds.

> The decorator `kwargs_to_strings` convert the list `[w, e, s, n]` to a string *w/e/s/n*. We need to convert datetime64 object to string internally, but it's not ideal to do the conversion in the decorator. I don't have a good solution now.

_Originally posted by @seisman in https://github.com/GenericMappingTools/pygmt/pull/464#issuecomment-636585247_

Minimal working example:

```python
import pandas as pd
import pygmt

fig = pygmt.Figure()
fig.plot(x=["2020-06-30"], y=[1], region=[pd.Timestamp("2020-01-01"), pd.Timestamp("2020-12-31"), 0, 2])
fig.show()
```

The error message is:

```python-traceback
GMTCLibError: Module 'plot' failed with status code 71:
plot [ERROR]: Option -R parsing failure. Correct syntax:
plot [ERROR]: Offending option -R2020-01-01
```

This workaround does work, but it's cumbersome:

```python
fig = pygmt.Figure()
fig.plot(
    x=[pd.Timestamp("2020-06-30")],
    y=[1],
    region=[
        pd.Timestamp("2020-01-01").isoformat(),
        pd.Timestamp("2020-12-31").isoformat(),
        0,
        2,
    ],
    style="a10c",
    frame=True,
)
fig.show()
```

produces:

![Expected plot with star in middle](https://user-images.githubusercontent.com/23487320/90197481-e0cce480-de22-11ea-8032-8a4ce3c75542.png)

**Are you willing to help implement and maintain this feature?** Yes, but where should this code logic go?

**Comment by seisman** [comment]
Add a check in the `kwargs_to_strings` decorator?https://github.com/GenericMappingTools/pygmt/blob/2ddbb0e1977af85bf6a6ac63d7cbac9da3d08f05/pygmt/helpers/decorators.py#L244

**Comment by weiji14** [comment]
I'm wondering if this functionality is specific to `plot` only, or if there are other places which can take datetime-like 'region' arguments.

**Comment by seisman** [comment]
Almost any modules can accept datetime-like region, for example, basemap, histogram, and even grdimage (maybe, but never tried).

**Comment by weiji14** [comment]
Ok, the extra 'datetime' check might slow things down by a bit, but since it's only checking for 4 (or 6) items in a list, it should be fine.
