### ISSUE TITLE
Wrap histogram

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#563]
**Description of the desired feature**

The **histogram** module is useful and should be wrapped.

Some useful resources:

- [GMT's histogram manpage](https://docs.generic-mapping-tools.org/dev/histogram.html)
- [GMT.jl's histogram wrapper](https://www.generic-mapping-tools.org/GMT.jl/latest/#GMT.histogram)
- [numpy.histogram](https://numpy.org/doc/stable/reference/generated/numpy.histogram.html)
- [matplotlib.pyplot.hist](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.hist.html)

**Are you willing to help implement and maintain this feature?** 
Yes, but may have no time recently, so contributions are welcomed.

**Comment by willschlitzer** [comment]
More power to someone if they can come to the project and immediately wrap `histogram`, but I don't think this should be marked as a "good first issue"

**Comment by core-man** [comment]
This issue will be my highest priority after I finish #1065.
