### ISSUE TITLE
Kernel dies if an additional subset map is added

### ISSUE THREAD

**Issue by michaelgrund** [GenericMappingTools/pygmt#569]
Hey guys,

I recently tried to generate a figure in a jupyter notebook which consists of two maps (A and B). For that I first generated a map (A) using `fig.coast(...)` which works well. For the second map (B) I first use `shift_origin` to move it a little bit right. Then I use again `fig.coast(...)` to generate map B. At this point the kernel dies and it's not possible to continue. Any ideas what happens here?

The issue is similar to [https://github.com/GenericMappingTools/pygmt/issues/514](https://github.com/GenericMappingTools/pygmt/issues/514), however, not exactly the same.

```python

import pygmt

fig = pygmt.Figure()

lon = 19
lat = 64

fig.coast(region = 'g',
          projection = 'E' + str(lon) + '/' + str(lat) + '/5c',
          resolution = 'c', 
          shorelines = '1/thinnest,black', 
          frame = ['30g0'],
          area_thresh = ['5000'],
          G = 'lightgray',
          C = 'lightgray')

fig.shift_origin(xshift = '3c')

fig.coast(region = 'g',
          projection = 'E' + str(lon) + '/' + str(lat) + '/5c',
          resolution = 'c', 
          shorelines = '1/thinnest,black', 
          frame = ['30g0'],
          area_thresh = ['5000'],
          G = 'lightgray',
          C = 'lightgray')
```

**Comment by MarkWieczorek** [comment]
I think that `shift_origin()` only works with gmt 6.1.1. This is supposed to be released in a few days, but if you are impatient, you can install from source. On macOS, this is easy to do with `brew install gmt --HEAD`.

**Comment by michaelgrund** [comment]
> 
> 
> I think that `shift_origin()` only works with gmt 6.1.1. This is supposed to be released in a few days, but if you are impatient, you can install from source. On macOS, this is easy to do with `brew install gmt --HEAD`.

Hmm, I created several other maps in the same manner, however, using different projections and everything worked so far without having 6.1.1

**Comment by MarkWieczorek** [comment]
I confirm that this crashes the kernel on my system using the most up to date versions of gmt and pygmt (as of about a week ago...)

```
coast [WARNING]: Fill/clip continent option (-G) may not work for this projection.
coast [WARNING]: If the antipode (0/-5.52561e+09) is in the ocean then chances are good it will work.
coast [WARNING]: Otherwise, avoid projection center coordinates that are exact multiples of 199 degrees.
[1]    75191 segmentation fault  ipython
```

**Comment by michaelgrund** [comment]
> And, the crash is unrelated to `shift_origin`. If you simply call fig.coast twice, the kernel dies....

That's strange since in another figure I perform nearly the same, except that I use two different projections for the subsets ([https://github.com/michaelgrund/GMT-plotting/blob/master/009_paper_GR2020/pygmt_jn_fig_2/GR_2020_Fig_2.ipynb](https://github.com/michaelgrund/GMT-plotting/blob/master/009_paper_GR2020/pygmt_jn_fig_2/GR_2020_Fig_2.ipynb)). It seems that it crashes if multiple times the same projection is used...

**Comment by seisman** [comment]
I can confirm that it's an upstream GMT bug. 

@PaulWessel Please see if you can fix it in GMT.

**Comment by michaelgrund** [comment]
Great to hear!

**Comment by michaelgrund** [comment]
yes after updating to 6.1.1 it works, thanks for your efforts!!!
