### ISSUE TITLE
Ensure all maintainers can publish PyGMT to Zenodo and make a DOI

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#601]
Need to make sure that every core maintainer can reserve a new Zenodo version DOI for PyGMT. Continuing discussion from https://github.com/GenericMappingTools/pygmt/pull/599#discussion_r486769250_. I.e. everyone should be able to click on the green "New version" button (see sceenshot).

![PyGMT Zenodo page](https://user-images.githubusercontent.com/23487320/92861143-3958c700-f44d-11ea-979a-30d599713ec0.png)

Which will take you to a page where there should be a 'Reserve DOI' button somewhere. Click on that, and copy the DOI link to the changelog/release notes for the new PyGMT version (e.g. at #599).

As to why we can't just automate this, see https://github.com/GenericMappingTools/pygmt/pull/599#discussion_r487308959_ (quoted below):

> Just to clarify, there's 2 options that I know of to make a Zenodo DOI, each with pros/cons (see also FAQs at https://help.zenodo.org/):

> 1. Use the **automated** Github integration:
>  - Pro: It's automated, publishing a release creates the DOI automatiically
>  - Con: We don't know the DOI number beforehand, so can't put it into the release notes. Also, I couldn't manage to link it to our current permanent/concept DOI at https://doi.org/10.5281/zenodo.3781524.

> 2. **Manually** reserve a DOI (what was done for PyGMT v0.1.x):
>  - Pro: We know the DOI beforehand, so can put it into our release notes. Also more control with the metadata information.
>  - Con: It's not automated, I had to manually download the pygmt-v0.1.x.zip file, and upload it to Zenodo. Also as we found out, maybe it's linked only to my account?!!

Either way, would be good to discuss what we want to do :neutral_face:

**Comment by leouieda** [comment]
Copying from #599:

I was just checking on some of my own uploads and it seems like only the original creator can upload a new version. This really sucks since we can't use the DOI versioning and have multiple release managers at the same time. I have sent them an email asking is there is a workaround and if not, making that a feature request.

At the moment, it seems like we only have 2 options:

1. Wei Ji creates new Zenodo uploads forever 😉 
1. We go back to making a new upload for every release instead of creating a new version. This would allow anyone to do the upload. Con is that we have to copy authors and descriptions every time.

I don't think the GitHub automation is an option since it doesn't allow reserving the DOI. In the end, I found it more trouble than it's worth. One thing we could do is build our own automation using the Zenodo API. It lets us reserve DOIs and make uploads. But that could be a lot of work.

**Comment by weiji14** [comment]
After some more searching, I found that the multi-user feature is on their current roadmap (see https://about.zenodo.org/roadmap/), and due for (Northern Hemisphere) autumn 2020 according to https://github.com/zenodo/zenodo/issues/35. So maybe I won't need to do this forever after all :laughing:

**Comment by leouieda** [comment]
And here I thought that I had you hooked for good...

**Comment by weiji14** [comment]
Just an update, things appear to have been pushed out to (Northern Hemisphere) autumn 2021 (see https://github.com/zenodo/zenodo/issues/810#issuecomment-753917462). The multi-curator feature will likely come to InvenioRDM in May 2021 (see https://inveniosoftware.org/products/rdm/roadmap/), and once Zenodo migrates their system to InvenioRDM in the near term (hopefully sometime this year in 2021), we'll be able to add other PyGMT maintainers into the list.

![Zenodo roadmap](https://user-images.githubusercontent.com/23487320/116831413-5f60f080-ac03-11eb-9bda-6e8fcde1d8d0.png)

**Comment by seisman** [comment]
Some updates: https://blog.zenodo.org/2022/12/07/2022-12-07-zenodo-on-inveniordm/

Let's expect a new Zenodo in Autumn 2023.

**Comment by leouieda** [comment]
Hi all, on Fatiando we got around this by creating an account for the organisation, which all maintainers will have access. We then asked the Zenodo support to transfer all existing uploads to that account. See https://github.com/fatiando/community/pull/98#issuecomment-1471725321

**Comment by seisman** [comment]
Let's expect something new on Sep. 29 https://blog.zenodo.org/2023/09/06/2023-09-06-zenodo-rdm/.

**Comment by seisman** [comment]
The Zenodo migration has been done today (see https://blog.zenodo.org/2023/10/13/2023-10-13-zenodo-rdm/),  although currently it's slow.

Here is the latest record of the PyGMT package (https://zenodo.org/records/8303186) and here is the "GenericMappingTools" community (https://zenodo.org/communities/generic-mapping-tools).

**Comment by seisman** [comment]
@PaulWessel Zenodo has migrated its system to InvenioRDM. Now it allows multiple members with different roles (Reader, Curator, Manager and Owner) to add a new record or edit an existing record (see https://help.zenodo.org/docs/about/whats-new/#communities-members) to the GMT community.

Currently, you're the only member (Owner) of the [GMT Community](https://zenodo.org/communities/generic-mapping-tools). Could you please add me as an "Owner", so that I can invite other PyGMT maintainers as "Curators" if necessary?

**Comment by weiji14** [comment]
Thanks @seisman! Once you have Owner access from @PaulWessel, could you also also add me and some of the other maintainers to the GMT Community on Zenodo? I'd be happy to walk someone through the Zenodo upload process for the next PyGMT v0.11.0 release (but still happy to do these in the future too :wink:).

**Comment by weiji14** [comment]
Continuing thread from https://github.com/GenericMappingTools/pygmt/issues/2843#issuecomment-1913149405 (so we don't clutter the v0.11.0 release issue.

> > * Reserve a DOI on [Zenodo](https://zenodo.org) by clicking on "New Version"
> 
> @weiji14 Not sure what's happening. I can create a new version for GMT, but can't do it for PyGMT.
>
> For PyGMT: <img alt="image" width="1642" src="https://private-user-images.githubusercontent.com/3974108/300179005-3523feae-b9be-45ce-b1af-c6b7da5c0fdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MDY4ODIsIm5iZiI6MTcwNjQwNjU4MiwicGF0aCI6Ii8zOTc0MTA4LzMwMDE3OTAwNS0zNTIzZmVhZS1iOWJlLTQ1Y2UtYjFhZi1jNmI3ZGE1YzBmZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMDE0OTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmZmNTk0YzVhMmE2ODY1ZTg5MTZlZjViYmUxOGFjOTI0NmIyZDNjZTY4ZTNjZTliZmI2M2M1MWY3NDZjZjI5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7M9b-P9rrPMcfEPkL0AhlZYcwEtp00Xyg41heOI8IDs">

Hmm, I can see the 'New version' button on my side.

![image](https://github.com/GenericMappingTools/pygmt/assets/23487320/fc2f199b-814d-4ad3-b26f-eb8a216d5b20)

On my end, I only have 'Curator' role access to the 'Generic Mapping Tools' Zenodo community, but I see that you and Paul are 'Owner's. Maybe there is some permissions setting you need to set? I can't seem to find any settings about transferring ownership on my end.

Strangely enough, I can create a new version for GMT, but not for [DCW-GMT](https://zenodo.org/records/6823057). Is it because there was a recent GMT 6.5.0 release that uses the new Zenodo community permissions setup? Maybe I will need to create a new PyGMT release this time, and then you can do it next time?

**Comment by seisman** [comment]
> Is it because there was a recent GMT 6.5.0 release that uses the new Zenodo community permissions setup? 

It's likely.

> Maybe I will need to create a new PyGMT release this time, and then you can do it next time?

Yes, please give it a try.

**Comment by seisman** [comment]
I filed a support ticket a few days ago and here is the reply:

> The records were created prior to the migration of Zenodo last October and they were not automatically available for community curation - like newer records. Since the uploaders are also owners of this community, we enabled the records curation for all the owners / curators of the community.

Now I can see the "Edit" and "New Version" buttons for all records in the GMT community. 

Closing.

**Comment by weiji14** [comment]
Awesome! I'll let you do the upload for v0.13.0 :smile:

One thing to note: when downloading the source code zip file from https://github.com/GenericMappingTools/pygmt/releases, the filename will be something like `pygmt-0.13.0.zip`. You'll need to remember to rename it to `pygmt-v0.13.0.zip` (as mentioned on the release checklist) before uploading to Zenodo.
