### ISSUE TITLE
Switch between different versions of documentations

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#609]
**Description of the desired feature**

We have versioned documentation for each PyGMT release. All the versions are listed in the PyGMT main site.
![image](https://user-images.githubusercontent.com/3974108/93421472-707d0d00-f87f-11ea-839c-b0e35647978c.png)

GMT's PR https://github.com/GenericMappingTools/gmt/pull/4110 enables switching between different versions. You can try the switcher in the [GMT's documentation site](https://docs.generic-mapping-tools.org/latest/).

To me, it would be great if the same feature can be implemented in the PyGMT site.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by weiji14** [comment]
Probably easiest to follow the PR at https://github.com/GenericMappingTools/gmt/pull/4110. I wonder though how other projects put it on the bottom bar. See e.g. xarray at http://xarray.pydata.org/en/stable/:

![image](https://user-images.githubusercontent.com/23487320/93422529-0ceaf200-f908-11ea-8573-599c856c6467.png)

**Comment by seisman** [comment]
> I wonder though how other projects put it on the bottom bar. See e.g. xarray at http://xarray.pydata.org/en/stable/:

ReadTheDocs automatically shows all versions if the project documentation is hosted on their server.

**Comment by weiji14** [comment]
Ah ok, but we don't use ReadTheDocs. Then just use the `version_switch.js` file then.
