### ISSUE TITLE
Grdcontour's long alias for G (label_placement) is not properly documented

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#622]
**Description of the problem**

Documentation for [`grdcontour`](https://www.pygmt.org/v0.2.0/api/generated/pygmt.Figure.grdcontour.html#pygmt.Figure.grdcontour) uses the common alias `{G}` which should be a custom one for 'label_placement'. But this incorrectly points to the common alias for `color (G)`:

https://github.com/GenericMappingTools/pygmt/blob/d3e131a863a008f14979e7d9764cc6167156376f/pygmt/base_plotting.py#L274

https://github.com/GenericMappingTools/pygmt/blob/d3e131a863a008f14979e7d9764cc6167156376f/pygmt/helpers/decorators.py#L37-L40

The fix shouldn't be too hard, just need to change the line `{G}` above to the full documentation at https://docs.generic-mapping-tools.org/6.1/grdcontour.html#g.

```
label_placement : str
    ``[d|f|n|l|L|x|X]params``.
    The required argument controls the placement of labels along the quoted lines. Choose among five controlling algorithms:
    ...
```

Make sure you wrap the docstring to 79 characters as per #384!

**System information**

Please paste the output of `python -c "import pygmt; pygmt.show_versions()"`:

```
pygmt: v0.2.0
```

**Comment by seisman** [comment]
The **-G** option is really complicated. Perhaps we can just write a one-sentence description and then link it to the GMT module documentation. It's not perfect, but at least it's better than the current wrong description.

**Comment by willschlitzer** [comment]
Can we close this issue now that the -G alias has been explained in the linked PR by @seisman ?
