### ISSUE TITLE
How to reproduce original GMT arguments in PyGMT documentation

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#631]
**Description of the desired feature**

The GMT documentation has many instances where bold and italicized fonts are mixed, looking something like:

<pre><b>+n</b><i>args</i></pre>

The PyGMT documentation has been rather inconsistent with this (see mentions at https://github.com/GenericMappingTools/pygmt/pull/525#discussion_r454414687 and https://github.com/GenericMappingTools/pygmt/pull/620#discussion_r493088431).

What we should do is to standardize how we want **`+n`** *`args`* to be written in the documentation. This is a bit complicated, but boils down to (at least) two options:

1. `r" **+n**\ *args* "`. Use a raw-string in Python, allowing us to follow upstream GMT (as per https://github.com/GenericMappingTools/pygmt/pull/620#discussion_r493088431)

2. `" **+n**\\ *args* "`. Use a double-backslash to avoid the flake8 error `W605 invalid escape sequence '\ '`.

An alternative would be to find a way to ignore the flake8 error somehow for the ReST docstrings.

Also, should we find a way to put these in code-formatted blocks (i.e. with backticks), as mentioned at https://github.com/GenericMappingTools/pygmt/pull/525/files#r454746311? 

**Are you willing to help implement and maintain this feature?** Somewhat short on time, but will look into it.

References:
- https://meta.stackexchange.com/questions/183610/how-to-combine-bold-and-code-sample-in-markdown

**Comment by seisman** [comment]
This is what [PEP-257](https://www.python.org/dev/peps/pep-0257/) says:

> For consistency, always use """triple double quotes""" around docstrings. Use r"""raw triple double quotes""" if you use any backslashes in your docstrings. For Unicode docstrings, use u"""Unicode triple-quoted strings""".

So, instead of using `r" **+n**\ *args* "` for each individual cases, we should use `r`  for the whole docstring, e.g., 

```
def function():
    r"""
    A long docstring string.

    We now can write doctsrings with backslashes **+n**\ *args*
    """
```

**Comment by seisman** [comment]
As pointed out by @weiji14, the PyGMT documentation is inconsistently using _italics_, **bold**, and `code` strings.

I think we can following these conventions:

1. Use `code` for Python function arguments
2. Use **bold** and *italics* for GMT syntax like **+n***args*, in which bold **+n** means it should be typed as it is, and italic *args* should be given a specific value.

This is a good example of what it looks like (https://www.pygmt.org/dev/tutorials/frames.html):

![image](https://user-images.githubusercontent.com/3974108/102562428-0d309000-40a5-11eb-9c8d-ab9cf204144e.png)

**Comment by seisman** [comment]
Ping @GenericMappingTools/python @willschlitzer for thoughts on this.

**Comment by willschlitzer** [comment]
@seisman I like this convention for explaining literal titles and the associated arguments that go with them. Are you thinking there should be similar formatting in the string of arguments given in the doctstring?

**Comment by seisman** [comment]
> Are you thinking there should be similar formatting in the string of arguments given in the doctstring?

Yes, but need feedbacks first.

**Comment by seisman** [comment]
Ping @GenericMappingTools/python for comments.

**Comment by seisman** [comment]
Ping @GenericMappingTools/python, @GenericMappingTools/python-maintainers and @GenericMappingTools/python-contributors for thoughts on https://github.com/GenericMappingTools/pygmt/issues/631#issuecomment-747532492 and https://github.com/GenericMappingTools/pygmt/issues/631#issuecomment-747806369.

**Comment by weiji14** [comment]
Let's go with Option 1 (using the raw string). Easier to copy from GMT, and avoids messy backslashes. Also agree on the backtick `code` blocks.

Will need to document this (with an example) somewhere in CONTRIBUTING.md

**Comment by willschlitzer** [comment]
I think making the entire docstring a raw string is the way to go; I think a double backslash might be confusing to some, and copying directly from GMT makes life easier.

I can write this up in CONTRIBUTING.md when we come to a consensus.

**Comment by seisman** [comment]
> I can write this up in CONTRIBUTING.md when we come to a consensus.

At least three of the maintainers agree with this. I think we can do it now.

**Comment by seisman** [comment]
As most of us agree with the new docstring conventions, we should do:

- [ ] documentation the docstring conventions
- [ ] review the whole project and fix any inconsistence

**Comment by willschlitzer** [comment]
When referencing and explaining the written code in documentation, should it all be in ``code`` format or should it the bold/italicize documentation format. Some examples I encountered in `earth-relief.py`:

``"a2500"`` or **a***2500*
``"x+lElevation"`` or **x+l***Elevation* 

My opinion is to leave it all as ``code`` formatting, but I can see it both ways.

**Comment by seisman** [comment]
> My opinion is to leave it all as `code` formatting to denote that it is the literal string being passed

I think this is the better way.

**Comment by weiji14** [comment]
I've just been looking through some of the new API docs and noticed a problem. E.g. https://www.pygmt.org/dev/api/generated/pygmt.Figure.coast.html after #765 looks like this:

![image](https://user-images.githubusercontent.com/23487320/105417342-570e2680-5ca0-11eb-9907-0b0d98d3df2c.png)

I think we need to add a fullstop/period (.) between `[+z]` and `Select ...` to break the flow, or have `Select ...` appear on a newline as in the GMT docs:

![image](https://user-images.githubusercontent.com/23487320/105417621-c126cb80-5ca0-11eb-8f81-7e82187f1cb4.png)

**Comment by weiji14** [comment]
Anything else remaining after #862?

**Comment by seisman** [comment]
Some module-specific arguments still need updates, for example, [`basemap`'s `map_scale` argument](https://www.pygmt.org/dev/api/generated/pygmt.Figure.basemap.html#pygmt.Figure.basemap).

**Comment by meghanrjones** [comment]
> Some module-specific arguments still need updates, for example, [`basemap`'s `map_scale` argument](https://www.pygmt.org/dev/api/generated/pygmt.Figure.basemap.html#pygmt.Figure.basemap).

Let me know if you'd like me to help with updating these.

**Comment by willschlitzer** [comment]
@meghanrjones Please do! I'm planning on going through the documentation tomorrow; no complaints if you submit a PR for changes!

**Comment by meghanrjones** [comment]
> @meghanrjones Please do! I'm planning on going through the documentation tomorrow; no complaints if you submit a PR for changes!

Sounds good. I'll try to get it done before then.

**Comment by seisman** [comment]
> > @meghanrjones Please do! I'm planning on going through the documentation tomorrow; no complaints if you submit a PR for changes!
> 
> Sounds good. I'll try to get it done before then.

Great! Please try your best to follow the standards as documented here (https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md#example-code-standards). 

There may be some cases that are not covered by the standards. We can discuss more later.

**Comment by meghanrjones** [comment]
Is the convention for documenting defaults in PyGMT set? In GMT, it is typically brackets [ ] without any explanation before the default. I remember a comment in which @seisman mentioned that "[Default is ...]" is more clear than just "[...]", but I couldn't track find that comment again.

**Comment by seisman** [comment]
> In GMT, it is typically brackets [ ] without any explanation before the default. I remember a comment in which @seisman mentioned that "[Default is ...]" is more clear than just "[...]",

Yes, it's open for discussions. The GMT documentation sometimes also uses "[Default is ...]".

**Comment by meghanrjones** [comment]
Moving forward is seems that the GMT documentation will be going with "[Default is ...]" (see https://github.com/GenericMappingTools/gmt/pull/4834).

**Comment by seisman** [comment]
> Moving forward is seems that the GMT documentation will be going with "[Default is ...]" (see [GenericMappingTools/gmt#4834](https://github.com/GenericMappingTools/gmt/pull/4834)).

I think we can document it in the ["Example code standards"](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md#example-code-standards) section, then close the issue, right?

**Comment by meghanrjones** [comment]
Yes, I can add that guideline after #1126 is merged.
