### ISSUE TITLE
xyz2grd wrapper

### ISSUE THREAD

**Issue by carocamargo** [GenericMappingTools/pygmt#635]
Hi, 

I tried to write a wrapper of the [xyz2grd function ](http://gmt.soest.hawaii.edu/doc/5.3.2/xyz2grd.html), in a similar way to the grdfilter wrapper:
I added the function to the gridops.py file, and call it in the __init__.py file. Still, the function doesn't appear when I try to call it. 
![image](https://user-images.githubusercontent.com/47150926/94416255-e8500f00-017e-11eb-8f86-1be204f3fd24.png)
Maybe it wasn't as simple as change the 'grdcut' to 'grdfilter', but I would expect it to recognise the function anyway, and then give me errors... 

**xyz2grd**
The function is used to transform a table/text file into a binary grid file. 

Right now I use <os> library to call gmt from python:

> os.chdir(path_to_xyzfile)
> res='60m'
> infile=flist[0]
> outfile='../nc/test.nc'
> command=str('gmt xyz2grd '+str(infile)+' -G'+str(outfile)+' -I'+str(res)+' -Rg') 
> os.system(command)

Any ideas of how I can solve it?

![image](https://user-images.githubusercontent.com/47150926/94417121-f94d5000-017f-11eb-9ede-1dda66100aa1.png)
![image](https://user-images.githubusercontent.com/47150926/94417164-04a07b80-0180-11eb-8eeb-44cfa121941c.png)
![image](https://user-images.githubusercontent.com/47150926/94417199-11bd6a80-0180-11eb-98fd-8f52206e6327.png)

**Comment by weiji14** [comment]
Could you try removing the space at line 222 between `@kwargs_to_string` and `def xyz2grd` to see if that helps?

**Comment by carocamargo** [comment]
> Could you try removing the space at line 222 between `@kwargs_to_string` and `def xyz2grd` to see if that helps?

It didn't...

**Comment by seisman** [comment]
@carocamargo It seems you almost finished wrapping xyz2grd. Perhaps you could submit a pull request so that we can comment and improve it together? Of course, it's OK if you want to finish grdfilter (https://github.com/GenericMappingTools/pygmt/pull/616) first.

BTW, `xyz2grd` is a gridding module. Perhaps better to put it in `pygmt/gridding.py`, like `surface`?

**Comment by carocamargo** [comment]
> @carocamargo It seems you almost finished wrapping xyz2grd. Perhaps you could submit a pull request so that we can comment and improve it together? Of course, it's OK if you want to finish grdfilter (#616) first.
> 
> BTW, `xyz2grd` is a gridding module. Perhaps better to put it in `pygmt/gridding.py`, like `surface`?

Ok, I think I did a PR for the xyz2grd function (on gridding.py)
