### ISSUE TITLE
Check Python 3.9 compatibility

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#644]
**Description of the desired feature**

Python 3.9 has been released on 2020-10-05. Should check to see if pygmt works well with Python 3.9. See also previous issue for Python 3.8 at #340.

![Python 3.9 and newer release cycle](https://aws1.discourse-cdn.com/business6/uploads/python1/optimized/2X/8/8fb6ece53f24d80e482effc74aab5d0b8f04625b_2_690x364.png)

Links:
- https://blog.python.org/2020/10/python-390-is-now-available-and-you-can.html
- PEP 596 -- Python 3.9 Release Schedule at https://www.python.org/dev/peps/pep-0596/
- https://realpython.com/python39-new-features/
- PEP 602 -- Annual Release Cycle for Python at https://www.python.org/dev/peps/pep-0602/

### Drop Python 3.6 support?

Also, just bringing up the topic of whether we should follow  [NEP 29 — Recommend Python and Numpy version support as a community policy standard](https://numpy.org/neps/nep-0029-deprecation_policy.html) as noted before in https://github.com/GenericMappingTools/pygmt/issues/340#issuecomment-554545546. This would mean dropping support for Python 3.6.

In practice, we'll need to follow in the footsteps of our dependent packages:

- pandas 1.2 dropped Python 3.6 at https://github.com/pandas-dev/pandas/pull/35214
- xarray is less aggressive, they're thinking about it at https://github.com/pydata/xarray/issues/4179

Some options we can take are:

1. Agressive option - Do a PyGMT v0.2.1 release which is the **last** version to support Python 3.6, and state that PyGMT v0.3.0 requires Python 3.7 or newer. 
2. Less aggressive option - Still support Python 3.6 for PyGMT v0.3.0 (but maybe drop it from our test suite to save on CI resources).

**Are you willing to help implement and maintain this feature?** Yes

**Comment by seisman** [comment]
It's a little unclear to me what exactly "Dropping Python 3.6 support" means. Does it mean that users cannot install pygmt via `pip install pygmt` or `conda install pygmt` if they're still using Python 3.6? Or they can still install it, but there is no guarantee that all PyGMT functionalities work well with Python 3.6?

**Comment by weiji14** [comment]
> Does it mean that users cannot install pygmt via `pip install pygmt` or `conda install pygmt` if they're still using Python 3.6? Or they can still install it, but there is no guarantee that all PyGMT functionalities work well with Python 3.6?

It will be quite hard to support four minor versions of Python (3.6, 3.7, 3.8, 3.9), especially for the `conda` packages where there is a separate build for each one (unless we can work out how to get a 'noarch' build). We *could* still allow `pip install pygmt` Python 3.6 (with no support guarantees, i.e. no CI checks), but it will become a maintenance burden when our dependency packages (numpy, pandas, xarray) move on.

There's no rush to do all this, since Python 3.9 is just released, and there are some libraries still to catch up. Even matplotlib (who has more maintainers) is dropping Python 3.6 for their v3.4 (see https://github.com/matplotlib/matplotlib/pull/17662) so it's worth thinking about following NEP 29 for PyGMT v0.3.0.

**Comment by seisman** [comment]
Re-open this issue? Or open a new issue for dropping Python 3.6 support?

**Comment by weiji14** [comment]
I'll open a new one and copy the thread across.
