### ISSUE TITLE
Mute message "begin [INFORMATION]: Creating a workflow ..."

### ISSUE THREAD

**Issue by MarkWieczorek** [GenericMappingTools/pygmt#658]
Everytime that pygmt is imported, an informational message is printed to the screen stating that a new gmt session is being created:
```
begin [INFORMATION]: Creating a workflow directory /Users/lunokhod/.gmt/sessions/gmt_session.18485
```
This is relatively benign, but I don't know why I would need to know the gmt session number. Furthermore, the vast majority of the time I see this message, I am not even using pygmt functionality: it is just that another module imports pygmt by default. 

I would suggest simply turning this message off. If the gmt session information is important, it could be put into a method like `pygmt.get_session_id().`

**Comment by seisman** [comment]
The message is only printed if the GMT verbose level is set to *i*, *c* or *d*. The reason that you see the message is possibly because you have a gmt.conf file in your current directory or home directory, and the GMT_VERBSOE setting is set.

**Comment by MarkWieczorek** [comment]
It turns out that I do have a .gmt/gmt.conf file, and in this file is the line
```
GMT_VERBOSE                    = compat
```
Removing this file gets rid of the warning. Given that I don't know what "compat" means, I'm pretty sure that I didn't modify the default value of "warning". Perhaps this is a holdover of an older version/beta of gmt/pygmt?

**Comment by seisman** [comment]
That's the default value for GMT<=5.4.
