### ISSUE TITLE
Wrapper for inset

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#663]
**Description of the desired feature**

Implement [`inset`](https://docs.generic-mapping-tools.org/6.1/inset.html) which " is used to carve out a sub-region of the current plot canvas and restrict further plotting to that section of the canvas".

At the moment, users have to manually position inset maps using xshift and yshift (which was aliased in #624). Still, the results can be impressive as in this example (from https://github.com/mrsiegfried/Venturelli2020-GRL):

![Cool example of manually positioning map insets over Antarctica](https://user-images.githubusercontent.com/23487320/96937473-b5522e80-1524-11eb-847f-9f5dbcd6bc2a.png)

There's a gallery example over at GMT at https://docs.generic-mapping-tools.org/6.1/gallery/ex44.html on `inset`, and also a good GMT tutorial (in Chinese) at https://docs.gmt-china.org/latest/tutorial/inset/ we could translate over:

![GMT inset example](https://docs.gmt-china.org/latest/_images/inset-gmtplot-11.png)

How should we implement this though? This is actually quite tricky since we need to have the inset map *nested* inside an existing figure. The user experience side of things also needs to be considered, and it's tricky balancing the two.

Option 1 would be to put it in a `with` statement/context manager:

```python
with pygmt.inset(...):
    fig.basemap(...)
    fig.colorbar(...)
```

Option 2 might be to declare the start and end inset explicitly (similar, but not exactly the same as the current subplot wrapper at #427). :

```python
fig.begin_inset()
fig.basemap(...)
fig.colorbar(...)
fig.end_inset()
```

Thoughts? Any Option 3?

**Are you willing to help implement and maintain this feature?** Eventually, perhaps good to model the implementation after the subplot implementation at #427

**Comment by seisman** [comment]
> Still, the results can be impressive as in this example (from https://github.com/mrsiegfried/Venturelli2020-GRL):

It's a really beautiful and impressive figure! 🤩
