### ISSUE TITLE
Refreshing our Code of Conduct to v2.0

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#672]
**Description of the desired feature**

Our original Code of Conduct was added 3 years ago at https://github.com/GenericMappingTools/pygmt/commit/5123e401c9a9bbff9db46073a79e17b94aa67151 by @leouieda on 22 July 2017, and is based on version **1.4** of the Contributor Covenant (see https://www.contributor-covenant.org/version/1/4/code-of-conduct/).

A lot has happened to the world since then, and it is time, as a (bigger) community :people_holding_hands:, to put a bit of time into refreshing the document. There is a draft Pull Request to update our Code of Conduct to v2.0 at #673, but **please** take the time to voice your opinion on what you would like (or not like) PyGMT to look like - in terms of communication style - for the next 3 years (or so).

In particular, I'm hoping to hear what we can do to recruit a broader range of contributors that reflects the **diversity** of the geosciences community. We're doing good on the international front with people spread out over different continents/timezones, but there are many other dimensions like race, gender, etc, which definitely needs more work. That's enough of me talking, let's hear from some other folks :smile:

References:
- https://www.contributor-covenant.org/version/2/0/code_of_conduct/
- https://github.com/ContributorCovenant/contributor_covenant/pull/709

**Are you willing to help implement and maintain this feature?** Yes

**Comment by weiji14** [comment]
Just wanted to share this blog post on the "Complexities of Codes of Conduct" at https://reshamas.github.io/the-complexities-of-codes-of-conduct/. in light of a recent incident at JupyterCon 2020. It's interesting in that you get to see all sides of the story. Goes to show how everyone one of us in the open source community, big or small, still has much to learn!

**Comment by leouieda** [comment]
Thanks for sharing @weiji14. I was following the JupyterCon incident and it's well worth a read. I hadn't seen this post yet
