### ISSUE TITLE
PyGMT authorship policy for Changelog, Zenodo and Publications

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#691]
**Description of the desired feature**

The PyGMT project started by @leouieda in 2017 is gaining quite some traction, and it's time to come up with a good system to assign authorship as we work towards more releases and perhaps a paper (#677) in the future!

Originally raised by @leouieda at https://github.com/GenericMappingTools/pygmt/issues/677#issue-732055450:

> It's really important that we agree on this before doing any work a paper. See the [Fatiando policy](https://github.com/fatiando/contributing/blob/master/AUTHORSHIP.md) which was generated after long discussion and research into similar policies.

Also mentioned at https://github.com/GenericMappingTools/pygmt/pull/683#discussion_r519031191_

---

To begin, I think https://github.com/fatiando/contributing/blob/master/AUTHORSHIP.md is a nice starting template to use, and so is the original discussion at https://github.com/fatiando/contributing/pull/13. The TLDR of it I think is:

- **Changelog**: If you made a commit as a contributor, we'll mention your Github `@` handle (at the very minimum) or your full name in our [changelog](https://www.pygmt.org/dev/changes.html) for a particular version
- **Zenodo**: Your full name must be in [AUTHORS.md](https://github.com/GenericMappingTools/pygmt/blob/master/AUTHORS.md), (+ Affiliation and ORCID). See also https://doi.org/10.5281/zenodo.3781524.
- **Paper**: Have made a 'significant' contribution to the PyGMT project (which can be more than just coding) and you are involved in the writing of the manuscript.

---

And just to link to a few useful references from https://github.com/GenericMappingTools/pygmt/issues/677#issuecomment-721410615_:

- FORCE11 Software Citation Implementation Working Group at https://github.com/force11/force11-sciwg.
- CRediT – Contributor Roles Taxonomy at https://casrai.org/credit/

**Are you willing to help implement and maintain this feature?** Yes

**Comment by seisman** [comment]
The policy sounds good to me. 

Let's hear more voices from @GenericMappingTools/python @GenericMappingTools/python-contributors

**Comment by leouieda** [comment]
Just to add a little bit of background, the reason for that policy was to create a clear document we can point to as both an incentive for new contributors and to avoid toxic discussions that can arise about authorship. Our goal was to be as inclusive as possible and very generous with respect to credit. The policy does that with a 3 tier system: changelog, Zenodo, paper. Each has more "prestige" than the previous and so we can also expect more effort from people. To get into the changelog, you only need to make a PR. To go into Zenodo, you need to edit the Authors file as well. To get into the paper, you need to read/revise the paper and add yourself as author on top of the previous requirements.

**Comment by seisman** [comment]
I just opened a PR (#726) to push it forward.
