### ISSUE TITLE
Basic support for FreeBSD

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#698]
**Description of the desired feature**

Although FreeBSD is not as popular as Linux/macOS/Windows, there are still some FreeBSD + GMT users (see https://forum.generic-mapping-tools.org/t/building-gmt-on-freebsd-12-1-release/967), and they're also potential PyGMT users.

As I understand it, [`sys.platform`](https://docs.python.org/3/library/sys.html#sys.platform) will return `freebsdX` on FreeBSD _X_, thus function [`clib_names`](https://github.com/GenericMappingTools/pygmt/blob/7e7da78c773c280d2d9c6724c79ce8b41f6532b0/pygmt/clib/loading.py#L54) will report an error:
```
Operating system "freebsdx" not supported.
```

What we can do is:

1. Confirm the return value of `sys.platform` on FreeBSD (`freebsdX` if I understand the docs correctly)
2. Confirm the suffix of shared libraries on FreeBSD (`.so` based on search results)
3. Add an if test for freebsd

For points 1 and 2, we may ask for some help in this post https://forum.generic-mapping-tools.org/t/967.

We won't have a CI job testing FreeBSD, but at least we can provide some basic support.

**Are you willing to help implement and maintain this feature?** Yes, but we need more inputs from FreeBSD users.

**Comment by weiji14** [comment]
> We won't have a CI job testing FreeBSD, but at least we can provide some basic support.

Seems like Travis CI has experimental FreeBSD support according to https://travis-ci.community/t/freebsd-vms-support/2125. So it *is* possible to test it :slightly_smiling_face:

**Comment by seisman** [comment]
Don't want to add Travis CI back, and conda-forge may NOT support FreeBSD (https://github.com/conda/conda/issues/61).

**Comment by weiji14** [comment]
Yeah, but maybe we should at least run our full test suite at least once on FreeBSD somehow. Either we do it through (Travis) CI, set up a FreeBSD Virtual Machine (e.g. via QEMU) or have a FreeBSD user test things.

**Comment by seisman** [comment]
See feedbacks from FreeBSD users https://forum.generic-mapping-tools.org/t/building-gmt-on-freebsd-12-1-release/967/18
