### ISSUE TITLE
Use numpys ndpointer instead of ctypes POINTER(double)

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/pygmt#71]
The numpy ctypeslib provides a helper function to specify array argument types to ctypes functions: https://docs.scipy.org/doc/numpy/reference/routines.ctypeslib.html#numpy.ctypeslib.ndpointer

Use this instead of the ctypes pointers that are used right now.

**Comment by seisman** [comment]
I tried to address this issue but failed. The problem is that if a argument is defined using numpy ndpointer (double), then we have to pass a ndarray with dtype=np.float64, and we cannot pass NULL or None to the library. See https://stackoverflow.com/questions/32120178/ for some discussion.

**Comment by leouieda** [comment]
Yep, I thought it might make things easier but GMT uses a lot of NULL. Closing
