### ISSUE TITLE
how to draw a rose in cartesian projection

### ISSUE THREAD

**Issue by mattijn** [GenericMappingTools/pygmt#714]
I found out I'm able to add a _map scale_ and a _rose_ for a **geographic** projection:
```python
fig = pygmt.Figure()
fig.basemap(region=[0, 5, 55, 56], projection="S2.5/90/2i", frame=["a+ue", "wsEN"], rose='jMC+w0.5i')
fig.show()
```
![image](https://user-images.githubusercontent.com/5186265/101072386-3d086f80-359e-11eb-9c90-8910f52ab211.png)

```
fig = pygmt.Figure()
fig.basemap(region=[0, 5, 55, 56], projection="S2.5/90/2i", frame=["a+ue", "wsEN"], map_scale='jMC+c1+w100k+f+l')
fig.show()
```
![image](https://user-images.githubusercontent.com/5186265/101072414-48f43180-359e-11eb-91e0-c38d536e1311.png)

And I could add a map scale in a **cartesian** projection
```
fig = pygmt.Figure()
fig.basemap(region='0/1000/1000/2000+ue', projection='x1:10000', frame=["ag", "wsEN"], map_scale='jMC+w500e+l')
fig.show()
```
![image](https://user-images.githubusercontent.com/5186265/101072427-4f82a900-359e-11eb-8851-acc80082d3a4.png)

But how do I add a _rose_ in a **cartesian** projection?
Since the following is giving me a blank plot:
```
fig = pygmt.Figure()
fig.basemap(region='0/1000/1000/2000+ue', projection='x1:10000', frame=["ag", "wsEN"], rose='jMC+w0.2i+l')
fig.show()
```
![image](https://user-images.githubusercontent.com/5186265/101072444-57424d80-359e-11eb-8061-c64d0bb7e0e7.png)

**Comment by seisman** [comment]
@PaulWessel Any thoughts?

**Comment by PaulWessel** [comment]
Well, not sure what "north" means if x is time and y is in kilos.  If the user has UTM meters then one can lay down basemaps in geographic coordinates and plot the meters as Cartesian but that is a special case.

**Comment by mattijn** [comment]
My real plot is in [EPSG:28992](https://epsg.io/28992) projection, which are meters. It looks as follow:

<img width="522" alt="image" src="https://user-images.githubusercontent.com/5186265/101078715-d471c080-35a6-11eb-9acc-748448bb3b5f.png">
Which was prepared with this [notebook](https://github.com/mattijn/KNMI-radar-PyGMT/blob/main/pygmt%20rioxarray%20KNMI%20radar.ipynb)

**Comment by seisman** [comment]
@mattijn The issue has been addressed in upstream PR https://github.com/GenericMappingTools/gmt/pull/4535.

**Comment by mattijn** [comment]
Fast! +1

**Comment by seisman** [comment]
As mentioned above, the issue has been fixed in upstream GMT codes. I don't think we need to add a PyGMT test for this. Closing the issue.
