### ISSUE TITLE
Table for different map projections

### ISSUE THREAD

**Issue by willschlitzer** [GenericMappingTools/pygmt#746]
The current projection gallery displays the different types of projections by name and a sample image. I propose that the home page for the projections also include a table listing the different projection "codes" (R, G, X, M etc.) and the associated projection name. This will allow someone to quickly identify the projection specified if they are referencing a PyGMT script but unfamiliar with the available projections (as happened to me after seeing the usage of ``projection="R-130/5i"`` in Liam's YouTube tutorial).

**Are you willing to help implement and maintain this feature?** Yes

I'm happy to do this, but am unfamiliar with how to add a table using Sphinx.

**Comment by seisman** [comment]
GMT provides a table for projections (https://docs.generic-mapping-tools.org/latest/proj-codes.html), and the code is available from https://github.com/GenericMappingTools/gmt/edit/master/doc/rst/source/proj-codes.rst.

The table shows both GMT and PROJ projections codes, but perhaps we only want the GMT ones to keep it simple? Also related to https://github.com/GenericMappingTools/pygmt/issues/356.

**Comment by seisman** [comment]
Closed by #753.
