### ISSUE TITLE
Add explanatory text for the particular projections to the projection gallery

### ISSUE THREAD

**Issue by phloose** [GenericMappingTools/pygmt#747]
To support choosing a projection especially for new users it would be helpful to add some explanatory text to the projection gallery plots about a particular projection. This has been started in #318. 

The [GMT cookbook](https://docs.generic-mapping-tools.org/latest/cookbook/map-projections.html) can be used as reference since it already contains some information about the different projections GMT supports. While the descriptions are already complete and could be adopted as is, if someone has background knowledge and can clarify/simplify/improve some of the explanations it would be great.

With reference to #292, https://github.com/GenericMappingTools/pygmt/issues/292#issuecomment-513183815 and https://github.com/GenericMappingTools/pygmt/issues/292#issuecomment-747743344

**Comment by willschlitzer** [comment]
I'll work on this.  My knowledge of the benefits and drawbacks of different projections is going to be limited to what the GMT Cookbook presents, so I anticipate this largely being a copy-and-paste operation for me.
