### ISSUE TITLE
Support table on forward/backward compatibility of PyGMT with Python and GMT versions

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#748]
**Description of the desired feature**

To be nice to our users and clear up any potential source of confusion on PyGMT's compatibility with GMT, we should have a table or something indicating forward/backward compatibility. It's a bit hard to pick thing out from the changelog at https://www.pygmt.org/latest/changes.html. Something like so, inspired by https://github.com/holoviz/pyviz_comms#compatibility (correct me if I'm wrong):

| PyGMT | GMT | Notes |
|---|---|---|
| 0.1.0 | >= 6.0.0, < 6.1.0? | #363, requires GMT modern mode |
| 0.1.1 | >= 6.0.0, < 6.1.0? |          |
| 0.2.0 | >= 6.1.1                | #577, new earth relief pixel registration default |
| 0.2.1 | >= 6.1.1                |          |
| 0.3.0 | >= 6.1.1  ?            |          |
| 0.4.0 | >= 6.2.0  ?            |          |

See thread at https://github.com/GenericMappingTools/pygmt/issues/729#issuecomment-747968293_ for context. Probably should add a column for Python compatibility too, related to issue #690.

**Are you willing to help implement and maintain this feature?** Discuss first on where to put this, maybe at https://github.com/GenericMappingTools/pygmt#documentation-for-other-versions?

**Comment by seisman** [comment]
Sounds a great idea, although it makes the README even longer 😄
