### ISSUE TITLE
colorbar is missing documentation for "-I" and lacks a "shading" alias

### ISSUE THREAD

**Issue by MarkWieczorek** [GenericMappingTools/pygmt#749]
In practice, whenever an image is plotted using shading ("grdimage -I...") it is common to use the "-I" option for the colorbar as well.  At present there is no documentation of the colorbar "-I" option, but it turns out that you can get this to work anyways. Two calling options are 
```
fig.colorbar(I='')
```
or
```
fig.colorbar(I=True)
```
For simplicity, I would probably document the second option.

Furthermore, for consistency with `grdimage` the colobar function should have an alias called `shading` so that we don't have to use the cryptic gmt short commands.

**Comment by seisman** [comment]
Closed by #752.
