### ISSUE TITLE
The workflow of "GMT Latest Tests" are triggered multiple times

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#828]
**Description of the problem**

In my recent PR (#827), the workflow of "GMT Latest Tests" are triggered twice (https://github.com/GenericMappingTools/pygmt/actions/runs/524773762, and https://github.com/GenericMappingTools/pygmt/actions/runs/524773759), possibly because I asked two teams for review.

Can we improve the workflow triggering condition?
https://github.com/GenericMappingTools/pygmt/blob/8e2b3691f40b8e455885195f7f738bfc979dc845/.github/workflows/ci_tests_dev.yaml#L6-L13

**Comment by weiji14** [comment]
Or you could just ask one team at a time to review...

**Comment by seisman** [comment]
> Or you could just ask one team at a time to review...

The problem is that [python-maintainers](https://github.com/orgs/GenericMappingTools/teams/python-maintainers) team only has two people (@willschlitzer and I), and @willschlitzer is not in the [python](https://github.com/orgs/GenericMappingTools/teams/python) team. 

Ideally, the python-maintainers team should have all the people in the python team.

**Comment by weiji14** [comment]
I'm happy to be added to the `python-maintainers` team, or we could add @willschlitzer to the `python` team 😆

**Comment by seisman** [comment]
Better to redesign the teams to be [nested](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-teams#nested-teams).

**Comment by weiji14** [comment]
> Better to redesign the teams to be [nested](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-teams#nested-teams).

Agree, but let's do it for the whole https://github.com/orgs/GenericMappingTools/teams organization. I'll open up a discussion at https://github.com/GenericMappingTools/gmt/discussions

**Comment by seisman** [comment]
Yes. Please open a discussion.

**Comment by weiji14** [comment]
Ok, done at https://github.com/GenericMappingTools/gmt/discussions/4732. Let's leave this issue open for a while.
