### ISSUE TITLE
Do not run workflows if only non-source-code files are changed

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#837]
**Description of the desired feature**

Sometimes, we make changes to plain text files (.md, .rst), without changing any source codes. We know that the changes won't break our tests, but the workflow still runs 9 jobs (Ubuntu/macOS/Windows + Python 3.7/3.8/3.9). It's a waste of CI resources. For example, #726, #802, and #836.

GitHub Actions actually can skip workflows based on the files that are changed, 

> When using the `push` and `pull_request` events, you can configure a workflow to run when at least one file does not match `paths-ignore` or at least one modified file matches the configured `paths`. Path filters are not evaluated for pushes to tags.

see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths for details.

We may explore this to reduce our CI usages. IMHO, we can skip running workflows if only the following files are changes:

- `*.md`
- `**/*.rst`
- `doc/**`
- `examples/**` (?)

Note that, the documentation is still built by vercel, so documentation preview still works.

**Are you willing to help implement and maintain this feature?** Yes, but let's discuss it first and contributions are welcomed.

**Comment by liamtoney** [comment]
I think this makes a lot of sense.
