### ISSUE TITLE
Add more PyGMT-related grants

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#860]
**Description of the desired feature**

In the [`README.rst`](https://github.com/GenericMappingTools/pygmt/blob/master/README.rst) file, we mention:

> The development of PyGMT was funded by NSF grant OCE-1558403.

Compared to the [GMT support page](https://www.generic-mapping-tools.org/about/#support):

- NSF grant OCE-1558403 is not mentioned in the GMT support page
- Some recent grants in the GMT support page are not listed in the PyGMT project.

Questions for @PaulWessel:

1. Should "NSF grant OCE-1558403" be added to the GMT support page? Are there any other grants that are not listed?
2. Are there any grants you think we should list in the PyGMT project?

**Comment by PaulWessel** [comment]
OCE-1558403 should be added for sure. 15 means 2015 so it should be placed in the right order.  We should also add workshop proposal OCE-1841660 which funded the summits.  Looking at NSF I also see EAR-1347184.  Finally OCE-1648602 which is what got the money to hire Leo, so that needs to be on PyGMT page.

**Comment by seisman** [comment]
If I understand you correctly, we should

1. Add OCE-1558403, OCE-1841660, EAR-1347184, OCE-1648602 (in the correct order) to the GMT support page
2. Add OCE-1648602 to the PyGMT page

correct?

**Comment by PaulWessel** [comment]
Yep, taht should do it.  The NSF page is confusing since they often give separate numbers to small supplements - I kept those off.  The 16* is a funny insider competition grant without any review and involves cost-matches across many units, so not just OCE I think.  WHo knows.

**Comment by seisman** [comment]
I can't find the NFS link for OCE-1648602.

**Comment by PaulWessel** [comment]
Try EAR, and if not then it is just some internal number considered a supplement to the 15, and then we can leave it off.

**Comment by seisman** [comment]
Also can't find EAR-1648602. Will leave it off.

**Comment by weiji14** [comment]
I'm reopening this because we only have NSF grant OCE-1558403 listed on the main page at https://github.com/GenericMappingTools/pygmt/tree/57da40a0fde0d08cac1b1789167406894af99918#support. Probably should list down a few more.

**Comment by seisman** [comment]
> I'm reopening this because we only have NSF grant OCE-1558403 listed on the main page at [`57da40a`#support](https://github.com/GenericMappingTools/pygmt/tree/57da40a0fde0d08cac1b1789167406894af99918#support). Probably should list down [EAR-1948602](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1948602) too.

Ping @PaulWessel

**Comment by PaulWessel** [comment]
Certainly add EAR-1948603. Leo was paid off the supplement to OCE-15 so I think these two are the only ones explicitly supporting work on Python (i.e., Meghan on 19).

**Comment by weiji14** [comment]
Somehow we have EAR-1948603 on the Zenodo page at https://doi.org/10.5281/zenodo.4253459 already, but not on the main README page. I'll make a quick PR for it, thanks for the confirmation Paul.
