### ISSUE TITLE
Short affiliation names in AUTHORS.md

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#897]
Initial discussed in https://github.com/GenericMappingTools/pygmt/pull/857#pullrequestreview-588235476:

> > 1. Do we want the affiliation to be the full Department, University, City, Country format? I understand that the full affiliation would be needed for a paper, but again, a lot can happen between now and the paper coming out. Right now it's only the University name listed on Zenodo (hover over the names at https://zenodo.org/record/4253459).
> 
> Is the motivation to update this less often? We could forgo affiliations here and just ask for them when making releases or just when writing papers?

> Yeah, would be best to keep changes to a minimum. Do people update their ORCID page often? I suppose we could just use what's on their ORCID page, even if it might be a pain during releases to check through every single person's current location.

The full affiliation names sometimes are longer than one line in GitHub web UI, and more than 200 characters in the plaintext markdown file (see the screenshot below). 

![image](https://user-images.githubusercontent.com/3974108/107901220-1dcc7d80-6f11-11eb-98bf-8577b24c483f.png)

And the full affiliation names won't be used unless when we write the first paper. So I prefer to have shorter affiliation names.

**Comment by liamtoney** [comment]
I'm fine with short affiliations. Looking at the line wraps above, I appear to be the worst offender 😉 .

**Comment by seisman** [comment]
Ping @leouieda @mjziebarth @michaelgrund @tjnewton @willschlitzer @weiji14

**Comment by weiji14** [comment]
Alternatively, if people want to keep their full affiliation, we can use a table, by adding:

```
| Name | ORCID | Affiliation
|:--|:--:|:--|
```

![image](https://user-images.githubusercontent.com/23487320/108111029-051ebc00-70f9-11eb-8867-84219baafe6a.png)

**Comment by michaelgrund** [comment]
I'm fine with short affiliations, too. However, since mine is currently the shortest I'd leave it to the others to decide.

**Comment by seisman** [comment]
It seems more than half (5/9) of the "PyGMT Developers" agree with short affiliation names. 

> Alternatively, if people want to keep their full affiliation, we can use a table, by adding:

The table looks good, but making the plain markdown file more complicated.

**Comment by core-man** [comment]
Could I help with this issue? It seems that it is a good first issue for me.

Based on the above discussion, could we just keep the authors' full names, ORCID, and university/institute.
The maximum length is about 73 under preview (i.e., Meghan Jones), which corresponds to 146 characters.

* [Dongdong Tian](https://seisman.info/) | [0000-0001-7967-1197](https://orcid.org/0000-0001-7967-1197) | Michigan State University
* [Leonardo Uieda](http://www.leouieda.com/) | [0000-0001-6123-9515](https://orcid.org/0000-0001-6123-9515) | University of Liverpool
* [Liam Toney](https://liam.earth/) | [0000-0003-0167-9433](https://orcid.org/0000-0003-0167-9433) | University of Alaska Fairbanks
* [Malte Ziebarth](https://github.com/mjziebarth) | [0000-0002-5190-4478](https://orcid.org/0000-0002-5190-4478) | GFZ
* [Meghan Jones](https://github.com/meghanrjones) | [0000-0003-0180-8928](https://orcid.org/0000-0003-0180-8928) | University of Hawai'i at Mānoa
* [Michael Grund](https://github.com/michaelgrund) | [0000-0001-8759-2018](https://orcid.org/0000-0001-8759-2018) | Innoplexia GmbH
* [Tyler Newton](http://www.tnewton.com/) | [0000-0002-1560-6553](https://orcid.org/0000-0002-1560-6553) | University of Oregon
* [Wei Ji Leong](https://github.com/weiji14) | [0000-0003-2354-1988](https://orcid.org/0000-0003-2354-1988) | Victoria University of Wellington
* [William Schlitzer](https://github.com/willschlitzer) | [0000-0002-5843-2282](https://orcid.org/0000-0002-5843-2282) | Unaffiliated

The second solution is to replace the authors' homepage with ORCID at the same time. Usually, we can find the authors' homepage on their ORCID websites. The maximum length is only 48 under preview and 91 in plaintext.

* [Dongdong Tian](https://orcid.org/0000-0001-7967-1197) | Michigan State University
* [Leonardo Uieda](https://orcid.org/0000-0001-6123-9515) | University of Liverpool
* [Liam Toney](https://orcid.org/0000-0003-0167-9433) | University of Alaska Fairbanks
* [Malte Ziebarth](https://orcid.org/0000-0002-5190-4478) | GFZ
* [Meghan Jones](https://orcid.org/0000-0003-0180-8928) | University of Hawai'i at Mānoa
* [Michael Grund](https://orcid.org/0000-0001-8759-2018) | Innoplexia GmbH
* [Tyler Newton](https://orcid.org/0000-0002-1560-6553) | University of Oregon
* [Wei Ji Leong](https://orcid.org/0000-0003-2354-1988) | Victoria University of Wellington
* [William Schlitzer](https://orcid.org/0000-0002-5843-2282) | Unaffiliated

**Comment by michaelgrund** [comment]
> 
> 
> > The second solution is to replace the authors' homepage with ORCID at the same time. Usually, we can find the authors' homepage on their ORCID websites.
> 
> That's not always true. I'm in favor of the first solution.

Me too, as pointed out not everybody has listed a homepage on the ORCID portal and some people don't even have a "real" homepage (execpt the linked GitHub profile).

**Comment by weiji14** [comment]
Cool, let's go with Solution 1 in https://github.com/GenericMappingTools/pygmt/issues/897#issuecomment-783413696 then, i.e.:

- [Name]() | 0000-0001-2345-6789 | University/Company/Unaffiliatied

@core-man, feel free to open up a Pull Request for this, have a look at [CONTRIBUTING.md](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md) to get started and don't hesitate to ask us if you need any help!
