### ISSUE TITLE
Improve the .gitignore file

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#902]
**Description of the desired feature**

The `.gitignore` file tells Git to ignore some files when running commands like `git status` and `git add`. The current [`.gitignore`](https://github.com/GenericMappingTools/pygmt/blob/master/.gitignore) file could be improved in some aspects:

- List the ignore patterns in groups and sort alphabetically in each group (see https://github.com/github/gitignore/blob/master/Python.gitignore for an example) 
- Some files should be ignored 
  - `.DS_Store` (macOS only)
  - `results` directory: generated when running `pytest`
  - `.eggs`: generated when making distributions

**Are you willing to help implement and maintain this feature?** Volunteers are welcomed.

**Comment by core-man** [comment]
I'd like to help to improve `.gitignore`.
