### ISSUE TITLE
Document how to skip CI in the contributing guides

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#908]
https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

> GitHub Actions now supports skipping push and pull_request workflows by looking for some common keywords in your commit message.

> If any commit message in your push or the HEAD commit of your PR contains the strings [skip ci], [ci skip], [no ci], [skip actions], or [actions skip] workflows triggered on the push or pull_request events will be skipped.

Finally, GitHub support skipping workflows to save CI resources! Will try how it looks like in next pushes/PRs. If it works well, we should document it in the contributing guides at [CONTRIBUTING.md](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md), and even in the [Pull Request template](https://github.com/GenericMappingTools/pygmt/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by weiji14** [comment]
Actually, do you want to just document this in MAINTENANCE.md at the current PR #906?

**Comment by seisman** [comment]
Better to do one simple thing in one PR.

**Comment by seisman** [comment]
One note: when we merge a PR, we should be cautious that the merge message (default to be a list of commit messages in this branch) can't contain `[ci skip]`, otherwise the merged commit won't trigger CI jobs when merged into master branch.

**Comment by weiji14** [comment]
Just checking, do you think it's really necessary to document this in our guide (since it's getting quite long)? Or can we just point it out to people (on a need to know basis) and close this issue?

**Comment by seisman** [comment]
OK with closing the issue.
