### ISSUE TITLE
PyGMT version is not dynamic in develop mode?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#912]
**Full code that generated the error**

I have the full git repository of the PyGMT project, and then run the following commands:
```
# Checkout master branch and install it
$ cd pygmt/
$ git checkout master
$ make install

# Check current PyGMT version
$ python -c "import pygmt; print(pygmt.__version__)"
v0.3.1.dev3+g27c09271

# Checkout the v0.3.0 tag and check the PyGMT version
$ git checkout v0.3.0
HEAD is now at 65b099a5 Changelog entry for v0.3.0 (#887)
$ python -c "import pygmt; print(pygmt.__version__)"
v0.3.1.dev3+g27c09271
```

As shown above, should the version string to `v0.3.0` when I checked out the `v0.3.0` tag?

**Comment by seisman** [comment]
Related to https://github.com/pypa/setuptools_scm/issues/518

**Comment by weiji14** [comment]
Don't think there's much we can do with this, other than using post commit/checkout hooks as mentioned in https://github.com/pypa/setuptools_scm/issues/518#issuecomment-782190444. So closing for now.

**Comment by seisman** [comment]
Maybe we can try https://github.com/jwodder/versioningit. According to this post,
https://www.nijho.lt/post/best-python-dev-tooling/#-7-versioningit-version-management-with-git-tags, it works with editable installations.
