### ISSUE TITLE
Update "setting up your environment" in CONTRIBUTING.md

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#913]
**Description of the problem**

In the [setting up your environment](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md#setting-up-your-environment) section of CONTRIBUTING.md, the instruction for activating the environment created from the ```environment.yml``` file is:

```source activate ENVIRONMENT_NAME```

Starting with conda 4.4, ```conda activate``` is recommended over ```source activate```. Since the environment name (``pygmt``) is specified in ```environment.yml```, ```ENVIRONMENT_NAME``` in this command could also be updated to ```pygmt``` with the new instruction being:

```conda activate pygmt```

**Comment by seisman** [comment]
Sounds good. 

Reference: https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#managing-python

**Comment by tawandamoyo** [comment]
I'd like to work on this

**Comment by seisman** [comment]
> I'd like to work on this

@tawandamoyo Great! You can following our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md). Let us know if you need any help.
