### ISSUE TITLE
Add more targets to doc/makefile help information

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#914]
**Description of the problem**

The available targets in [the docs Makefile](https://github.com/GenericMappingTools/pygmt/blob/master/doc/Makefile) are ``help``, ``clean``, ``html``, ``api``, ``linkcheck``, ``doctest``, and ``serve``. The ``help`` target only lists information about the ``all``, ``html``, ``linkcheck``, and ``doctest`` targets. One line each could be added to ``help`` to describe ``clean``,``api``, and ``serve``, for example ``@echo "  clean      clean up build and generated files"``.

**Comment by seisman** [comment]
We may want to remove the `linkcheck` target, because `make linkcheck` is so slow (> 5 minutes for me), and we will have a workflow for checking links (#634) (in process, but close to be ready).

**Comment by weiji14** [comment]
I never even realized we had a `make linkcheck` :sweat_smile: But yes, agree that this is a good first issue.

And just wanting to raise the issue of making things cross-platform (read: runs on Windows). Leo suggested using [nox](https://nox.thea.codes/en/stable/) at https://github.com/GenericMappingTools/pygmt/pull/679#issuecomment-723147333, but I'm wondering if our Makefile would just work on Windows if we install [`make` from conda-forge](https://anaconda.org/conda-forge/make)?

**Comment by seisman** [comment]
@GenericMappingTools/python @GenericMappingTools/gmt-contributors @GenericMappingTools/python-maintainers 

We are close to the v0.3.1 release, and I think we can wrap up this issue. Does anyone want to work on it?

**Comment by core-man** [comment]
> @GenericMappingTools/python @GenericMappingTools/python-contributors @GenericMappingTools/python-maintainers
> 
> We are close to the v0.3.1 release, and I think we can wrap up this issue. Does anyone want to work on it?

I am working on it.
