### ISSUE TITLE
Better web font for I (capital i) and l (small L)

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#933]
**Description of the problem**

See this page as an example: https://pygmt-6lvxfpcmx.vercel.app/gallery/line/vector-heads-tails.html

![image](https://user-images.githubusercontent.com/3974108/108530368-86b24d80-72a3-11eb-8aab-445003cbbe62.png)

The two "I" in the two red boxes are different. The first one is capital `i`, and the second one is small `L`. However, they look the same in the current font (I'm using Microsoft Edge on macOS. Not sure what they look like on other web browsers and platforms).

Should we switch to a better web font? Does the current theme "sphinx_rtd_theme" support custom web fonts?

**Comment by meghanrjones** [comment]
I agree with you. I think it would just involve changing a couple lines in ``doc/build/_static/style.css``. For example, this is the output for the vector example with this css style (which is currently set to open sans):
```
body {
    font-family: "Tahoma", sans-serif;
}

h1, h2, h3, h4 {
    font-weight: 300;
    font-family: "Tahoma",sans-serif;
}
```

> <img width="934" alt="image" src="https://user-images.githubusercontent.com/14077947/108533968-b77f8c00-727d-11eb-9f8f-3a9989d063f9.png">


I like Tahoma because it is sans-serif but still has differences between those two characters.

**Comment by seisman** [comment]
Looks good. Does Linux support it?

**Comment by meghanrjones** [comment]
Good point, probably not. We can include multiple fonts in the font-family property as a fall-back and/or find an open source alternative to Tahoma that still makes those characters more distinct.

**Comment by seisman** [comment]
It would be better if you can open a PR so that we can preview what the new font settings look like.

**Comment by weiji14** [comment]
Ok, here's 3 open PRs with new web fonts to preview:

- #934 (Tahoma) - [Microsoft Windows only?](https://docs.microsoft.com/en-us/typography/font-list/tahoma) - https://pygmt-git-docs-fonts.gmt.vercel.app/api/generated/pygmt.Figure.basemap.html
- #936 (IBM Plex Sans) - [Open Font License](https://en.wikipedia.org/wiki/SIL_Open_Font_License) - https://pygmt-git-docs-fonts-serve.gmt.vercel.app/api/generated/pygmt.Figure.basemap.html
- #938 (Atkinson Hyperlegible) - [Somewhat modified Open Font License](https://www.brailleinstitute.org/wp-content/uploads/2020/11/Atkinson-Hyperlegible-Font-License-2020-1104.pdf) - https://pygmt-git-docs-fonts-legible.gmt.vercel.app/api/generated/pygmt.Figure.basemap.html

Any other candidates :laughing:?

**Comment by meghanrjones** [comment]
The Atkinson Hyperlegible font looks great IMO

**Comment by liamtoney** [comment]
> The Atkinson Hyperlegible font looks great IMO

Agreed! I'd be happy w/ this and don't mind the zero with the slash. One concern I have is that it's on the smaller side, I'd suggest we bump up the font size a bit if we use this (easy).

**Comment by weiji14** [comment]
> > The Atkinson Hyperlegible font looks great IMO
> 
> Agreed! I'd be happy w/ this and don't mind the zero with the slash. One concern I have is that it's on the smaller side, I'd suggest we bump up the font size a bit if we use this (easy).

Increasing the font size sounds good, I'll look into the style.css file.

Also, should we/do we need a list of fallback font types if we serve the font directly? I.e. do something like `font-family: "Atkinson Hyperlegible", "Tahoma", sans-serif;`?

**Comment by liamtoney** [comment]
I think that it's best practice to include a fallback font regardless. I'd suggest just falling back to generic `sans-serif` from Atkinson though.

**Comment by weiji14** [comment]
Ok, done at f14a8e1ec597c61e23fffc031128f0bbdeed2f39. See https://pygmt-git-docs-fonts-legible-gmt.vercel.app/gallery/line/vector-heads-tails.html#sphx-glr-gallery-line-vector-heads-tails-py, compare with https://www.pygmt.org/dev/gallery/line/vector-heads-tails.html.

**Comment by liamtoney** [comment]
Thanks, @weiji14. I think having a slightly heavier font is fine and might even be better for small screens. Plus, then we don't have to serve the "light" font or whatever.

I think this looks great, adds a bit more style to our site, and hopefully makes it more readable too. But I think we should check with other @GenericMappingTools/python folks too!

**Comment by seisman** [comment]
Looks good to me.
