### ISSUE TITLE
Remove trailing white spaces automatically 

### ISSUE THREAD

**Issue by michaelgrund** [GenericMappingTools/pygmt#935]
So far trailing white spaces in files are not automatically detected when running `make format`, `make check` and `make lint` (see #890) . 

Do you think we should add such check, if possible, to follow the PEP8 guidelines?  

**Are you willing to help implement and maintain this feature?** Discuss first

**Comment by seisman** [comment]
I tried the following script (with invisible trailing whitespaces in many lines):
```python
"""
This is a test.   
"""

def add(x, y):   
    """
    >>> add(5, 4)   
    9   
    """
    # this is a comment   
    return x + y   

```
Running `black` removes all trailing whitespaces for me.

Not sure why it hehaves differently in #890.

**Comment by seisman** [comment]
> Running `black` removes all trailing whitespaces for me.

No, `black` doesn't remove the trailing whitespace in the docstrings of the file.

**Comment by meghanrjones** [comment]
``flake8`` would check for whitespace and lines >80 (both not caught by ``black`` in examples); currently ``flake8`` is only used for pygmt, setup.py, and doc/conf.py.

**Comment by weiji14** [comment]
> > Running `black` removes all trailing whitespaces for me.
> 
> No, `black` doesn't remove the trailing whitespace in the docstrings of the file.

Doesn't `blackdoc ` remove the trailing whitespace in the docstrings? Interesting :thinking: Might be worth filing an issue on https://github.com/keewis/blackdoc if we can confirm this.

**Comment by seisman** [comment]
> Does `blackdoc` not remove the trailing whitespace in the docstrings?

None of `black`, `blackdoc`, and `docformatter` does to the file-scope docstrings. It's possible these are not "docstrings" https://www.python.org/dev/peps/pep-0257/.

**Comment by seisman** [comment]
Related issue: https://github.com/psf/black/issues/318

**Comment by michaelgrund** [comment]
> 
> 
> Related issue: [psf/black#318](https://github.com/psf/black/issues/318)

Means it is not possible to do any automatic check and everybody has to care about the spaces before committing, right?

**Comment by seisman** [comment]
Perhaps [docformatter](https://github.com/myint/docformatter) should remove the trailing whitespace? It says:

> docformatter also handles some of the PEP 8 conventions.

> Don't write string literals that rely on significant trailing whitespace. Such trailing whitespace is visually indistinguishable and some editors (or more recently, reindent.py) will trim them.

**Comment by seisman** [comment]
`docformatter` can remove trailing whitespaces from the following script:
```
"""
A docstring with some invisible whitespace.     

More description with some invisible trailing whitespaces.   
"""
```

but does nothing to:
```
"""
A docstring with some invisible whitespace.     
=================================================

More description with some invisible trailing whitespaces.   
"""
```

Report a bug to `docformatter` at https://github.com/myint/docformatter/issues/71.

**Comment by michaelgrund** [comment]
> 
> 
> `docformatter` can remove trailing whitespaces from the following script:
> 
> ```
> """
> A docstring with some invisible whitespace.     
> 
> More description with some invisible trailing whitespaces.   
> """
> ```
> 
> but does nothing to:
> 
> ```
> """
> A docstring with some invisible whitespace.     
> =================================================
> 
> More description with some invisible trailing whitespaces.   
> """
> ```
> 
> Reported a bug to `docformatter` at [myint/docformatter#71](https://github.com/myint/docformatter/issues/71).

Interesting but good to know that we can differentiate between normal scripts and sphinx-gallery style header docstrings.

**Comment by seisman** [comment]
Perhaps we should try https://github.com/DanielNoord/pydocstringformatter.

**Comment by brnt** [comment]
Trailing spaces in docstrings sometimes have syntactical meaning (e.g., forcing a [markdown line break](https://daringfireball.net/projects/markdown/syntax#block)).  As questionable as it is to have some count of non-printing characters trigger a material document change, we are where we are (and Markdown is _extremely_ prevalent). Stripping those trailing spaces in docstrings could break the formatting of parameter lists in IDE code hints (and probably some other stuff I haven't thought of).

**Comment by seisman** [comment]
I'm going to close the issue mainly because: (1) it's a minor issue and (2) it does't bother us  in the last two years.
