### ISSUE TITLE
Intersphinx mapping not working in Returns

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#937]
**Description of the problem**

The intersphinx mapping to pandas.DataFrame does not seem to be working in the Returns section of the docstrings. See [blockmedian](https://www.pygmt.org/dev/api/generated/pygmt.blockmedian.html#pygmt.blockmedian) for an example.

*Originally posted by @weiji14 in https://github.com/GenericMappingTools/pygmt/pull/930#discussion_r579526151*

**Comment by meghanrjones** [comment]
Relevant issue: https://github.com/sphinx-doc/sphinx/issues/8290

Seems the options here are to either set ``napoleon_use_rtype = True`` in doc/conf.py, manually define the links, or wait for a bug fix.

**Comment by seisman** [comment]
Tried `napoleon_use_rtype = True`, it gives:

![image](https://user-images.githubusercontent.com/3974108/108609675-78485c80-739d-11eb-8835-b4bfd30a89fd.png)

**Comment by seisman** [comment]
`napoleon_use_rtype = True` gives inconsistent rendering for returns and parameters. I don't think this is what we want. I think we should manually define the links or just ignore them.

**Comment by meghanrjones** [comment]
My preference would be to ignore the missing links in the rtypes (seems like an upstream bug to me) and manually define the links in the bullet lists (if present) below the rtypes (which would not be automatically linked regardless of the bug). These are the module docstrings which would need to be updated if we chose this solution:

- [ ] blockmedian.py (L61)
- [ ] grdcut.py (L85)
- [ ] grdfilter.py (L119)
- [ ] grdtrack.py (L66)
- [ ] info.py (L66)

**Comment by seisman** [comment]
> My preference would be to ignore the missing links in the rtypes (seems like an upstream bug to me) and manually define the links in the bullet lists (if present) below the rtypes (which would not be automatically linked regardless of the bug).

Sounds good.
