### ISSUE TITLE
Add more examples for polar projections

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#942]
We already have a very simple example (https://www.pygmt.org/dev/projections/nongeo/polar.html) showing how polar projection looks like, but the polar projection (**-JP**) is more complicated (also more powerful). We should add more examples for the polar projections.

Here are some examples from [the GMT Chinese documentation](https://docs.gmt-china.org/latest/proj/Jp/). 

![image](https://user-images.githubusercontent.com/3974108/108615246-25d46380-73d0-11eb-9ad0-28d5ef426c7a.png)

**Resources:**

- [Full -JP syntax](https://docs.generic-mapping-tools.org/latest/proj-codes.html)
- [GMT documentation](https://docs.generic-mapping-tools.org/latest/cookbook/coordinate-transformations.html#linear-projection-with-polar-coordinates-jp-jp)
- [GMT Chinese documentation](https://docs.gmt-china.org/latest/proj/Jp/)

Questions:

1. Should we put it on this page https://www.pygmt.org/dev/projections/nongeo/polar.html? Or as a standalone gallery example?

**Comment by michaelgrund** [comment]
Great idea, I would put it into a standalone gallery example according to the figure you show above. Since I worked a lot with such projections in the past (and some parts were really confusing to me in the beginning) I could work on this if there are no other volunteers :wink:
