### ISSUE TITLE
Let flake8 check examples

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#948]
``flake8`` would check for whitespace and lines >80 (both not caught by ``black`` in examples); currently ``flake8`` is only used for pygmt, setup.py, and doc/conf.py.

_Originally posted by @meghanrjones in https://github.com/GenericMappingTools/pygmt/issues/935#issuecomment-782408392_

Do we want flake8 to check all examples? Or do we want to limit line length in examples?

**Comment by seisman** [comment]
I don't like `flake8` because it still doesn't support pyproject.toml (https://gitlab.com/pycqa/flake8/-/issues/428), but there are alternatives (e.g., https://flakehell.readthedocs.io/)

**Comment by weiji14** [comment]
Funny, I was looking at `flakehell` too last week. Dropping `flake8` and switching to `flakehell` might allow us to get rid of the [`setup.cfg`](https://github.com/GenericMappingTools/pygmt/blob/v0.3.0/setup.cfg) file I think. See also https://dev.to/bowmanjd/using-flake8-and-pyproject-toml-with-flakehell-1cn1

**Comment by seisman** [comment]
> allow us to get rid of the [`setup.cfg`](https://github.com/GenericMappingTools/pygmt/blob/v0.3.0/setup.cfg?rgh-link-date=2021-02-21T22%3A46%3A13Z) file I think.

Yes!

**Comment by weiji14** [comment]
> > allow us to get rid of the [`setup.cfg`](https://github.com/GenericMappingTools/pygmt/blob/v0.3.0/setup.cfg?rgh-link-date=2021-02-21T22%3A46%3A13Z) file I think.
> 
> Yes!

See also https://stackoverflow.com/questions/44878600/is-setup-cfg-deprecated :smile:. I think it should be safe to remove `setup.cfg` once (and **if**) we switch from `flake8` to `flakehell`, but need to be extra careful in case it breaks some obscure Python packaging component.

**Comment by seisman** [comment]
Unfortunately, [`flakehell`](https://github.com/life4/flakehell) is no longer maintained.

**Comment by weiji14** [comment]
> Unfortunately, [`flakehell`](https://github.com/life4/flakehell) is no longer maintained.

Oo, that was sudden. Guess we'll need to find or wait for an alternative.

**Comment by seisman** [comment]
As I understand it, `flake8` is still the most popular and widely-used tool for style checking. I think we should still use `flake8`, and (1) wait for the official pyproject.toml support (https://gitlab.com/pycqa/flake8/-/issues/428); (2) see if someone forks and maintains `flakehell`; (3) see if there are similar wrappers.

Back to the initial issue, I think we should let `flake8` check the examples. It should also fix the trailing whitespace issue in #935.

To let `flake8` check all examples, we need to change one single line in `Makefile`:
https://github.com/GenericMappingTools/pygmt/blob/e0579275d00c7a69d25a82b4c8936e0b0b1b7577/Makefile#L11
and fix all warnings. 

Before that, we need to discuss #962 first.

**Comment by seisman** [comment]
There is an "official" fork of [flakehell](https://github.com/life4/flakehell) at https://github.com/flakehell/flakehell.
