### ISSUE TITLE
Change the line length limit of docstrings to 88 characters

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#962]
We use the [Black](https://github.com/psf/black) tool to format the code, and the default line length of Black is [88 characters](https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length). The 88-char line length limit is only applied to code, not docstrings. For docstrings, the line length limit is 79 characters, and we use several tools, [blackdoc](https://github.com/keewis/blackdoc), [docformatter](https://github.com/myint/docformatter) and [flake8](https://flake8.pycqa.org/en/latest/) to check and format the docstrings.

Then, the question is, why do we use different line length limits for code and docstrings? 

We started to adopt the 79-char line length limit for docstrings in PR #384. The PR description also explains why we choose 79-char length (also see some external discussions in https://github.com/fatiando/verde/issues/177)

> Jupyter, IPython, and other IDEs don't usually render the rst in the
docstrings and just show them literally. The problem is that many of
these break lines at 79 characters. So docstrings with more characters
look terrible in these settings and sometimes almost unreadable. Wrap
all docstrings to 79 characters instead of Black's 88. 

---

Is the reason still valid?

I just changed one line of the docstrings of `Figure.basemap()` to ~120 chars, and checked what the docstrings look like in Jupyter, IPython, PyCharm, and VS Code. Here are the results:

In Jupyter Notebook, the long docstrings look good with the `help()` function:

![image](https://user-images.githubusercontent.com/3974108/108947164-eacf6b80-762d-11eb-8db7-6614a4fb5bd0.png)

Also look good in the Notebook Contextual Help page:

![image](https://user-images.githubusercontent.com/3974108/108947238-1d796400-762e-11eb-842a-bc2f247a4528.png)

In a Python or IPython console:

![image](https://user-images.githubusercontent.com/3974108/108947321-3e41b980-762e-11eb-9953-b9336170e2a8.png)

In VS Code:

![image](https://user-images.githubusercontent.com/3974108/108947545-ad1f1280-762e-11eb-932b-521d7a53ac44.png)

In PyCharm:

![image](https://user-images.githubusercontent.com/3974108/108947674-ece5fa00-762e-11eb-9871-57b1df36db45.png)

----

From the above screenshots, it's clear that these consoles, editors, and IDEs don't wrap docstrings at 80 characters and work well with long docstrings.

Now the questions are:

1. Are they any other common editors or IDEs that force wrapping docstrings at 80 characters?
2. Should we change the line length limit of docstrings to 88 characters?

**Comment by meghanrjones** [comment]
To me, the example docstring looks good in VSCode and PyCharm but the return between 'separate'/'tick-intervals' and 'or'/'``compass``' in the Notebook and the Python console decreases readability and does not look good. Do you know why there are returns in those two locations?

**Comment by seisman** [comment]
Oh, sorry for the confusion. To test what long docstrings look like, I changed (locally) the docstrings of `Figure.basemap()` to:
```python
@kwargs_to_strings(R="sequence", c="sequence_comma", p="sequence")
def basemap(self, **kwargs):
    r"""
    Plot base maps and frames for the figure.

    Creates a basic or fancy basemap with axes, fill, and titles. Several map projections are available, and the user
    may specify separate
    tick-mark intervals for boundary annotation, ticking, and [optionally]
    gridlines. A simple map scale or directional rose may also be plotted.

    At least one of the parameters ``frame``, ``map_scale``, ``rose`` or
    ``compass`` must be specified.
```
So it seems VSCode and PyCharm remove all "returns" in the docstrings, while Python and notebook keep them.

**Comment by seisman** [comment]
Ping @GenericMappingTools/python @GenericMappingTools/python-maintainers for thoughts.

**Comment by meghanrjones** [comment]
I have no problems with changing it. Is your preference 88 or ~120 characters @seisman?

**Comment by seisman** [comment]
> Is your preference 88 or ~120 characters

We will stick with 88 characters (the default value of `Black`) if others agree.

**Comment by michaelgrund** [comment]
> 
> 
> > Is your preference 88 or ~120 characters
> 
> We will stick with 88 characters (the default value of `Black`) if others agree.

Would be fine for me.

**Comment by weiji14** [comment]
I would keep it at 79 characters. The point made at #384 and https://github.com/fatiando/verde/issues/177 is for the **Parameters^^ section. E.g. in `jupyterlab`, try reading this:

![image](https://user-images.githubusercontent.com/23487320/109343850-d233af80-78d2-11eb-8e80-5c29810e1708.png)

**Comment by seisman** [comment]
Hmmm, I didn't know the "Shift+Tab" shortcut for the docstring tooltip until today. 

It seems JupyterLab wraps at 90 characters, but Jupyter Notebook wraps at 80 characters.

So, the only reason to keep 79 characters is to make it look better in the classic Jupyter Notebook? But, is jupyter notebook still heavily used by people? Even the [jupyter notebook](https://github.com/jupyter/notebook) project encourages people to use JupyterLab instead. 

> Please note that this repository is currently maintained by a skeleton crew of maintainers from the Jupyter community. We encourage users to transition to JupyterLab, where more immediate support can occur.

**Comment by weiji14** [comment]
> Hmmm, I didn't know the "Shift+Tab" shortcut for the docstring tooltip until today. 

Wow, you've missed out on so much then!!

> So, the only reason to keep 79 characters is to make it look better in the classic Jupyter Notebook? But, is jupyter notebook still heavily used by people? Even the [jupyter notebook](https://github.com/jupyter/notebook) project encourages people to use JupyterLab instead. 
> 
> > Please note that this repository is currently maintained by a skeleton crew of maintainers from the Jupyter community. We encourage users to transition to JupyterLab, where more immediate support can occur.

You will be surprised at how many people still use the classic notebook, even as jupyerlab has been around for a few years. I haven't had time to look, but Google Collaboratory, Kaggle and others probably use a similar classic notebook interface. This is one of those things where it's better to keep things as it is - if it ain't broken, don't fix it.

**Comment by seisman** [comment]
> You will be surprised at how many people still use the classic notebook, even as jupyerlab has been around for a few years. I haven't had time to look, but Google Collaboratory, Kaggle and others probably use a similar classic notebook interface. This is one of those things where it's better to keep things as it is - if it ain't broken, don't fix it.

Fair enough. Let's keep the docstring to 79 characters.

**Comment by seisman** [comment]
I'm reopening the issue so that we can revisit it again.

**Comment by seisman** [comment]
The main reasons that I prefer to set the line-length limit of docstrings to 88 characters:

1. Make line-lengths of source codes and docstrings consistent. 
2. Increase line length and reduce number of lines.
3. The 79-character line-length limit makes no sense for comments in gallery example files.

**Comment by leouieda** [comment]
@seisman does the update handle indentation in Parameters blocks? That's still the worst part. 

And my experience is also that loads of people still use the classic notebook and have no intention of going to Jupyter Lab.

**Comment by seisman** [comment]
> does the update handle indentation in Parameters blocks? That's still the worst part.

I tried to merge two lines into a single long line. As you can see below, the word `with` is wrapped into two lines and `t` is the 86-th character. So it seems the classic notebook wraps at 86-characters, not 88.

<img width="784" alt="image" src="https://github.com/GenericMappingTools/pygmt/assets/3974108/66cc051d-1377-496d-9906-8270a02e89d6">

Jupyter Lab wraps at 96-characters:

<img width="781" alt="image" src="https://github.com/GenericMappingTools/pygmt/assets/3974108/d9755e80-c705-4b15-8f99-43bc51dd3653">

**Comment by seisman** [comment]
Quickly checked the line-length in numpy, xarray and pandas. It seems numpy strictly follows the 80-char rule, while in xarray and pandas, most lines are shorter than 80-char, but there are also many lines longer than 80-char.

**Comment by seisman** [comment]
Not sure why I had `notebook` v6.0.0 installed in  https://github.com/GenericMappingTools/pygmt/issues/962#issuecomment-1771283669. I just tried again with `notebook` versions >=6.1. It turns out they all wrap at 88 characters.

Here is the docstrings that I have changed for testing:
```python
    lakes : str or list                                                         
        *fill*\ [**+l**\|\ **+r**].                                             
        Set the shade, color, or pattern for lakes and river-lakes. The default is the fill chosen for wet areas set by the ``water``
        parameter. Optionally, specify separate fills by appending              
        **+l** for lakes or **+r** for river-lakes, and passing multiple        
        strings in a list. 
```
Here is how the long line is wrapped in Jupyter Notebook v6.1.6:
![Screenshot from 2023-12-22 20-32-31](https://github.com/GenericMappingTools/pygmt/assets/3974108/fc1b3dd2-8c41-4e4f-9976-79bdb0b4966e)
The word `fill` starts at exactly column 89, so it's clear that Notebook wraps at 88 for notebook>=6.1. 

Since Notebook [v6.1.6](https://github.com/jupyter/notebook/releases/tag/6.1.6) was released three years ago on Dec, 24, 2020, I think it's OK to assume that users are using notebook>=6.1, and then it's safe to set the length limit to 88-characters.

**Comment by weiji14** [comment]
I'm ok with moving to 88-characters, if only to simplify the linter configuration (e.g. with #2909). But I'm not keen on re-wrapping all the docstrings from 79 to 88 characters and making lots of big diffs. We can enforce a line-length of 88, but only apply it for newly written documentation perhaps?

**Comment by seisman** [comment]
> We can enforce a line-length of 88, but only apply it for newly written documentation perhaps?

I don't think we can. The line length of docstrings are controlled by 
https://github.com/GenericMappingTools/pygmt/blob/013014b71f22d048c28a93412e1028f03450e5ce/pyproject.toml#L86-L87

If we change them to 88, all docstrings will be reformatted.

**Comment by weiji14** [comment]
Well, as long as it's automated by `ruff`, that should be ok? Could configure the setting in `pyproject.toml`, and then call `/format` in a PR to see how big the diff is :slightly_smiling_face:.

**Comment by seisman** [comment]
> Well, as long as it's automated by `ruff`, that should be ok?

There must be some misunderstandings here. Currently, the docstrings are formatted by `docformatter` and the code snippets in docstrings (i.e., doctests) are formatted by `blackdoc`.

As in #2909, `blackdoc` will be replaced by `ruff`, but docstrings are still formatted by `docformatter`, unless we enable ruff's [`pydocstyle` (D)](https://docs.astral.sh/ruff/rules/#pydocstyle-d) rules, which is close to `docformatter` (https://github.com/astral-sh/ruff/issues/1335).

**Comment by weiji14** [comment]
> > Well, as long as it's automated by `ruff`, that should be ok?
> 
> There must be some misunderstandings here. Currently, the docstrings are formatted by `docformatter` and the code snippets in docstrings (i.e., doctests) are formatted by `blackdoc`.
> 
> As in #2909, `blackdoc` will be replaced by `ruff`, but docstrings are still formatted by `docformatter`, unless we enable ruff's [`pydocstyle` (D)](https://docs.astral.sh/ruff/rules/#pydocstyle-d) rules, which is close to `docformatter` ([astral-sh/ruff#1335](https://github.com/astral-sh/ruff/issues/1335)).

Ah yes, we're talking about the docstrings here, so `docformatter`. I just tried changing the settings to `wrap-summaries = 88` and  `wrap-descriptions = 88`, and also need to set `tool.ruff.lint.pycodestyle - max-doc-length = 88`. There were 77 files that were modified. But it seems like only the summaries were re-wrapped to 88 line-lengths, while the descriptions below stayed the same at 79 characters? I was expecting the Parameters and other sections to be wrapped too, but it looks like the diff will be smaller than expected (which is good).

**Comment by seisman** [comment]
> But it seems like only the summaries were re-wrapped to 88 line-lengths, while the descriptions below stayed the same at 79 characters? I was expecting the Parameters and other sections to be wrapped too

It's a known issue https://docformatter.readthedocs.io/en/latest/faq.html.
