### ISSUE TITLE
Allow load_earth_relief() to load the original land-only SRTM tiles

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#966]
**Description of the desired feature**

Refer to https://docs.generic-mapping-tools.org/latest/datasets/remote-data.html#technical-information for details.

> The 3 and 1 arc second data are the SRTM 1x1 degree tiles from NASA. Note: The 3 and 1 arc second grids only extend to latitudes ±60˚ and are only available over land. When these grids are accessed as @earth_relief_01s or @earth_relief_03s we will automatically up-sample the relevant @earth_relief_15s tiles to fill in the missing ocean values. If you just want the original land-only SRTM tiles you may use the special names @srtm_relief_03s or @srtm_relief_01s instead. 

Currently, the `load_earth_relief()` function can load `01s` and `03s` Earth relief grid, but can't load the original land-only SRTM grid. 

It seems easy to add the feature. We just need to add a new parameter `use_srtm` (default to `False`) to the `load_earth_relief` function.

If `resolution="01s"` or `resolution="03s"`, we check the value of `use_srtm` to determine the remote file prefix (either `earth_relief_` or `srtm_relief_`).

**Are you willing to help implement and maintain this feature?** Yes, but volunteers are welcomed.

**Comment by willschlitzer** [comment]
I think this is a good idea.

**Comment by core-man** [comment]
I'd like to help with this issue if possible. It seems a good issue to begin to be familiar with pygmt.
